- build-tools/src/main/resources/build-tools/dependency-check/suppressions.xml
- gateway-test-release/pom.xml
- pom.xml
This is for review only. Patches will be attached to KNOX-1421
> KNOX-1421 - Enable OWASP Dependency Check

- build.xml
We do support (re-) starting test servers without debug mode; I added a new Ant target to start test servers where remote debugging is enabled for the gateway.
**Note**: this PR is created for review only; the patch - if approved - will be attached to [KNOX-1758](https://issues.apache.org/jira/browse/KNOX-1758).
Manually tested
```
HW15069:knox smolnar$ ant start-test-servers-debug
Buildfile: /Users/smolnar/projects/knox/build.xml
start-test-ldap:
[exec] Starting LDAP succeeded with PID 26571.
start-debug-gateway:
[exec] Listening for transport dt_socket at address: 5005
```
> KNOX-1758 - New Ant target to ease starting test servers enabling remote debugging

- gateway-server/src/main/java/org/apache/knox/gateway/GatewayMessages.java
- gateway-service-remoteconfig/pom.xml
- gateway-service-remoteconfig/src/main/java/org/apache/knox/gateway/service/config/remote/zk/CuratorClientService.java
- gateway-service-remoteconfig/src/main/java/org/apache/knox/gateway/service/config/remote/zk/RemoteConfigurationRegistryJAASConfig.java
- gateway-service-remoteconfig/src/test/java/org/apache/knox/gateway/service/config/remote/zk/RemoteConfigurationRegistryJAASConfigTest.java
- gateway-util-urltemplate/src/test/java/org/apache/knox/gateway/util/urltemplate/MatcherTest.java
When there is a misconfiguration in the supplied JAAS configuration (i.e. `conf/krb5JAASLogin.conf`) the server fails to start and the information in gateway.log wasn't at all helpful. To make it better the following changes have been made:
- *all* `FATAL` messages are logged with the full stack trace
- in case the supplied JAAS configuration file does not exist or cannot be parsed we wrap the `IOException` coming from security login configuration into our own `ConfigurationException` with a meaningful error message
(an additional change is to fix a unit test case in `MatcherTest` to avoid compilation error; I'm not sure how it was working before but it constantly fails locally for me)
Added new unit test cases and executed them (including integration tests):
```
[INFO] …
```
> KNOX-1162 - Logging stacktrace for FATAL messages and displaying a meaningful error message in case of missing/non-parsable JAAS configuration

- gateway-provider-security-pac4j/src/main/java/org/apache/knox/gateway/pac4j/filter/Pac4jDispatcherFilter.java
- gateway-provider-security-pac4j/src/main/java/org/apache/knox/gateway/pac4j/session/KnoxSessionStore.java
Currently OIDC support for Azure AD was broken. This is because Azure AD does not allow ? in callback urls. This fix updates the callback flow in Knox so that the callback urls now can have callback parameter as a path element rather than a query parameter.
This patch was manually tested with Azure AD (OIDC), Google (OIDC) and Okta (SAML) authentication providers.
> KNOX-1191 - Azure AD support for KnoxSSO

- gateway-provider-security-pac4j/src/main/java/org/apache/knox/gateway/pac4j/filter/Pac4jDispatcherFilter.java
- gateway-server/src/main/java/org/apache/knox/gateway/GatewayServer.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/CLIGatewayServices.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/DefaultGatewayServices.java
- gateway-server/src/main/java/org/apache/knox/gateway/topology/simple/SimpleDescriptorHandler.java
- gateway-server/src/main/java/org/apache/knox/gateway/util/KnoxCLI.java
- gateway-server/src/test/java/org/apache/knox/gateway/util/KnoxCLITest.java
- gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/DefaultHttpClientFactory.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/GatewayServices.java
- gateway-test/src/test/java/org/apache/knox/gateway/SimpleDescriptorHandlerFuncTest.java
Currently "MasterService" is a string throughout the code base. This should be a field on the interface GatewayServices like other services.
- Added `GatewayServices.MASTER_SERVICE` constant.
- Alphabetized service name constants in `GatewayServices` 
- Replaced "MasterService" strings speckled throughout the code with `GatewayServices.MASTER_SERVICE`
- Replaced an instance of "SSLService" with "GatewayServices.SSL_SERVICE"
(If this patch involves UI changes, please …
> KNOX-1791 - MasterService should be a field on GatewayServices

- gateway-server/src/main/java/org/apache/knox/gateway/GatewayResources.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/DefaultGatewayServices.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/security/impl/DefaultKeystoreService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/DefaultTokenAuthorityService.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/DefaultTokenAuthorityServiceTest.java
Moved validation to `org.apache.knox.gateway.services.token.impl.DefaultTokenAuthorityService#start`.   
Added call to `org.apache.knox.gateway.services.token.impl.DefaultTokenAuthorityService#start` in `org.apache.knox.gateway.services.DefaultGatewayServices#start`.
Created message resource values in `org.apache.knox.gateway.GatewayResources` to help manage error messages. 
Added new unit tests.
Ran unit tested
Tested the following scenarios:
* Existing Default signing keystore (gateway.jks) and aliases
* Existing Custom signing keystore and aliaes
* Missing default signing keystore - keystore created on start
* Invalid master key (negative test)
* Missing custom signing keystore (negative test)
* Existing custom signing keystore with invalid password (negative test)
* Existing custom …
> KNOX-1793 - DefaultKeystoreService should not validate the signing key on initialization

- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/CLIGatewayServices.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/DefaultGatewayServices.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/security/impl/RemoteAliasService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/security/impl/ZookeeperRemoteAliasService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/security/impl/ZookeeperRemoteAliasServiceProvider.java
- gateway-server/src/main/resources/META-INF/services/org.apache.knox.gateway.security.RemoteAliasServiceProvider
- gateway-server/src/test/java/org/apache/knox/gateway/services/security/impl/RemoteAliasServiceTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/security/impl/RemoteAliasServiceTestProvider.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/security/impl/ZookeeperRemoteAliasMonitorTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/security/impl/ZookeeperRemoteAliasServiceTest.java
- gateway-server/src/test/resources/META-INF/services/org.apache.knox.gateway.security.RemoteAliasServiceProvider
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
- gateway-spi/src/main/java/org/apache/knox/gateway/security/RemoteAliasServiceProvider.java
- gateway-test-release-utils/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
The RemoteAliasService should use service loading to ensure make the RemoteAliasService extensible. Moved existing Zookeeper impl to its own class and loaded via service loading.
`mvn -T.5C verify -Ppackage,release`
> KNOX-1789 - Refactor RemoteAliasService to use service loading

- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/deploy/JWTAccessTokenAssertionContributor.java
- gateway-release/pom.xml
- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/security/impl/DefaultAliasService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/security/impl/DefaultKeystoreService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/security/impl/RemoteAliasService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/security/impl/ZookeeperRemoteAliasService.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/security/impl/RemoteAliasServiceTestProvider.java
- gateway-service-hashicorp-vault/pom.xml
- gateway-service-hashicorp-vault/src/main/java/org/apache/knox/gateway/backend/hashicorp/vault/HashicorpVaultAliasService.java
- gateway-service-hashicorp-vault/src/main/java/org/apache/knox/gateway/backend/hashicorp/vault/HashicorpVaultRemoteAliasServiceProvider.java
- gateway-service-hashicorp-vault/src/main/java/org/apache/knox/gateway/backend/hashicorp/vault/authentication/HashicorpVaultClientAuthenticationProvider.java
- gateway-service-hashicorp-vault/src/main/java/org/apache/knox/gateway/backend/hashicorp/vault/authentication/KubernetesHashicorpVaultClientAuthenticationProvider.java
- gateway-service-hashicorp-vault/src/main/java/org/apache/knox/gateway/backend/hashicorp/vault/authentication/TokenHashicorpVaultClientAuthenticationProvider.java
- gateway-service-hashicorp-vault/src/main/resources/META-INF/services/org.apache.knox.gateway.backend.hashicorp.vault.authentication.HashicorpVaultClientAuthenticationProvider
- gateway-service-hashicorp-vault/src/main/resources/META-INF/services/org.apache.knox.gateway.security.RemoteAliasServiceProvider
- gateway-service-hashicorp-vault/src/test/java/org/apache/knox/gateway/backend/hashicorp/vault/TestHashicorpVaultAliasService.java
- gateway-service-hashicorp-vault/src/test/resources/log4j.properties
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/AliasService.java
- pom.xml
Hashicorp Vault remote alias service provider
https://www.vaultproject.io/
https://www.vaultproject.io/api/libraries.html#java
With Docker running to ensure that Vault can be started in a container:
`mvn -T.5C verify -Ppackage,release`
If Docker is not running, the integration test will be skipped.
> KNOX-1687 - Hashicorp Vault RemoteAliasService provider

- gateway-release/home/bin/gateway.sh
Gateway's output (both standard output and error) is being redirected even if the `GATEWAY_SERVER_RUN_IN_FOREGROUND` environment variable is set to `true`. This should be stopped so that end-users get immediate feedback in case of any error upon startup (without browsing error/output files).
```
$ export GATEWAY_SERVER_RUN_IN_FOREGROUND=true
$ echo $GATEWAY_SERVER_RUN_IN_FOREGROUND
true
$ ./knox-1.3.0-SNAPSHOT/bin/gateway.sh start
log4j:WARN No such property [maxBackupIndex] in org.apache.log4j.DailyRollingFileAppender.
log4j:WARN No such property [maxFileSize] in org.apache.log4j.DailyRollingFileAppender.
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
```
> KNOX-1803 - Stop redirecting stderr & stdout to a file when the server runs in the foreground

- gateway-server/src/main/java/org/apache/knox/gateway/GatewayMessages.java
- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/security/impl/DefaultKeystoreService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/security/impl/JettySSLService.java
- gateway-server/src/test/java/org/apache/knox/gateway/config/impl/GatewayConfigImplTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/security/impl/DefaultKeystoreServiceTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/security/impl/JettySSLServiceTest.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
- gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/DefaultHttpClientFactory.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/KeystoreService.java
- gateway-test-release-utils/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
The Knox Gateway truststore should be configurable
Knox relies on a trust store for various purposes
- The *KnoxCLI* (via a KnoxSession) uses a truststore to trust the connection to the Knox Gateway server
- The truststore is determined by the Java system properties (`javax.net.ssl.trustStore`, `javax.net.ssl.trustStorePassword`) or the JVM's cacerts file
- The *Knox Gateway* server uses a truststore to trust the connections going out to the services (if connecting via TLS/SSL)
- The truststore is set to be the same keystore as the Gateway's identitiy keystore.
- See `org.apache.knox.gateway.dispatch.DefaultHttpClientFactory#createHttpClient`.
- The *Knox Gateway* server uses a truststore to trust the user/client connecting to it when clientauth is enabled
- The truststore is set to be …
> KNOX-1812 - The Knox Gateway truststore should be configurable

- gateway-release/home/bin/gateway.sh
- gateway-server/src/main/java/org/apache/knox/gateway/GatewayServer.java
`conf` and `data` directories are configurable using GATEWAY_HOME (or newly introduced env variable) in the Java layer, therefore those checks should either be removed from the `bash` layer, so they take those variables into account within the Java code.
Running JUnit tests:
```
$ mvn -T1C verify -Prelease,package
...
[INFO] Total time: 19:13 min (Wall Clock)
[INFO] Finished at: 2019-03-11T11:04:32+01:00
[INFO] Final Memory: 272M/1965M
```
Additionally, the following manual test steps were executed:
1. Using non-existing `conf` and …
> KNOX-1814 - Moving conf/data folder checking to Java layer from bash

- gateway-release-common/home/bin/knox-functions.sh
- gateway-release/home/bin/gateway.sh
- gateway-release/home/bin/ldap.sh
Removing code duplication in `gateway.sh` and `ldap.sh` files.
Executing the following manual test steps:
```
-- Gateway test --
$ ./knox-1.3.0-SNAPSHOT/bin/gateway.sh status
Gateway is not running. No PID file found.
$ ./knox-1.3.0-SNAPSHOT/bin/gateway.sh clean
Removed the Gateway PID file: /home/knox/knox-1.3.0-SNAPSHOT/pids/gateway.pid.
Removed the Gateway OUT file: /home/knox/knox-1.3.0-SNAPSHOT/logs/gateway.out.
Removed the Gateway ERR file: /home/knox/knox-1.3.0-SNAPSHOT/logs/gateway.err.
$ export KNOX_GATEWAY_CONF_DIR=~knox/nonExistingFolder
$ ./knox-1.3.0-SNAPSHOT/bin/gateway.sh start --printEnv
APP_CONF_DIR = /home/knox/nonExistingFolder
APP_LOG_DIR = /home/knox/knox-1.3.0-SNAPSHOT/logs
APP_DATA_DIR = /home/knox/knox-1.3.0-SNAPSHOT/data
APP_PID_DIR = …
```
> KNOX-1804 - Moving copy-pasted bash functions to knox-function.sh

- gateway-server/src/main/java/org/apache/knox/gateway/websockets/ProxyInboundClient.java
- gateway-server/src/main/java/org/apache/knox/gateway/websockets/ProxyWebSocketAdapter.java
- gateway-server/src/test/java/org/apache/knox/gateway/websockets/BigEchoSocketHandler.java
- gateway-server/src/test/java/org/apache/knox/gateway/websockets/MessageFailureTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/websockets/ProxyInboundClientTest.java
Resolves issue with Zeppelin and websocket messages being capped at 65,536 bytes.
Set websocket container max text and binary message sizes to Integer.MAX_VALUE.
Create workbook in zeppelin that returns more than 65,536 bytes of data. I used a sql query from Phoenix but anything that makes a big message should work.
After proxying through Knox page never completes loading and Knox spams error logs with message too large.
(If this patch involves UI changes, please attach a …
> KNOX-1828 Fix Websocket Message Size

- gateway-release-common/home/bin/knox-functions.sh
Running the Knox Gateway and the LDAP server using exec in the foreground gives us the opportunity to execute the underlying Java command that completely replaces the current bash process (there won't be any parent process which makes graceful stops easier by clients).
Note: without this change CM will consider the Gateway stopped even if the JAva process is still running in the background.
Running Knox Gateway and the LDAP server in the foreground after I built the project.
> KNOX-1849 - Start the Java process with 'exec' when running the app in the foreground

- gateway-server/pom.xml
- gateway-server/src/main/java/org/apache/knox/gateway/services/security/impl/ZookeeperRemoteAliasServiceProvider.java
- gateway-server/src/main/java/org/apache/knox/gateway/util/KnoxCLI.java
This PR fixes issue with gateway starting up (due to NPE) when zookeeper remote alias service is configured.
Manual testing with local Zookeeper instance.
> KNOX-1851 - Fix NPE in Zookeeper Remote Alias Service

- gateway-server/src/main/java/org/apache/knox/gateway/services/security/impl/ZookeeperRemoteAliasServiceProvider.java
This is just a cleanup for the previous patch. Removing the unnecessary `registryClientService instanceof ZooKeeperClientService` check so that the ZookeeperRemoteAliasServiceProvider can be generic and not dependent on the ZooKeeperClientService.
Tested locally on my machine with local ZK instance.
> KNOX-1851 - remove the unnecessary instanceof check

- gateway-service-definitions/src/main/resources/services/zeppelinui/0.8.0/rewrite.xml
Update rewrite rule for ZeppelinUI. Current service.xml is sending all the js and webfont files to the rule ZEPPELINUI/zeppelin/inbound/rootAppScript which is looking for a file pattern starting with app. This removes that restriction allow the webfonts to work again.
(Please fill in changes proposed in this fix)
Setup Zeppelin 0.8.0 and Knox and watch the Knox logs for failure to rewrite errors for *.woff files.
Please review [Knox Contributing …
> KNOX-1827 - Knox Fails to Rewrite WebFonts for Zeppelin

- gateway-provider-security-hadoopauth/pom.xml
- gateway-provider-security-hadoopauth/src/main/java/org/apache/knox/gateway/hadoopauth/HadoopAuthMessages.java
- gateway-provider-security-hadoopauth/src/main/java/org/apache/knox/gateway/hadoopauth/deploy/HadoopAuthDeploymentContributor.java
- gateway-provider-security-hadoopauth/src/main/java/org/apache/knox/gateway/hadoopauth/filter/HadoopAuthFilter.java
- gateway-provider-security-hadoopauth/src/test/java/org/apache/knox/gateway/hadoopauth/HadoopAuthDeploymentContributorTest.java
- gateway-provider-security-hadoopauth/src/test/java/org/apache/knox/gateway/hadoopauth/filter/HadoopAuthFilterTest.java
KNOX-1522 added the initial ability to resolve property names to aliases. This was implemented in a way that wasn't optimal. We should improve this so aliases are resolved within the auth filter config itself instead of in the contributor.
This also makes sure we use follow the existing "${ALIAS=...}" convention when resolving the aliases. This is a behavior change but makes it much more readable to know what is an alias vs a plain text value.
`mvn -T.5C clean verify -Ppackage,release`
> KNOX-1859 - Improve alias lookup for HadoopAuthProvider

- gateway-release/home/conf/gateway-site.xml
- gateway-server-xforwarded-filter/src/main/java/org/apache/knox/gateway/filter/XForwardedHeaderFilter.java
- gateway-server-xforwarded-filter/src/main/java/org/apache/knox/gateway/filter/XForwardedHeaderRequestWrapper.java
- gateway-server-xforwarded-filter/src/test/java/org/apache/knox/gateway/filter/XForwardHeaderFilterTest.java
- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-server/src/main/java/org/apache/knox/gateway/deploy/impl/ApplicationDeploymentContributor.java
- gateway-server/src/main/java/org/apache/knox/gateway/deploy/impl/ServiceDefinitionDeploymentContributor.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
- gateway-test-release-utils/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
Add a configurable way to append service name to the X-Forward-Context header
Manually  tested using netcat to check headers.
> KNOX-1858 - Add service name to X-Forwarded-Context header

- gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/AbstractGatewayDispatch.java
- gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/DefaultDispatch.java
- gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/Dispatch.java
- gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/GatewayDispatchFilter.java
the PATCH http method was not implemented and is necessary for certain REST api's (e.g. Apache Metron) to function.
It was tested by manually replacing the gateway-spi jar by the newly built one and validating if the expected functionality works properly.
Before the patch, Knox would return a 405 http error when a patch request was submitted. After the patch, a 200 OK is returned as expected.
> KNOX-1864: Implement PATCH method

- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-server/src/test/java/org/apache/knox/gateway/config/impl/GatewayConfigImplTest.java
Make sure to default `gateway.remote.alias.service.config.type` to `zookeeper` in case it was not set in `gateway-site.xml`
Running JUnit tests.
> KNOX-1848 - Default to 'zookeeper' as remote alias configuration type in case it is not set in gateway-site.xml

- gateway-service-definitions/src/main/resources/services/zeppelinui/0.8.0/service.xml
Set service.xml version to 0.8.0 to match folder structure.
`mvn -T.5C clean verify -Ppackage,release`
> KNOX-1870 - Zeppelin UI service definition service.xml has wrong version

- gateway-service-definitions/src/main/resources/services/ranger/1.0.0/rewrite.xml
- gateway-service-definitions/src/main/resources/services/ranger/1.0.0/service.xml
- gateway-service-definitions/src/main/resources/services/rangerui/1.0.0/rewrite.xml
- gateway-service-definitions/src/main/resources/services/rangerui/1.0.0/service.xml
- gateway-test/src/test/java/org/apache/knox/gateway/deploy/DeploymentFactoryFuncTest.java
Make Ranger service definitions support trusted proxy by default
* Tested proxying Ranger UI and API with updated service definitions on Kerberized cluster
> KNOX-1872 - Update Ranger service definitions to support trusted proxy

- gateway-service-definitions/src/main/resources/services/zeppelinui/0.8.1/rewrite.xml
- gateway-service-definitions/src/main/resources/services/zeppelinui/0.8.1/service.xml
- gateway-service-definitions/src/main/resources/services/zeppelinws/0.8.1/rewrite.xml
- gateway-service-definitions/src/main/resources/services/zeppelinws/0.8.1/service.xml
Make Zeppelin use default dispatch and remove hard coded policies from service definition.
* Manually checked that service definitions work against Kerberized Zeppelin
> KNOX-1876 - Zeppelin should default to trusted proxy for service definition

- gateway-service-definitions/src/main/resources/services/atlas-api/2.0.0/rewrite.xml
- gateway-service-definitions/src/main/resources/services/atlas-api/2.0.0/service.xml
- gateway-service-definitions/src/main/resources/services/atlas/2.0.0/rewrite.xml
- gateway-service-definitions/src/main/resources/services/atlas/2.0.0/service.xml
Add new atlas and atlas-api 2.0.0 service definitions that default to trusted proxy.
* `mvn clean verify -Ppackage,release`
* Manually tested updated service definitions with Kerberized Atlas and Knox
> KNOX-1877 - Atlas service definitions should default to trusted proxy

- gateway-service-definitions/src/main/resources/services/hdfsui/3.0.0/service.xml
Add ha-classname to HDFSUI service definition
* `mvn clean verify -Ppackage,release`
* Checked that HDFSUI service definition works with HaProvider on cluster
> KNOX-1879 - HDFSUI service definition doesn't work with DefaultHaDispatch

- gateway-server/src/main/java/org/apache/knox/gateway/services/security/impl/DefaultKeystoreService.java
Use Java NIO locking to ensure that Keystores are not written to by multiple processes. Removes the read/write lock and falls back to synchronized methods for the few interactions with keystores. Reading should be handled by the OS and will wait until the writing lock is released.
* Will be trying to change aliases with both `knoxcli` and the `gateway` to see if corrupt keystore issue goes away.
> KNOX-1881 - DefaultKeystoreService should use Java NIO API locking as well

- gateway-util-common/src/main/java/org/apache/knox/gateway/util/X509CertificateUtil.java
`X509CertificateUtil` should set both CN and SAN when creating a certificate.
* Knox doesn't compile with IBM so moving forward there.
* Tested with building and running Knox. Checked that OOTB there are 2 SAN cert entries one for `localhost` and the other for the hostname of the machine.
> KNOX-1912 - X509CertificateUtil should set CN and SAN

- gateway-util-common/src/main/java/org/apache/knox/gateway/util/X509CertificateUtil.java
X509CertificateUtil SAN should have both the fully qualified and short hostname.
* Built Knox and checked generated TLS certificate
> KNOX-1915 - X509CertificateUtil SAN should contain fully qualified hostname

- gateway-admin-ui/package-lock.json
- gateway-provider-security-hadoopauth/pom.xml
- gateway-provider-security-hadoopauth/src/main/java/org/apache/knox/gateway/hadoopauth/HadoopAuthMessages.java
- gateway-provider-security-hadoopauth/src/main/java/org/apache/knox/gateway/hadoopauth/filter/HadoopAuthFilter.java
- gateway-provider-security-hadoopauth/src/test/java/org/apache/knox/gateway/hadoopauth/filter/HadoopAuthFilterTest.java
- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/AbstractRequest.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/knox/token/Get.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/knox/token/Token.java
- gateway-shell/src/test/java/org/apache/knox/gateway/shell/AbstractRequestTest.java
- gateway-shell/src/test/java/org/apache/knox/gateway/shell/knox/token/GetTest.java
- gateway-shell/src/test/java/org/apache/knox/gateway/shell/knox/token/TokenTest.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
- gateway-test-release-utils/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
There are token exchange scenarios where an application may want to acquire a KnoxToken on behalf of a user authenticated by the application. We need to implement a version of the Hadoop Trusted Proxy/Impersonation pattern for Knox at the topology level.
This includes:
- Principal assertion method (possibilities: doAs query param, path segment within an API, HTTP header)
-  Config within topology for trusted principals, groups that they are allowed to impersonate, users that they are allowed to impersonate, ip address from which requests are expected
- Make part of the identity assertion provider since this is the provider that determines which identity to assert to the down stream service
- Config will need to be qualified by service due to the multiple services per topology
- (Please …
> KNOX-1740 - Add Trusted Proxy Support to Knox

- gateway-server/src/main/java/org/apache/knox/gateway/services/security/impl/DefaultKeystoreService.java
Use a shared read lock to ensure that multiple processes won't read/write at the same time.
`mvn -T.5C clean verify -Ppackage,release`
> KNOX-1917 - DefaultKeystoreService should use a shared read lock

- gateway-service-definitions/src/main/resources/services/atlas-api/0.1.2.0/rewrite.xml
- gateway-service-definitions/src/main/resources/services/atlas-api/0.8.0/rewrite.xml
- gateway-service-definitions/src/main/resources/services/atlas-api/2.0.0/rewrite.xml
Prevent global HDFS rules from triggering when using Atlas API
* Checked that hdfs urls are not changed when using Atlas API
> KNOX-1918 - Atlas API - prevent global HDFS rules from triggering

- gateway-provider-security-shiro/src/main/java/org/apache/knox/gateway/filter/RedirectToUrlFilter.java
- gateway-provider-security-shiro/src/test/java/org/apache/knox/gateway/filter/RedirectToUrlFilterTest.java
- gateway-release/home/conf/topologies/knoxsso.xml
Before my change, the `redirectToUrl` parameter in the OOTB `knoxsso.xml` topology was hardcoded to `/gateway/knoxsso/knoxauth/login.html`. In case we changed the `gateway.path` configuration element the admin UI became unreachable. If you knew where to find the root cause it was easy to fix it, but we can do this smarter.
I changed the sample URL to `/${GATEWAY_PATH}/knoxsso/knoxauth/login.html` and made sure to replace the `${GATEWAY_PATH}` placeholder with the actual value of `gateway.path`.
Tested manually as follows: 
1. changed `gateway.path` to `smolnar_test` in `gateway-site.xml`
2. restarted the server
3. hit the following URL: `https://localhost:8443/smolnar_test/manager/admin-ui/`
4. as expected I got redirected to the proper URL
> KNOX-1919 - Taking gateway.path into consideration when processing redirectToUrl provider param with the OOTB knoxsso.xml sample

- .travis.yml
- gateway-release-common/home/bin/knox-functions.sh
- gateway-release-common/pom.xml
- gateway-release/home/bin/gateway.sh
- gateway-release/home/bin/knoxcli.sh
- gateway-release/home/bin/ldap.sh
- gateway-release/pom.xml
- gateway-shell-release/home/bin/knoxshell.sh
- gateway-shell-release/pom.xml
- pom.xml
[Shellcheck](https://www.shellcheck.net/) is a very useful tool that helps developers to avoid common pitfalls with their bash scripts. The following changes were made:
1. optionally added shellcheck validation to knox build in these sub-projects:
- gateway-release
- gateway-release-common
- gateway-shell-release
To activate this feature the command should include `-Dshellcheck=true` (by default this is turned off).
**Note:** since there is no official Maven plugin for shellcheck you need to install the tool manually first. According to its [Github readme](https://github.com/koalaman/shellcheck#travis-ci) Travis CI comes with built-in shellcheck so it should be safe to include that flag in our TravisCI build.
2. I fixed our shell scripts to conform shellcheck
Built the project with and …
> KNOX-1816 - Optionally added shellcheck validation to our build and fixed issues shellcheck already found

- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/AbstractJWTFilterTest.java
- gateway-util-common/src/main/java/org/apache/knox/gateway/util/X509CertificateUtil.java
Checking if hostname starts with a letter before generating a `DNSName` with it.
Running JUnit test with Oracle JDK u151 (I was able to reproduce this issue with that JDK):
```
$ export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/
$ java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
$ mvn clean -T1C verify -Prelease,package
...
[INFO] Total time: 27:04 min (Wall Clock)
[INFO] Finished at: 2019-07-16T11:08:16+02:00
[INFO] Final Memory: 380M/2163M
[INFO] …
```
> KNOX-1922 - Processing a DNSName only if the hostname starts with a letter

- gateway-service-definitions/src/main/resources/services/sparkhistoryui/2.3.0/rewrite.xml
Testing Done:
Deployed on a cluster with Knox and ensured that the URLs are rewritten
> KNOX-1744 - Add rewrite rules to fix executor stdout/stderr links in Spark History Server UI

- gateway-provider-rewrite/src/main/java/org/apache/knox/gateway/filter/rewrite/i18n/UrlRewriteMessages.java
- gateway-provider-rewrite/src/main/java/org/apache/knox/gateway/filter/rewrite/impl/json/JsonUrlRewriteFilterReader.java
- gateway-provider-rewrite/src/test/java/org/apache/knox/gateway/filter/rewrite/api/UrlRewriteServletFilterTest.java
This change affects inbound requests with JSON payloads that do not have any rewrite rules defined. Currently Knox will try to apply the *best match* from all the inbound rules which in most cases is problematic. This patch will prevent rewriting inbound JSON payloads unless there a rewrite rule is explicitly defined for that request payload. 
This change will not affect other rewrite functionality.
This patch was manually tested and unit tests provided.
> KNOX-1948 - If no rules are defined don't rewrite

- gateway-admin-ui/admin-ui/app/gateway-version.service.ts
- gateway-admin-ui/admin-ui/app/resource/resource.service.ts
- gateway-admin-ui/admin-ui/app/topology.service.ts
Use `window.location` instead of hardcoding the API endpoints
* `mvn -T.5C clean verify -Ppackage,release -Dshellcheck`
* Ran built Knox and updated `gateway.path` in `gateway-site.xml` and checked the AdminUI
> KNOX-1955 - Admin UI should handle gateway.path change

- gateway-service-definitions/src/main/resources/services/ranger/1.0.0/rewrite.xml
- gateway-service-definitions/src/main/resources/services/ranger/1.0.0/service.xml
Added Request paths in the Knox Ranger service definition allowed paths and rewrite rules.
Verified that the calls to the allowed path are accessible through proxy.
> KNOX-1963 - Ranger API service should proxy xusers/users and and xusers/groups

- gateway-server/src/main/java/org/apache/knox/gateway/GatewayMessages.java
- gateway-server/src/main/java/org/apache/knox/gateway/GatewayServer.java
- gateway-server/src/main/java/org/apache/knox/gateway/filter/PortMappingHelperHandler.java
- gateway-test/src/test/java/org/apache/knox/gateway/GatewayDefaultTopologyTest.java
- gateway-test/src/test/java/org/apache/knox/gateway/GatewayPortMappingFailTest.java
- gateway-test/src/test/java/org/apache/knox/gateway/GatewayPortMappingFuncTest.java
- gateway-test/src/test/java/org/apache/knox/gateway/PortMappingHelper.java
Currently with topology port mapping feature, port mapped topologies are exposed on gateway port as well (default 8443) this is undesirable in a lot of cases. This feature locks the topologies that are mapped to specific port to only those ports and they are not exposed on the default gateway port. 
There are new and old Unit tests added to test this feature. This patch was tested locally. Following cases were tested.
1. Make sure topology port mapping feature works as expected.
2. Make sure port mapped topologies are not exposed on gateway port.
3. Make sure default topology feature works as expected.
4. Make sure default topology can also …
> KNOX-1694 - Prevent port mapped topologies from being exposed to gateway port

- gateway-release/pom.xml
- gateway-service-definitions/src/main/resources/services/impala/1.0.0/rewrite.xml
- gateway-service-definitions/src/main/resources/services/impala/1.0.0/service.xml
- gateway-service-impala/pom.xml
- gateway-service-impala/src/main/java/org/apache/knox/gateway/impala/ImpalaDispatch.java
- gateway-service-impala/src/main/java/org/apache/knox/gateway/impala/ImpalaDispatchUtils.java
- gateway-service-impala/src/main/java/org/apache/knox/gateway/impala/ImpalaHaDispatch.java
- pom.xml
Allows for proxying connections to Impala's Hiveserver2 interface.
The service definition is based on Hive's Hiveserver2 definition.
Impala does not currently support HA.
Tested by setting up Impala and Knox in a real cluster and verifying that Impala can be connected to over Knox and queries can be run through jdbc and impala-shell
> KNOX-1967 - Add a service definition for Impala Hiveserver2

- gateway-provider-rewrite/src/main/java/org/apache/knox/gateway/filter/rewrite/impl/UrlRewriteRequest.java
- gateway-provider-rewrite/src/test/java/org/apache/knox/gateway/filter/rewrite/impl/UrlRewriteRequestTest.java
- gateway-test-utils/src/main/java/org/apache/knox/test/mock/MockServletInputStream.java
Prevent Knox from rewriting empty payload, this is especially problematic for xml content types.
(Please fill in changes proposed in this fix)
See if there is payload data if not skip adding rewrite filters.
Manually tested. Unit test added as well.
> KNOX-1986 - Do not attempt to rewrite empty payload

- gateway-service-definitions/src/main/resources/services/sparkhistoryui/2.3.0/rewrite.xml
KNOX-1744 fixed the links but made them point to the old YARN UI.
Change the links to point to YARN UI v2.
Tested manually. Applied the change to a cluster and verified the links in the Knox-proxied Spark History Server.
> KNOX-1988 - In Spark History Server UI, make links for Executor logs point to YARN UI v2

- gateway-service-remoteconfig/src/test/java/org/apache/knox/gateway/service/config/remote/zk/RemoteConfigurationRegistryJAASConfigTest.java
`RemoteConfigurationRegistryJAASConfigTest.shouldRaiseAnErrorWithMeaningfulErrorMessageXXX` fails while Travis CI is building the project upon submitting a new PR (or patch) in Github, intermittently.
This was happening due to the parallel JUnit test execution (I could never reproduce this issue while running that test class sequentially from my IDE) because those test cases manipulated the System properties by setting valid/non-existing/non-parsable JAAS configuration. To fix this issue I made sure these test cases are running sequentially.
Executed `mvn clean -Dshellcheck=true -T1C verify -Prelease,package -pl gateway-service-remoteconfig` 10 times with the following outcome:
1. before my changes: failed 4 times out of 10
2. after my changes: succeeded every time
> KNOX-1990 - Testing non-existing/non-parsable JAAS configuration in sequential order even if parallel test execution is enabled

- gateway-release/home/conf/topologies/knoxsso.xml
- gateway-service-knoxsso/pom.xml
- gateway-service-knoxsso/src/main/java/org/apache/knox/gateway/service/knoxsso/WebSSOResource.java
- gateway-service-knoxsso/src/test/java/org/apache/knox/gateway/service/knoxsso/WebSSOResourceTest.java
In case the `knoxsso.cookie.secure.only` is not set we use the value of `ssl.enabled` flag (defaults to true). Using this approach and not setting `knoxsso.cookie.secure.only` in our OOTB `knoxsso.xml` makes it easier to access the admin UI without the need to edit the `knoxsso` topology in case SSL is disabled.
Adding new JUnit tests:
```
$ mvn clean -Dshellcheck=true -T1C verify -Prelease,package
...
[INFO] Total time: 17:33 min (Wall Clock)
[INFO] Finished at: 2019-08-25T17:21:54+02:00
[INFO] Final Memory: 384M/2246M
```
Also …
> KNOX-1934 - Setting the default value of knoxsso.cookie.secure.only based on ssl.enabled flag in gateway-site.xml

- gateway-service-definitions/src/main/resources/services/webhdfs/2.4.0/rewrite.xml
All WEBHDFS rules are global for backwards compatibility, as a result the rule 'WEBHDFS/webhdfs/outbound' is rewriting links from AtlasUI.
There is no reason to rewrite hdfs:// to https://, at-least for other UIs so we need to limit the scope of this rule to local scope from global scope.
The fix is to make the scope of this rule local.
The patch was manually tested on a local hadoop cluster.
> KNOX-1999 - Make WEBHDFS rule that rewrites hdfs:// local

- gateway-admin-ui/admin-ui/app/provider-config-wizard/webappsec-wizard.ts
- gateway-admin-ui/admin-ui/app/provider-config-wizard/xss-provider-config.ts
The `XSSProtectionFilter` has been added more than a year ago but there was no support to configure this filter on the `Admin UI`
Running JUnit tests and executed the following E2E test steps:
1. built and deployed Knox locally then logged into the `Admin UI`
2. added a new `Provider Configuration`: set the name to `smolnarTest` and selected `Web Application Security` from the provider category list and clicked the `Next` button
3. the new option - `X-XSS-Protection` - was displayed in the `Web Application Security Provider Type` list; I choose it and clicked the `Next button`
4. The only parameter for this provider was shown with the appropriate default value (`1;mode=block`)
5. I tested different invalid inputs to see if validation works as expected
6. Saved the newly created provider …
> KNOX-1788 - New XSS Provider is added to Web Application Security Provider List

- gateway-service-definitions/src/main/resources/services/rangerui/1.0.0/service.xml
This PR updates the dispatch for RangerUI from DefaulrDispatch to ConfigurableDispatch. This is done to allow SET-COOKIE response header to pass through Knox.
> KNOX-2011 - Don't block SET-COOKIE response header for Ranger UI

- gateway-service-definitions/src/main/resources/services/webhdfs/2.4.0/rewrite.xml
- gateway-service-definitions/src/main/resources/services/webhdfs/2.4.0/service.xml
rewrite.xml for webhdfs service definition does not have rewrite rule for Location field in json response. The location field contains a url which must be rewritten.
> KNOX-1998: WebHDFS rewrite.xml does not have rewrite rule for Location field in json

- gateway-discovery-cm/pom.xml
- pom.xml
Fixing build issue of MAven cannot find Cloudera dependencies in all Knox Maven projects (other than `gateway-discovery-cm`.
Running JUnit tests and checked manually if the packaged deliverable has the `cloudera-manager-api-swagger:jar`
> KNOX-2017 - Making Cloudera repository available in Knox's parent POM so that Cloudera dependencies are available in every children project

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/phoenix/PhoenixServiceModelGenerator.java
- gateway-discovery-cm/src/main/resources/META-INF/services/org.apache.knox.gateway.topology.discovery.cm.ServiceModelGenerator
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryTest.java
Adding a new module to CM discovery to automatically create AVATICA service that can be used to access the Phoenix Query Servers running in the cluster
I have brought up a test cluster, added "AVATICA" to the list autoconfigured services, started autodiscovery, and checked that the default.xml topology file gets correctly generated.
I have also connected to the Phoenix Query Server via Knox.
> KNOX-2013 - CM discovery - Add Phoenix to auto discovery

- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/dispatch/AtlasTrustedProxyHaDispatch.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/dispatch/ConfigurableHADispatch.java
- gateway-service-definitions/src/main/resources/services/atlas/2.0.0/service.xml
This PR contains two changes
1. Update Atlas dispatch from DefaultDispatch to ConfigurableDispatch so set-cookie header is not blocked.
2. DefaultHADispatch now extends ConfigurableDispatch. It is possible to create a new dispatch ConfigurableHADispatch but that would be unnecessary code duplication. If anyone thinks this is a better way let me know.
> KNOX-2014 - Make sure ATLASSESSIONID cookie is set

- gateway-server/pom.xml
- pom.xml
Upgrade jaxws-ri version to 2.3.2 so that it uses the same version (2.7.4) of eclipse persistence classes.
Otherwise, there are these files in knox/dep folder, and depends on loading sequence of classloader, you might encouter the NoSuchFieldError:
eclipselink-2.7.4.jar
org.eclipse.persistence.core-2.7.2.jar
org.eclipse.persistence.moxy-2.7.2.jar
org.eclipse.persistence.asm-2.7.2.jar
org.eclipse.persistence.sdo-2.7.2.jar
Manual tests
> KNOX-1987: knox failed to start because knoxcli failed with "java.lan…g.NoSuchFieldError: DEFAULT_XML_TYPE_ATTRIBUTE"

- gateway-docker/README.md
Fixing Typo related to gateway docker files path in README.md
> KNOX-2021 - Fix typo in gateway-docker/README.md

- gateway-shell/src/main/java/org/apache/knox/gateway/shell/table/KnoxShellTableFilter.java
- gateway-shell/src/test/java/org/apache/knox/gateway/shell/table/KnoxShellTableFilterTest.java
Added lessThan, greaterThanOrEqualTo, lessThanOrEqualTo, and equalTo methods for KnoxShellTable. 
Unit and manual tests
> KNOX-2018 - KnoxShellTable Filtering needs greaterThan and lessThan, equals Methods

- gateway-service-storm/src/main/java/org/apache/knox/gateway/storm/StormDispatch.java
- gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/ConfigurableDispatch.java
- gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/DefaultDispatch.java
- gateway-spi/src/test/java/org/apache/knox/gateway/dispatch/ConfigurableDispatchTest.java
As of now, end-users can either exclude the SET-COOKIE header entirely (as well as any other request/response header) or include it in the outbound response by invoking `ConfigurableDispatch.setResponseExcludeHeaders` with the appropriate `Set`. What this change brought to the table is that certain SET-COOKIE headers are excluded but some of them are not. 
For instance:
- let say the following header is set in the inbound response: `Set-Cookie: Domain=<domain-value>; Secure; HttpOnly`
- as of now, one can configure Knox to exclude all of these (in fact the default setting is to exclude the SET-COOKIE header)
- however, one may want to configure Knox to exclude only the `Domain=<domain-value>` name/value pair going forward -> the outbound response header will still contain `Set-Cookie: …
> KNOX-2015 - Allow end-users to exclude only certain directives of the SET-COOKIE HTTP header

- gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/HadoopAuthCookieStore.java
This patch modifies HadoopAuthCookieStore to accept cookies with
Impala's cookie name, "impala.auth".
It also updates a check that is used to ensure the cookie belongs to
Knox - previously, this check parsed the cookie according to the
specific format that Hadoop uses for its cookies and ensures that the
Knox principal appears in the expected location.
Impala uses a similar cookie format, but with a few changes such as
fields being in a different order. The check is made more permissive
such that it will accept any cookie that contains the Knox principal
anywhere in it.
Testing:
- Deployed in a cluster and verified that Knox accepts and returns
Impala's cookies as expected.
> KNOX-2026: Accept Impala's authentication cookies

- gateway-shell/pom.xml
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/table/KnoxShellTable.java
- gateway-shell/src/test/java/org/apache/knox/gateway/shell/table/KnoxShellTableTest.java
- pom.xml
Added mean, median, mode, sum, max, min, and toDoubleArray methods so to enable usage of the Apache Commons math StatUtils library (methods require double[]). 
Manual and unit tests.
> KNOX-2052 - KnoxShellTable mean, median, and mode methods

- gateway-shell/src/main/java/org/apache/knox/gateway/shell/table/KnoxShellTable.java
- gateway-shell/src/test/java/org/apache/knox/gateway/shell/table/KnoxShellTableTest.java
Added ability to convert columns of type String to double[] for operations with StatUtils (mean, median, mode, etc). 
Manual and unit tests.
> KNOX-2060 - Extend KnoxShellTable statistics methods to work with columns of Strings

- gateway-admin-ui/admin-ui/app/app.component.ts
- gateway-admin-ui/admin-ui/app/app.module.ts
- gateway-admin-ui/admin-ui/app/resource-detail/resource-detail.component.html
- gateway-admin-ui/admin-ui/app/resource/resource.component.html
- gateway-admin-ui/admin-ui/app/resource/resource.component.ts
- gateway-admin-ui/admin-ui/app/resource/resource.service.ts
- gateway-admin-ui/admin-ui/app/resourcetypes/resourcetypes.service.ts
- gateway-admin-ui/admin-ui/app/service-definition/rewrite.rule.ts
- gateway-admin-ui/admin-ui/app/service-definition/rewrite.rules.ts
- gateway-admin-ui/admin-ui/app/service-definition/service.ts
- gateway-admin-ui/admin-ui/app/service-definition/servicedefinition-detail.component.ts
- gateway-admin-ui/admin-ui/app/service-definition/servicedefinition.service.ts
- gateway-admin-ui/admin-ui/app/service-definition/servicedefinition.ts
- gateway-admin-ui/package-lock.json
- gateway-admin-ui/package.json
- gateway-server/src/main/java/org/apache/knox/gateway/GatewayMessages.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/registry/impl/DefaultServiceDefinitionRegistry.java
- gateway-service-admin/src/main/java/org/apache/knox/gateway/service/admin/ServiceDefinitionCollectionMarshaller.java
- gateway-service-admin/src/main/java/org/apache/knox/gateway/service/admin/ServiceDefinitionsResource.java
- gateway-service-admin/src/main/java/org/apache/knox/gateway/service/admin/TopologiesResource.java
The following features are implemented with this PR:
- listing existing service definitions in admin UI (using pagination since Knox comes with 65 service definitions OOTB)
- end-users can remove a service definition
- end-users can update a service definition
Tested locally:
Listing:
Updating:
Deleting:
> KNOX-2056 - Adding Service Definitions management into Admin UI

- gateway-service-definitions/src/main/resources/services/kuduui/1.0.0/rewrite.xml
- gateway-service-definitions/src/main/resources/services/kuduui/1.0.0/service.xml
This patch adds a new service definition for accessing Apache Kudu's web UI.
Like Apache Impala, every server has a web UI, so we use scheme/host/port
query parameters to disambiguate between servers. Unlike Impala, the Kudu
web UI will add /KNOX-BASE tokens to URLs in its web pages when it detects
it is being proxied by Knox; we use these tokens as the basis for pattern
matching in our rewrite rules.
I tried to avoid cargo culting from existing service definitions and I added
comments to explain syntax and other things that weren't obvious to me as a
non-Knox developer.
I tested this manually by deploying a small Kudu cluster on my machine along
with a Knox gateway and a really simple topology. I then browsed every page
in the web UI and verified its correct behavior.
> KNOX-2072: Kudu web UI service definition

- gateway-shell/src/main/java/org/apache/knox/gateway/shell/table/JoinKnoxShellTableBuilder.java
- gateway-shell/src/test/java/org/apache/knox/gateway/shell/table/KnoxShellTableTest.java
Overloaded method to join on columns of the same data with different names (ex. ID vs Student_ID)
Manual and unit tests.
> KNOX-2025 - KnoxShellTable - Join Builder on Method should accept Col Names

- gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/DefaultHttpClientFactory.java
- gateway-spi/src/test/java/org/apache/knox/gateway/dispatch/DefaultHttpClientFactoryTest.java
- gateway-test-utils/src/main/java/org/apache/knox/test/mock/MockRequestMatcher.java
- gateway-test/src/test/java/org/apache/knox/gateway/GatewayBasicFuncTest.java
- pom.xml
HttpClient 4.5.7 broke url normalization. Knox
didn't have any tests for this case and so we
had to revert after the fact. HttpClient 4.5.8
fixed a lot of the url normalization and some
libraries decided to turn url normalization off.
This commit does the following:
* Adds a test for %2F - KNOX-1005
* This test passes under HttpClient 4.5.6 and 4.5.8+
* It breaks as expected under HttpClient 4.5.7
* Adds an explicit config enabling url normalization
* Ensures that we are in control of url normalization
* Adds a test for this configuration as well
* Test with both HttpClient normalization enabled and disabled
* `rest-assured` doesn't expose `RequestConfig` to disable
url normalization
* Shows how to use HttpClient in `GatewayBasicFuncTest`
All the url safe characters like %2F are fixed by …
> KNOX-1842 - Upgrade httpclient to 4.5.10

- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/AliasBasedTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/DefaultTokenStateService.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/DefaultTokenStateServiceTest.java
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
- gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/TokenStateService.java
Added the ability to specify the maximum token lifetime (i.e., token renewal limit) via topology service params.
Ran automated unit/integration tests and manual tests.
Manual tests included configuration a short maximum token lifetime, attempting to renew a token (via curl), and verifying the error response.
> KNOX-2071 - Configurable maximum token lifetime for TokenStateService

- gateway-test-release/pom.xml
- pom.xml
Use maven enforcer plugin to make sure only single version of dependency is included.
> KNOX-1878 - Enforce single version of dependencies

- gateway-shell/src/main/java/org/apache/knox/gateway/shell/ErrorResponse.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/knox/token/AbstractTokenLifecycleRequest.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/knox/token/Renew.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/knox/token/Revoke.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/knox/token/Token.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/knox/token/TokenLifecycleResponse.java
- gateway-shell/src/test/java/org/apache/knox/gateway/shell/knox/token/TokenTest.java
Adds KnoxShell support for Knox token renewal and revocation.
Automated unit/integration tests, manual tests. Manual testing included the groovy script attached to the JIRA issue, invoked with different user credentials (some in the configured whitelist, others not).
> KNOX-2105 - KnoxShell support for token renewal and revocation

- gateway-admin-ui/admin-ui/app/resource/resource.component.ts
Staying on the same page after updating/removing a Knox resource (note: currently only `Service Definitions` is displayed with pagination since the number of other resources is less than 10).
(another note: having this one line change is a result of several hours of coding and analyzing `DataTable` and trying to understand why did `activePage` always got reset even if I told the exact number. That one line caused the headache :) )
See [this video](https://streamable.com/so8wi) about my manual testing.
> KNOX-2104 - Removing redundant resource cleanup so that data table can keep track of its activePage/rowsOnTable attributes

- pom.xml
The dom4j Maven coordinates changed from 1.x to 2.x.
See https://github.com/dom4j/dom4j/issues/58 for details.
There are some CVEs associated with the older version so should upgrade.
`mvn -T.5C verify -Ppackage,release -Dshellcheck`
> KNOX-2112 - Upgrade dom4j to 2.1.1

- gateway-shell-release/home/bin/knoxshell.sh
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/Shell.java
Eliminated 1 of the 2 entry points in the `knoxshell.sh`. Only invoking `org.apache.knox.gateway.shell.Shell` results in the `launcher` framework doing its job (setting launcher.name, log4j configuration, etc..). The removed bash logic has been moved to the Java class.
```
$ bin/knoxshell.sh destroy
$ bin/knoxshell.sh list
Knox token cache does not exist. Please login with init.
$ bin/knoxshell.sh init https://localhost:8443/gateway/sandbox
Enter username: admin
Enter password: 
knoxinit successful!
Token Type: Bearer
Expires On: 11/09/2019 02:26:20
Target URL: https://localhost:8443/gateway/tokenbased
$ ls -al logs/
total 0
drwxr-xr-x   3 smolnar  staff  102 Nov  8 15:49 .
drwxr-xr-x  10 smolnar  staff  340 Nov  8 15:49 ..
-rw-r--r--   1 smolnar  staff    0 Nov  8 15:49 …
```
> KNOX-2100 - Make sure knoxshell initializes logging by using the 'launcher' framework like other products (gateway, cli, ldap) do

- .travis.yml
* Cleanup workarounds that are no longer valid in .travis.yml.
* Mount docker to be able to run the docker tests.
* Reduce parallelism slightly to avoid saturating Travis worker.
* Clean/update dependencies to ensure latest are picked up.
Checking travis output :)
> KNOX-2115 - Improve .travis.yml

- gateway-shell/src/main/java/org/apache/knox/gateway/shell/KnoxSh.java
- gateway-shell/src/test/java/org/apache/knox/gateway/shell/KnoxShTest.java
Using the default port of the protocol when no port is declared in the URL when building truststore
Added new unit test cases as well as tested manually:
```
mvn clean -Dshellcheck=true -T1C verify -Prelease,package -am -pl gateway-shell-release
...
[INFO] Reactor Summary:
[INFO] 
[INFO] build-tools ........................................ SUCCESS [  1.747 s]
[INFO] gateway ............................................ SUCCESS [ 23.531 s]
[INFO] gateway-test-utils ................................. SUCCESS [ 12.192 s]
[INFO] gateway-i18n ....................................... SUCCESS [ 10.662 s]
[INFO] gateway-util-common ................................ SUCCESS [ 15.405 s]
[INFO] gateway-util-launcher …
```
> KNOX-2099 - Using the default port of the protocol when no port is declared in the URL when building truststore.

- gateway-provider-ha/src/test/java/org/apache/knox/gateway/ha/provider/impl/AtlasZookeeperURLManagerTest.java
- gateway-provider-ha/src/test/java/org/apache/knox/gateway/ha/provider/impl/HBaseZookeeperURLManagerTest.java
- gateway-provider-ha/src/test/java/org/apache/knox/gateway/ha/provider/impl/HS2ZookeeperURLManagerTest.java
- gateway-provider-ha/src/test/java/org/apache/knox/gateway/ha/provider/impl/KafkaZookeeperURLManagerTest.java
- gateway-provider-ha/src/test/java/org/apache/knox/gateway/ha/provider/impl/SOLRZookeeperURLManagerTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/security/impl/ZookeeperRemoteAliasMonitorTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/security/impl/ZookeeperRemoteAliasServiceTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/topology/monitor/ZooKeeperConfigurationMonitorTest.java
- gateway-service-remoteconfig/src/test/java/org/apache/knox/gateway/service/config/remote/zk/RemoteConfigurationRegistryClientServiceTest.java
- gateway-test/src/test/java/org/apache/knox/gateway/topology/monitor/RemoteConfigurationMonitorTest.java
Our Zookeeper tests don't require 3 instances
for them to run. We can instead use 1 instance
and run the tests with fewer resources.
The timeout for cluster starting up is determined
by hostname lookup speed and can't easily be changed.
https://github.com/apache/curator/blob/master/curator-test/src/main/java/org/apache/curator/test/TestingZooKeeperMain.java#L74
> KNOX-2121 - Zookeeper - Reduce amount of resources required to run tests

- gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/ConfigurableDispatch.java
- gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/DefaultDispatch.java
- gateway-spi/src/test/java/org/apache/knox/gateway/dispatch/ConfigurableDispatchTest.java
- gateway-util-common/src/main/java/org/apache/knox/gateway/util/StringUtils.java
- gateway-util-common/src/test/java/org/apache/knox/gateway/util/StringUtilsTest.java
Make responseExcludeHeaders parameter in ConfigurableDispatch case insensitive
Updated and executed JUnit tests:
```
[INFO] Total time: 18:06 min (Wall Clock)
[INFO] Finished at: 2019-11-12T18:40:30+01:00
[INFO] Final Memory: 379M/2012M
```
> KNOX-2103 - Make responseExcludeHeaders parameter in ConfigurableDispatch case insensitive

- gateway-test/src/test/resources/log4j.properties
Disable logging `org.apache.directory.api.ldap.model.entry.Value` ERRORs when running `gateway-test` tests. There might be other places this applies but this is a majority of the integration tests.
> KNOX-1718 - Hide org.apache.directory.api.ldap.model.entry.Value errors

- gateway-discovery-ambari/src/main/java/org/apache/knox/gateway/topology/discovery/ambari/AmbariConfigurationMonitor.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/dispatch/ConfigurableHADispatch.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/dispatch/DefaultHaDispatch.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/topology/impl/DefaultTopologyService.java
- gateway-service-rm/src/main/java/org/apache/knox/gateway/rm/dispatch/RMHaBaseDispatcher.java
- gateway-service-webhdfs/src/main/java/org/apache/knox/gateway/hdfs/dispatch/AbstractHdfsHaDispatch.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/KnoxSession.java
- gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/KnoxSpnegoAuthScheme.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/impl/CMFMasterService.java
- gateway-test-utils/src/main/java/org/apache/knox/test/TestUtils.java
- gateway-util-common/src/main/java/org/apache/knox/gateway/audit/log4j/appender/JdbmStoreAndForwardAppender.java
Currently we catch interrupted exception in a bunch of places. We should at minimum let the calling method know that we have been interrupted. See the Jira for a description and rationale.
> KNOX-2130 - Handle InterruptedException better

- build-tools/src/main/resources/build-tools/forbiddenapis/signatures.txt
- gateway-server/src/main/java/org/apache/knox/gateway/util/KnoxCLI.java
- gateway-service-test/src/main/java/org/apache/knox/gateway/service/test/ServiceTestResource.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/KnoxSession.java
- gateway-spi/pom.xml
- gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/DefaultHttpClientFactory.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/impl/CMFMasterService.java
- pom.xml
Use forbiddenapis to block poor TLS usage. Note this could break some of the CLI stuff if using a self signed certificate. Fix the truststore instead :) The KnoxShell classes provide a way to properly setup the truststore. 
`mvn -T.75C verify -Ppackage,release -Dshellcheck`
> KNOX-2133 - Ensure that Knox always validates TLS

- gateway-server/src/main/java/org/apache/knox/gateway/websockets/MessageEventCallback.java
- gateway-server/src/main/java/org/apache/knox/gateway/websockets/ProxyInboundClient.java
- gateway-server/src/main/java/org/apache/knox/gateway/websockets/ProxyWebSocketAdapter.java
- gateway-server/src/test/java/org/apache/knox/gateway/websockets/ProxyInboundClientTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/websockets/WebsocketClient.java
- gateway-server/src/test/java/org/apache/knox/gateway/websockets/WebsocketServerInitiatedPingTest.java
Changes add a new message handler for handling Ping/Pong messages from backend websocket server and relay the same to Frontend. Ping/Pong messages are control messages to keep websocket connection alive.
Changes were tested on a local test setup to check if websocket was indeed kept alive and it was working. In absence of these changes, any Ping messages received from backend server, were being responded by lower jetty server layer and were propagated to front end. Because of this, Frontend connection was getting timed out. With these changes, timeouts were not seen.
I have also added a Unit Test for the same.
> KNOX-2004 - Adding changes for handling Ping/Pong message from backend server on websocket connection

- gateway-service-definitions/src/main/resources/services/yarnui/2.7.0/rewrite.xml
Add slash to rewrite template of *YARNUI/yarn/outbound/proxy*, *YARNUI/yarn/outbound/apps/history*, *YARNUI/yarn/outbound/proxy1*.
> KNOX-2074: Tracking UI of flink session is broken in YARNUI

- gateway-server/src/main/java/org/apache/knox/gateway/filter/PortMappingHelperHandler.java
- gateway-server/src/main/java/org/apache/knox/gateway/filter/RequestUpdateHandler.java
- gateway-server/src/test/java/org/apache/knox/gateway/filter/ForwardedRequestTest.java
`RequestUpdateHandler.FrowardedRequest#getRequestURL` needs to return a valid URL per the interface contract.
* Checked that `getRequestURL` properly generates a valid requestURL.
> KNOX-2140 - RequestUpdateHandler.ForwardedRequest#getRequestURL needs to return a valid URL

- gateway-shell/src/main/java/org/apache/knox/gateway/shell/alias/AbstractAliasRequest.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/alias/Alias.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/alias/AliasResponse.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/alias/DeleteRequest.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/alias/ListRequest.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/alias/PostRequest.java
- gateway-shell/src/test/java/org/apache/knox/gateway/shell/alias/AliasTest.java
Added KnoxShell classes for interacting with the Alias Service API.
Unit tests, and manual tests. Attached ExampleAliases.groovy to the JIRA issue.
> KNOX-1410 - Knox Shell support for remote Alias management

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerCluster.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ServiceModel.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ServiceURLCollector.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/collector/AbstractURLCollector.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/collector/DefaultURLCollector.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/collector/HueURLCollector.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/collector/ServiceURLCollectors.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/AbstractServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/atlas/AtlasServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/hue/HueLBServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/hue/HueServiceModelGenerator.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/collector/AbstractURLCollectorTest.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/collector/HueURLCollectorTest.java
Added ServiceURLCollector abstraction for services like Hue, where URLs have to be selectively chosen based on the roles deployed. Employed this abstraction to deal with Hue Load Balancer.
Ran existing CM discovery tests, added HueURLCollectorTest, and manually tested CM service discovery against a cluster with Hue Load Balancer deployed.
> KNOX-1935 - CM discovery - Hue should not have both LB and non LB

- gateway-server/src/main/java/org/apache/knox/gateway/GatewayFilter.java
- gateway-server/src/main/java/org/apache/knox/gateway/GatewayServlet.java
- gateway-server/src/main/java/org/apache/knox/gateway/util/ServletRequestUtils.java
If the service was unavailable at the time of the service was being served then there was no `SOURCE_REQUEST_CONTEXT_URL_ATTRIBUTE_NAME` attribute set in the given `servletRequest`. This led to a NPE when logging into audit log. Another mistake was that we did not consider the action-outcome in this case and we tried to log everything as `SUCCESS`. I changed this too.
Running JUnit tests:
```
mvn clean -Dshellcheck=true -T1C verify -Prelease,package
...
[INFO] Total time: 19:31 min (Wall Clock)
[INFO] Finished at: 2019-12-16T15:58:38+01:00
[INFO] Final Memory: 412M/1951M
[INFO] …
```
> KNOX-2123 - Setting requestURI using the given servletRequest in case the service is unavailable and logging it with the appropriate action outcome

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/collector/HueURLCollector.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/collector/HueURLCollectorTest.java
Added support for SSL-enabled Hue load balancer URLs.
Ran existing CM discovery tests, added HueURLCollectorTest#testLBSSL(), and manually tested CM service discovery against a cluster.
> KNOX-1921 - CM discovery - Hue Load balancer HTTP/HTTPS scheme

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/hive/WebHCatServiceModelGenerator.java
- gateway-discovery-cm/src/main/resources/META-INF/services/org.apache.knox.gateway.topology.discovery.cm.ServiceModelGenerator
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryTest.java
Added support for WEBHCAT service discovery from CM.
Ran existing CM discovery tests, added ClouderaManagerServiceDiscoveryTest#testWebHCatDiscovery(), and manually tested CM service discovery against a cluster.
> KNOX-1932 - CM discovery - WEBHCAT URLs not discovered

- gateway-server/src/main/java/org/apache/knox/gateway/services/security/impl/ZookeeperRemoteAliasService.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/security/impl/ZookeeperRemoteAliasMonitorTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/security/impl/ZookeeperRemoteAliasServiceTest.java
Formatted the code and did a minor cleanup to make it easier to read and understand the code.
Apart from code cleanup, I changed the way how passwords are fetched in `ZookeeperRemoteAliasService`: before going to the remote ZK server we first check if the desired password is available through the local alias service. If so; we skip the remote check. This came with a separate commit to make it easier for review (see [here](https://github.com/apache/knox/pull/218/commits/2703684c0d4900340ac18741a731869c4199b451)).
Added a JUnit test to measure performance (ignoring it from automatic execution, but can be executed manually by commenting out the `Ignore` annotation): added and fetched 200 aliases/passwords with and without my changes in place with the following results
|Without cache (ms) | …
> KNOX-2134 - Checking if password is available via local alias service before going to fetch it from remote ZK server

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/AbstractServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/atlas/AtlasAPIServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/atlas/AtlasServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/hbase/WebHBaseServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/hdfs/NameNodeServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/hive/HiveOnTezServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/hive/HiveServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/hive/WebHCatServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/hue/HueLBServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/hue/HueServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/impala/ImpalaServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/impala/ImpalaUIServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/livy/LivyServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/oozie/OozieServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/phoenix/PhoenixServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/ranger/RangerServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/solr/SolrServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/spark/SparkHistoryUIServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/yarn/JobHistoryUIServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/yarn/ResourceManagerServiceModelGeneratorBase.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/zeppelin/ZeppelinServiceModelGenerator.java
- gateway-discovery-cm/src/main/resources/META-INF/services/org.apache.knox.gateway.topology.discovery.cm.ServiceModelGenerator
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryTest.java
Added support for Impala and Impala UI discovery from CM. Also moved the most commonly used implementation of ServiceModelGenerator#handles() to AbstractServiceModelGenerator.
Added discovery tests for Impala and Impala UI, executed all Knox tests, and manually tested Impala discovery against a CM cluster.
> KNOX-1970 - CM discovery - Add Impala HS2 to auto discovery

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/hive/HiveOnTezServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/hive/HiveServiceModelGenerator.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryTest.java
Fixed the HIVE_ON_TEZ HS2 discovery from ClouderaManager-managed clusters. Changed to check the role configuration, rather than the hive-site safety valve for the transport mode.
Updated ClouderaManagerServiceDiscoveryTest#doTestHiveOnTezServiceDiscovery, manually tested against a cluster, and executed all the Knox tests.
> KNOX-2151 - HIVE_ON_TEZ HS2 Discovery doesn't work

- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
Disabling Ambari cluster monitoring by default.
Ran Knox build/tests, manual validation
> KNOX-2152 - Disable Ambari cluster configuration monitoring by default

- gateway-shell/src/main/java/org/apache/knox/gateway/shell/table/JDBCKnoxShellTableBuilder.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/table/KnoxShellTable.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/table/KnoxShellTableCall.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/table/KnoxShellTableJSONSerializer.java
- gateway-shell/src/test/java/org/apache/knox/gateway/shell/table/KnoxShellTableTest.java
Since [KNOX-2132](https://issues.apache.org/jira/browse/KNOX-2134) the `JDBCKnoxShellTableBuilder` can handle `username` and `password` fields. These are sensitive data which we do not want to display when:
- querying the call history
- converting to JSON format and displaying on STDOUT
To address this issue the following has been done:
- `KnoxShellTable.toJSON()` method got overloaded to let end-users saving the JSON output into a file. The file will be protected with file permissions of `600` so that only the owner can read/write it. In case the end-user wants to write the call history in this file (i.e. not the data itself) the sensitive data will be written there too.
- in any other case when the call history-related information is displayed on the standard output the sensitive data …
> KNOX-2147 - Mask username/password in case we display call history and keep them safely (by setting proper file permissions) in JSON file

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/kudu/KuduUIServiceModelGenerator.java
- gateway-discovery-cm/src/main/resources/META-INF/services/org.apache.knox.gateway.topology.discovery.cm.ServiceModelGenerator
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryTest.java
Added support for discovering URLs for the Apache Kudu UI.
Added tests to ClouderaManagerServiceDiscoveryTest, and manually tested.
> KNOX-2156 - CM discovery - KUDUUI discovery

- gateway-service-definitions/src/main/resources/services/zeppelinui/0.8.0/rewrite.xml
- gateway-service-definitions/src/main/resources/services/zeppelinui/0.8.1/rewrite.xml
Some of Zeppelin UI was broken as API(s) get params are not being sent.
manually tested.
> KNOX-2148 - ZEPPELINUI service definition should pass query parameters for API

- gateway-shell/src/main/java/org/apache/knox/gateway/shell/KnoxSh.java
Modified exception message to include the specific reason for failure with "Cause:" as seen in the following examples
Untrusted certificate:
Hostname verification failure:
Invalid login credentials:
Manual tests
> KNOX-2101 - knoxshell doesn't handle invalid TLS well

- gateway-applications/src/main/resources/applications/knoxauth/app/js/knoxauth.js
Provide feedback on the KnoxSSO login page when an error occurs dispatching to the backend.
* `mvn -T.5C verify -Ppackage,release -Dshellcheck`
* Checked with KnoxSSO login against WebHDFS that if no WebHDFS 500 error and message is shown to end user.
> KNOX-718 - KnoxSSO login page doesn't display any feedback on error

- gateway-cm-integration/src/main/java/org/apache/knox/gateway/ClouderaManagerIntegrationMessages.java
- gateway-cm-integration/src/main/java/org/apache/knox/gateway/cm/descriptor/ClouderaManagerDescriptorMonitor.java
- gateway-cm-integration/src/main/java/org/apache/knox/gateway/cm/descriptor/ClouderaManagerDescriptorParser.java
- gateway-cm-integration/src/main/java/org/apache/knox/gateway/topology/discovery/advanced/AdvanceServiceDiscoveryConfigurationMessages.java
- gateway-cm-integration/src/main/java/org/apache/knox/gateway/topology/discovery/advanced/AdvancedServiceDiscoveryConfig.java
- gateway-cm-integration/src/main/java/org/apache/knox/gateway/topology/discovery/advanced/AdvancedServiceDiscoveryConfigChangeListener.java
- gateway-cm-integration/src/main/java/org/apache/knox/gateway/topology/discovery/advanced/AdvancedServiceDiscoveryConfigurationMonitor.java
- gateway-cm-integration/src/test/java/org/apache/knox/gateway/cm/descriptor/ClouderaManagerDescriptorParserTest.java
- gateway-cm-integration/src/test/resources/testDescriptor.xml
- gateway-cm-integration/src/test/resources/testDescriptorConfigurationWithWrongDescriptor.xml
- gateway-server/src/main/java/org/apache/knox/gateway/GatewayServer.java
- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
- gateway-test-release-utils/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
- gateway-topology-simple/src/main/java/org/apache/knox/gateway/topology/simple/SimpleDescriptorImpl.java
Implemented CM specific advanced service discovery feature as described in [KNOX-2186](https://issues.apache.org/jira/browse/KNOX-2186).
Updated and ran JUnit tests:
```
[INFO] Total time: 18:37 min (Wall Clock)
[INFO] Finished at: 2020-01-16T11:47:14+01:00
[INFO] Final Memory: 421M/2310M
```
Additionally, I tested new features manually. I've used the following two files:
`/Users/smolnar/test/knoxGateway/conf/descriptors/testDescriptor.cm`
```
<property>
<name>topology1</name>
<value>
discoveryType=ClouderaManager; …
```
> KNOX-2186 - Advanced service discovery configuration handling

- build-tools/src/main/resources/build-tools/pmd/pmd-ruleset.xml
- build-tools/src/main/resources/build-tools/spotbugs-filter.xml
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/KnoxSession.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/KnoxSh.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/Shell.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/commands/AbstractSQLCommandSupport.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/commands/DataSourceCommand.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/jdbc/KnoxLine.java
Adding a simple SQL client/shell to KnoxShell for accessing JDBC data sources such as HiveServer2 and others. Rather than providing connection details on the command line for the data source, this shell leverages the DataSource persistence introduced in KNOX-2128.
Enter the SQL client, list datasources, select datasources and execute SQL query:
lmccay@strange:~/Projects/releases/knoxshell-1.4.0-SNAPSHOT$ bin/knoxshell.sh knoxline
_                    _ _            
| | ___ __   _____  _| (_)_ __   ___ 
| |/ / '_ \ / _ \ \/ / | | '_ \ / _ \
|   <| | | | (_) >  <| | | | | |  __/
|_|\_\_| |_|\___/_/\_\_|_|_| |_|\\__|
powered by Apache Knox …
> KNOX-1742 - Simple SQL Client in KnoxShell for access to JDBC sources

- gateway-cm-integration/src/main/java/org/apache/knox/gateway/cm/descriptor/ClouderaManagerDescriptorParser.java
- gateway-cm-integration/src/main/java/org/apache/knox/gateway/topology/discovery/advanced/AdvancedServiceDiscoveryConfig.java
- gateway-cm-integration/src/test/java/org/apache/knox/gateway/cm/descriptor/ClouderaManagerDescriptorParserTest.java
- gateway-cm-integration/src/test/resources/testDescriptorWithoutDiscoveryDetails.xml
Setting the following discovery details in a Knox descriptor, if they are not customized in the CM descriptors file:
- discovery address
- discovery cluster
- discovery type
Updated and executed JUnit tests:
```
[INFO] Total time: 19:59 min (Wall Clock)
[INFO] Finished at: 2020-01-20T10:28:22+01:00
[INFO] Final Memory: 424M/1987M
```
> KNOX-2188 - Handling discovery details via advanced configuration

- gateway-cm-integration/src/main/java/org/apache/knox/gateway/ClouderaManagerIntegrationMessages.java
- gateway-cm-integration/src/main/java/org/apache/knox/gateway/cm/descriptor/ClouderaManagerDescriptorMonitor.java
- gateway-cm-integration/src/main/java/org/apache/knox/gateway/cm/descriptor/ClouderaManagerDescriptorParser.java
- gateway-cm-integration/src/main/java/org/apache/knox/gateway/topology/discovery/advanced/AdvanceServiceDiscoveryConfigurationMessages.java
- gateway-cm-integration/src/main/java/org/apache/knox/gateway/topology/discovery/advanced/AdvancedServiceDiscoveryConfig.java
- gateway-cm-integration/src/main/java/org/apache/knox/gateway/topology/discovery/advanced/AdvancedServiceDiscoveryConfigurationMonitor.java
- gateway-cm-integration/src/test/java/org/apache/knox/gateway/cm/descriptor/ClouderaManagerDescriptorParserTest.java
- gateway-server/src/main/java/org/apache/knox/gateway/GatewayServer.java
- gateway-test/src/test/java/org/apache/knox/gateway/SimpleDescriptorHandlerFuncTest.java
Instead of applying advance service discovery configuration listed in `KNOX_CONF_DIR/conf/auto-discovery-advanced-configuration.properties`. From now on, the advance service configuration monitor checks any files in `KNOX_CONF_DIR` with `auto-discovery-advanced-configuration` prefix. This file contains the advanced configuration of one topology which is declared within the configuration. If such a file is updated the affected topology will be redeployed.
JUnit:
```
[INFO] Total time: 19:24 min (Wall Clock)
[INFO] Finished at: 2020-01-22T11:48:12+01:00
[INFO] Final Memory: 421M/2351M
[INFO] …
```
> KNOX-2190 - Processing advanced service discovery configuration on topology level

- gateway-provider-rewrite/src/main/java/org/apache/knox/gateway/filter/rewrite/api/UrlRewriteStreamFilterFactory.java
- gateway-provider-rewrite/src/main/java/org/apache/knox/gateway/filter/rewrite/impl/UrlRewriteRequest.java
- gateway-provider-rewrite/src/main/java/org/apache/knox/gateway/filter/rewrite/impl/UrlRewriteResponse.java
- gateway-provider-rewrite/src/test/java/org/apache/knox/gateway/filter/rewrite/impl/UrlRewriteRequestTest.java
- gateway-provider-rewrite/src/test/java/org/apache/knox/gateway/filter/rewrite/impl/UrlRewriteResponseTest.java
Using UTF-8 for default content encoding instead of ISO-8859-1. 
* Added unit tests showing failure before change
* Checked that failing unit tests pass after change
* Manually verified that changes fix Oozie UTF-8 XML issue
> KNOX-2202 - Knox should use UTF-8 as default encoding instead of ISO-8859-1

- gateway-provider-security-authz-acls/src/main/java/org/apache/knox/gateway/filter/AclsAuthorizationMessages.java
Move AclsAuthorizationFilter log access at DEBUG level
* Checked that log is at DEBUG instead of INFO when running Knox
> KNOX-2208 - AclsAuthorizationFilter should log access at DEBUG level

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscovery.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryMessages.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ServiceModelGeneratorHandleResponse.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/AbstractServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/hdfs/WebHdfsServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/hive/HiveOnTezServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/hive/HiveServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/impala/ImpalaUIServiceModelGenerator.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/model/AbstractServiceModelGeneratorTest.java
Adding a `WARN` level log in case there is a configuration issue with the discovered service role.
JUnit tests:
```
mvn clean -Dshellcheck=true -T1C verify -Prelease,package
...
[INFO] Total time: 19:14 min (Wall Clock)
[INFO] Finished at: 2020-01-30T09:38:40+01:00
[INFO] Final Memory: 421M/2282M
```
Additionally, I executed the following manual test steps:
1. built, deployed and started Knox with may changes
2. produced a shared-provider and descriptor with proper CM discovery settings pointing to my test cluster
3. made sure that …
> KNOX-2206 - Log exclusion of a discovered service due to configuration issues

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscovery.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/cm/ClouderaManagerAPIServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/cm/ClouderaManagerUIServiceModelGenerator.java
- gateway-discovery-cm/src/main/resources/META-INF/services/org.apache.knox.gateway.topology.discovery.cm.ServiceModelGenerator
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryTest.java
Currently when autodiscovery is turned on for CM all the services that are defined in the descriptor are added to the topology except for the CM UI and CM API. They are special cases given CM url is used for service discovery. This PR populates the topology with CM UI and CM API url when they are added to the descriptor.
This patch was manually Tested.
> KNOX-2213 - Service Discovery Support for CM UI, API

- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/AliasBasedTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/DefaultTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/TokenStateServiceMessages.java
Do not maintain state for revoked tokens. 
This patch was manually tested.
> KNOX-2207 - TokenStateService revocation should remove persisted token state

- gateway-service-definitions/src/main/resources/services/hbaseui/2.1.0/rewrite.xml
Tested against HBase 2.2.4-SNAPSHOT and HBCK Report page was accessible
This change fixes HBase UI such that the HBCK Report page is accessible via Knox.
Deployed KNOX-1.4.0-SNAPSHOT locally and tested HBase-2.2.4-SNAPSHOT along with it. I was able to access the HBCK Report page via UI. Have uploaded a sample image of the UI for reference.
> KNOX-2222 - Fix HBase UI Proxying for HBCK Report page

- gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/HadoopAuthCookieStore.java
- gateway-spi/src/test/java/org/apache/knox/gateway/dispatch/HadoopAuthCookieStoreTest.java
This ensures that Knox principal both short
and long will be compared against the cookie
returned. This will match the HS2 cookie.
> KNOX-2223 - HS2 cookie not stored in HadoopAuthCookieStore

- gateway-release/src/assembly.xml
Don't exclude Kerby jars since they are used transitive by Knox through Hadoop dependencies like hadoop-auth.
* Checked that in the release the `deps` folder has the `kerby` jars.
> KNOX-2229 - Knox shouldn't exclude Kerby since it is used by Hadoop

- gateway-shell/src/main/java/org/apache/knox/gateway/shell/table/KnoxShellTable.java
- gateway-shell/src/test/java/org/apache/knox/gateway/shell/table/KnoxShellTableTest.java
Ability to use whitespace as a delimiter in the select method
Manual and unit tests
> KNOX-2189 - KnoxShellTable.select() must handle whitespace

- gateway-admin-ui/admin-ui/app/resource-detail/descriptor.ts
- gateway-admin-ui/admin-ui/app/resource-detail/resource-detail.component.html
- gateway-admin-ui/admin-ui/app/resource-detail/resource-detail.component.ts
- gateway-admin-ui/admin-ui/app/resource/resource.service.ts
- gateway-cm-integration/src/main/java/org/apache/knox/gateway/cm/descriptor/ClouderaManagerDescriptorParser.java
- gateway-cm-integration/src/test/java/org/apache/knox/gateway/cm/descriptor/ClouderaManagerDescriptorParserTest.java
- gateway-topology-simple/src/main/java/org/apache/knox/gateway/topology/simple/SimpleDescriptor.java
- gateway-topology-simple/src/main/java/org/apache/knox/gateway/topology/simple/SimpleDescriptorImpl.java
#236  introduces a new descriptor type (using on Hadoop XML structure). Descriptors generated out of those XML configurations are read-only on Admin UI from now on.
Updated and executed JUnit tests.
Additionally, the following manual test steps were executed:
1. built and deployed Knox with my changes
2. logged into Admin UI
3. created a descriptor called `testDescriptor` on Admin UI
4. placed the following CM-type descriptor in Knox's descriptor directory:
```
<property>
<name>topology1</name>
<value>
providerConfigRef=default-providers;
app:knoxauth:param1.name=param1.value;
HIVE:url=http://localhost:456;
HIVE:version=1.0;
HIVE:httpclient.connectionTimeout=5m;
</value>
</property>
<property>
<name>topology2</name>
<value> …
```
> KNOX-2161 - CM generated descriptors are read-only on Admin UI

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/phoenix/PhoenixServiceModelGenerator.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryTest.java
Add TLS support for Phoenix Query Server for the CM service discovery module
The TLS support was omitted from the original discovery module, as PQS didn't have TLS support yet. 
Now I have re-added the TLS support. The code is a little different from most similar modules, because the ssl_enabled property is not present in older CM releases, and we have to handle that as well.
* Wrote and run new unit test
* Tested against live Cloudera Manager instance which had the the TLS for PQS support
* Tested against live older Cloudera Manager instance which did not have the TLS for PQS support
In both cases I was able to connect to the auto discovered PQS service.
> KNOX-2238 CM discovery - Add TLS support to Phoenix auto discovery

- gateway-server/pom.xml
- gateway-server/src/main/java/org/apache/knox/gateway/websockets/GatewayWebsocketHandler.java
- gateway-server/src/main/java/org/apache/knox/gateway/websockets/ProxyWebSocketAdapter.java
- pom.xml
In Knox wss support was broken, the jetty implementation was picking up system keystore and not the keystore configured in gateway-site.xml file. This PR fixes it.
This was tested locally with ws and wss protocols.
> KNOX-2239 - Websocket use the configured truststore in gateway-site config file

- gateway-release/pom.xml
- gateway-shell-release/pom.xml
Remove deprecated tasks and switch to target for maven-antrun-plugin.
* `mvn -T.5C clean verify -U -Ppackage,release -Dshellcheck`
> KNOX-2250 - maven-antrun-plugin use target instead of tasks

- gateway-admin-ui/admin-ui/app/new-desc-wizard/new-desc-wizard.component.ts
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/spark/Spark3HistoryUIServiceModelGenerator.java
- gateway-discovery-cm/src/main/resources/META-INF/services/org.apache.knox.gateway.topology.discovery.cm.ServiceModelGenerator
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryTest.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/model/spark/Spark3HistoryUIServiceModelGeneratorTest.java
- gateway-service-definitions/src/main/resources/services/spark3historyui/3.0.0/rewrite.xml
- gateway-service-definitions/src/main/resources/services/spark3historyui/3.0.0/service.xml
Add Spark 3 History Server definition. Spark 3 HS could be run alongside Spark 2 HS, so separate service definition is required.
Manually and with unit tests.
> KNOX-2249 Add Spark 3 History Server definition

- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/AliasBasedTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/DefaultTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/TokenStateServiceMessages.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/DefaultTokenStateServiceTest.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
- gateway-test-release-utils/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
When `gateway.knox.token.permissive.failure.enabled`  property is set to true in gateway-site.xml (by default it is false) **and** `knox.token.exp.server-managed` is set to true in the descriptor (server managed token state is enabled) then, when Knox encounters a valid token which is not stored in it's token state Knox uses the expiry date of the JWT token instead of flagging it as "Unknown Token"
This patch was locally tested
> KNOX-2212 - Token permissiveness

- gateway-service-definitions/src/main/resources/services/livy/0.4.0/rewrite.xml
- gateway-service-definitions/src/main/resources/services/livy/0.4.0/service.xml
Added a new rewrite rule in Livy service for handling redirects to /ui endpoint
Manually tested in a Cluster with Knox and Livy Services.
1. Edited the rewrite/service.xml for Livy service with the changes.
2. Verified that `https://<KNOX_HOST:KNOX_PORT>/gateway/default/livy` gets redirected to `https://<KNOX_HOST:KNOX_PORT>/gateway/default/livy/ui`
> KNOX-2258 - Add new rewrite rule in Livy service for handling redirect requests to /ui

- gateway-service-definitions/src/main/resources/services/livy/0.4.0/rewrite.xml
- gateway-service-definitions/src/main/resources/services/livy/0.4.0/service.xml
Follow up for #276 
Added a new filter in Livy rewrite.xml for replacing Location header
Removed rewrite rules from routes path in service.xml
Manually tested in a Cluster with Knox and Livy Services.
1. Edited the rewrite/service.xml for Livy service with the changes.
2. Verified that `https://<KNOX_HOST:KNOX_PORT>/gateway/default/livy` gets redirected to `https://<KNOX_HOST:KNOX_PORT>/gateway/default/livy/ui`
3. Verified that `https://<KNOX_HOST:KNOX_PORT>/gateway/default/livy/` gets redirected to `https://<KNOX_HOST:KNOX_PORT>/gateway/default/livy/ui`
> KNOX-2258 - Add filter for Location header

- gateway-docker/pom.xml
- gateway-docker/src/main/resources/docker-compose.yml
Make sure that only the version is in the docker image tag.
* `mvn -T.75C package -Ppackage,release,docker -Dshellcheck -DskipTests`
* Checked created image
```
docker images | grep -F apache/
apache/knox-demo-ldap                                                              1.4.0-SNAPSHOT                             714adc69aef4        17 seconds ago      533MB
apache/knox-gateway                                                                1.4.0-SNAPSHOT                             1e6f961b86f0        34 seconds ago      533MB
```
> KNOX-2263 - Docker - make sure not to put anything except version in the tag

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/AbstractServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/hive/HiveServiceModelGenerator.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryTest.java
CM configuration's related name is used when looking up service/role configurations.
Moreover, it turned out that `hive.server2.use.SSL` is a service configuration rather than being a role configuration.
Updated and ran JUnit tests and tested manually:
1. had a secure remote cluster (i.e. SSL enabled) with Hive/Hive on TEZ
2. redeployed Knox locally and added a descriptor with HIVE
3. set the remote cluster's attributes in this descriptor's `Service Discovery` details
4. confirmed that
- service discovery worked
- Hive URLs start with the `https` scheme
> KNOX-2265 - Checking CM configs by their related names and read hive.server2.use.SSL from the service configuration

- gateway-service-definitions/src/main/resources/services/hbaseui/2.1.0/service.xml
- gateway-service-definitions/src/main/resources/services/impalaui/1.0.0/service.xml
- gateway-service-definitions/src/main/resources/services/kuduui/1.0.0/service.xml
- gateway-service-metadata/src/main/java/org/apache/knox/gateway/service/metadata/KnoxMetadataResource.java
- gateway-service-metadata/src/main/java/org/apache/knox/gateway/service/metadata/ServiceModel.java
Corrected the contexts for Impala/Kudu/HBase UI services and fixed the code which selects the correct service definition when looking for metadata (the version was not considered before).
Tested manually: added a sample descriptor (with IMPALAUI, KUDUUI, HBASEUI services) pointing to a remote cluster (where valid URLs are found). Knox generated the topology properly and the correct URLs are displayed on the Home page.
> KNOX-2259 KNOX-2260 KNOX-2261 - Fixed Impala/Kudu/HBase UI context path in service metadata

- gateway-discovery-ambari/src/main/java/org/apache/knox/gateway/topology/discovery/ambari/AmbariClientCommon.java
- gateway-discovery-ambari/src/main/java/org/apache/knox/gateway/topology/discovery/ambari/AmbariClusterConfigurationMonitorProvider.java
- gateway-discovery-ambari/src/main/java/org/apache/knox/gateway/topology/discovery/ambari/AmbariConfigurationMonitor.java
- gateway-discovery-ambari/src/main/java/org/apache/knox/gateway/topology/discovery/ambari/AmbariServiceDiscovery.java
- gateway-discovery-ambari/src/main/java/org/apache/knox/gateway/topology/discovery/ambari/RESTInvoker.java
- gateway-discovery-ambari/src/test/java/org/apache/knox/gateway/topology/discovery/ambari/AmbariConfigurationMonitorTest.java
- gateway-discovery-ambari/src/test/java/org/apache/knox/gateway/topology/discovery/ambari/AmbariServiceDiscoveryTest.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscovery.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryMessages.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/DiscoveryApiClient.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/monitor/ClouderaManagerClusterConfigurationMonitor.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/monitor/ClouderaManagerClusterConfigurationMonitorProvider.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/monitor/PollingConfigurationAnalyzer.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryTest.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/monitor/PollingConfigurationAnalyzerTest.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/DefaultGatewayServices.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/topology/impl/DefaultClusterConfigurationMonitorService.java
- gateway-spi/src/main/java/org/apache/knox/gateway/i18n/GatewaySpiMessages.java
- gateway-spi/src/main/java/org/apache/knox/gateway/topology/discovery/ClusterConfigurationMonitorProvider.java
- gateway-spi/src/main/java/org/apache/knox/gateway/util/TruststoreSSLContextUtils.java
Currently Ambari and CM discovery doesn't use the configured HTTP truststore. This change adds the HTTP truststore to both the Ambari and CM discovery HTTP clients.
* Spun up a cluster with CM AutoTLS and checked that Knox didn't get handshake errors talking to CM
> KNOX-2267 - Ambari/CM discovery - Needs to point to configured truststore

- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/AbstractJWTFilter.java
- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/AccessTokenFederationFilter.java
- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/CommonJWTFilterTest.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/AliasBasedTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/DefaultTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/TokenStateServiceMessages.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/DefaultTokenStateServiceTest.java
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceMessages.java
- gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/TokenStateService.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/TokenUtils.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/UnknownTokenException.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/impl/JWTToken.java
- gateway-spi/src/test/java/org/apache/knox/gateway/services/security/token/impl/JWTTokenTest.java
JWTs issued and validated by Knox now include a unique identifier as a private claim. This is mostly to guarantee token uniqueness, even for multiple requests within the same second.
Further, the TokenStateService has been updated to leverage this unique identifier as the key for handling token state. This identifier is less susceptible to the nuances of some storage mechanisms.
Mulitple existing tests were modified to accommodate this change while ensuring the maintenance of existing behavior. TokenServiceResourceTest#testConcurrentGetToken was added to validate these changes. I've also done a bit of manual testing.
> KNOX-2266 - Tokens Should Include a Unique Identifier

- gateway-cm-integration/src/main/java/org/apache/knox/gateway/ClouderaManagerIntegrationMessages.java
- gateway-cm-integration/src/main/java/org/apache/knox/gateway/cm/descriptor/ClouderaManagerDescriptorMonitor.java
- gateway-server/src/main/java/org/apache/knox/gateway/GatewayServer.java
Handling CM descriptors after Knox shared-provider/descriptor/topology monitors are started
Tested manually:
1. redeployed Knox with my changes in place; brand new installation, only the OOTB topologies existed
2. produced a CM descriptor (cm-topologies.cm) with the following content:
```
<property>
<name>topology1</name>
<value>
providerConfigRef=default-providers;
app:knoxauth:param1.name=param1.value;
HIVE:url=http://localhost:456;
HIVE:version=1.0;
HIVE:httpclient.connectionTimeout=5m;
</value>
</property>
<property>
<name>topology2</name>
<value>
providerConfigRef=default-providers;
HDFS:url=http://localhost:456;
HDFS:httpclient.connectionTimeout=5m;
HDFS:httpclient.socketTimeout=100m
</value>
</property>
</configuration>
```
3. …
> KNOX-2284 - Handling CM descriptors after Knox shared-provider/descriptor/topology monitors are started

- gateway-server/src/main/java/org/apache/knox/gateway/GatewayMessages.java
- gateway-server/src/main/java/org/apache/knox/gateway/GatewayServer.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/topology/impl/DefaultTopologyService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/topology/monitor/DescriptorsMonitor.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/topology/monitor/SharedProviderConfigMonitor.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/topology/DefaultTopologyServiceTest.java
Clearly indicating in the logs when
- a monitor (topologies/providers/descriptors) is configured
- a monitor (topologies/providers/descriptors) is started
As part of this job, I refactored out the `SharedProviderConfigMonitor` and `DescriptorsMonitor` classes from `DefaultTopologyService` into a new package (`org.apache.knox.gateway.services.topology.monitor`).
Redeployed Knox with my changes and touched files in `conf/shared-providers`, `conf/descriptors` and `conf/topologies` directories: monitoring worked as expected.
Relevant logs:
```
2020-03-11 17:27:22,838 INFO  knox.gateway (DefaultTopologyService.java:init(643)) - Configured monitoring topologies in directory: /Users/smolnar/test/knoxGateway/conf/topologies
2020-03-11 17:27:22,839 INFO  knox.gateway …
```
> KNOX-2286 Cleaner log messages about monitoring topologies/providers/descriptors

- gateway-service-definitions/pom.xml
- gateway-service-definitions/src/main/java/org/apache/knox/gateway/service/definition/Metadata.java
- gateway-service-metadata/pom.xml
- gateway-service-metadata/src/main/java/org/apache/knox/gateway/service/metadata/KnoxMetadataResource.java
- gateway-service-metadata/src/main/java/org/apache/knox/gateway/service/metadata/ServiceModel.java
- gateway-service-metadata/src/main/java/org/apache/knox/gateway/service/metadata/TopologyInformation.java
- gateway-service-metadata/src/main/java/org/apache/knox/gateway/service/metadata/TopologyInformationWrapper.java
- gateway-service-metadata/src/test/java/org/apache/knox/gateway/service/metadata/ServiceModelTest.java
Returning a `Set` of service models instead of a `List` for both UI and API services. This results in displaying only one service logo/URL with multiple service URLs in case the service URLs do not contain service-specific host/port parts.
- added a topology (`cdp-proxy`) with IMPALA and IMPALAUI services
- both services had 2 service URLs defined
- redeployed Knox and confirmed the following using the Metadata API:
- Impala UI logo appeared twice pointing to two different instances as the service URL of IMPALA UI contains `{{HOST}}` and `{{PORT}}` placeholders
- Impala API link appeared only once
> KNOX-2296 - Passing down the service URL field when building up a service model

- gateway-service-metadata/src/main/java/org/apache/knox/gateway/service/metadata/ServiceModel.java
- gateway-service-metadata/src/test/java/org/apache/knox/gateway/service/metadata/ServiceModelTest.java
Replaced the wrong Hive JDBC URL to a valid one.
Updated and ran JUnit tests.
> KNOX-2299 - Fixed Hive JDBC URL on Knox Home page

- gateway-service-definitions/src/main/resources/services/livy/0.4.0/service.xml
- gateway-service-definitions/src/main/resources/services/solr/5.5.0/service.xml
- gateway-service-definitions/src/main/resources/services/solr/6.0.0/service.xml
- gateway-service-metadata/src/main/java/org/apache/knox/gateway/service/metadata/KnoxMetadataResource.java
- gateway-service-metadata/src/main/java/org/apache/knox/gateway/service/metadata/ServiceModel.java
From now on Livy Server's and Solr's logo will be displayed in the UI services section as well as listed in the API services table.
> KNOX-2300 - Livy and Solr handled as both API and UI services

- gateway-discovery-cm/pom.xml
- pom.xml
Blacklist Maven 3.6.2 and move cloudera repository to child pom
> KNOX-2305 - Blacklist Maven 3.6.2 and move cloudera repository to child pom

- gateway-server/src/main/java/org/apache/knox/gateway/GatewayMessages.java
- gateway-server/src/main/java/org/apache/knox/gateway/model/DescriptorConfiguration.java
- gateway-server/src/main/java/org/apache/knox/gateway/model/ProviderConfiguration.java
- gateway-server/src/main/java/org/apache/knox/gateway/model/Topology.java
- gateway-server/src/main/java/org/apache/knox/gateway/util/KnoxCLI.java
- gateway-server/src/main/java/org/apache/knox/gateway/util/TopologyToDescriptor.java
- gateway-server/src/test/java/org/apache/knox/gateway/util/KnoxCLITest.java
- gateway-server/src/test/resources/token-test.xml
This PR proposes to add a KnoxCLI command to convert topology to provider and descriptor.
```
knoxcli.sh convert-topology 
--path "path/to/topology.xml" 
--provider-name my-provider.json 
[--descriptor-name my-descriptor.json] 
[--topology-name topologyName] 
[--output-path "path/to/configs/"] 
[--force] 
[--cluster clusterName] 
[--discovery-url url] 
[--discovery-user discoveryUser] 
[--discovery-pwd-alias discoveryPasswordAlias] 
[--discovery-type discoveryType]
```
_Options are as follows:_
**--path** (required) path to topology xml file
**--provider-name** (required) name of the provider json config file (including .json extension)
**--descriptor-name** (optional) name of descriptor json config file (including .json extension)
**--topology-name** (optional) topology-name can be use …
> KNOX-2287 KnoxCLI convert topology to provider and descriptor

- gateway-server/src/main/java/org/apache/knox/gateway/services/topology/impl/DefaultTopologyService.java
- gateway-server/src/main/java/org/apache/knox/gateway/util/TopologyUtils.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/topology/DefaultTopologyServiceTest.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/topology/TopologyService.java
- gateway-spi/src/main/java/org/apache/knox/gateway/topology/Provider.java
- gateway-spi/src/main/java/org/apache/knox/gateway/topology/Service.java
- gateway-spi/src/main/java/org/apache/knox/gateway/topology/Topology.java
- gateway-spi/src/test/java/org/apache/knox/gateway/topology/TopologyTest.java
- gateway-test-release-utils/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
- gateway-test-release-utils/src/main/java/org/apache/knox/gateway/GatewayTestDriver.java
- gateway-test/src/test/java/org/apache/knox/gateway/AmbariServiceDefinitionTest.java
- gateway-test/src/test/java/org/apache/knox/gateway/GatewayAdminFuncTest.java
- gateway-test/src/test/java/org/apache/knox/gateway/GatewayAppFuncTest.java
- gateway-test/src/test/java/org/apache/knox/gateway/GatewayCorrelationIdTest.java
- gateway-test/src/test/java/org/apache/knox/gateway/GatewayDeployFuncTest.java
- gateway-test/src/test/java/org/apache/knox/gateway/GatewayHealthFuncTest.java
- gateway-test/src/test/java/org/apache/knox/gateway/GatewayLocalServiceFuncTest.java
- gateway-test/src/test/java/org/apache/knox/gateway/GatewayMultiFuncTest.java
- gateway-test/src/test/java/org/apache/knox/gateway/GatewaySampleFuncTest.java
- gateway-test/src/test/java/org/apache/knox/gateway/GatewaySslFuncTest.java
- gateway-topology-simple/src/main/java/org/apache/knox/gateway/topology/simple/SimpleDescriptorHandler.java
- gateway-topology-simple/src/main/java/org/apache/knox/gateway/topology/simple/SimpleDescriptorMessages.java
These are two closely-related issues. Added (actually, removed restrictions on) performing re-discovery for every applicable descriptor on gateway start-up. To prevent unnecessary redeployments of unchanged topologies, also added a check to skip the persistence of generated topologies if there exists an equivalent deployed topology of the same name.
A great deal of manual testing was performed, and a number of existing tests were modified.  Also added some new tests.
> KNOX-2301 and KNOX-2302

- gateway-shell/src/main/java/org/apache/knox/gateway/shell/KnoxSession.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/Shell.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/commands/AbstractKnoxShellCommand.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/commands/AbstractSQLCommandSupport.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/commands/CSVCommand.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/commands/WebHDFSCommand.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/hdfs/Ls.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/hdfs/Mkdir.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/hdfs/Put.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/hdfs/Rm.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/table/CSVKnoxShellTableBuilder.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/table/KnoxShellTable.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/table/KnoxShellTableFileUtils.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/table/KnoxShellTableJSONSerializer.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/table/KnoxShellTableRenderer.java
- gateway-shell/src/test/java/org/apache/knox/gateway/shell/table/KnoxShellTableTest.java
- gateway-util-common/src/main/java/org/apache/knox/gateway/util/JsonUtils.java
- gateway-util-common/src/test/java/org/apache/knox/gateway/util/JsonUtilsTest.java
This PR introduces a new custom groovy command for KnoxShell for interaction with hadoop filesystems through the WebHDFS API. This includes the ability to mount filesystems, unmount them and list mounts. Mounts are persisted in the user's home directory for knoxshell so that they live across KnoxShell sessions.
It is limited to the hdfs client classes that are provided in KnoxShell today but with follow up patches to both the client classes and the command will cover more of the Hadoop filesystem capabilities - such as chown and chmod.
Primarily tested through manual use of the KnoxShell environment. Minor improvements in CSV builder have …
> KNOX-2240 - KnoxShell Custom Command for WEBHDFS Use

- gateway-shell/src/main/java/org/apache/knox/gateway/shell/table/KnoxShellTable.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/table/KnoxShellTableAggregator.java
- gateway-shell/src/test/java/org/apache/knox/gateway/shell/table/KnoxShellTableTest.java
A simple method for producing a meaningful mathematical report of a dataset would allow the user to quickly determine some basic metrics of a dataset.
For instance, given a dataset with time series data across columns, an aggregation of:
min
max
mean
median
mode
sum
for specific columns would provide a way to visualize the changes across time.
knox:000> test.aggregate() columns "A,B,C" functions "min, max, mean, median, mode,sum"
===> +----------+----------------------+----------+----------+
|          |          A           |    B     |    C     |
+----------+----------------------+----------+----------+
|   min    |        100.0         | …
> KNOX-2310 - Add aggregate method to KnoxShellTable

- gateway-spi/src/main/java/org/apache/knox/gateway/topology/Service.java
- gateway-spi/src/main/java/org/apache/knox/gateway/topology/Topology.java
- gateway-spi/src/test/java/org/apache/knox/gateway/topology/TopologyTest.java
- gateway-topology-simple/src/main/java/org/apache/knox/gateway/topology/simple/SimpleDescriptorHandler.java
Fixed NPE when the urls member of a Service object is null, and its equals() method is invoked.
Manual testing, and added testTopologiesWithSameServicesWithNullURLs() to org.apache.knox.gateway.topology.TopologyTest
> KNOX-2314 - NPE from topology Service equals implementation when no URLs

- knox-homepage-ui/home/app/topologies/topology.information.component.html
All UI service links were open on the same tab (separate from the Home page tab though). With this fix, all links are open on their own tabs.
Manually tested.
> KNOX-2317 - Open UI services from Knox Home page on new tabs

- gateway-server/src/main/java/org/apache/knox/gateway/services/security/impl/ZookeeperRemoteAliasService.java
- gateway-server/src/test/java/org/apache/knox/gateway/service/config/remote/LocalFileSystemRemoteConfigurationRegistryClientService.java
- gateway-service-remoteconfig/pom.xml
- gateway-service-remoteconfig/src/main/java/org/apache/knox/gateway/service/config/remote/RemoteConfigurationRegistryConfig.java
- gateway-service-remoteconfig/src/main/java/org/apache/knox/gateway/service/config/remote/config/DefaultRemoteConfigurationRegistries.java
- gateway-service-remoteconfig/src/main/java/org/apache/knox/gateway/service/config/remote/config/RemoteConfigurationRegistry.java
- gateway-service-remoteconfig/src/main/java/org/apache/knox/gateway/service/config/remote/zk/CuratorClientService.java
- gateway-service-remoteconfig/src/main/java/org/apache/knox/gateway/service/config/remote/zk/RemoteConfigurationRegistryJAASConfig.java
- gateway-service-remoteconfig/src/main/java/org/apache/knox/gateway/service/config/remote/zk/ZooKeeperClientService.java
- gateway-service-remoteconfig/src/test/java/org/apache/knox/gateway/service/config/remote/zk/RemoteConfigurationRegistryJAASConfigTest.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/config/client/RemoteConfigurationRegistryClient.java
This PR fixes issues with Zookeeper Kerberos authentication. This PR contains following changes.
1. Fix issues in code that were causing bad configuration issues, such as typos and wrong variable names.
2. For Znodes created by Knox the permissions are more restricted and only knox users can read and write the data to Znodes owned by Knox.
3. Auth scheme for Kerberos authentication is now "sasl"
4. A configuration boolean parameter "backwardsCompatible" is introduced which falls back to old behavior (likely broken behavior)
This patch was locally tested on a secure cluster with Kerberos authentication between Knox and Zookeeper.
> KNOX-2315 - Fix zookeeper Kerberos Auth

- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/DefaultTokenStateService.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/DefaultTokenStateServiceTest.java
Fix DefaultTokenStateServiceTest timeouts to be more reasonable. I used TimeUnit every where to ensure we are doing things with the correct unit of time. Previously there were issues where milliseconds and seconds were being mixed. This caused race conditions in AliasBasedTokenStateServiceTest which extends DefaultTokenStateServiceTest.
* Ran `AliasBasedTokenStateServiceTest` and `DefaultTokenStateServiceTest` repeatedly in IDE
* `mvn -T.5C clean verify -U -Ppackage,release -Dshellcheck`
> KNOX-2340 - Fix DefaultTokenStateServiceTest timeouts

- gateway-service-definitions/src/main/resources/services/hdfsui/3.0.0/rewrite.xml
https://issues.apache.org/jira/browse/KNOX-2321
Add a rewrite rule for LogLevel in hdfs ui.
The patch was tested on a cluster.
> KNOX-2321 - HDFS UI rewrite rules should handle LogLevel

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/monitor/PollingConfigurationAnalyzer.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/monitor/PollingConfigurationAnalyzerTest.java
Checking if the given CM event has either `COMMAND` or `COMMAND_STATUS` attribute before calling `.get(0)` on the attribute map entry (which is `null` if the above condition is not true).
Updated and ran JUnit tests as well as executing the following manual test steps in a cluster with 2 Knox instances with CM configuration monitoring enabled:
- redeployed Knox with my changes in place
- changed Atlas's HTTPS server port from 31445 to 31446 and restarted Atlas
- confirmed that CM configuration monitor picked up the change (in both Knox instances) and re-deployed the affected topologies:
```
2020-04-20 22:11:49,606 DEBUG discovery.cm (PollingConfigurationAnalyzer.java:run(171)) - Checking Cluster 1 @ https://$CM_HOST:7183 for configuration changes...
2020-04-20 22:11:49,615 DEBUG …
```
> KNOX-2350 - Handling event types w/o COMMAND and/or COMMAND_STATUS attributes when polling CM events

- gateway-cm-integration/src/main/java/org/apache/knox/gateway/ClouderaManagerIntegrationMessages.java
- gateway-cm-integration/src/main/java/org/apache/knox/gateway/cm/descriptor/ClouderaManagerDescriptorMonitor.java
- gateway-cm-integration/src/main/java/org/apache/knox/gateway/topology/discovery/advanced/AdvanceServiceDiscoveryConfigurationMessages.java
- gateway-cm-integration/src/main/java/org/apache/knox/gateway/topology/discovery/advanced/AdvancedServiceDiscoveryConfigurationMonitor.java
- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
By default, the following features are disabled:
- CM Descriptor Monitor
- Advance Service Discovery Monitor
```
2020-04-21 21:04:41,741 INFO  discovery.advanced (AdvancedServiceDiscoveryConfigurationMonitor.java:setupMonitor(75)) - Monitoring advanced service discovery configuration changes is disabled.
2020-04-21 21:04:41,743 INFO  knox.gateway (ClouderaManagerDescriptorMonitor.java:setupMonitor(68)) - Monitoring Cloudera Manager descriptors is disabled.
```
> KNOX-2353 - Disabled CM descriptor monitoring and advanced service discovery changes monitoring by default

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryMessages.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/monitor/PollingConfigurationAnalyzer.java
Surrounding the CM configuration check logic with a `try/catch` block and logging if any issue occurred during the operation.
1. deployed Knox w/o the in #319 and deployed a descriptor pointing to a CM cluster where I made a configuration change in one the services
2. waited until CM configuration change monitoring occurred
3. as expected, the monitoring failed. This time the monitoring thread did not get suspended and the appropriate log message was shown:
```
2020-04-21 15:38:00,270 DEBUG discovery.cm (PollingConfigurationAnalyzer.java:run(169)) - Checking Cluster 1 @ http://$CM_HOST:7180 for configuration changes...
2020-04-21 15:38:00,274 DEBUG discovery.cm (PollingConfigurationAnalyzer.java:getRelevantEvents(373)) - Querying restart events from Cluster 1 @ …
```
> KNOX-2351 - Catching any errors while monitoring CM configuration changes

- src/assembly.xml
Remove the node_modules folder from the src zip file.
* Checked that src zip doesn't have node_modules folders anymore
> KNOX-2359 - Knox src zip should not include node_modules folder

- gateway-admin-ui/admin-ui/index.html
The main issue was that the footer covered the bottom of the resource detail panel -> the buttons were not visible.
I added an empty 50px high `div` before the footer to make this issue disappear.
Before my changes:
After my changes:
> KNOX-2356 - Added a 50px high div before the footer to prevent overflow from resource detail panel

- gateway-admin-ui/admin-ui/app/resource-detail/resource-detail.component.html
- gateway-admin-ui/admin-ui/app/resource-detail/resource-detail.component.ts
- gateway-cm-integration/src/main/java/org/apache/knox/gateway/ClouderaManagerIntegrationMessages.java
- gateway-cm-integration/src/main/java/org/apache/knox/gateway/cm/descriptor/ClouderaManagerDescriptorMonitor.java
- gateway-cm-integration/src/main/java/org/apache/knox/gateway/cm/descriptor/ClouderaManagerDescriptorParser.java
- gateway-cm-integration/src/main/java/org/apache/knox/gateway/cm/descriptor/ClouderaManagerDescriptorParserResult.java
- gateway-cm-integration/src/test/java/org/apache/knox/gateway/cm/descriptor/ClouderaManagerDescriptorParserTest.java
- gateway-cm-integration/src/test/resources/testDescriptor.xml
- gateway-cm-integration/src/test/resources/testDescriptorConfigurationWithNonHadoopStyleConfiguration.xml
- gateway-cm-integration/src/test/resources/testDescriptorWithAdminProviderConfigRemovedUserDnTemplate.xml
- gateway-cm-integration/src/test/resources/testDescriptorWithAdminProviderConfigUpdatedLdapUrl.xml
- gateway-cm-integration/src/test/resources/testDescriptorWithoutDiscoveryDetails.xml
- gateway-server/src/main/java/org/apache/knox/gateway/GatewayServer.java
- gateway-server/src/test/java/org/apache/knox/gateway/topology/simple/ProviderConfigurationParserTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/topology/simple/SimpleDescriptorHandlerTest.java
- gateway-topology-simple/pom.xml
- gateway-topology-simple/src/main/java/org/apache/knox/gateway/topology/simple/JSONProviderConfiguration.java
- gateway-topology-simple/src/main/java/org/apache/knox/gateway/topology/simple/ProviderConfigurationParser.java
- gateway-topology-simple/src/main/java/org/apache/knox/gateway/topology/simple/ProviderOrder.java
- gateway-topology-simple/src/main/java/org/apache/knox/gateway/topology/simple/XMLProviderConfiguration.java
Main changes in this commit:
- implemented a language that Knox understands when parsing shared provider configuration(s) in Haddop XML type descriptors
- XML/JSON provider configurations are moved out to their own classes from ProviderConfigurationParser
- XML/JSON provider configuration classes implement hashCode/equals properly
- XML/JSON provider classes implement Comparable (based on a predefined provider order) as well as fixing the order of fields and alphabetical order withing parameters when serializing
- changed the separator in Hadoop XML type descriptors from semicolon (;) to hash (#) to conform new requirements
- shared providers that are generated using this framework are read-only on Admin UI
- end-users can modify/remove any parameters in a provider w/o touching others
- …
> KNOX-2365 - Knox parses shared provider configuration from Hadoop XML type configuration files

- gateway-server/src/main/java/org/apache/knox/gateway/util/KnoxCLI.java
Fix a bug in KnoxCLI that prevents creating alias when remote zookeeper registry is used with Kerberos auth.
The patch was tested locally.
> KNOX-2348 - Fix knoxcli when kerberos auth is used

- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-service-metadata/pom.xml
- gateway-service-metadata/src/main/java/org/apache/knox/gateway/service/metadata/KnoxMetadataResource.java
- gateway-service-metadata/src/main/java/org/apache/knox/gateway/service/metadata/TopologyInformation.java
- gateway-service-metadata/src/main/java/org/apache/knox/gateway/service/metadata/TopologyInformationWrapper.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
- gateway-test-release-utils/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
- knox-homepage-ui/home/app/generalProxyInformation/general.proxy.information.component.html
- knox-homepage-ui/home/app/generalProxyInformation/general.proxy.information.component.ts
- knox-homepage-ui/home/app/topologies/topology.information.component.html
- knox-homepage-ui/home/app/topologies/topology.information.component.ts
- knox-homepage-ui/home/app/topologies/topology.information.ts
Introduced a new property in `gateway-site.xml` called `knox.homepage.pinned.topologies`. This is a comma-separated list of topology names indicating they should be pinned on the Home Page. If a topology is pinned it's going to be expanded when opening the home page.
The order of the topologies are fixed as follows:
1. pinned topologies come first
2. topologies are sorted in alphabetical order
I made the `General Proxy Information` and `Topologies` sections expandable/collapsable too and made sure the first section is collapsed by default.
On the Home page, you'll see an icon next to the topology name:
- either a pushpin: if the topology is pinned. This is a tooltip icon with a meaningful description of how to make the topology un-pinned.
- or a cog: if the topology is un-pinned. This is …
> KNOX-2366 - Pinned topologies are expanded and general proxy information section is collapsed on HomePage by default

- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/AliasBasedTokenStateService.java
Logging change to be more accurate. As it was, the same log message was being emitted twice for every token.
Full build/tests, and then manually verified the logging change.
> KNOX-2378 - AliasBasedTokenStateService log message is misleading

- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/AliasBasedTokenStateService.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/AliasBasedTokenStateServiceTest.java
The issue was that `AliasBasedTokenStateService.getTokenExpiration(...)` only checked the in-memory cache for token expiration if `validate` flag was set to `false`.  Therefore, if the client wanted to use the previoulsy acquired token before it got written out to the underlying keystore (`__gateway-credentials.jceks`) it received an `expired token` error because this method returned 0 (=nothing was found in either in the memory nor in the keystore).
The fix is as simple as making sure the `validate` flag should not affect the source of the token expiration (it should only validate if needed)
Updated and executed JUnit tests:
```
$ mvn clean -Dshellcheck=true -T1C verify -Prelease,package
...
[INFO] BUILD …
```
> KNOX-2383 - Checking token expiration in cache should not depend on the validate flag

- gateway-service-definitions/src/main/resources/services/yarnuiv2/3.0.0/rewrite.xml
A fix for a missing trailing '/' issue in YARNUIV2 that already fixed in YARNUI see [KNOX-2074](https://issues.apache.org/jira/browse/KNOX-2074)
Manually see the attached screenshot
> KNOX-2381 racking UI of flink session is broken in YARNUIV2

- gateway-service-definitions/src/main/resources/services/flink/1.10.1/rewrite.xml
- gateway-service-definitions/src/main/resources/services/flink/1.10.1/service.xml
This change provides support for Apache Flink Dashboard (a.k.a Flink History Server )
Manual Testing
> KNOX-2385 Flink Dashboard (History Server) Support

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/flink/FlinkServiceModelGenerator.java
- gateway-discovery-cm/src/main/resources/META-INF/services/org.apache.knox.gateway.topology.discovery.cm.ServiceModelGenerator
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/model/flink/FlinkServiceModelGeneratorTest.java
Added CM service discovery support for Apache Flink
Unit testing:
```
[INFO] Total time: 18:09 min (Wall Clock)
[INFO] Finished at: 2020-06-11T14:17:20+02:00
[INFO] Final Memory: 429M/2075M
```
1. deployed Knox with my changes in a running CM cluster
2. updated `Flink Dashboard Port` from 8082 to 9999 and restarted Flink
3. Confirmed that Knox picked-up the change:
```
2020-06-11 04:55:39,891 DEBUG discovery.cm (PollingConfigurationAnalyzer.java:getCurrentServiceConfiguration(470)) - Getting current configuration for …
```
> KNOX-2386 - Added CM service discovery support for Apache Flink

- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/AliasBasedTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/TokenStateServiceMessages.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/state/FileTokenStateJournal.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/state/MultiFileTokenStateJournal.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/state/TokenStateJournalFactory.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/state/JournalEntry.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/state/TokenStateJournal.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/AliasBasedTokenStateServiceTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/DefaultTokenStateServiceTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/state/AbstractFileTokenStateJournalTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/state/FileTokenStateJournalTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/state/MultiFileTokenStateJournalTest.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/TokenStateService.java
With the resolution of KNOX-2375, the potential for token state to be lost between the issuance of a token and its persistence to the keystore. To address this risk, this patchset introduces a TokenStateJournal, the default implementation of which persists small individual files for each token's state until it is persisted in the keystore. This new facility has been integrated into the AliasBasedTokenStateService, which is the driver behind creating it. When token state it added, an entry (file) is added to the journal; Then, once that state has been persisted in the keystore, the journal entry (file) is removed since the risk of loss is no longer present.
Part of the integration includes loading all the persisted token state journal entries when the AliasBasedTokenStateService is …
> KNOX-2377 - Address potential loss of token state

- gateway-service-knoxsso/src/main/java/org/apache/knox/gateway/service/knoxsso/WebSSOResource.java
- gateway-service-knoxsso/src/test/java/org/apache/knox/gateway/service/knoxsso/WebSSOResourceTest.java
Update the Set-Cookie header for hadoop-jwt cookie to include SameSite=none parameter.
> KNOX-2387 - SameSite fix for hadoop-jwt cookie

- gateway-provider-security-pac4j/src/main/java/org/apache/knox/gateway/pac4j/config/AzureADClientConfigurationDecorator.java
- gateway-provider-security-pac4j/src/main/java/org/apache/knox/gateway/pac4j/config/ClientConfigurationDecorator.java
- gateway-provider-security-pac4j/src/main/java/org/apache/knox/gateway/pac4j/config/Pac4jClientConfigurationDecorator.java
- gateway-provider-security-pac4j/src/main/java/org/apache/knox/gateway/pac4j/config/SAML2ClientConfigurationDecorator.java
- gateway-provider-security-pac4j/src/main/java/org/apache/knox/gateway/pac4j/filter/Pac4jDispatcherFilter.java
- gateway-provider-security-pac4j/src/test/java/org/apache/knox/gateway/pac4j/config/AzureADClientConfigurationDecoratorTest.java
- gateway-provider-security-pac4j/src/test/java/org/apache/knox/gateway/pac4j/config/Pac4jClientConfigurationDecoratorTest.java
- gateway-provider-security-pac4j/src/test/java/org/apache/knox/gateway/pac4j/config/SAML2ClientConfigurationDecoratorTest.java
From now on, end-users can set the following SAML 2 configurations using provider parameters (in addition to the already supported params):
- useNameQualifier
- forceAuth
- passive
- nameIdPolicyFormat
Additionally, I refactored the special `Azure AD` client handling to its own class (another implementation of the new interface).
Added and executed JUnit tests:
```
[INFO] Total time: 18:47 min (Wall Clock)
[INFO] Finished at: 2020-06-18T12:40:14+02:00
[INFO] Final Memory: 432M/2028M
```
Manually tested with different provider …
> KNOX-2390 - Let end-users configure SAML2 client configuration using Pac4J provider parameters

- gateway-provider-security-jwt/pom.xml
- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/JWTMessages.java
- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/SSOCookieFederationFilter.java
This patch was tested on local cluster
This change proposes adding a configurable parameter that adds a list of path elements to be ignored by SSOCookieProvider. Default set includes favicon.ico.
This is because Browsers will send unsolicited requests to get favicon.ico which can break SSO experience especially when default topology feature is used when content is served from the root.
> KNOX-2393 - Add a configurable list of paths  that SSOCookieProvider can ignore

- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/AliasBasedTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/JournalBasedTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/TokenStateServiceMessages.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/AliasBasedTokenStateServiceTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/DefaultTokenStateServiceTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/JournalBasedTokenStateServiceTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/state/AbstractFileTokenStateJournalTest.java
I've created a TokenStateService implementation that avoids the unnecessary overhead associated with the AliasBasedTokenStateService (size of keystore and associated performance of access).
Since KNOX-2377 added the TokenStateJournal for addressing the potential loss of token state due to changes necessary to improve the performance of the AliasBasedTokenStateService, this new implementation leverages that journaling facility alone to manage token state. It is effectively, the AliasBasedTokenStateService without the keystore interactions.
I've not yet made this implementation the default, but I have tested it locally, and I foresee this becoming the default for the near future since the use of the keystore presents an unnecessary burden now that secrets are no longer persisted with token …
> KNOX-2392 - Simple file-based TokenStateService implementation

- pom.xml
`netty-all` is pulled in transitively and we should upgrade to the latest 4.1.x version.
> KNOX-2405 - Upgrade transitive Netty to 4.1.51.Final

- gateway-server/src/main/java/org/apache/knox/gateway/services/factory/AbstractServiceFactory.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/factory/AliasServiceFactory.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/factory/TokenStateServiceFactory.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/security/impl/ZookeeperRemoteAliasService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/security/impl/ZookeeperRemoteAliasServiceProvider.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/ZookeeperTokenStateService.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/factory/ServiceFactoryTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/factory/TokenStateServiceFactoryTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/security/impl/RemoteAliasServiceTestProvider.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/ZookeeperTokenStateServiceTest.java
- gateway-service-hashicorp-vault/src/main/java/org/apache/knox/gateway/backend/hashicorp/vault/HashicorpVaultRemoteAliasServiceProvider.java
- gateway-spi/src/main/java/org/apache/knox/gateway/security/RemoteAliasServiceProvider.java
Added a new token state service implementation that uses Zookeeper as token storage.
Updated/ran JUnit tests and executed the following manual test steps:
1. Enabled token state service in sandbox:
```
<param>
<name>knox.token.exp.server-managed</name>
</param>
```
2. Configured Knox to use the new ZK Token State Service in `gateway-site.xml`:
```
<property>
<name>gateway.service.tokenstate.impl</name>
<value>org.apache.knox.gateway.services.token.impl.ZookeeperTokenStateService</value>
</property>
<property>
<name>gateway.remote.config.registry.zookeeper-client</name>
<value>type=ZooKeeper;address=$ZK_HOST:2181</value>
<description>ZooKeeper configuration registry client details.</description>
</property>
<property>
<name>gateway.remote.config.monitor.client</name> …
```
> KNOX-2399 - Implemented ZookeeperTokenStateService

- pom.xml
* Use bom for jackson, jetty, netty, and spring.
* `mvn -T.75C clean verify -U -Ppackage,release -Dshellcheck`
> KNOX-2406 - Use dependency bom for dependency management

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/monitor/PollingConfigurationAnalyzer.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/monitor/PollingConfigurationAnalyzerTest.java
CM service discovery handles the recently introduced `RestartWaitingForStalenessSuccess` audit event.
Updated and ran JUnit tests. As well as manually tested:
1. redeployed Knox with my changes (topology cdp-proxy was already configured to monitor my remote CM cluster where ATLAS was installed)
2. changed `atlas.server.https.port` from 31443 to 31445 and restarted the stale services
3. waited for the restart to finish and confirmed that `cdp-proxy` got redeployed due to the CM config change and ATLAS had the new port number:
> KNOX-2410 - Handling the new 'RestartWaitingForStalenessSuccess' CM audit event

- pom.xml
knox failed to start with error "java.lang.NoSuchMethodError:org.eclipse.persistence.internal.oxm.mappings.Field.setNestedArray(Z)V"
There are mixed version of 2.7.6 and 2.7.4 eclipse persistence jars in knox/dep folder:
eclipselink-2.7.6.jar
sdo-eclipselink-plugin-2.3.2.jar
jaxws-eclipselink-plugin-2.3.2.jar
org.eclipse.persistence.core-2.7.4.jar
org.eclipse.persistence.sdo-2.7.4.jar
org.eclipse.persistence.asm-2.7.4.jar
org.eclipse.persistence.moxy-2.7.4.jar
We should upgrade jaxws-ri from 2.3.2 to 2.3.3 so that eclipse persistence class will have the same 2.7.6 version.
> KNOX-2397 knox failed to start with error "java.lang.NoSuchMethodError: org.eclipse.persistence.internal.oxm.mappings.Field.setNestedArray(Z)V"

- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-server/src/test/java/org/apache/knox/gateway/GatewayGlobalConfigTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/config/impl/GatewayConfigImplTest.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
Replace hardcoded `JKS` with `KeyStore.getDefaultType()`
* Check that this fixes FIPS crypto when default keystore configured at JDK level
> KNOX-2434 - Knox should fallback to JDK default keystore/truststore type instead of hardcoding JKS

- gateway-service-definitions/src/main/resources/services/nifi-registry/0.5.0/service.xml
- gateway-service-definitions/src/main/resources/services/nifi/1.4.0/service.xml
In this jira i've fixed NiFi UI and NiFi Registry UI links in Knox UI. In general urls were correct, but in the end of each url also should be added "/nifi" and "/nifi-registry".
I've deployed DC cluster https://vbfkis-1.vbfkis.root.hwx.site:7183/cmf/home, changed service.xml files for NiFi and NiFi Registry (via Knox Admin UI) and restarted Knox. After that i was able to get into NiFi UI and NiFi Registry UI through Knox UI links.
> KNOX-2435 Fix NiFi and NiFi Registry UI links in Knox UI

- gateway-provider-security-hadoopauth/pom.xml
- gateway-provider-security-hadoopauth/src/main/java/org/apache/knox/gateway/hadoopauth/HadoopAuthMessages.java
- gateway-provider-security-hadoopauth/src/main/java/org/apache/knox/gateway/hadoopauth/filter/HadoopAuthFilter.java
- gateway-provider-security-hadoopauth/src/main/java/org/apache/knox/gateway/hadoopauth/filter/HadoopAuthPostFilter.java
- gateway-provider-security-hadoopauth/src/test/java/org/apache/knox/gateway/hadoopauth/filter/HadoopAuthFilterTest.java
- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/AbstractJWTFilter.java
- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/JWTFederationFilter.java
- gateway-server/src/main/java/org/apache/knox/gateway/GatewayFilter.java
Added a new provider configuration parameter in the `HadoopAuth` security provider to enable end-users to use JWT tokens instead of the usual Hadoop Authentication mechanism if there is a Bearer token defined in the request's `Authorization` header. The new parameter name is `support.jwt`. If that is set to `true` (defaults to `false`) and there is a _valid_  (parsable, non-expired) JWT token in the authorization header Knox will use that token in the HadoopAuth security provider.
Updated and ran JUnit tests:
```
[INFO] Total time: 20:01 min (Wall Clock)
[INFO] Finished at: 2020-07-30T22:42:31+02:00
[INFO] …
```
> KNOX-2413 - Added JWT support in HadoopAuth provider

- build-tools/src/main/resources/build-tools/spotbugs-filter.xml
- gateway-performance-test/pom.xml
- gateway-performance-test/src/main/java/org/apache/knox/gateway/performance/test/ExecutorServiceUtils.java
- gateway-performance-test/src/main/java/org/apache/knox/gateway/performance/test/PerformanceTestConfiguration.java
- gateway-performance-test/src/main/java/org/apache/knox/gateway/performance/test/PerformanceTestLifeCyleListener.java
- gateway-performance-test/src/main/java/org/apache/knox/gateway/performance/test/PerformanceTestMessages.java
- gateway-performance-test/src/main/java/org/apache/knox/gateway/performance/test/PerformanceTestRunner.java
- gateway-performance-test/src/main/java/org/apache/knox/gateway/performance/test/ResponseTimeCache.java
- gateway-performance-test/src/main/java/org/apache/knox/gateway/performance/test/UseCaseRunner.java
- gateway-performance-test/src/main/java/org/apache/knox/gateway/performance/test/knoxtoken/KnoxTokenAction.java
- gateway-performance-test/src/main/java/org/apache/knox/gateway/performance/test/knoxtoken/KnoxTokenCache.java
- gateway-performance-test/src/main/java/org/apache/knox/gateway/performance/test/knoxtoken/KnoxTokenUseCaseRunner.java
- gateway-performance-test/src/main/java/org/apache/knox/gateway/performance/test/knoxtoken/KnoxTokenWorkerThread.java
- gateway-performance-test/src/main/java/org/apache/knox/gateway/performance/test/reporting/AbstractReportEngine.java
- gateway-performance-test/src/main/java/org/apache/knox/gateway/performance/test/reporting/GatewayMetricsReporter.java
- gateway-performance-test/src/main/java/org/apache/knox/gateway/performance/test/reporting/JsonReportEngine.java
- gateway-performance-test/src/main/java/org/apache/knox/gateway/performance/test/reporting/ReportEngine.java
- gateway-performance-test/src/main/java/org/apache/knox/gateway/performance/test/reporting/YamlReportEngine.java
- gateway-performance-test/src/main/resources/META-INF/services/org.apache.knox.gateway.performance.test.UseCaseRunner
- gateway-performance-test/src/test/resources/performance.test.configuration.properties
- gateway-performance-test/src/test/resources/performanceTest-log4j.properties
- gateway-release/pom.xml
- gateway-server/src/main/java/org/apache/knox/gateway/services/security/impl/DefaultKeystoreService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/TokenStateServiceStatistics.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/AliasBasedTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/DefaultTokenStateService.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/AbstractRequest.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/TokenStateServiceStatisticsMBean.java
- pom.xml
All is described [here](https://cwiki.apache.org/confluence/display/KNOX/KNOX-2402+-+Develop+a+performance-test+framework+to+test+token+state+service).
Manual testing: configured a Knox Gateway and executed the performance test tool multiple times. I checked the generated test results as well as the log files. See the above-referenced link for more information.
I even revealed some performance test issues in `AliasBasedTokenStateService` (see [KNOX-2408](https://issues.apache.org/jira/browse/KNOX-2408))
> KNOX-2402 - Adding Gateway performance testing

- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/security/impl/DefaultAliasService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/security/impl/DefaultKeystoreService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/security/impl/RemoteAliasService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/security/impl/ZookeeperRemoteAliasService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/AliasBasedTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/DefaultTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/JournalBasedTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/TokenStateServiceMessages.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/security/CryptoServiceTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/security/impl/RemoteAliasServiceTestProvider.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/AliasBasedTokenStateServiceTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/DefaultTokenAuthorityServiceTest.java
- gateway-service-hashicorp-vault/src/main/java/org/apache/knox/gateway/backend/hashicorp/vault/HashicorpVaultAliasService.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/AbstractAliasService.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/AliasService.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/KeystoreService.java
- gateway-test-release-utils/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
- Let end-users customize the size/TTL attributes of the cache in `DefaultKeystoreService` I introduced while working on [KNOX-2136](https://issues.apache.org/jira/browse/KNOX-2136)
- `AliasBasedTokenStateService.updateExpiration` updates the data in-memory and let the background thread does its job
- if `AliasBasedTokenStateService` is selected as token state service, a new background thread is run when the service is started which reads previously persisted relevant aliases into the in-memory collections (in `DefaultTokenStateService`). With this change, it's not needed to override `getTokens` in `AliasBasedTokenStateService` which is only used by the reaper thread when evicting expired tokens. Instead, the token eviction logic will wait until everything is loaded.
- …
> KNOX-2408 - Improved AliasBasedTokenState service and house-keeping

- gateway-server/src/main/java/org/apache/knox/gateway/websockets/GatewayWebsocketHandler.java
URI.getPath() returns is an encoded URL
The request does not have to be coded, they should be rewritten but left as they are.
Backend applications expect that they are not.
all unit tests are working after the fix
> KNOX-2437 The request url does not have to be coded

- gateway-server/src/main/java/org/apache/knox/gateway/websockets/GatewayWebsocketHandler.java
- gateway-server/src/test/java/org/apache/knox/gateway/websockets/WebsocketBackendUrlTest.java
Fix proper handling of [Host header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host) when websocket requests are proxied through Knox. Currently the host header contains knox hostname instead of the websocket backend host name (this is during the http upgrade part of WS request). This PR fixes this issue.
This patch was tested on a local cluster
> KNOX-2453 Fix Host header handling in websockets

- gateway-topology-simple/src/main/java/org/apache/knox/gateway/topology/simple/SimpleDescriptorHandler.java
There are some services internal to the Knox Gateway that do not need any URL or param defined in a descriptor to be added in the generated topology. Until now, only the `KNOX` service was like that. However, there are 3 more services which should behave the same way: `KNOX-METADATA`, `KNOXSSOUT` and `KNOX-SESSION`.
Tested manually: added a new descriptor called `test` with these services and confirmed that the generated topology contained all of them.
> KNOX-2459 - KNOX-METADATA, KNOXSSOUT and KNOX-SESSION services do not need any URL or param to be added in the generated topology

- gateway-provider-security-shiro/src/main/java/org/apache/knox/gateway/deploy/impl/ShiroConfig.java
- gateway-test-release-utils/src/main/java/org/apache/knox/gateway/GatewayTestDriver.java
- gateway-test/src/test/java/org/apache/knox/gateway/GatewayShiroAuthTest.java
- pom.xml
This PR is to upgrade Shiro library to 1.6.0. Shiro 1.6.0 introduces some drastic changes in response to a security issue (see [Global Filters](https://shiro.apache.org/web.html#global-filters)) these changes will break some of the proxying services that include `;` `\` in the URL. `;` is most commonly used for `jsessionid` so that likely will introduce some breakage. We try to mitigate this breakage by turning off blocking `;`, `\` and non-ascii characters by setting the following properties to false out of the box.
1. `invalidRequest.blockBackslash = false`
2. `invalidRequest.blockSemicolon = false`
3. `invalidRequest.blockNonAscii = false`
These properties can be set to true in Knox topology (by adding shiro providers param section).
This PR also adds unit tests to test these changes. …
> KNOX-2455 - Upgrade Shiro to 1.6.0

- gateway-provider-ha/pom.xml
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/dispatch/DefaultHaDispatch.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/dispatch/i18n/HaDispatchMessages.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/HaProvider.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/HaServiceConfig.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/URLManager.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/impl/BaseZookeeperURLManager.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/impl/DefaultHaProvider.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/impl/DefaultHaServiceConfig.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/impl/DefaultURLManager.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/impl/HaDescriptorConstants.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/impl/HaDescriptorFactory.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/impl/HaDescriptorManager.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/impl/HaServiceConfigConstants.java
- gateway-provider-ha/src/test/java/org/apache/knox/gateway/ha/dispatch/DefaultHaDispatchTest.java
- gateway-provider-ha/src/test/java/org/apache/knox/gateway/ha/provider/impl/HaDescriptorFactoryTest.java
- gateway-provider-ha/src/test/java/org/apache/knox/gateway/ha/provider/impl/HaDescriptorManagerTest.java
- gateway-service-rm/src/test/java/org/apache/knox/gateway/rm/dispatch/RMHaDispatchTest.java
- gateway-service-webhdfs/src/test/java/org/apache/knox/gateway/hdfs/dispatch/WebHdfsHaDispatchTest.java
- gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/DefaultDispatch.java
This PR introduces a way for Knox to load balance backend clients. This is done by introducing 3 parameters in `HaProvider`
1. `enableStickySession` - Enables sticky sessions
2. `stickySessionCookieName` - Customize sticky session cookie name, default is KNOX_BACKEND-{serviceName}
3. `noFallback` - when this flag is set, Knox will return a 502 (Bad Gateway) if a request comes with a cookie and the corresponding backend is unavailable. This is applicable only when `stickySessionCookieName` is enabled.
4. `enableLoadBalancing` - Enable loadbalancing, roundrobin requests to backend HA urls
```
<provider>
<role>ha</role>
<name>HaProvider</name>
<param>
<name>WHOAMI</name>
<value>enabled=true;maxFailoverAttempts=3;failoverSleep=1000;enableStickySession=true;noFallback=tr …
```
> KNOX-843 - Client side HA

- gateway-server/src/main/java/org/apache/knox/gateway/GatewayMessages.java
- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/security/impl/CLIMasterService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/security/impl/DefaultKeystoreService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/AliasBasedTokenStateService.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/security/impl/RemoteAliasServiceTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/DefaultTokenAuthorityServiceTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/websockets/BadUrlTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/websockets/WebsocketEchoTestBase.java
- gateway-server/src/test/java/org/apache/knox/gateway/websockets/WebsocketMultipleConnectionTest.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
- gateway-test-release-utils/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
KNOX-2463 - Let end-users customize security algorithm for internal credential stores
KNOX-2464 - KnoxCLI should pass GatewayConfig when setting up master secret so that encryptor becomes initialized
This PR contains resolution for 3 JIRAs at once (using different commits, of course) as they are related to each other. In these commits, I made sure that:
- credential store type is configurable via `gateway-site.xml` (defaults to `JCEKS`)
- the algorithm Knox uses when creating an entry in a credential is configurable via `gateway-site.xml` (defaults to `AES`)
- fixed the bug in KnoxCLI of not considering inputs from `gateway-site.xml`
Tested manually in a CM managed cluster where I set:
```
gateway.credential.store.type = BCFKS
gateway.credential.store.alg = HMACSHA512 …
```
> KNOX-2462 - Make credential store type configurable

- gateway-server/src/main/java/org/apache/knox/gateway/services/security/impl/DefaultKeystoreService.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/security/impl/DefaultKeystoreServiceTest.java
This patch fixes a potential issue regarding the creation of Knox's keystores. The current logic checks to see if the keystore path exists--if it doesn't, it tries to create the parent folder of the keystore path. However, there is an edge case, as described in JDK-8130464, where the directory creation fails if the final, parent directory of the keystore path is a symlink. This causes a failure during startup. This PR remedies this by checking if the keystore parent directory exists instead of checking the keystore itself, as checking directories is symlink-safe. There is also no extra logic after the keystore creation, so if the keystore …
> KNOX-2469 - Fixing Knox keystore path directory creation for symlinks

- gateway-service-nifi/src/main/java/org/apache/knox/gateway/dispatch/NiFiRequestUtil.java
Fix an issue where extra nifi-app context is appended when there is a HA failover.
Patch was tested locally
> KNOX-2476 - Fix issue with X-Forwarded-Context header when there is a failover

- gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/DefaultDispatch.java
- gateway-spi/src/test/java/org/apache/knox/gateway/dispatch/ConfigurableDispatchTest.java
Fix an issue where set-cookie responses from are broken when backend services send set-cookies with no spaces.
Locally tested
> KNOX-2479 - Fix an issue where Knox munges set-cookie header

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerCluster.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ServiceModel.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/hdfs/HdfsUIServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/hdfs/NameNodeServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/hdfs/WebHdfsServiceModelGenerator.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/solr/SolrServiceModelGenerator.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/model/AbstractServiceModelGeneratorTest.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/model/hdfs/HdfsUIServiceModelGeneratorTest.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/model/hdfs/NameNodeServiceModelGeneratorTest.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/model/hdfs/WebHdfsServiceModelGeneratorTest.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/model/solr/SolrServiceModelGeneratorTest.java
In the case of some services, or specific deployments of those services, there exists the need to direct the discovery process for topology generation. One example is HA HDFS deployments, where a particular nameservice can be desired to be proxied. Another example is multiple Solr instances within the same cluster, where one should be proxied but not the other(s).
This change introduces for Cloudera Manager discovery the concept of discovery-time-only service parameters in simple descriptors. This is already supported by Amabari service discovery for the aforementioned HDFS HA scenario, and the same pattern is being applied and extended for Cloudera Manager.
Service parameters beginning with "discovery-" can be declared for supported services in simple descriptors. The actual names of the …
> KNOX-2530 - Support qualifying service params for CM discovery control

- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/AbstractJWTFilter.java
- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/JWTAccessTokenAssertionFilter.java
- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/JWTAuthCodeAssertionFilter.java
- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/AbstractJWTFilterTest.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/DefaultTokenAuthorityService.java
- gateway-service-knoxsso/src/main/java/org/apache/knox/gateway/service/knoxsso/WebSSOResource.java
- gateway-service-knoxsso/src/test/java/org/apache/knox/gateway/service/knoxsso/WebSSOResourceTest.java
- gateway-service-knoxtoken/pom.xml
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
- gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
- gateway-spi/src/main/java/org/apache/knox/gateway/filter/security/AbstractIdentityAssertionFilter.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/TokenUtils.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/impl/JWT.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/impl/JWTToken.java
In this change, I'm extending the current RSA based token signing with the use of HMAC. As described in the corresponding JIRA, from now on end-users are able to configure an HMAC secret in the gateway's alias service which then will be used as a signature secret (pay attention to the key size requirements!).
Updated and ran a full maven build successfully and executed E2E tests:
1. configured the `gateway.signing.hmac.secret` alias:
```
$ bin/knoxcli.sh list-alias
Listing aliases for: __gateway
gateway.signing.hmac.secret
```
2. Added the `KNOXTOKEN` service in the `sandbox` topology:
```
<service>
<role>KNOXTOKEN</role>
<param>
<name>knox.token.ttl</name>
<value>36000000</value>
</param>
<param>
<name>knox.token.audiences</name>
<value>tokenbased</value>
</param>
<param> …
```
> KNOX-2527 - Added support for HMAC signature/verification in JWT token authority

- gateway-admin-ui/admin-ui/app/provider-config-wizard/switchcase-idassertion-provider-config.ts
Modified the Admin UI to allow entering `none` in the SwichCase shared provider configuration for the `Principal Case` and `Group Principal Case` input fields.
Manually confirmed it's working:
```
$ cat conf/shared-providers/test.json 
{
"providers": [
{
"role": "identity-assertion",
"name": "SwitchCase",
"enabled": "true",
"params": {
"principal.case": "none",
"group.principal.case": "none"
}
}
]
}
```
> KNOX-2532 Supporting 'none' user/group principal case setting in SwitchCase identity assertion provider

- gateway-service-definitions/src/main/resources/services/yarnui/2.7.0/rewrite.xml
For unexplained reasons, most of the time SHS links are in the format `http://host:port/proxy/application_123_456`, but sometimes they can be `/proxy/application_123_456`.
This causes broken URLs on the page, along with the following logged error.
```
Failed to rewrite URL: /proxy/application_1597654526563_0024/, direction: OUT via rule: YARNUI/yarn/outbound/apps/history, status: FAILURE
```
This patch fixes the issue.
Tested in local production cluster.  Spawned up hundreds of spark jobs and checked links, without this patch every 1 in 20 or so is broken.  With the patch, all previously broken links now work.
> KNOX-2456 SHS links sometimes broken on FINISHED jobs page

- .travis.yml
Adds an extra job to TravisCI config to run the build and tests on ARM64 Graviton2 node.
With this change the current build and tests will be executed on ARM64 CPU architecture and make sure that Knox works properly on this architecture.
> KNOX-2535 Add a job to build and test on ARM64 Graviton2 node at TravisCI

- gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/DefaultDispatch.java
- gateway-spi/src/test/java/org/apache/knox/gateway/dispatch/ConfigurableDispatchTest.java
In Knox dispatch make sure the SET-COOKIE attributes are ordered to prevent breaking services.
tested manually locally.
> KNOX-2538 - Make sure SET-COOKIE attributes are ordered properly

- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/JWTFederationFilter.java
- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/JWTAsHTTPBasicCredsFederationFilterTest.java
Change-Id: I37271ed387a990ce1c0f54aa5893cec50281765e
To facilitate the use of token based authentication for 3rd party tools, like BI tools and others that expose username and password fields but nothing for Bearer token, this change will allow HTTP Basic creds to carry a JWT token as the password.
* New unit tests added
* Manual testing of http basic creds with JWT token
> KNOX-2539 - Enhance JWTProvider to accept token via HTTP Basic

- gateway-release/home/conf/gateway-site.xml
This PR fixes a typo in current gateway-site.xml. Config gateway.group.config.hadoop.security.group.mapping.ldap.search.attr.member is written incorrectly as hgateway.group.config.adoop.security.group.mapping.ldap.search.attr.member
It looks a very small typo, so relying on Travis CI tests only, please suggest if any more tests are required
> KNOX-2541: Fixed Typo in gateway-site.xml

- gateway-provider-security-hadoopauth/src/main/java/org/apache/knox/gateway/hadoopauth/filter/HadoopAuthFilter.java
- gateway-provider-security-hadoopauth/src/main/java/org/apache/knox/gateway/hadoopauth/filter/HadoopAuthPostFilter.java
- gateway-provider-security-hadoopauth/src/test/java/org/apache/knox/gateway/hadoopauth/filter/HadoopAuthFilterTest.java
- gateway-server/src/main/java/org/apache/knox/gateway/GatewayFilter.java
Removed the redundant modification of the filter parameters as it's not needed but might cause issues.
Ran unit tests and manual E2E testing.
> KNOX-2548 - Removing redundant removeParamPrefix method and its references

- gateway-discovery-cm/pom.xml
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryMessages.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/monitor/PollingConfigurationAnalyzer.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/monitor/PollingConfigurationAnalyzerTest.java
To mitigate the chance of losing relevant audit events from CM, Knox needs to look back a little bit more than the last query timestamp. To be able to do this without processing relevant events again and again a cache was introduced to have them in memory for a short time.
Additionally, I removed made the maximum audit event resultset size so that every audit event are fetched from CM within the given time interval.
(Manual testing with Knox HA and a live CM.
> KNOX-2549 - Fetching audit events from CM beyond previous query timestamp

- gateway-service-definitions/src/main/resources/services/spark3historyui/3.0.0/service.xml
Added the missing metadata into Spark3's service.xml
Manually tested and verified Spark 3 UI tile is displayed on the Knox Home page.
> KNOX-2550 - Added metadata into Spark3's service.xml

- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
- gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
From now on, the generated token ID is added into to JSON response in addition to the access token.
Updated/ran JUnit test.
Sample response (used `curl`):
```
{"access_token":"eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJoZGZzIiwiYXVkIjoiaWRicm9rZXIiLCJpc3MiOiJLTk9YU1NPIiwiZXhwIjoxNjE1ODM1Njc1LCJrbm94LmlkIjoiMjU1ZTdlNDctY2FiZi00MTRjLTk5N2MtOGM4NWI1ZTcwYTc4In0.NYWsM3hZ6pEu-cWU0lr5Fge06eh5_iS5bIl5OSr8nf-t_hl12rJ4eNoeCx0lIpiwEQYQFJ46vnSlMIrG5q6bJDI6JyuPVejIq4qOWqtBkGjwm0BtDTehPU0xm0l5ykwdVfiyzeZ27ED19pUEq3L2cgJeC5T3NrgYtuXFRFmz1SnEiQMv0ycnFhlcdtLWEv6dS26Sq_T0HS2YF5-MN7IaAiAu4VplqaQ-N7C86FNLA3GNcVu3vnUbZ-cj8gKZXEj0lLxLMYpedSHGVTptfOyR9Dw6FwGI6OlDH1BC2gtnAX6lLiL-fuJ9-VzLvrt-c7v9A8MQMyJkjKwlYxc3ENgOxA","endpoint_public_cert":"MIIDkDCCAnigAwIBAgIIYxwYvhmkhgkwDQYJKoZIhvcNAQEFBQAwXzELMAkGA1UEBhMCVVMxDTALBgNVBAg …
```
> KNOX-2552 - Including the generated Token ID in the JSON response for the KnoxToken service

- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/JWTAccessTokenAssertionFilter.java
- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/JWTAuthCodeAssertionFilter.java
- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/AbstractJWTFilterTest.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/DefaultTokenAuthorityService.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/DefaultTokenAuthorityServiceTest.java
- gateway-service-knoxsso/src/main/java/org/apache/knox/gateway/service/knoxsso/WebSSOResource.java
- gateway-service-knoxsso/src/test/java/org/apache/knox/gateway/service/knoxsso/WebSSOResourceTest.java
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
- gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/JWTokenAttributes.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/JWTokenAttributesBuilder.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/JWTokenAuthority.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/impl/JWTToken.java
In order to avoid adding new and confusing methods into `JWTokenAuthority`, I introduced a model object to store possible JWT attributes and kept only one method to issue a token.
So, from now on, the `managed` flag is available in:
- the JSON response as a new element
- the issued JWT token within a claim called `managed.token`
Updated/added/ran unit tests and executed manual testing:
1. added the `KNOXTOKEN` service into `sandbox`. Set the `knox.token.exp.server-managed` to `false` and then changed it to `true` (see results below)
2. added a new topology called `tokenbased`
3. I could login to the Knox Home page and to Admin UI
4. Issued the following `curl` commands
4.1 `knox.token.exp.server-managed = false`
```
$ curl -iku admin:admin-password …
```
> KNOX-2553 - Adding the 'managed_token' flag in the issued JWT as well as the JSON response of our KnoxToken service

- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/AliasBasedTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/DefaultTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/JournalBasedTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/ZookeeperTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/state/FileTokenStateJournal.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/state/MultiFileTokenStateJournal.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/state/JournalEntry.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/state/TokenStateJournal.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/AliasBasedTokenStateServiceTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/DefaultTokenStateServiceTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/JournalBasedTokenStateServiceTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/ZookeeperTokenStateServiceTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/state/AbstractFileTokenStateJournalTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/state/FileTokenStateJournalTest.java
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
- gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/TokenMetadata.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/TokenStateService.java
Enriched the token state persistence layer (in-memory, alias, and file journal) to store additional metadata:
- username
- comment
Updated and ran JUnit tests:
```
$ mvn clean -Dshellcheck=true verify -Prelease,package -am -pl gateway-service-knoxtoken
...
[INFO] Reactor Summary:
[INFO] 
[INFO] build-tools ........................................ SUCCESS [  3.144 s]
[INFO] gateway ............................................ SUCCESS [ 26.414 s]
[INFO] gateway-test-utils ................................. SUCCESS [ 11.378 s]
[INFO] gateway-i18n ....................................... SUCCESS [ 13.076 s]
[INFO] gateway-util-common ................................ SUCCESS [ 15.629 s]
[INFO] …
```
> KNOX-2557 - Persisting token related metadata using Knox's alias service

- gateway-provider-security-hadoopauth/pom.xml
- gateway-provider-security-hadoopauth/src/main/java/org/apache/knox/gateway/hadoopauth/filter/HadoopAuthPostFilter.java
- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/JWTMessages.java
- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/AbstractJWTFilter.java
- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/JWTFederationFilter.java
- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/AbstractJWTFilterTest.java
- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/CommonJWTFilterTest.java
- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/JWTAsHTTPBasicCredsFederationFilterTest.java
- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/JWTFederationFilterTest.java
- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/TestJWTFederationFilter.java
- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/TokenIDAsHTTPBasicCredsFederationFilterTest.java
Added JWTProvider support for specifying the unique identifier associated with Knox JWTs as a HTTP Basic password (username=TokenPasscode, password=&lt;UUID&gt;) when server-managed token state is enabled.
Example:
curl -ivku TokenPasscode:$PASSCODE "https://localhost:8443/gateway/proxy-token/webhdfs/v1/?op=LISTSTATUS"
I've added org.apache.knox.gateway.provider.federation.TokenIDAsHTTPBasicCredsFederationFilterTest and executed all the existing Knox tests (mvn -Ppackage,release clean package).
I've manually tested by:
- Enabling server-managed token state in the homepage deployment of KNOXTOKEN
- Defining a provider configuration with the JWTProvider (with server-managed token state enabled)
- Defining a descriptor that references that provider config
- Generated a token using the …
> KNOX-2556 - Enhance JWTProvider to accept knox.id as Passcode Token

- gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/DefaultHttpClientFactory.java
- gateway-spi/src/test/java/org/apache/knox/gateway/dispatch/DefaultHttpClientFactoryTest.java
Add option to replay requests when the server unexpectedly closes the connection (not in case of socket timeouts where the server is unable to reach)
Proposed changes are adding optional service params 
1. `retryCount` - how many times should a request be retried
2. `retryNonSafeRequest` - Should an unsafe request be retries, unsafe = POST, PUT, DELETE (!GET)
example
`
<service>
<role>WHOAMI</role>
<url>http://localhost:50071</url>
<param name="retryCount" value="5"/>
</service>
`
> KNOX-2543 - Add ability to retry failed requests

- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/JWTMessages.java
- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/AbstractJWTFilter.java
- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/JWTFederationFilter.java
- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/AbstractJWTFilterTest.java
- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/JWTAsHTTPBasicCredsFederationFilterTest.java
- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/TokenIDAsHTTPBasicCredsFederationFilterTest.java
Added some checks for missing Knox token UUID claim around the signature verification caching (which was added as part of KNOX-2544) to avoid NullPointerException when JWTs which were not issued by Knox (but which Knox can verify) are received.
Added org.apache.knox.gateway.provider.federation.AbstractJWTFilterTest#testJWTWithoutKnoxUUIDClaim() and org.apache.knox.gateway.provider.federation.AbstractJWTFilterTest#testExpiredJWTWithoutKnoxUUIDClaim()to reproduce the NPE condition and then to verify the fix. Ran all other existing tests as part of the build.
> KNOX-2566 - JWT Token Signature Verification Caching NPE

- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/AliasBasedTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/DefaultTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/JournalBasedTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/ZookeeperTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/state/MultiFileTokenStateJournal.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/ZookeeperTokenStateServiceTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/state/MultiFileTokenStateJournalTest.java
- gateway-util-common/src/main/java/org/apache/knox/gateway/util/Tokens.java
- gateway-util-common/src/test/java/org/apache/knox/gateway/util/TokensTest.java
Apparently, there are a number of places where the UUIDs associated with Knox JWTs are still being logged in their entirety.
This change is to mask all of those remaining messages.
Added ZookeeperTokenStateServiceTest#testTokenIDDisplayText() to test the masking of token ID in aliases.
Added MultiFileTokenStateJournalTest#testGetDisplayableJournalFilepathWithID() and MultiFileTokenStateJournalTest#testGetDisplayableJournalFilepathWithoutID() to test the masking of journal entry file paths that contain UUIDs.
The rest of the changes involving plain tokens uses the previously tested Tokens.getTokenIDDisplayText(String id) facility.
> KNOX-2572 - Unique token identifiers still being logged in entirety

- gateway-service-knoxtoken/pom.xml
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/JWKSResource.java
- gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/JWKSResourceTest.java
This PR adds support for JWKS endpoint that exposes the public key used to sign the JWT tokens. The format used is the standard JWKS format. 
This is an example of rest request
` curl -ku admin:admin-password 'https://localhost:8443/gateway/sandbox/knoxtoken/api/v1/.well-known/jwks.json`
and the response
```
{
"keys":[
{
"kty":"RSA",
"e":"AQAB",
"use":"sig",
"kid":"7T805L6i36S0U0mVcO\/WjuPD1TtNehUXjQa7uBdet34=",
"alg":"RS256",
"n":"t2muUKwV9Zx8Q3NWy5vhu_EszpBkfa8cZjhJpF8IHNkx2kbf8aeRTr3KwGInPYx6bVVD1eNzjDX_m5afyHfQr4O_PHSiaxtJPN16kmoVnxQW8ZxnT2GlMUY6TL2t79Ovrhnkig-4_rP5qH0ruZZJpNcly-FLKoMd23apy8BCe9lSaSIbWUVU5YrVzWzuO3TWILSQCoIS8-4j6G0JmzaOu4t3f0yATE7WaJbqW9UmEAyTDIlft0Xnh1Oz_UHWAe5LLVYyVh6Xr8lMUOBj1oAVAKLJrd0ZeKb-UerTKuCzuRM2yI-idXCZFaJQ3x4KklYihL6Qc7FPjRestPxIeBJl1w"
}
]
}
```
The patch …
> KNOX-2570 - Add support for JWKS endpoint

- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-service-metadata/src/main/java/org/apache/knox/gateway/service/metadata/KnoxMetadataResource.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
- gateway-spi/src/main/java/org/apache/knox/gateway/dto/HomePageProfile.java
- gateway-spi/src/test/java/org/apache/knox/gateway/dto/HomePageProfileTest.java
- gateway-test-release-utils/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
- knox-homepage-ui/home/app/app.module.ts
- knox-homepage-ui/home/app/generalProxyInformation/general.proxy.information.component.html
- knox-homepage-ui/home/app/generalProxyInformation/general.proxy.information.component.ts
- knox-homepage-ui/home/app/homepage.service.ts
- knox-homepage-ui/home/app/sessionInformation/session.information.component.html
- knox-homepage-ui/home/app/topologies/topology.information.component.ts
- knox-homepage-ui/home/index.html
Added the ability to declare an arbitrary number of homepage profiles in `gateway-site.xml`. The relevant configuration prefix is `knox.homepage.profile.` which should be finished with the profile name (e.g. `knox.homepage.profile.smolnar` declares the profile called `smolnar`).
The purpose of these profiles is to
- control what's going to be displayed in General Proxy Information
- optionally, filter topologies too
The following language elements should be used when declaring a profile in `gateway-site.xml`
- gpi_version - allows `Knox Version`
- gpi_cert - allows `TLS Public Certificate`
- gpi_admin_ui - allows `Admin UI URL`
- gpi_admin_api - allows `Admin API Details`
- gpi_md_api - allows `Metadata API`
- gpi_tokens - allows `Integration Tokens`
- top_$TOPOLOGY_LIST - allows to …
> KNOX-2571 - Introducing Knox Home page profiles

- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
Replace the logging of Knox token UUIDs in TokenResource with masked representations which are safe to present in logs.
mvn -Ppackage,release clean install
1. Installed the gateway and enabled DEBUG logging.
2. Deployed the KNOXTOKEN service with server-managed state enabled.
3. Deployed a topology with the JWTProvider (server-managed state enabled) and WEBHDFS.
4. Requested a token.
5. curl -ivku Token:$TOKEN "https://localhost:8443/gateway/pz-demo/webhdfs/v1/?op=LISTSTATUS"
6. curl -ivku Passcode:$PASSCODE "https://localhost:8443/gateway/pz-demo/webhdfs/v1/tmp?op=LISTSTATUS"
7. Performed the same with invalid token/passcode (to verify UnknownTokenException contents).
8. Grepped the logs for (\S){8}-(\S){4}-(\S){4}-(\S){4}-(\S){12} - confirmed no matches
9. Grepped the logs for …
> KNOX-2578 - TokenResource logging token UUIDs

- gateway-server/pom.xml
- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/factory/TokenStateServiceFactory.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/DefaultTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/JDBCTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/TokenStateDatabase.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/TokenStateServiceMessages.java
- gateway-server/src/main/java/org/apache/knox/gateway/util/JDBCUtils.java
- gateway-server/src/main/resources/createKnoxTokenDatabaseTable.sql
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/JDBCTokenStateServiceTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/util/JDBCUtilsTest.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/jdbc/derby/DerbyDatabase.java
- gateway-shell/src/test/java/org/apache/knox/gateway/shell/table/KnoxShellTableTest.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/TokenStateServiceException.java
- gateway-test-release-utils/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
- pom.xml
This change introduces a new `TokenStateService` implementation that operates using pure JDBC connections to relational databases. In the first version, only `Postgres` and `Derby` database types are supported.
Added new JUnit test classes and updated existing test cases as needed.
I also executed manual testing:
1. Used our new `tokengen` application to fetch a token
```
2021-04-19 23:24:38,972 DEBUG knox.gateway (GatewayFilter.java:doFilter(116)) - Received request: GET /knoxtoken/api/v1/token
2021-04-19 23:24:38,982 INFO  service.knoxtoken (TokenResource.java:getAuthenticationToken(419)) - Knox Token service (homepage) issued token eyJhbG...WdNDTw (8c419cf4...675b1dc14cce)
2021-04-19 23:24:39,001 DEBUG token.state (JDBCTokenStateService.java:addToken(59)) - Token …
```
> KNOX-2554 - Implemented JDBC Token State Service

- gateway-service-definitions/src/main/resources/services/livy/0.4.3/rewrite.xml
- gateway-service-definitions/src/main/resources/services/livy/0.4.3/service.xml
In the Livy UI, there are links to the Spark application and the driver log. They point to the old YARN UI.
Make the links point to the YARN UI v2.
Manually modified the rewrite.xml in a Knox gateway and tested the links.
> KNOX-2577 - In Livy UI, make application and container log links point to YARN UI v2

- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/TokenStateDatabase.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/JDBCTokenStateServiceTest.java
Instead of relying on that `KNOX_TOKENS` is being created externally, we do create that table as part of `JDBCTokenStateService` init if the table does not exist.
Updated JUnit tests (removed table creation) so that the Derby path is tested.
I ran manual testing against a PostgresSQL instance and started/stopped the server several times. Between these operations, I dropped the table + created tokens and confirmed the outcome matches my expectations.
> KNOX-2595 - KNOX_TOKENS table is created automatically if not exists

- gateway-server/src/main/java/org/apache/knox/gateway/util/JDBCUtils.java
- gateway-server/src/test/java/org/apache/knox/gateway/util/JDBCUtilsTest.java
Changed the expected `gateway.database.type` value for PostgreSQL.
Updated the relevant JUnit test and executed a manual test round locally.
> KNOX-2596 - Changed gateway-site config value to support PostgeSQL as token state backend

- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-server/src/main/java/org/apache/knox/gateway/util/JDBCUtils.java
- gateway-server/src/test/java/org/apache/knox/gateway/util/JDBCUtilsTest.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
- gateway-test-release-utils/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
Made it possible to connect to an SSL-enabled PostgreSQL server using an SSL connection. To be able to achieve our goals here I needed to introduce the following `gateway-site.xml` configuration:
- `gateway.database.ssl.enabled` - whether SSL should be enabled when connection to the configured PostgreSQL server. Defaults to `false`.
- `gateway.database.ssl.verify.server.cert` - a boolean flag that may allows SSL connections to be made without validating the server's certificate. This is more convenient for some applications but is less secure as it allows "man in the middle" attacks. Defaults to `true` (i.e. the server's certificate is validated by default)
- `gateway.database.ssl.truststore.file` - the SSL root certificate's file path (only used if …
> KNOX-2598 - Added SSL connection support for PostgreSQL database type in JDBC token state management

- gateway-applications/src/main/resources/applications/tokengen/app/index.html
- gateway-applications/src/main/resources/applications/tokengen/app/js/tokengen.js
- gateway-server/src/main/java/org/apache/knox/gateway/GatewayMessages.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/factory/TokenStateServiceFactory.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/JDBCTokenStateService.java
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
- gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
The following features are implemented by this change:
- if there is a misconfiguration in JDBCTokenState service, the AliasBasedTokenStateService is going to be used instead of failing the Knox Gateway at startup
- a new REST API is added to get the status of the token management backend
- on the `tokengen` UI there is new information displayed about token management
Updated and executed JUnit test. I also run manual testing:
1. Token management is disabled in the `homepage` topology
2. Token management is set to DB, but I misconfigured it in `gateway-site.xml` -> falling back to `AliasBasedtokenStateService`
3. Token management is set to DB, but I misconfigured it in `gateway-site.xml` -> falling back to `AliasBasedtokenStateService`. I also set …
> KNOX-2597 - Falling back to AliasBasedTokenStateService in case of DB configuration issues

- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-server/src/main/java/org/apache/knox/gateway/util/JDBCUtils.java
- gateway-server/src/test/java/org/apache/knox/gateway/util/JDBCUtilsTest.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
- gateway-test-release-utils/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
Instead of declaring connection properties one-by-one in `gateway-site.xml` a simple `connection URL` is enough to create connections to PostgreSQL DB server.
Updated and ran JUnit tests as well as executing the following manual test steps:
1. Configured the Knox Gateway as follows and started it successfully
```
<property>
<name>gateway.service.tokenstate.impl</name>
<value>org.apache.knox.gateway.services.token.impl.JDBCTokenStateService</value>
</property>
<property>
<name>gateway.database.type</name>
<value>postgresql</value>
</property>
<property>
<name>gateway.database.connection.url</name>
<value>jdbc:postgresql://smolnar-MBP15.local:5432/postgres?user=postgres&amp;ssl=true&amp;sslmode=verify-full&amp;sslrootcert=/usr/local/var/postgresql@10/data/root.crt</value>
</property>
```
2. …
> KNOX-2600 - It's now possible to setup a PostgreSQL connection using a JDBC URL

- gateway-applications/src/main/resources/applications/tokengen/app/index.html
- gateway-applications/src/main/resources/applications/tokengen/app/js/tokengen.js
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceMessages.java
- gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
- let end-users declare a more refined lifespan
- let end-users add a comment to the generated
Updated and ran JUnit tests. Additionally, I did manual testing.
1. Tested a wrong lifetime:
2. Tested custom lifespan (token generated at 30 Apr 2021 01:32:14 AM)
3. Saved comment with tricky characters:
```
postgres=# select * from knox_tokens where token_id = '0dd15ada-4986-4de8-a261-001668af93f5';
token_id               |  issue_time   |  expiration   | max_lifetime  | username |                                  comment                                  
--------------------------------------+---------------+---------------+---------------+----------+---------------------------------------------------------------------------
0dd15ada-4986-4de8-a261-001668af93f5 | 1619739244250 | 1619825644246 …
```
> KNOX-2599 - Improve tokengen UI

- gateway-service-definitions/src/main/resources/services/zeppelinui/0.8.1/service.xml
Zeppelin uses JSESSIONID to identify a session. Zeppelin UI service definition uses DefaultDispatch which prevents "SET-COOKIE" response header from being set causing Zeppelin to create multiple sessions with KnoxSSO. The change uses ConfigurableDispatch instead of DefaultDispatch.
The patch was locally tested
> KNOX-2601: ZeppelinUI creates multiple sessions when going via Knox

- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/JDBCTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/TokenStateDatabase.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/TokenStateServiceMessages.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/state/FileTokenStateJournal.java
- gateway-server/src/main/resources/createKnoxTokenMetadataDatabaseTable.sql
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/DefaultTokenStateServiceTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/JDBCTokenStateServiceTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/ZookeeperTokenStateServiceTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/state/FileTokenStateJournalTest.java
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceMessages.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/TokenMetadata.java
There is a new `KNOXTOKEN` service API to enable/disable a Knox-generated token.
Instead of adding another column in the `KNOX_TOKENS` table, a brand new DB table was introduced where an arbitrary number of token metadata can be stored (identified by the given token's ID and the metadata name).
In our alias-based token state management implementations, this is stored as a new JSON field whereas in the file journal-based implementation the new flag is added before the user name.
Updated and executed JUnit tests.
Additionally, the following manual test steps were executed:
1. Created a token using the tokengen application:
```
postgres=# select * from knox_tokens kt, knox_token_metadata ktm WHERE kt.token_id = ktm.token_id;
token_id               |  issue_time   |  expiration   | …
```
> KNOX-2602 - Added the enabled flag and related token service API into the tokens' metadata.

- gateway-provider-security-hadoopauth/src/test/java/org/apache/knox/gateway/hadoopauth/filter/HadoopAuthFilterTest.java
- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/AbstractJWTFilter.java
- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/JWTFederationFilter.java
- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/SignatureVerificationCache.java
- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/AbstractJWTFilterTest.java
- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/TokenIDAsHTTPBasicCredsFederationFilterTest.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/AliasBasedTokenStateService.java
In order to avoid expensive MAC calculation at request verification time, previous successful passcode token verifications are cached and checked when validating a passcode token.
Updated existing JUnit tests: I made sure common `testVerificationOptimization` is invoked in `TokenIDAsHTTPBasicCredsFederationFilterTest` (where we test passcode tokens)
> KNOX-2603 - Caching passcode token verifications

- gateway-applications/src/main/resources/applications/tokengen/app/js/tokengen.js
Added more refined validation on each token lifespan field to make sure we do not allow:
- negative values
- floating numbers
- out-of-range values:
- days: 0- 3650
- hours: 0 - 23
- mins: 0- 59
- empty input
Manually tested with different combinations of the lifespan input fields.
> KNOX-2605 - Better validation of the supplied token lifespan fields

- gateway-applications/src/main/resources/applications/tokengen/app/index.html
- gateway-applications/src/main/resources/applications/tokengen/app/js/tokengen.js
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
In order to avoid misunderstandings and customer escalations, the token generation UI now indicates what is the configured maximum lifetime (`knox.token.ttl` in the relevant topology). In case end-users wants to generate a token that exceeds the configured maximum, a confirmation window is shown where we explain the side effects.
Please note that if `knox.token.ttl` is set to `-1` the topology owner explicitly configured `unlimited lifetime`, so we do not need to check the supplied lifespan.
Manually tested.
> KNOX-2606 - Indicate configured token TTL on UI and ask for confirmation when end-users try to generate a token above the configured limit

- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/impl/JWTToken.java
- gateway-spi/src/test/java/org/apache/knox/gateway/services/security/token/impl/JWTTokenTest.java
Adding 'kid' and 'jku' claims as part of JOSE Headers for tokens issued by Knox
This patch was tested locally. Added unit tests.
> KNOX-2608 - JWT tokens issues by Knox should have 'kid' and 'jku' as part of JOSE Headers

- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/JDBCTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/TokenStateDatabase.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/TokenStateServiceMessages.java
Instead of logging the number of expired tokens removed from the DB at `DEBUG` level, Knox logs the 
Tested manually:
```
2021-06-08 12:45:54,837 INFO  service.knoxtoken (TokenResource.java:getAuthenticationToken(570)) - Knox Token service (homepage) issued token eyJqa3...sHsZgg (ab56217a...aa2afedee2bc)
2021-06-08 12:45:56,445 INFO  service.knoxtoken (TokenResource.java:getAuthenticationToken(570)) - Knox Token service (homepage) issued token eyJqa3...qC7Kag (99212174...e50a90ccffa5)
2021-06-08 12:45:57,793 INFO  service.knoxtoken (TokenResource.java:getAuthenticationToken(570)) - Knox Token service (homepage) issued token eyJqa3...WG117A (9bf33980...be4eb1ac08dc)
2021-06-08 12:45:58,925 INFO  service.knoxtoken (TokenResource.java:getAuthenticationToken(570)) - Knox Token service …
```
> KNOX-2618 - INFO level logging added about removing expired tokens from the DB

- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/JWKSResource.java
- gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/JWKSResourceTest.java
Populating and returning the appropriate signature algorithm in the response of Knox's JWKS endpoint.
Updated and ran `org.apache.knox.gateway.service.knoxtoken.JWKSResourceTest` successfully.
In addition to uni testing I re-deployed Knox locally and invoked the updated JWKS endpoint:
```
curl -iku admin:admin-password https://localhost:8443/gateway/homepage/knoxtoken/api/v1/jwks.json
Date: Wed, 09 Jun 2021 21:29:26 GMT
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1;mode=block
Content-Type: application/json
Content-Length: 462
{
"keys": [{
"kty": "RSA",
"e": "AQAB",
"use": "sig",
"kid": "1jmRkVmXLeT-XYd5D8SVccjvNRaqiHypUhZCsIgOoSU",
"alg": "RS256",
"n": "mQ57g6fP3KeCAnGR9CuWzh4qBbNQZeCPU6mb47mxu3SF-KPuHSwvJwhnxlBPpzIC-IbpZjg5EnOfXC9sEZMB2VxFeUAkHOqq8K0nMFDaTXLekaoCDAMYwQXh …
```
> KNOX-2620 - Using the proper signature algorithm name in JWKS endpoint

- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/AbstractJWTFilter.java
In some cases, it's better to return `401/UNAUTHORIZED` than `400/BAD_REQUEST`.
Ran JUnit tests and executed manual testing locally.
> KNOX-2621 - Consolidated some HTTP error codes upon JWT/Passcode validation

- gateway-provider-rewrite/src/main/java/org/apache/knox/gateway/filter/rewrite/impl/UrlRewriteResponse.java
- gateway-provider-rewrite/src/test/java/org/apache/knox/gateway/filter/rewrite/impl/UrlRewriteResponseTest.java
Currently, Knox only supports the Content-Encoding "gzip" and the Content-Encoding "deflate" is not supported. When the upstream server (such as Livy 0.7 Server) returns a response which is deflated, Knox does not know how to decode it.
The current code only considers the "gzip" format and the "deflate" format is not considered. We should also handle the case when the format is "deflate" and use InflaterInputStream to read the in-bound response and use DeflaterOutputStream to write the out-bound response.
Here is the JIRA (https://issues.apache.org/jira/browse/KNOX-2622) that describes this issue.
Existing unit tests and newly added unit tests.
Please review [Knox Contributing Process](https://cwiki.apache.org/confluence/display/KNOX/Contribution+Process#ContributionProcess-GithubWorkflow) …
> [KNOX-2622] Support Deflate Encoding for the Inbound Response

- gateway-applications/src/main/resources/applications/tokengen/app/index.html
- gateway-applications/src/main/resources/applications/tokengen/app/js/tokengen.js
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
- gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
By default, lifespan attributes (day, hour, and minute spinners) are displayed on the token generation UI. However, end-users have a way to hide these input fields by setting a newly introduced topology-level configuration, called `knox.token.lifespan.input.enabled`, to `false`.
In this case, the generated token will have the configured/default token TTL.
I also made the default value of the lifespan attributes to 1 hour.
Updated the JUnit tests and executed several manual testing locally (with and w/o the lifespan properties).
> KNOX-2623 - Lifespan attributes are optional on token generation UI and default to 1 hour

- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/AliasBasedTokenStateService.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/AliasBasedTokenStateServiceTest.java
Added the missing alias names while removing a token from the keystore (and from memory).
Repeated the same steps as described in the JIRA and confirmed that all token aliases were removed from the credential store.
> KNOX-2628 - Metadata and issue time aliases are removed too during token revocation

- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceMessages.java
- gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
- gateway-test-release-utils/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
- gateway-util-common/src/main/java/org/apache/knox/gateway/util/JsonUtils.java
From now on, users are limited to manage only up to a pre-configured number of tokens (defaults to `10`). It's possible to eliminate this limit by setting the new `gateway.knox.token.limit.per.user` to `-1`. In this case, end-users are allowed to manage as many tokens as they want.
This configuration only applies when server-managed token state is enabled either in gateway-site or at the topology level.
Added new JUnit tests and executed manual test steps using the token generation UI.
> KNOX-2627 - Limiting the number of managed tokens per user

- gateway-release/home/conf/topologies/homepage.xml
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
- gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
Updated the logic which parses configured `knox.token.client.data` to honour values with multiple `=` characters.
Updated an existing JUnit test case to check `knox.token.client.data` too.
Modified our `homepage` topology to contain the appropriate profile name and the `sandbox` topology, then redeployed Knox. I confirmed the `Homepage` link on the token generation UI pointed to the configured URL and it actually opened the homepage with the proper filters in place.
> KNOX-2633 - Handling supplied client data with multiple '=' signs when generating a token

- gateway-server/pom.xml
- gateway-server/src/main/java/org/apache/knox/gateway/util/JDBCUtils.java
- gateway-server/src/test/java/org/apache/knox/gateway/util/JDBCUtilsTest.java
- pom.xml
Until now, JDBCTokenStateService only supported Postgres and Derby databases. This patch adds MySql support. There are two ways to define a MySql data source, either via a full connection string or by individual properties.
Tested with a local MySql with and without SSL. I used the following images:
```
$ docker pull mysql/mysql-server:latest
$ docker pull cyprien/mysql-tls:5.7
```
1.
In gateway-site, I set `gateway.database.type=mysql` plus added the connection properties/connection url. 
I created a token at `https://localhost:8443/gateway/homepage/tokengen/index.html` and inspected the KNOX_TOKENS and KNOX_TOKEN_METADATA tables in the database.
2.
For the SSL test I used the following MySql config:
```
[client]
protocol=tcp
port=3306
[mysqld]
bind-address=0.0.0.0
port=3306 …
```
> KNOX-2626. Support MySQL in JDBCTokenStateService

- gateway-server/src/test/java/org/apache/knox/gateway/websockets/BadBackendTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/websockets/BadUrlTest.java
BadUrlTest and BadBackendTest are failing time to time locally, increasing the timeout from 1 second to 5 seems to solve the problem
Running `mvn test -Dtest=BadBackendTest,BadUrlTest` multiple times.
> KNOX-2630. BadUrlTest and BadBackendTest are flaky (amagyar)

- gateway-provider-ha/pom.xml
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/dispatch/ConfigurableHADispatch.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/dispatch/i18n/HaDispatchMessages.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/HaServiceConfig.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/impl/DefaultHaServiceConfig.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/impl/HaDescriptorFactory.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/impl/HaServiceConfigConstants.java
- gateway-provider-ha/src/test/java/org/apache/knox/gateway/ha/dispatch/DefaultHaDispatchTest.java
Add a way to turn off HA loadbalancing based on user agent.
This is done because some non-browser clients such as ODBC drivers do not honor multiple SET-COOKIE headers in response body. This config is to work around that issue. 
This PR proposed a configuration in HA Provider called `disableLoadBalancingForUserAgents` which takes a comma separated list of user agents that should disable the HA loadbalancing ifeature.
Following is an example config 
```
<provider>
<role>ha</role>
<name>HaProvider</name>
<param>
<name>HIVE</name>     <value>enableStickySession=true;enableLoadBalancing=true;enabled=true;maxFailoverAttempts=42;failoverSleep=50;maxRetryAttempts=1;disableLoadBalancingForUserAgents=Test User Agent, Test User Agent2,Test User Agent3 ,Test User Agent4 …
```
> KNOX-2634 - Disable HA loadbalancing for ODBC driver and make this setting configurable.

- gateway-test/src/test/java/org/apache/knox/gateway/GatewayAppFuncTest.java
Typical failure look like:
```
[ERROR]   GatewayAppFuncTest.testMultiApps:338 1 expectation failed.
Expected status code <200> but was <404>. 
```
It happens in test which are running right after testDeploymentCleanup or testDefaultTopology. These tests restart the gateway service during the test run.
The subsequent test overwrite the topology file which are used by all tests but file access date granularity is 1 second (msec part is always 000, this is likley FS specific) therefore the topology is never redeployed.
Adding clean up logic in between these restarts seem to solve the issue.
```bash
mvn test -Dtest=GatewayAppFuncTest   
while [ $? -eq 0 ]; do
mvn test -Dtest=GatewayAppFuncTest   
done
```
> KNOX-2635 - GatewayAppFuncTest is flaky

- gateway-provider-security-pac4j/src/main/java/org/apache/knox/gateway/pac4j/filter/Pac4jDispatcherFilter.java
- gateway-provider-security-pac4j/src/test/java/org/apache/knox/gateway/pac4j/Pac4jProviderTest.java
The patch makes possible to use an alias in pac4j provider config so that `oidc.secret` is no longer need to be hardcoded in the topology as plain text.
Added an alias for oidc.secret in knoxsso.xml.
```
<param>
<name>oidc.secret</name>                  
<value>${ALIAS=myOidcSecret}</value>
</param>
```
Created the alias with knoxcli.
```bash
$ bin/knoxcli.sh create-alias myOidcSecret --value <my-secret> --cluster knoxsso
````
Tested authentication with auth0.com.
> KNOX-2534. Allow alias to be used in pac4j topology block

- gateway-provider-security-shiro/src/main/java/org/apache/knox/gateway/deploy/impl/ShiroConfig.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/topology/impl/DefaultTopologyService.java
STR:
1. Have an existing topology (test.xml), see if blockSemicolon/blockBackslash/blockNonAscii are in the get topology output:
```bash
$ curl -u admin:admin-password -k -X GET https://localhost:8443/gateway/admin/api/v1/topologies/test | grep blockSemicolon
<name>main.invalidRequest.blockSemicolon</name>
```
2. Deploy a new topology file (test2.xml)
```bash
cp ./conf/topologies/test.xml ./conf/topologies/test2.xml 
```
3. blockSemicolon/blockBackslash/blockNonAscii are no longer in the orignial test.xml output:
```bash
$ curl -u admin:admin-password  -k -X GET https://localhost:8443/gateway/admin/api/v1/topologies/test | grep  blockSemicolon 
```
The reason why these shiro properties are missing is because we only add these after a topology deployment to the in memory representation of …
> KNOX-2638 - Shiro propererties are missing after topology deployment

- .github/workflows/main.yml
- .travis.yml
Trying to get rid of build instability errors like this:
```
Error:  Failed to execute goal on project gateway-test-release: Could not resolve dependencies for project org.apache.knox:gateway-test-release:pom:1.6.0-SNAPSHOT: Failed to collect dependencies at org.eclipse.jetty:jetty-util-ajax:jar:9.4.34.v20201102: Failed to read artifact descriptor for org.eclipse.jetty:jetty-util-ajax:jar:9.4.34.v20201102: 
Could not transfer artifact org.eclipse.jetty:jetty-util-ajax:pom:9.4.34.v20201102 from/to central (https://repo.maven.apache.org/maven2): transfer failed for https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-util-ajax/9.4.34.v20201102/jetty-util-ajax-9.4.34.v20201102.pom: 
Connection timed out (Read failed) -> [Help 1]
```
There is a `maven.wagon.http.retryHandler.count` …
> KNOX-2639. Build instability because of maven artifact download failure

- gateway-discovery-ambari/src/main/java/org/apache/knox/gateway/topology/discovery/ambari/AmbariServiceDiscoveryMessages.java
- gateway-provider-security-shiro/src/main/java/org/apache/knox/gateway/shirorealm/impl/i18n/KnoxShiroMessages.java
- gateway-server/src/main/java/org/apache/knox/gateway/GatewayMessages.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/TokenStateServiceMessages.java
- gateway-service-metadata/src/main/java/org/apache/knox/gateway/service/metadata/MetadataServiceMessages.java
- gateway-topology-hadoop-xml/src/main/java/org/apache/knox/gateway/topology/discovery/advanced/AdvanceServiceDiscoveryConfigurationMessages.java
MessageFormat is zero based but there are multiple places where we use 1 based indexing, therefore the arguments are not visible in the log.
Such as: 
```
@Message( level = MessageLevel.DEBUG, text = "Failed to Authenticate with LDAP server: {1}" )
```
Manually:
Before the fix:
```
logs/gateway.log:2021-08-16 12:53:44,692 DEBUG knox.gateway (KnoxLdapRealm.java:doGetAuthenticationInfo(204)) - Failed to Authenticate with LDAP server: {1}
```
After the fix:
```
logs/gateway.log:2021-08-16 12:55:44,074 DEBUG knox.gateway (KnoxLdapRealm.java:doGetAuthenticationInfo(204)) - Failed to Authenticate with LDAP server: org.apache.shiro.authc.AuthenticationException: LDAP authentication failed.
```
> KNOX-2642. Incorrect message format indexes

- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
- gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
TokeResource currently responds to failed requests to renew or revoke a token with an error message. Any client behavior based on the nature of the failure must currently depend on the error message content, which is not robust.
This patch extends the response with an error code, which is backward compatible with the existing responses.
Created a token with API call:
```
$ curl -v -k -u admin:admin-password  https://localhost:8443/gateway/homepage/knoxtoken/api/v1/token
```
Tried renew/revoke/enable/disable endpoints:
```
$ curl -X PUT -d "<tokenId>" -vvv -k -u admin:admin-password https://localhost:8443/knoxtoken/api/v1/token/enable
{
"setEnabledFlag": "false",
"error": "Token is already enabled",
"code": 70
}
```
```
$ curl -X PUT -d "<tokenId>" -vvv -k -u admin:admin-password …
```
> KNOX-2396 - TokenResource Renew and Revoke Should Respond With Error Codes That Identify Specific Errors

- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
- gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
We have an equality check when checking the max number of tokens per user. But if the user already have N number of tokens, and later the admin changes the gateway.knox.token.limit.per.user to a smaller number then this check will never trigger.
1. Having no limit and generating N tokens
2. Changing gateway.knox.token.limit.per.user to a lower number than N and restarting the service
3. Trying to generate one more token and getting a limit exception
> KNOX-2646. The tokenLimitPerUser check doesn't always work.

- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/JDBCTokenStateService.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/JDBCTokenStateServiceTest.java
As described in the JIRA; in-memory lookup is skipped in JDBC token state service while fetching token expiration or metadata. Instead, we go directly to the DB in this implementation.
Since those queries are simple (there is no table join involved) and they rely on indexed columns the is no significant performance issue.
Updated JUnit test cases and repeated the same steps as described in the JIRA. With my fix, the disabled authentication request fails on node 2 like this:
```
$ curl -ku Passcode:WXpVNVlUZGlNRGt0WWpFMk5TMDBZamxsTFRobVpEY3ROV0psWW1WbE1EVTRZakF4OjpOVFptWW1VNVlXVXROelppTVMwME5URmhMVGcxWXpRdFl6Z3hNVEUwTmpkak5XUTA= https://localhost:8444/gateway/tokenbased/webhdfs/v1?op=LISTSTATUS
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error …
```
> KNOX-2658 - Skipping in-memory lookup while fetching expiration/metadata for a token

- gateway-applications/src/main/resources/applications/tokengen/app/index.html
- gateway-applications/src/main/resources/applications/tokengen/app/js/tokengen.js
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/KnoxToken.java
- knox-token-management-ui/token-management/app/token.management.component.html
- knox-token-management-ui/token-management/app/token.management.component.ts
- error box is decorated and hidden when not required
- result box is displayed upon successful token generation
- date/time information on token management and token generation page uses the same format and time zone
Implemented the changes listed in KNOX-2657
Manual testing (UI changes, we have no automated UI tests yet).
> KNOX-2657 - Token generation page improvements:

- .travis.yml
Travis builds are failing with:
```
Status: Downloaded newer image for maven:3-jdk-8
travis_time:end:1f172450:start=1631006005539129433,finish=1631006018654506434,duration=13115377001,event=before_install
[0Ktravis_fold:end:before_install.2
[0Ktravis_time:start:06b9262b
[0K$ $DOCKERRUN $IMAGE mvn -T.75C clean verify -U -Dshellcheck=true -Dsurefire.useFile=false -Djavax.net.ssl.trustStorePassword=changeit -Dmaven.wagon.http.retryHandler.count=5 -Dmaven.wagon.http.retryHandler.class=default -Dmaven.wagon.http.retryHandler.nonRetryableClasses=java.io.InterruptedIOException -Dhttp.keepAlive=false -B -V
ls: cannot access '/usr/bin/mvn': Operation not permitted
Error: Could not find or load main class org.codehaus.plexus.classworlds.launcher.Launcher
```
Let's try this and see what happens.
> KNOX-2659 - Travis build failure: '/usr/bin/mvn': Operation not permitted.

- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/JDBCTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/TokenStateDatabase.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/JDBCTokenStateServiceTest.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/KnoxToken.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/TokenMetadata.java
Having lots of tokens causes slowness when loading the token management page. The reason is that the token metadata is loaded in a separate query and for each token we open a new connection when running the query.
This patch merges the 2 queries into one.
1. Creating few hundred tokens
2. Loading the token management page
> KNOX-2650 - Loading token management page can be slow if there are lots of tokens

- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/JWTMessages.java
- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/JWTFederationFilter.java
- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/JWTFederationFilterTest.java
There can be a NPE when there is a space between the username and password.
```
$ curl -vvv -iku Token: xxxx https://localhost:8443/gateway/sandbox/webhdfs/v1/?op=LISTSTATUS
```
> KNOX-2651 - NPE when token value is missing

- gateway-spi/src/main/java/org/apache/knox/gateway/dto/HomePageProfile.java
- gateway-spi/src/test/java/org/apache/knox/gateway/dto/HomePageProfileTest.java
The `General Proxy Information` section is extended with Knox's TLS public certs when the `token` profile is used.
Added relevant JUnit tests and did a manual test round too:
> KNOX-2662 - Added TLS certs into General Proxy Information for the token profile

- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
- knox-token-management-ui/token-management/app/token.management.service.ts
There were some public API endpoints in `TokenResource` with wrong HTTP methods. I changed hem and now the resource looks like this:
- GET - `/knoxtoken/api/v1/token`
- GET - `/knoxtoken/api/v1/token/getUserTokens`
- GET - `/knoxtoken/api/v1/token/getTssStatus`
- POST - `/knoxtoken/api/v1/token`
- PUT - `/knoxtoken/api/v1/token/renew`
- PUT - `/knoxtoken/api/v1/token/enable`
- PUT - `/knoxtoken/api/v1/token/disable`
- DELETE - `/knoxtoken/api/v1/token/revoke`
Ran manual test steps (including token management UI operations and `curl` requests)
> KNOX-2661 - Consolidated HTTP methods in TokenResource

- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
- gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
Users can revoke tokens created for them even they are not listed in `knox.token.renewer.whitelist`
Added a new JUnit test case and ran manual test steps:
1. installed the new version of Knox
2. logged into the Knox Home page as `guest` (this user is not added into `knox.token.renewer.whitelist` in to `homepage` topology)
3. generated a token on the token generation page
4. revoked the previously generated token on the token management page successfully
> KNOX-2664 - Let end-users revoke their own tokens

- gateway-applications/src/main/resources/applications/knoxauth/app/redirecting.jsp
There is a parse error in redirect.jsp 
```
:8443/gateway/knoxss…/home/?refresh=1:49 Uncaught SyntaxError: Unexpected token ':'
```
This happens because the quotes are missing around the original url:
```js
var originalUrl = <%= originalUrl %>;
```
So expression like this is generated into the html:
```js
var originalUrl = https://localhost:8443/gateway/homepage/home/?refresh=1;
```
Manually triggered the redirect with logging into knox.
> KNOX-2665 Knox redirecting.jsp parsing error

- gateway-provider-rewrite/src/main/java/org/apache/knox/gateway/filter/rewrite/impl/FrontendFunctionProcessor.java
- gateway-server/src/main/java/org/apache/knox/gateway/GatewayServer.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/GatewayServices.java
This PR exposes a variable `{$frontend[gateway.name]}` for gateway name.
Tested on a local cluster.
> KNOX-2666 - Add support for gateway name in rewrite rules

- gateway-service-definitions/src/main/resources/services/rangerui/1.0.0/rewrite.xml
What changes were proposed in this pull request?
Fixed an issue where the rewrite rule is not referenced in the filter
How was this patch tested?
This patch was tested by deploying updated servicedef in knox and test against Ranger changes on CDP cluster.
Manually tested the logout and timeout flow in Ranger redirecting to knox logout.jsp page.
> KNOX-2667: Fixed an issue where the rewrite rule is not referenced in the filter

- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/AliasBasedTokenStateService.java
See the root cause analysis in https://issues.apache.org/jira/browse/KNOX-2670.
Additional note: the newly implemented `triesToRevokeOwnToken(String, String)` method solves the original issue 1 layer above, but the problem with the `AliasBasedTokenStateService` would still exist w/o removing the `removeToken(String)` method.
I ran Junit tests and I executed the steps I used for reproducing the original issue (I temporary removed the `triesToRevokeOwnToken(String, String)` call to make sure my change actually solves the issue).
> KNOX-2670 - Deleting unnecessary removeToken override from AliasBasedTokenStateService

- gateway-applications/src/main/resources/applications/knoxauth/app/logout.jsp
- gateway-applications/src/main/resources/applications/knoxauth/service.xml
For global logout, the requests goes to the knoxauth app which is configured to use identity-assertion provider which can throw "Subject not found" exception in case of Pac4J authentication provider. This PR also fixes an issue where delete cookie method now uses samesite property.
Patch was tested on a local cluster.
> KNOX-2671 - From knox homepage clicking logout returns 500 error code

- gateway-provider-security-hadoopauth/src/main/java/org/apache/knox/gateway/hadoopauth/HadoopAuthMessages.java
- gateway-provider-security-hadoopauth/src/main/java/org/apache/knox/gateway/hadoopauth/filter/HadoopAuthFilter.java
- gateway-provider-security-hadoopauth/src/test/java/org/apache/knox/gateway/hadoopauth/filter/HadoopAuthFilterTest.java
The `HadoopAuthFilter` is now able to lookup aliases in the `__gateway` credential store too.
Added a new unit test and ran them all.
Additionally, I executed manual testing:
1. saved an alias on the gateway level called `kerberos.keytab` pointing to a non-existing keytab path
```
$ bin/knoxcli.sh create-alias kerberos.keytab --value /tmp/knox.keytab
kerberos.keytab has been successfully created .
$ bin/knoxcli.sh list-alias
Listing aliases for: __gateway
kerberos.keytab
knox.token.hash.key
2 items.
```
2. created a new provider/descriptor pair:
```
$ cat conf/shared-providers/kerberos-providers.json 
{
"providers": [
{
"role": "authentication",
"name": "HadoopAuth",
"enabled": "true",
"params": {
"config.prefix": "hadoop.auth.config",
"hadoop.auth.config.type": "kerberos", …
```
> KNOX-2672 - Handle aliases in HadoopAuth filter on gateway level too

- gateway-service-definitions/src/main/resources/services/oozie/5.0.0/rewrite.xml
Added a new  rewrite rule which replaces the internal Yarn url to a one using Knox gateway
I had an environment with Knox and Oozie. I edited the /var/lib/knox/gateway/data/services/oozie/5.0.0/rewrite.xml by adding the changes described in this commit. Then I added a new line to /var/lib/knox/gateway/conf/topologies/some-topology.xml to force Knox to redeploy the affected topology. Then I navigated to https://knox-gateway-host:8443/gateway/some-topology/oozie/, logged in, went to  "All Jobs", selected one, selected the action and on the "Action info" tab I saw that Console URL is a Knox url.
> KNOX-2675 Oozie Console URL on the web UI should be a Knox URL

- gateway-service-metadata/src/main/java/org/apache/knox/gateway/service/metadata/GeneralProxyInformation.java
- gateway-service-metadata/src/main/java/org/apache/knox/gateway/service/metadata/KnoxMetadataResource.java
- gateway-service-metadata/src/main/java/org/apache/knox/gateway/service/metadata/MetadataServiceMessages.java
- knox-homepage-ui/home/app/generalProxyInformation/general.proxy.information.component.html
- knox-homepage-ui/home/app/generalProxyInformation/general.proxy.information.component.ts
- knox-homepage-ui/home/app/generalProxyInformation/general.proxy.information.ts
The Token Integration link on the Home page must be hidden if the required `knox.token.hash.key` Gateway-level alias is missing.
Manual testing.
Without the alias:
With the alias (running `bin/knoxcli.sh generate-jwk --saveAlias knox.token.hash.key`):
> KNOX-2685 - Show/hide (enable/disable) Knox token management links on Home Page if required alias is created

- gateway-applications/src/main/resources/applications/knoxauth/app/redirecting.jsp
- gateway-util-common/src/main/java/org/apache/knox/gateway/util/Urls.java
- gateway-util-common/src/test/java/org/apache/knox/gateway/util/UrlsTest.java
Invalidate any originalUrl being used in the flow for KnoxSSO that contains user information (username and password).
There is no reason for an SSO flow to result in username and password being sent by the browser as part of the URL and would represent poor credential hygiene.
This change explicitly checks the incoming originalUrl for the existence of userInfo and if the url contains it the flow is disrupted as possible phishing attack.
Existing unit tests and new unit tests added for Urls.containsUserInfo method.
Manually tested a url with userinfo and observed expected behavior.
Manually tested a valid url and observed normal KnoxSSO flow success.
> KNOX-2655 - Disallow Userinfo in KnoxSSO originalURL Query Param

- gateway-provider-security-pac4j/src/main/java/org/apache/knox/gateway/pac4j/filter/Pac4jDispatcherFilter.java
- gateway-provider-security-pac4j/src/main/java/org/apache/knox/gateway/pac4j/session/KnoxSessionStore.java
- gateway-provider-security-pac4j/src/test/java/org/apache/knox/gateway/pac4j/session/KnoxSessionStoreTest.java
There are cases where IdP sends back custom attributes that might be too big. For instance groups name attribute could be `https://knox.apache.org/SAML/Attributes/groups` which might contain large number of groups that might prevent setting cookies properly. This patch adds the ability to remove custom attributes from pac4j profile cookie.
`pac4j.session.store.exclude.custom.attributes` is the configuration setting and it takes a comma separated list of values. Default is blank string.
> KNOX-2679 - Add ability to remove custom attributes from Pac4j cookie

- pom.xml
New json-smart version.
```bash
$ mvn dependency:tree | grep json-smart | grep -v 2\.4\.1
```
> KNOX-2691 - Upgrade json-smart to 2.4.1 due to CVE

- gateway-server/src/main/java/org/apache/knox/gateway/GatewayServer.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/topology/impl/DefaultTopologyService.java
- gateway-server/src/main/java/org/apache/knox/gateway/topology/builder/BeanPropertyTopologyBuilder.java
- gateway-server/src/main/java/org/apache/knox/gateway/topology/xml/KnoxFormatXmlTopologyRules.java
- gateway-server/src/main/java/org/apache/knox/gateway/util/KnoxCLI.java
- gateway-server/src/main/resources/conf/topology-v1.xsd
- gateway-server/src/test/java/org/apache/knox/gateway/services/topology/DefaultTopologyServiceTest.java
- gateway-service-admin/src/main/java/org/apache/knox/gateway/service/admin/beans/BeanConverter.java
- gateway-service-admin/src/main/java/org/apache/knox/gateway/service/admin/beans/Topology.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/topology/TopologyService.java
- gateway-spi/src/main/java/org/apache/knox/gateway/topology/Topology.java
- gateway-test-utils/src/main/java/org/apache/knox/test/TestUtils.java
- gateway-test/src/test/java/org/apache/knox/gateway/GatewayAppFuncTest.java
- gateway-test/src/test/java/org/apache/knox/gateway/GatewayDeployFuncTest.java
- gateway-test/src/test/java/org/apache/knox/gateway/GatewayLdapDynamicGroupFuncTest.java
- gateway-test/src/test/java/org/apache/knox/gateway/GatewayLdapGroupFuncTest.java
- gateway-test/src/test/java/org/apache/knox/gateway/GatewayLdapPosixGroupFuncTest.java
- gateway-test/src/test/java/org/apache/knox/gateway/Knox242FuncTest.java
- gateway-test/src/test/resources/org/apache/knox/gateway/GatewayAppFuncTest/test-dynamic-app-topology.xml
From now on, a topology is redeployed only, and only if, there is a change within the topology itself. Not directly in the topology file, because Knox does not count adding/removing comments in the topology as an update. The change has to be a meaningful change such as a change in any of the services, providers, applications, or topology-level attributes.
With this change in place, the possibility to redeploy a topology, by simply touching it, is removed. Instead, clients should use KnoxCLI like this:
```
knoxcli.sh redeploy --cluster topologyName
E.g. knoxcli.sh redeploy --cluster sandbox
```
Updated and executed JUnit tests:
```
$ mvn clean -Dshellcheck=true verify -Prelease,package
... …
```
> KNOX-2689 - Redeploying a topology only if it was actually changed

- gateway-util-common/src/test/java/org/apache/knox/gateway/audit/StoreAndForwardAppenderTest.java
- gateway-util-common/src/test/resources/log4j2-test.xml
The NPE likely happens because of parallel test execution. If the target/audit file is written at the same time it might become corrupt.
```[INFO] Running org.apache.knox.gateway.audit.JdbmQueueTest
58592021-11-30 07:48:55,775 main ERROR Unable to invoke factory method in class org.apache.knox.gateway.audit.log4j.appender.JdbmStoreAndForwardAppender for element JdbmStoreAndForwardAppender: java.lang.NullPointerException java.lang.reflect.InvocationTargetException
5860	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
5861	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
5862	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
5863	at java.lang.reflect.Method.invoke(Method.java:498)
5864	at …
```
> KNOX-2694 - StoreAndForwardAppenderTest.testAppender is intermittenty failing with NPE

- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/topology/impl/DefaultTopologyService.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/topology/DefaultTopologyServiceTest.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
- gateway-test-release-utils/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
To support backward compatibility, a new Gateway-level configuration is introduced to allow end-users to configure if they require changes in topologies for redeployment or a simple `touch` is enough (relying on the topology file's timestamp).
Updated and executed JUnit tests. In addition to unit testing, I ran the following manual test steps:
- redeployed Knox w/ my changes
- confirmed that `touch conf/topologies/sandbox.xml` re-deployed the `sandbox` topology
- edit `gateway-site.xml` (set `gateway.topology.redeploy.requires.changes=true`) and re-started Knox
- confirmed that
- `touch conf/topologies/sandbox.xml` did not re-deploy the `sandbox` topology
- `bin/knoxcli.sh redeploy --cluster sandbox` re-deployed the `sandbox` topology
> KNOX-2692 - Topology redeployment can be configured to require changes in topologies

- pom.xml
Upgrade netty version.
```
$ mvn dependency:tree | grep netty
```
> KNOX-2695 - Upgrade netty to 4.1.68+ due to CVE

- gateway-discovery-ambari/src/main/java/org/apache/knox/gateway/topology/discovery/ambari/AmbariServiceDiscovery.java
- gateway-discovery-ambari/src/test/java/org/apache/knox/gateway/topology/discovery/ambari/AmbariServiceDiscoveryTest.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscovery.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryTest.java
- gateway-server/src/main/java/org/apache/knox/gateway/GatewayMessages.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/topology/monitor/DescriptorsMonitor.java
- gateway-server/src/test/java/org/apache/knox/gateway/topology/discovery/test/extension/DummyServiceDiscovery.java
- gateway-server/src/test/java/org/apache/knox/gateway/topology/discovery/test/extension/PropertiesFileServiceDiscovery.java
- gateway-server/src/test/java/org/apache/knox/gateway/topology/discovery/test/extension/SneakyServiceDiscoveryImpl.java
- gateway-server/src/test/java/org/apache/knox/gateway/topology/simple/SimpleDescriptorHandlerTest.java
- gateway-spi/src/main/java/org/apache/knox/gateway/topology/discovery/ServiceDiscovery.java
- gateway-test/src/test/java/org/apache/knox/gateway/SimpleDescriptorHandlerFuncTest.java
- gateway-topology-simple/src/main/java/org/apache/knox/gateway/topology/simple/DiscoveryException.java
- gateway-topology-simple/src/main/java/org/apache/knox/gateway/topology/simple/SimpleDescriptorHandler.java
- gateway-topology-simple/src/main/java/org/apache/knox/gateway/topology/simple/SimpleDescriptorMessages.java
When CM is intermittently unavailable, Knox still regenerates topologies with an empty service list. It should skip topology regeneration and log the error instead.
This patch fixes it by throwing an exception and avoiding the topology regeneration in case of a discovery failure.
The patch also removes some unused code around discovery.
Changed `discovery-address` in `/var/lib/knox/gateway/conf/descriptors/cdp-proxy.json` to an invalid address.
Checked the logs for the error message:
```
2021-11-12 11:14:41,394 INFO  discovery.cm (ClouderaManagerServiceDiscovery.java:discoverCluster(215)) - Performing cluster discovery for "Cluster 1"
2021-11-12 11:14:41,396 ERROR discovery.cm (ClouderaManagerServiceDiscovery.java:getClusterServices(276)) - Failed to access the service configurations for …
```
> KNOX-2690 - Service URLs are missing from Knox UI after a temporary discovery failure

- knox-token-management-ui/token-management/app/token.management.component.html
- knox-token-management-ui/token-management/app/token.management.component.ts
Expired tokens cannot be enabled/disabled on the token management page going forward.
In addition to this, I improved visualization too: token expiration data is shown in `red` for expired tokens and in `green` for the valid ones.
Manually tested as described in the JIRA:
> KNOX-2699 - Hide Enable/Disable button for expired tokens

- pom.xml
New JSON smart version
```
$ mvn dependency:tree | grep json-smart
```
> KNOX-2698 - Upgrade json-smart to 2.4.7 due to CVE

- gateway-server/src/main/java/org/apache/knox/gateway/services/topology/impl/DefaultTopologyService.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/topology/DefaultTopologyServiceTest.java
If there are subsequent changes to a topology and Knox still processes the one that came earlier it might happen that the second change is disregarded due to timing issues.
The solution is to make sure Knox always triggers an `UPDATE` event regardless of
- the topology file's timestamp
- or the `is change required` condition.
Updated and ran unit tests as well as conducted manual testing.
> KNOX-2693 - Redeploying a topology if it was changed regardless of its timestamp

- gateway-provider-security-hadoopauth/src/test/java/org/apache/knox/gateway/hadoopauth/filter/HadoopAuthFilterTest.java
- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/AbstractJWTFilter.java
- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/JWTFederationFilter.java
- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/AbstractJWTFilterTest.java
- gateway-release/home/conf/topologies/homepage.xml
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/DefaultTokenAuthorityService.java
- gateway-service-knoxsso/src/test/java/org/apache/knox/gateway/service/knoxsso/WebSSOResourceTest.java
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
- gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/JWTokenAttributes.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/JWTokenAttributesBuilder.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/JWTokenAuthority.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/impl/JWT.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/impl/JWTToken.java
- gateway-spi/src/test/java/org/apache/knox/gateway/services/security/token/impl/JWTTokenTest.java
Knox supports two new topology-level properties from now on:
- `knox.token.type` - this can be set as a `KNOXTOKEN` service parameter. If this is configured the generated JWT header will have this as the `typ` property
- `knox.token.allowed.jws.types` - this can be set as a `JWTProvider` provider parameter. Defaults to `JWT`. Please note, this configuration is only applied if token verification goes through the JWKS verification path as described in #216 .
Unit tested as well as executed manual test runs w/ different combinations of these new params.
> KNOX-2703 - Configuring JWT type at creation/verification time

- gateway-server/src/main/java/org/apache/knox/gateway/GatewayFilter.java
- gateway-server/src/main/java/org/apache/knox/gateway/filter/CorrelationHandler.java
- gateway-server/src/test/java/org/apache/knox/gateway/GatewayFilterTest.java
The PR adds a feature where, when a request comes to Knox with  header `X-Request-Id` then use that as a correlation id. This is useful to track requests that originate from other services or LBs and users need ability to trace requests.
This patch was tested locally on a local cluster.
> KNOX-2704 - Honor request id (correlation id) set by upstream loadbalancer

- gateway-discovery-ambari/src/main/java/org/apache/knox/gateway/topology/discovery/ambari/AmbariServiceDiscovery.java
- gateway-discovery-ambari/src/main/java/org/apache/knox/gateway/topology/discovery/ambari/AmbariServiceDiscoveryType.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscovery.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryMessages.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryRepository.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryType.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/DiscoveryApiClient.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryRepositoryTest.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryTest.java
- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-server/src/test/java/org/apache/knox/gateway/topology/discovery/test/extension/DummyServiceDiscovery.java
- gateway-server/src/test/java/org/apache/knox/gateway/topology/discovery/test/extension/DummyServiceDiscoveryType.java
- gateway-server/src/test/java/org/apache/knox/gateway/topology/discovery/test/extension/PropertiesFileServiceDiscovery.java
- gateway-server/src/test/java/org/apache/knox/gateway/topology/discovery/test/extension/PropertiesFileServiceDiscoveryType.java
- gateway-server/src/test/java/org/apache/knox/gateway/topology/discovery/test/extension/SneakyServiceDiscoveryImpl.java
- gateway-server/src/test/java/org/apache/knox/gateway/topology/discovery/test/extension/SneakyServiceDiscoveryType.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
- gateway-spi/src/main/java/org/apache/knox/gateway/topology/discovery/ServiceDiscovery.java
- gateway-spi/src/main/java/org/apache/knox/gateway/topology/discovery/ServiceDiscoveryFactory.java
- gateway-spi/src/main/java/org/apache/knox/gateway/topology/discovery/ServiceDiscoveryType.java
- gateway-test-release-utils/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
- gateway-test/src/test/java/org/apache/knox/gateway/SimpleDescriptorHandlerFuncTest.java
- gateway-topology-simple/src/main/java/org/apache/knox/gateway/topology/simple/SimpleDescriptorHandler.java
Two major changes are included (in two separate commits):
- the first is that Knox only discovers services that are actually listed in the given descriptor (instead of discovering the entire cluster)
- from now on, Knox maintains an in-memory repository of discovered data (cluster, service, and role configs). I used Caffeine as the cache implementation with the default of 10 mins of cache entry TTL.
Added/updated new/existing uni tests and ran comprehensive manual tests with different combinations of descriptors and services.
> KNOX-2680 - Introducing a central repository for CM service discovery configs

- gateway-release/home/conf/gateway-log4j2.xml
- gateway-server/src/main/java/org/apache/knox/gateway/GatewayFilter.java
- gateway-server/src/main/java/org/apache/knox/gateway/filter/CorrelationHandler.java
- gateway-spi/pom.xml
- gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/AbstractGatewayDispatch.java
- gateway-spi/src/test/java/org/apache/knox/gateway/dispatch/ConfigurableDispatchTest.java
This PR adds correlation id generated by Knox to gateway logs. In case where a request comes to Knox with header `X-Request-Id` that value is logged instead as trace id. This feature can be turned off by removing `%X{trace_id}` variable from `gateway-log4j2.xml` file.
Correlation is a random UUID or 16 random bytes, in hexadecimal if [generated by nginx](https://www.nginx.com/blog/application-tracing-nginx-plus/). 
One thing to note is that with this PR if correlation id is present it will be logged so it will slightly increase log size. 
Tested locally on single knox instance.
e.g.
`
curl -k -u guest:guest-password -X GET -H "X-Request-Id: 1234567890ABCD" https://localhost:8443/gateway/sandbox/webhdfs/v1/tmp/hello.txt\?op\=LISTSTATUS
`
```
==> …
```
> KNOX-2705 - Add correlation id to logs as trace_id

- gateway-service-definitions/src/main/resources/services/yarnui/2.7.0/rewrite.xml
The Kill Application button is broken, KNOX matches and rewrites the URL twice into an invalid URL.
This change removes the parentheses around the first pattern for `/ws/v1/`, so that relative paths are not rewritten twice.
It seems to work, though I'm not sure if it silently breaks other URLs just yet.
Tested in local production cluster. Spawned up a new spark job and killed it via the Kill Application button in YARN.
> KNOX-2531 Kill Application button in YARN does not work through KNOX

- gateway-provider-identity-assertion-common/pom.xml
- gateway-provider-identity-assertion-common/src/main/java/org/apache/knox/gateway/IdentityAsserterMessages.java
- gateway-provider-identity-assertion-common/src/main/java/org/apache/knox/gateway/identityasserter/common/filter/CommonIdentityAssertionFilter.java
- gateway-provider-identity-assertion-common/src/main/java/org/apache/knox/gateway/identityasserter/common/filter/VirtualGroupMapper.java
- gateway-provider-identity-assertion-common/src/test/java/org/apache/knox/gateway/identityasserter/common/filter/VirtualGroupMapperTest.java
- gateway-provider-identity-assertion-common/src/test/java/org/apache/knox/gateway/identityasserter/filter/CommonIdentityAssertionFilterTest.java
- gateway-provider-identity-assertion-hadoop-groups/src/test/java/org/apache/knox/gateway/identityasserter/hadoop/groups/filter/HadoopGroupProviderFilterTest.java
- gateway-provider-identity-assertion-pseudo/src/main/java/org/apache/knox/gateway/identityasserter/filter/IdentityAsserterDeploymentContributor.java
- gateway-util-common/src/main/java/org/apache/knox/gateway/plang/AbstractSyntaxTree.java
- gateway-util-common/src/main/java/org/apache/knox/gateway/plang/Arity.java
- gateway-util-common/src/main/java/org/apache/knox/gateway/plang/ArityException.java
- gateway-util-common/src/main/java/org/apache/knox/gateway/plang/Ast.java
- gateway-util-common/src/main/java/org/apache/knox/gateway/plang/Interpreter.java
- gateway-util-common/src/main/java/org/apache/knox/gateway/plang/InterpreterException.java
- gateway-util-common/src/main/java/org/apache/knox/gateway/plang/Parser.java
- gateway-util-common/src/main/java/org/apache/knox/gateway/plang/SyntaxException.java
- gateway-util-common/src/main/java/org/apache/knox/gateway/plang/TypeException.java
- gateway-util-common/src/main/java/org/apache/knox/gateway/plang/UndefinedSymbolException.java
- gateway-util-common/src/test/java/org/apache/knox/gateway/plang/InterpreterTest.java
- gateway-util-common/src/test/java/org/apache/knox/gateway/plang/ParserTest.java
A more flexible way to map principals to groups than the existing `group.principal.mapping` mechanism in `CommonIdentityAssertionFilter`.
This patch extends the existing `CommonIdentityAssertionFilter` with a new way to map virtual groups to users.
The syntax allows us to map a virtual group to a user, using arbitrary predicates expressed in a parenthesized prefix notation language.
```
<name>virtual.group.mapping.VIRTUAL-GROUP-NAME</name>
<value>PREDICATE</value>
```
The existing mappings like `principal.mapping` and `group.principal.mapping` are still supported by the provider.
Manually tested with the following shiro + provider config.
```xml
<provider>
<role>authentication</role>
<name>ShiroProvider</name>
<param>
<name>sessionTimeout</name>
<value>30</value> …
```
> KNOX-2707 - Virtual Group Mapping Provider

- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceMessages.java
- gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
Changing Knox's default behavior when a user exceeds the configured token limit: if `REMOVE_OLDEST` is configured, Knox will remove the oldest token instead of returning an error.
Updated existing JUnit tests as well as added new ones:
```
$ mvn clean -Dshellcheck=true verify -Prelease,package -am -pl gateway-service-knoxtoken
[INFO] Total time:  05:56 min
[INFO] Finished at: 2022-03-04T15:23:36+01:00
```
- set `gateway.knox.token.limit.per.user = 1` in `gateway-site.xml`
- set `knox.token.user.limit.exceeded.action …
> KNOX-2713 - Allowing end-users to customize 'user limit exceeded' action when creating Knox tokens

- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
- gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/KnoxToken.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/TokenMetadata.java
- knox-token-management-ui/token-management/app/metadata.ts
- knox-token-management-ui/token-management/app/token.management.component.html
- knox-token-management-ui/token-management/app/token.management.component.ts
The following enhancements were added by this change:
- the simple `GET` API is extended to handle custom metadata information
- the `getUserTokens` API  endpoint is extended to filter tokens by metadata name/value
- additional metadata information is displayed on the Knox Token Management page
Adjusted and ran JUnit tests:
```
$ mvn clean -Dshellcheck=true verify -Prelease,package -am -pl gateway-service-knoxtoken
...
[INFO] Total time:  06:01 min
[INFO] Finished at: 2022-03-04T09:32:59+01:00
```
Additionally, I tested the API …
> KNOX-2712 - Managing custom Knox Token metadata

- gateway-service-definitions/src/main/resources/services/trinoui/365/rewrite.xml
- gateway-service-definitions/src/main/resources/services/trinoui/365/service.xml
[Trino](https://trino.io/docs/current/) is a distributed SQL query engine designed to query large data sets distributed over one or more heterogeneous data sources. We can support it in knox service definition, so that knox can proivide proxying service for it.
Deploy knox in a cluster with trino, we can access trino ui with knox server port 8443.
> KNOX-2711 - Add trino ui support in service definition.

- gateway-provider-identity-assertion-common/src/main/java/org/apache/knox/gateway/identityasserter/common/filter/CommonIdentityAssertionFilter.java
- gateway-provider-identity-assertion-common/src/test/java/org/apache/knox/gateway/identityasserter/filter/CommonIdentityAssertionFilterTest.java
CommonIdentityAssertionFilter puts the same group multiple times as shown in the audit log:
```
22/02/17 17:40:38 ||b28adfe1-90ea-4fb5-9ad7-9d444edd3d26|audit|[0:0:0:0:0:0:0:1]|HIVE|tom|mapped-tom||identity-mapping|principal|mapped-tom|success|Groups: [lg1, lg1]
```
manually + unittest
> KNOX-2342 - CommonIdentityAssertionFilter calling mapGroupPrincipals Twice

- gateway-service-definitions/src/main/resources/services/hbaseui/2.1.0/rewrite.xml
Add rewrite rule for Named Queue Logs on HBase Master UI.
Copied the rewrite.xml file to a cluster, restarted Knox, and verified the URL is redirecting correctly.
> KNOX-2724 Add HBase UI proxying for Named Queue Logs

- gateway-service-definitions/src/main/resources/services/hiveserver2ui/3.1.2/rewrite.xml
- gateway-service-definitions/src/main/resources/services/hiveserver2ui/3.1.2/service.xml
[HiveServer2](https://cwiki.apache.org/confluence/display/hive/hiveserver2+overview) is a service that enables clients to execute queries against Hive. It supports multi-client concurrency and authentication. We can support it in knox service definition, so that knox can proivide proxying service for it.
Deploy knox in a cluster with HiveServer2, we can access HiveServer2 web ui with knox server port 8443.
> KNOX-2725 - Add HiveServer2 webui support in service definition.

- gateway-server/src/main/java/org/apache/knox/gateway/GatewayFilter.java
- gateway-server/src/main/java/org/apache/knox/gateway/GatewayServlet.java
- gateway-server/src/test/java/org/apache/knox/gateway/AuditLoggingTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/GatewayFilterTest.java
There was a change a while ago due to which correlation id in audit logs was missing in the last audit message for a request. This PR fixes that issue.
This patch was tested locally on local Knox instance. 
**Before Patch**
```
22/04/14 02:17:24 ||6bb6e07e-1540-47e9-9e07-7798563fe125|audit|[0:0:0:0:0:0:0:1]|WEATHER||||access|uri|/gateway/sandbox/weather/data/2.5/forecast?id=524901&APPID=54557732afcfe106bfc955b9da04fb14|unavailable|Request method: GET
22/04/14 02:17:24 ||6bb6e07e-1540-47e9-9e07-7798563fe125|audit|[0:0:0:0:0:0:0:1]|WEATHER|guest|||authentication|uri|/gateway/sandbox/weather/data/2.5/forecast?id=524901&APPID=54557732afcfe106bfc955b9da04fb14|success|
22/04/14 02:17:24 ||6bb6e07e-1540-47e9-9e07-7798563fe125|audit|[0:0:0:0:0:0:0:1]|WEATHER|guest|||authentication|uri|/gateway/san …
```
> KNOX-2730 - Fix missing Correlation id in audit logs

- gateway-provider-security-pac4j/src/main/java/org/apache/knox/gateway/pac4j/Pac4jMessages.java
- gateway-provider-security-pac4j/src/main/java/org/apache/knox/gateway/pac4j/config/SAML2ClientConfigurationDecorator.java
- gateway-provider-security-pac4j/src/main/java/org/apache/knox/gateway/pac4j/filter/Pac4jDispatcherFilter.java
- gateway-provider-security-pac4j/src/test/java/org/apache/knox/gateway/pac4j/config/SAML2ClientConfigurationDecoratorTest.java
This PR adds the ability to specify Keystore type and Keystore location used by Pac4j. 
Previously, default keystore type was always assumed to be JKS. With this PR we use the keystore type that is used by Knox.
This patch was tested on a local Knox instance with Okta SSO.
> KNOX-2733 - Support configurable value for saml.keyStoreType property in pac4j

- gateway-shell/src/main/java/org/apache/knox/gateway/shell/knox/token/Get.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/knox/token/Token.java
- gateway-shell/src/test/java/org/apache/knox/gateway/shell/knox/token/TokenTest.java
Added a flag to Knox shell Token.Get API to support tokens with group informations in them.
1.
Generated a token and checked the group information in the result:
```java
public static void main(String[] args) throws Exception {
ClientContext context = ClientContext.with("admin", "admin-password", "https://localhost:8443/gateway/homepage");
KnoxSession knoxSession = new KnoxSession(context);
System.out.println( Token.get(knoxSession, null, true).now().getString() );
}
```
2.
Generated a token and verified that there was no group information in the result:
```java
public static void main(String[] args) throws Exception {
ClientContext context = ClientContext.with("admin", "admin-password", "https://localhost:8443/gateway/homepage");
KnoxSession knoxSession = new KnoxSession(context); …
```
> KNOX-2735 Add support for group info inclusion in tokens to the KnoxShell client

- gateway-applications/src/main/resources/applications/tokengen/app/js/tokengen.js
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/AbstractPersistentTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/AliasBasedTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/JDBCTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/JournalBasedTokenStateService.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/AliasBasedTokenStateServiceTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/JournalBasedTokenStateServiceTest.java
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
- gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/PersistentTokenStateService.java
As described in [KNOX-2734](https://issues.apache.org/jira/browse/KNOX-2734), the passcode token should not be presented in the JSON response coming from TokenResource, when a Knox Token is generated, if:
- token state management is disabled
- the underlying token state backend stores the tokens in-memory only
The token generation UI got modified too: when there is no passcode tag in the JSON response there is no reason to show its label on the UI.
Added new JUnit tests to cover the new business logic.
Additionally, I did E2E testing:
- added KnoxToken service into the `sandbox` topology with `knox.token.exp.server-managed=false`
- configured the token state backend to `DefaultTokenStateService` in `gateway-site.xml`
- Left `knox.token.exp.server-managed=true` in the `homepage` topology
- …
> KNOX-2734 - Passcode token is optional in TokenResource's response

- gateway-server/src/main/java/org/apache/knox/gateway/GatewayMessages.java
- gateway-server/src/main/java/org/apache/knox/gateway/GatewayServer.java
- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
- gateway-test-release-utils/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
Knox's embedded Jetty's maxFormContentSize and maxFormKeys configurations are now configurable in `gateway-site.xml`
Ran JUnit tests:
```
$  mvn clean -Dshellcheck=true verify -Prelease,package -am -pl gateway-server
...
[INFO] Total time:  05:59 min
[INFO] Finished at: 2022-04-22T15:54:23+02:00
```
> KNOX-2737 - Make maxFormContentSize and maxFormKeys configurable in Knox's embedded Jetty server

- gateway-server/pom.xml
- gateway-server/src/main/java/org/apache/knox/gateway/util/JDBCUtils.java
- gateway-server/src/main/resources/createKnoxTokenDatabaseTable.sql
- gateway-server/src/main/resources/createKnoxTokenMetadataDatabaseTable.sql
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/JDBCTokenStateServiceTest.java
- pom.xml
Starting multiple knox instances can cause token state service initialization failures when they try to create the same database tables.
```
ERROR knox.gateway (TokenStateServiceFactory.java:createService(63)) - Error while initiatalizing org.apache.knox.gateway.services.token.impl.JDBCTokenStateService: Error while initiating JDBCTokenStateService: org.postgresql.util.PSQLException: ERROR: relation "knox_tokens" already exists
```
To fix this issue I added a `IF NOT EXISTS` clause to the create table statement. This is unfortunately not supported by Derby (which is only used for unit testing), so I replaced derby with hsql.
I tested manually with both mysql and postgres.
Postgres gateway-site config:
```xml
<property>
<name>gateway.service.tokenstate.impl</name> …
```
> KNOX-2738 On Fresh install JDBCTokenStateService initiation failed

- gateway-applications/src/main/resources/applications/tokengen/app/index.html
- gateway-applications/src/main/resources/applications/tokengen/app/js/tokengen.js
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
- knox-token-management-ui/token-management/app/token.management.component.html
- knox-token-management-ui/token-management/app/token.management.component.ts
- knox-token-management-ui/token-management/app/token.management.service.ts
Added a new KnonToken service level configuration to enable/disable token impersonation. It's called `knox.token.impersonation.enabled` and defaults to `true`. Using this boolean config we can show/hide impersonation-related fields in Knox UIs.
1. `knox.token.impersonation.enabled=true` or w/o declaring this config
Token Management UI:
Token Generation UI:
2. `knox.token.impersonation.enabled=false`
Token Management UI:
Token Generation UI:
> KNOX-2740 - Impersonation-related fields should be displayed only if that's enabled in the topology for the KnoxToken service

- gateway-provider-identity-assertion-common/pom.xml
- gateway-provider-rewrite-func-hostmap-static/pom.xml
- gateway-provider-rewrite-func-service-registry/pom.xml
- gateway-provider-rewrite-step-encrypt-uri/pom.xml
- gateway-provider-rewrite/pom.xml
- gateway-provider-security-pac4j/pom.xml
- gateway-server/pom.xml
- gateway-spi/pom.xml
- gateway-test-utils/pom.xml
- gateway-test-utils/src/main/java/org/apache/knox/test/TestUtils.java
- gateway-test/pom.xml
- gateway-test/src/test/java/org/apache/knox/gateway/AmbariServiceDefinitionTest.java
- gateway-test/src/test/java/org/apache/knox/gateway/GatewayBasicFuncTest.java
- pom.xml
Upgraded Velocity and Pac4j versions to address CVE issues in Velocity (Pac4j upgrade was a required upgrade to be compatible with the new Velocity version).
Usually upgrading a 3rd party version is happening on the scope of its own JIRAs, but in this case the Velocity upgrade w/o the Pac4j modification would lead to errors.
Built and started the Knox Gateway with the new dependencies. I also modified the `knoxsso` topology to have the Pac4j federation provider instead of Shiro authentication and confirmed that I could successfully log in to our environment.
> KNOX-2741 - Upgraded Velocity and Pac4j versions

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscovery.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryMessages.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryTest.java
- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
- gateway-test-release-utils/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
In case of `ConnectException`s coming from Cloudera Manager during service discovery, Knox may re-try connecting to CM every 3 seconds for the configured number of times in order to successfully discover the configured cluster for the configured descriptor.
In addition to adding new unit tests, I manually tested the solution:
- configured `gateway.cloudera.manager.service.discovery.maximum.retry.attemps` to 20 in `gateway-site.xml`
- declared a descriptor with valid CM service discovery params
- started Knox in a way such as it started 20-30 seconds earlier than the configured Cloudera Manager server. In the logs I saw the retry attempt, and, finally, the successful service discovery.
> KNOX-2742 - Retrying CM service discovery in case of ConnectExceptions

- pom.xml
Bump protobuf version to 3.16.1
```bash
amagyar-MBP16:knox attilamagyar$ mvn dependency:tree | grep protobuf-java
[INFO] |  \- com.google.protobuf:protobuf-java:jar:3.16.1:compile
[INFO] |     \- com.google.protobuf:protobuf-java:jar:3.16.1:compile
[INFO] |     \- com.google.protobuf:protobuf-java:jar:3.16.1:test
[INFO] |     \- com.google.protobuf:protobuf-java:jar:3.16.1:test
[INFO] |     \- com.google.protobuf:protobuf-java:jar:3.16.1:compile
[INFO] |     \- com.google.protobuf:protobuf-java:jar:3.16.1:compile
[INFO] |     \- com.google.protobuf:protobuf-java:jar:3.16.1:compile
[INFO] |     \- com.google.protobuf:protobuf-java:jar:3.16.1:compile
[INFO] |     \- com.google.protobuf:protobuf-java:jar:3.16.1:compile
[INFO] |     \- com.google.protobuf:protobuf-java:jar:3.16.1:test
[INFO] …
```
> KNOX-2744 Upgrade protobuf-java to 3.16.1

- gateway-provider-identity-assertion-common/src/main/java/org/apache/knox/gateway/identityasserter/common/filter/CommonIdentityAssertionFilter.java
- gateway-provider-identity-assertion-hadoop-groups/src/main/java/org/apache/knox/gateway/identityasserter/hadoop/groups/filter/HadoopGroupProviderFilter.java
- gateway-provider-identity-assertion-hadoop-groups/src/test/java/org/apache/knox/gateway/identityasserter/hadoop/groups/filter/HadoopGroupProviderFilterTest.java
Virtual group mapping didn't use the group information from HadoopGroupProviderFilter. 
HadoopGroupProviderFilter extends from CommonIdentityAssertionFilter so they share the doFilter method. But the hadoop groups were not passed to the virtual group mapper.
Using the following topology:
```xml
<topology>
<gateway>
<provider>
<role>authentication</role>
<name>ShiroProvider</name>
<param>
<name>sessionTimeout</name>
<value>30</value>
</param>
<param>
<name>main.ldapRealm</name>
<value>org.apache.knox.gateway.shirorealm.KnoxLdapRealm</value>
</param>
<param>
<name>main.ldapContextFactory</name>
<value>org.apache.knox.gateway.shirorealm.KnoxLdapContextFactory</value>
</param>
<param>
<name>main.ldapRealm.contextFactory</name>
<value>$ldapContextFactory</value> …
```
> KNOX-2745 VirtualGroupMapper doesn't use groups from HadoopGroupProviderFilter

- gateway-shell/src/main/java/org/apache/knox/gateway/shell/ClientContext.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/KnoxClientRetryHandler.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/KnoxSession.java
- gateway-shell/src/test/java/org/apache/knox/gateway/shell/KnoxSessionTest.java
The apache http client has a default mechanism (StandardHttpRequestRetryHandler and DefaultServiceUnavailableRetryStrategy) to support retries.
* DefaultServiceUnavailableRetryStrategy only retries in case of a 503 - ServiceUnavailable.
* StandardHttpRequestRetryHandler retries when a non excluded exception occurs during the request.
The excluded exceptions are: InterruptedIOException, UnknownHostException, ConnectException, SSLException. In these cases no retry is going to happen.
However I think we should also retry in case of a ConnectException since ConnectionRefused and ConnectionTimeoouts are subclasses of ConnectException.
The following HTTP methods are considered idempotent so they can be retried: GET, HEAD, PUT, DELETE, OPTIONS, TRACE.
Note that if an endpoint is implemented as a …
> KNOX-2736 Knox clients should support retry/failover

- gateway-provider-ha/src/test/java/org/apache/knox/gateway/ha/provider/impl/HaDescriptorFactoryTest.java
Removed the previously eliminated `maxRetryAttempts` and `retrySleep` HA configs from a test case which were accidentally re-introduced.
Unit testing.
> KNOX-2346 - Eliminated the accidentally re-introduced configs in one of the tests

- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/JWTAccessTokenAssertionFilter.java
- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/JWTAuthCodeAssertionFilter.java
- gateway-service-knoxsso/src/main/java/org/apache/knox/gateway/service/knoxsso/WebSSOResource.java
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
- gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/JWTokenAttributes.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/JWTokenAttributesBuilder.java
The issuer of the JWT tokens is now configurable.
1. Added `knox.token.issuer` to KNOXTOKEN service.
```
<param>
<name>knox.token.issuer</name>
<value>test 1 2 3</value>
</param>
````
2. Created a token on the UI and checked the issuer.
3. Removed the `knox.token.issuer` from the config and checked the issuer (default KNOXSSO) again
> KNOX-2732 Issuer claim in Knox JWTs should be configurable

- gateway-provider-identity-assertion-common/pom.xml
- gateway-provider-identity-assertion-common/src/main/java/org/apache/knox/gateway/IdentityAsserterMessages.java
- gateway-provider-identity-assertion-common/src/main/java/org/apache/knox/gateway/identityasserter/common/filter/AbstractIdentityAsserterDeploymentContributor.java
- gateway-provider-identity-assertion-common/src/main/java/org/apache/knox/gateway/identityasserter/common/filter/CommonIdentityAssertionFilter.java
- gateway-provider-identity-assertion-common/src/main/java/org/apache/knox/gateway/identityasserter/common/filter/IdentityAsserterHttpServletRequestWrapper.java
- gateway-provider-identity-assertion-common/src/test/java/org/apache/knox/gateway/identityasserter/common/filter/AbstractIdentityAsserterDeploymentContributorTest.java
- gateway-provider-identity-assertion-common/src/test/java/org/apache/knox/gateway/identityasserter/filter/CommonIdentityAssertionFilterTest.java
- gateway-provider-identity-assertion-common/src/test/java/org/apache/knox/gateway/identityasserter/filter/IdentityAssertionHttpServletRequestWrapperTest.java
- gateway-provider-identity-assertion-no-doas/src/main/java/org/apache/knox/gateway/identityasserter/filter/NoImpersonationAsserterRequestWrapper.java
- gateway-provider-identity-assertion-no-doas/src/main/java/org/apache/knox/gateway/identityasserter/filter/NoImpersonationFilter.java
- gateway-provider-identity-assertion-no-doas/src/test/java/org/apache/knox/gateway/identityasserter/filter/NoImpersonationFilterTest.java
- gateway-provider-identity-assertion-pseudo/src/test/java/org/apache/knox/gateway/identityasserter/filter/DefaultIdentityAssertionFilterTest.java
- gateway-server/src/main/java/org/apache/knox/gateway/deploy/impl/ServiceDefinitionDeploymentContributor.java
- gateway-service-definitions/src/main/java/org/apache/knox/gateway/service/definition/CustomDispatch.java
- gateway-service-definitions/src/main/java/org/apache/knox/gateway/service/definition/Policy.java
Impersonation Params should be configurable so that Knox can scrub these params before sending it out to the backend services. There could be cases where some services might use their own impersonation params (similar to doAs used by Knox). Including these parameters in request could have unknown side effects. In order to prevent these issue, Impersonation Params should be configurable. 
The PR proposes adding `impersonation.params` parameter to the `identity-assertion` provider. 
This can be added in `service.xml` file or in topology file.
e.g. `service.xml`
```
<policies>
<policy role="authentication"/>
<policy role="rewrite"/>
<policy role="identity-assertion" name="Default">
<param>
<name>impersonation.params</name>
<value>customID, customServiceID</value>
</param>
</policy> …
```
> KNOX-2726 - Impersonation Params should be configurable

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscovery.java
Configuring the CM retry params only, of `gatewayConfig` is not `null`.
```
$ curl -iku admin:admin-password https://localhost:8443/gateway/admin/api/v1/servicediscoveries
Date: Fri, 03 Jun 2022 05:11:31 GMT
Set-Cookie: KNOXSESSIONID=node01x6ieg9i4zz6x1nd5qa5u0q9ys0.node0; Path=/gateway/admin; Secure; HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Set-Cookie: rememberMe=deleteMe; Path=/gateway/admin; Max-Age=0; Expires=Thu, 02-Jun-2022 05:11:31 GMT; SameSite=lax
Content-Type: application/xml
Content-Length: 486
<?xml version="1.0" encoding="UTF-8"?>
<knoxServiceDiscoveries>
<knoxServiceDiscovery>
<type>Ambari</type>
<implementation>org.apache.knox.gateway.topology.discovery.ambari.AmbariServiceDiscovery</implementation>
</knoxServiceDiscovery> …
```
> KNOX-2756 - Fixing NPE caused by null GatewayConfig

- gateway-service-definitions/src/main/resources/services/presto/0.261/rewrite.xml
- gateway-service-definitions/src/main/resources/services/presto/0.261/service.xml
- gateway-service-definitions/src/main/resources/services/prestoui/0.261/rewrite.xml
- gateway-service-definitions/src/main/resources/services/prestoui/0.261/service.xml
[Presto](https://prestodb.io/docs/current/) is a distributed SQL query engine designed to query large data sets distributed over one or more heterogeneous data sources. Add support for in knox service definition, so that knox can provide proxying service for presto.
Deployed knox in a cluster with presto, and checked access presto ui with knox server port 8442. Also checked presto apis with knox server as proxy
API testing: 
`curl --insecure -X POST -d 'show catalogs' -H "X-Presto-User: user" -H "Content-Type: application/json" https://localhost:8442/gateway/default/presto/v1/statement`
{"id":"20220517_112614_00000_muw7k","infoUri":"https://localhost:8442/gateway/default/presto/ui/query.html?20220517_112614_00000_muw7k","nextUri":"https://localhost:8442/gateway/default/presto/v1/statement/ …
> KNOX-2746 - Add presto/presto ui support in service definition

- gateway-server/src/main/java/org/apache/knox/gateway/util/KnoxCLI.java
- gateway-server/src/test/java/org/apache/knox/gateway/util/KnoxCLITest.java
KnoxCLI only allow creating one alias at a time which can be really slow if we want to create lots of aliases.
This patch introduces batch alias creation using the following syntax:
```bash
bin/knoxcli.sh create-aliases --alias a1 --value v1 --alias a2 --value v2 --alias a3 --value v3
```
```bash
$ time ./batch-creation.sh 
10 alias(es) have been successfully created.
real	0m2.679s
user	0m5.480s
sys	0m0.276s
```
```bash
$ time ./one-by-one-creation.sh 
test-key has been successfully created.
test-key has been successfully created.
test-key has been successfully created.
test-key has been successfully created.
test-key has been successfully created.
test-key has been successfully created.
test-key has been successfully created.
test-key has been successfully created.
test-key has been …
```
> KNOX-2752 knoxcli should support batch alias creation

- gateway-provider-security-authz-composite/src/main/java/org/apache/knox/gateway/deploy/impl/CompositeAuthzDeploymentContributor.java
- gateway-provider-security-authz-composite/src/test/java/org/apache/knox/gateway/deploy/impl/CompositeAuthzProviderTest.java
Whitespaces around delimiters were causing problems while specifying composite auth provider names. The parseProviderNames function has been modified to trim provider names before passing it to the Deployment Contributor function. 
Ran automated unit/integration tests to ensure provider names did not contain whitespaces. Also ran manual tests to ensure no malfunctions.
[Knox Contributing Process](https://cwiki.apache.org/confluence/display/KNOX/Contribution+Process#ContributionProcess-GithubWorkflow) reviewed.
> KNOX-2762 

- gateway-shell/src/main/java/org/apache/knox/gateway/shell/HttpDelete.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/knox/token/AbstractTokenLifecycleRequest.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/knox/token/Renew.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/knox/token/Revoke.java
- gateway-shell/src/test/java/org/apache/knox/gateway/shell/knox/token/TokenTest.java
- pom.xml
As the corresponding JIRA states, #494 changed some of the HTTP methods in `TokenResource` that the KnoxShell classes were missing to implement.
Executed the existing unit tests (no new tests were added in this case; it wasn't needed) and ran manual tests using Knox's [performance test tool](https://cwiki.apache.org/confluence/display/KNOX/KNOX-2402+-+Develop+a+performance-test+framework+to+test+token+state+service).
In addition to this, I also tested these changes together with the newly added retry functionality in KnoxShell (thanks, @zeroflag for the detailed test steps in #568):
Mini HTTP server with the following Pharo image
```
| c  | 
c := 0.
Teapot on
GET: '/knoxtoken/api/v1/token' -> [ 
c := c + 1.
Transcript
cr;
show: 'Incoming request c=', c asString.
c < 3 
ifTrue:[ …
```
> KNOX-2761 - Knox Token renew/revoke operations are now PUT/DELETE HTTP methods in KnoxShell too

- pom.xml
[KNOX-2721](https://issues.apache.org/jira/browse/KNOX-2721): upgrade jetty to 9.4.45 due to cves
CI build
> KNOX-2721: upgrade jetty to 9.4.45 due to cves

- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/dispatch/ConfigurableHADispatch.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/HaServiceConfig.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/impl/DefaultHaServiceConfig.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/impl/HaDescriptorConstants.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/impl/HaDescriptorFactory.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/impl/HaDescriptorManager.java
- gateway-provider-ha/src/test/java/org/apache/knox/gateway/ha/dispatch/ConfigurableHADispatchTest.java
- gateway-provider-ha/src/test/java/org/apache/knox/gateway/ha/dispatch/DefaultHaDispatchTest.java
- gateway-provider-ha/src/test/java/org/apache/knox/gateway/ha/provider/impl/HaDescriptorFactoryTest.java
- gateway-provider-ha/src/test/java/org/apache/knox/gateway/ha/provider/impl/HaDescriptorManagerTest.java
- gateway-service-rm/src/test/java/org/apache/knox/gateway/rm/dispatch/RMHaDispatchTest.java
- gateway-service-webhdfs/src/test/java/org/apache/knox/gateway/hdfs/dispatch/WebHdfsHaDispatchTest.java
Fix case where `disableLoadBalancingForUserAgents` property defined in HA provider in a topology was not getting picked up.
> KNOX-2766 - Make sure disableLoadBalancingForUserAgents is picked up from HA configs

- gateway-provider-security-authz-composite/pom.xml
- gateway-provider-security-authz-composite/src/main/java/org/apache/knox/gateway/deploy/impl/CompositeAuthzDeploymentContributor.java
- gateway-provider-security-authz-composite/src/test/java/org/apache/knox/gateway/deploy/impl/CompositeAuthzProviderTest.java
Fix for NullPointer Exception arising due to whitespaces around delimiters in Composite Auth Provider Names. All review comments addressed.
Comprehensive Unit tests used to cover most possible test cases. Also manually tested.
[Knox Contributing Process](https://cwiki.apache.org/confluence/display/KNOX/Contribution+Process#ContributionProcess-GithubWorkflow) reviewed.
> KNOX-2762 Bug fixes for spaces around delimiters with all reviewed comments addressed

- gateway-spi/src/main/java/org/apache/knox/gateway/SpiGatewayMessages.java
- gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/DefaultHttpClientFactory.java
Changed log level of http connection timeout and socket timeout to from DEBUG to INFO and added INFO level log for retry count and retry non safe request parameters, because sometimes clients were confused why the timeout parameters haven't changed even though they changed it in gateway-site.xml, but service.xml override-s it. Now they can see in the log what is the value of these parameters, only after the first request after topology deployment.
I tested it manually, using ```curl -k -u tom:tom-password https://localhost:8443/gateway/sandbox/hive``` command from terminal.
1. Nothing is set:
2. Timeout params set in gateway-site.xml and retry params set in sandbox.xml:
3. Timeout params set in gateway-site.xml and in service.xml, retry params set like 2.:
We can see that service.xml …
> KNOX-2771 - Log HTTP client config parameters such as socket timeouts with info level

- gateway-spi/src/main/java/org/apache/knox/gateway/SpiGatewayMessages.java
The replayBufferSize log level was changed from debug to info, to prevent confusion on what value was used, since it can be configured in two places (topology file and service.xml). Now the client can see what value was configured as replayBufferSize in the log after the first request after deploying a topology.
I tested it manually, using the following curl command
`curl -k -u tom:tom-password https://localhost:8443/gateway/sandbox/hive`
1. No configuration in either file
The log output was:
```
2022-07-07 09:27:30,761 ff7f8623-703b-4118-9d83-7a73d5f37231 INFO  knox.gateway (KnoxLdapRealm.java:getUserDn(688)) - Computed userDn: uid=tom,ou=people,dc=hadoop,dc=apache,dc=org using dnTemplate for principal: tom
2022-07-07 09:27:34,515 ff7f8623-703b-4118-9d83-7a73d5f37231 INFO  knox.gateway …
```
> KNOX-2773 - Log replay buffer size with info level

- gateway-release-common/home/bin/knox-functions.sh
Changed  the value of DEFAULT_APP_STATUS_TEST_RETRY_SLEEP from `2s` to `2` in `knox-functions.sh`, because sleep command in BSD family of operating systems (such as FreeBSD) or macOS/mac OS X does NOT take any suffix arguments (m/h/d). It only takes arguments in seconds.
I tested it manually.
Before the change:
```
mbalazs-MBP15:test mbalazs$ bin/gateway.sh start
usage: sleep seconds
usage: sleep seconds
.
.
.
usage: sleep seconds
usage: sleep seconds
Starting Gateway succeeded with PID 55659.
```
After the change:
```
mbalazs-MBP15:test mbalazs$ bin/gateway.sh start
Starting Gateway succeeded with PID 55659.
```
I also tried a request using `curl -k -u tom:tom-password https://localhost:8443/gateway/sandbox/hive` and got 
```
2022-07-07 14:50:25,037 726f3103-8de2-4ff8-9bc8-f47f8929da49 …
```
> KNOX-2774 - "usage: sleep seconds" messages in terminal after starting knox

- gateway-provider-security-shiro/src/main/java/org/apache/knox/gateway/deploy/impl/ShiroConfig.java
In order to make the `user-auth-test` KnoxCLI command work after the 1.6 Shiro upgrade, I'd to add the `invalidRequest` filter's object class (`org.apache.shiro.web.filter.InvalidRequestFilter`) into the `main` section in the generated shiro.ini. Without that change, an error was thrown (see the corresponding JIRA).
Ran the `GatewayShiroAuthTest` that covers use-cases for Shiro LDAP authentication including a valid service URL with a semicolon (`;jsessionid=OI24B9ASD7BSSD`).
Other than this I made sure the `user-auth-test` KnoxCLI command works:
```
$ bin/knoxcli.sh user-auth-test --cluster sandbox --u admin --p admin-password --d
LDAP authentication successful!
```
> KNOX-2782 - Enhanced Shiro config with the object class of invalidRequest

- gateway-provider-identity-assertion-common/src/main/java/org/apache/knox/gateway/identityasserter/common/filter/CommonIdentityAssertionFilter.java
- gateway-provider-identity-assertion-common/src/test/java/org/apache/knox/gateway/identityasserter/filter/CommonIdentityAssertionFilterTest.java
If there is no group name after the `group.mapping.` then the user is mapped to an empty group ("").
Toplogy:
```xml
<provider>
<role>authentication</role>
<name>ShiroProvider</name>
<param>
<name>sessionTimeout</name>
<value>30</value>
</param>
<param>
<name>main.pamRealm</name>
<value>org.apache.knox.gateway.shirorealm.KnoxPamRealm</value>
</param>
<param>
<name>main.pamRealm.service</name>
<value>login</value>
</param>
<param>
<name>urls./**</name>
<value>authcBasic</value>
</param>
</provider>
<provider>
<role>identity-assertion</role>
<name>HadoopGroupProvider</name>
<param>
<name>hadoop.security.group.mapping</name>
<value>org.apache.hadoop.security.ShellBasedUnixGroupsMapping</value>
</param>
<param>
<name>group.mapping.</name> …
```
> KNOX-2783 - User can be mapped to an empty virtual group

- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/factory/ConcurrentSessionVerifierFactory.java
- gateway-server/src/main/java/org/apache/knox/gateway/session/control/EmptyConcurrentSessionVerifier.java
- gateway-server/src/main/java/org/apache/knox/gateway/session/control/InMemoryConcurrentSessionVerifier.java
- gateway-server/src/test/java/org/apache/knox/gateway/config/impl/GatewayConfigImplTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/factory/ConcurrentSessionVerifierFactoryTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/session/control/InMemoryConcurrentSessionVerifierTest.java
- gateway-service-knoxsso/src/main/java/org/apache/knox/gateway/service/knoxsso/WebSSOResource.java
- gateway-service-knoxsso/src/test/java/org/apache/knox/gateway/service/knoxsso/WebSSOResourceTest.java
- gateway-service-knoxssout/src/main/java/org/apache/knox/gateway/service/knoxsso/WebSSOutResource.java
- gateway-spi-common/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/ServiceType.java
I added an empty implementation of the `ConcurrentSessionVerifier` (`EmptyConcurrentSessionVerifier`), now it is the default so users do not waste resources when they forget to configure the verifier. If they need the `InMemoryConcurrentSessionVerifier` implementation they need to configure it and pay attention to configure at least one user in at least one of the groups.
For example:
```
<property>
<name>gateway.privileged.users</name>
<value>admin</value>
</property>
<property>
<name>gateway.service.concurrentsessionverifier.impl</name>
<value>org.apache.knox.gateway.session.control.InMemoryConcurrentSessionVerifier</value>
</property>
```
I also added a background thread which cleans out the expired tokens from the `InMemoryConcurrentSessionVerifier` to save some resources. The default …
> KNOX-2788 - Implementing EmptyVerifier and Cleaning background thread

- gateway-service-auth/pom.xml
- gateway-service-auth/src/main/java/org/apache/knox/gateway/service/auth/AuthBearerResource.java
- gateway-service-auth/src/test/java/org/apache/knox/gateway/service/auth/AuthBearerResourceTest.java
- pom.xml
A new REST API endpoint is added in `KNOX-AUTH-SERVICE` with `auth/api/v1/bearer` path.
Implemented new unit test cases to cover this new functionality and executed manual testing:
1. Default environment variable name:
```
$ export BEARER_AUTH_TOKEN=MY_AUTH_BEARER_TOKEN
$ bin/gateway.sh start
$ curl -iku admin:admin-password -X GET https://localhost:8443/gateway/sandbox/auth/api/v1/bearer
Date: Fri, 26 Aug 2022 09:11:00 GMT
Set-Cookie: KNOXSESSIONID=node01u0cyzk36nibi18g2binv7e1290.node0; Path=/gateway/sandbox; Secure; HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Set-Cookie: rememberMe=deleteMe; Path=/gateway/sandbox; Max-Age=0; Expires=Thu, 25-Aug-2022 09:11:00 GMT; SameSite=lax
Authorization: Bearer MY_AUTH_BEARER_TOKEN
Content-Length: 0
```
2. Custom environment …
> KNOX-2792 - new REST API endpoint to set Authorization/Bearer header in the response using an environment variable

- gateway-provider-security-pac4j/src/main/java/org/apache/knox/gateway/pac4j/Pac4jMessages.java
- gateway-provider-security-pac4j/src/main/java/org/apache/knox/gateway/pac4j/filter/Pac4jDispatcherFilter.java
The client name config parameter was handled in an inconsistent manner.
* When it was null we threw an exception saying that this parameter is mandatory
* However when it was an empty string, we did fallback using the default client name coming from the provider
I removed the null check so that we use the default in that case too.
Manually tested with a topology like this:
```xml
<provider>
<role>federation</role>
<name>pac4j</name>
<param>
<name>pac4j.callbackUrl</name>
<value>https://localhost:8443/gateway/knoxsso/api/v1/websso</value>
</param>
<param>
<name>oidc.id</name>
<value>....</value>
</param>
<param>
<name>oidc.secret</name>
<value>SECRET</value>
</param>
<param>
<name>oidc.discoveryUri</name>
<value>...</value>
</param>
<param> …
```
> KNOX-2795 Handling missing OIDC client name parameter

- gateway-release/home/conf/topologies/homepage.xml
- gateway-spi/src/main/java/org/apache/knox/gateway/i18n/GatewaySpiMessages.java
- gateway-spi/src/main/java/org/apache/knox/gateway/topology/Provider.java
It turned out to be a general problem that effects other filters as well. I added a warning message if there are filter config params with the same name.
Tested with the following config:
```xml
<provider>
<role>identity-assertion</role>
<name>HadoopGroupProvider</name>
<param>
<name>group.mapping.abhi</name>
</param>
<param>
<name>group.mapping.abhi</name>
<value>false</value>
</param>
</provider>
```
```bash
$ grep WARN logs/gateway.log 
2022-09-06 18:52:46,777  WARN  knox.gateway (Provider.java:addParam(67)) - Duplicated filter param key: group.mapping.abhi
```
> KNOX-2801 Error Message should come in virtual group mapping provider if there are multiple occurrence's of a virtual group.

- gateway-server/src/main/java/org/apache/knox/gateway/util/KnoxCLI.java
- gateway-server/src/test/java/org/apache/knox/gateway/util/KnoxCLITest.java
There is an inconsistency in naming of the output file of the export cert command. The doc says it should be `gateway-client-trust.<type>` but in case of pem it's `gateway-identity.pem`.
```bash
$ bin/knoxcli.sh export-cert --type pem
Certificate gateway-identity has been successfully exported to: /Users/attilamagyar/development/test/data/security/keystores/gateway-client-trust.pem
$  ls -al  /Users/attilamagyar/development/test/data/security/keystores/gateway-client-trust.pem
-rw-r--r--  1 attilamagyar  staff  1246 Sep  6 10:28 /Users/attilamagyar/development/test/data/security/keystores/gateway-client-trust.pem
````
> KNOX-2799 - When exporting certificate using Knox CLI, the certificate is coming with wrong name when type=PEM

- gateway-server/src/test/java/org/apache/knox/gateway/topology/simple/SimpleDescriptorHandlerTest.java
- gateway-server/src/test/resources/conf-full/conf/descriptors/test-topology.json
- gateway-server/src/test/resources/conf-full/conf/shared-providers/test-providers.json
- gateway-topology-simple/pom.xml
- gateway-topology-simple/src/main/java/org/apache/knox/gateway/topology/simple/SimpleDescriptorHandler.java
Before writing a parameter (at provider, application, or service level) from a provider/descriptor pair into a topology, the parameter value has to be XML escaped so that it won't make the generated XML fail when Knox parses it.
Added new unit test case and resource (contains a simple `&` character in the provider resource) to the existing `SimpleDescriptorHandlerTest` suite that handles JSON type provider/descriptor pairs.
Additionally, I used this JSON in my local Knox Gateway deployment as a shared-provider config and confirmed that after my fix were applied the topology generation went well.
Shared-provider config JSON I used for testing (`shared-providers/smolnar.json`):
```
{
"providers" : [ {
"role" : "webappsec",
"name" : "WebAppSec",
"enabled" : true,
"params" : { …
```
> KNOX-2804 - Escaping values in generated XML before trying to parse that XML using SAX

- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
If the user supplied the same metadata name with different values in Knox's `getUserTokens` API, the result only contained tokens that matched the first name/value pair. This is now fixed by including all values of each metadata name during the filter logic.
I manually tested this feature and added the metadata/expected result matrix in KNOX-2805.
The `curl` command I used to create the tokens:
```
curl -iku admin:admin-password --cookie "hadoop-jwt=$HADOOP_JWT_COOKIE" -X GET "https://localhost:8443/gateway/homepage/knoxtoken/api/v1/token?md_Name=reina&md_Score=50"
curl -iku admin:admin-password --cookie "hadoop-jwt=$HADOOP_JWT_COOKIE" -X GET "https://localhost:8443/gateway/homepage/knoxtoken/api/v1/token?md_Name=mary&md_Score=100"
curl -iku admin:admin-password --cookie …
```
> KNOX-2805 - getUserTokens honours different metadata values with the same name

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/hive/HiveServiceModelGenerator.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryTest.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/model/hive/HiveOnTezServiceModelGeneratorTest.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/model/hive/HiveServiceModelGeneratorTest.java
Knox's automated service discovery had a bug when it came to HIVE(_ON_TEZ) service discovery. These services have their SSL-enabled flag on the service level, but the generated service model (by Knox) stored that information in the HS2 role configs.
In addition to this, the CM configuration name referred to the so-called `related name` configuration field which Knox does not consider when comparing previous and current service/role configs.
Updated JUnit tests and executed manual testing in a cluster with KNOX, HIVE and HIVE_ON_TEZ.
> KNOX-2807 - Hive's SSL_ENABLED flag is processed on the service level with the correct service configuration name in CM

- gateway-applications/src/main/resources/applications/knoxauth/app/js/knoxauth.js
The `btoa` (third party) javascript functions can't base64 encode some of the special characters such as the letter `ë`. 
We use this function to create the basic authorization header. If user's password contains an unsupported character the login will fail.
I tested the new function manually:
```
unicodeBase64Encode('árvíztűrő tükörfúrógép ë !#$%^&*()_!#@V')
'w6FydsOtenTFsXLFkSB0w7xrw7ZyZsO6csOzZ8OpcCDDqyAhIyQlXiYqKClfISNAVg=='
unicodeBase64Encode('阪熊奈岡鹿梨阜埼茨栃')
'6Ziq54aK5aWI5bKh6bm/5qKo6Zic5Z+86Iyo5qCD'
阪熊奈岡鹿梨阜埼茨栃
```
The I decoded the result and I got back the original string.
The I changed sam's password in users.ldif:
```
dn: uid=sam,ou=people,dc=hadoop,dc=apache,dc=org
objectclass:top
objectclass:person
objectclass:organizationalPerson
objectclass:inetOrgPerson
cn: sam
sn: sam
uid: …
```
> KNOX-2810 - Login on Knox UI doesn't work when the password contains special character

- gateway-service-hbase/src/main/java/org/apache/knox/gateway/hbase/HBaseDispatch.java
- gateway-service-hbase/src/main/java/org/apache/knox/gateway/hbase/HBaseUIDispatch.java
- gateway-service-hive/src/main/java/org/apache/knox/gateway/hive/HiveDispatch.java
- gateway-service-impala/src/main/java/org/apache/knox/gateway/impala/ImpalaDispatch.java
- gateway-service-jkg/src/main/java/org/apache/knox/gateway/jkg/JkgDispatch.java
- gateway-service-livy/src/main/java/org/apache/knox/gateway/livy/LivyDispatch.java
- gateway-service-nifi/src/main/java/org/apache/knox/gateway/dispatch/NiFiDispatch.java
- gateway-service-rm/src/main/java/org/apache/knox/gateway/rm/dispatch/RMHaBaseDispatcher.java
- gateway-service-storm/src/main/java/org/apache/knox/gateway/storm/StormDispatch.java
- gateway-service-webhdfs/src/main/java/org/apache/knox/gateway/hdfs/dispatch/HdfsHttpClientDispatch.java
- gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/URLDecodingDispatch.java
Changed the base class of some custom service dispatch implementations to `ConfigurableDispatch`
Ran unit tests and checked the class tree:
> KNOX-2751 - Custom service dispatches are now configurable

- .github/workflows/main.yml
- gateway-release-common/pom.xml
- gateway-release/pom.xml
- gateway-shell-release/pom.xml
I'd like to make sure that Knox's GH actions flow includes the previously added/configured `shellcheck` plugin.
After creating this PR I'm going to check if the `shellcheck` plugin was enabled and executed in the affected Maven sub-modules.
> KNOX-2814 - Run shellcheck for GitHub Actions too

- gateway-service-knoxsso/src/main/java/org/apache/knox/gateway/service/knoxsso/WebSSOResource.java
- gateway-service-knoxsso/src/test/java/org/apache/knox/gateway/service/knoxsso/WebSSOResourceTest.java
The attribute for KnoxSSO cookie is currently hardocded.
This improvement will make its value configurable to better accommodate various deployment scenarios.
Added new unit tests and ran existing
> KNOX-2824 - Make SameSite attribute on KnoxSSO Cookie Configurable

- gateway-server/src/main/java/org/apache/knox/gateway/deploy/DeploymentFactory.java
Only add "Default" provider iff it is found in the provider contributor map. There could be cases where service loader might find other identity-assertion providers e.g. JWTAuthCodeAsserter
Tested locally
> KNOX-2825 - Webshell - Only add Default provider iff it is found in the provider contributor map

- gateway-provider-security-hadoopauth/src/main/java/org/apache/knox/gateway/hadoopauth/HadoopAuthMessages.java
- gateway-provider-security-hadoopauth/src/main/java/org/apache/knox/gateway/hadoopauth/filter/HadoopAuthFilter.java
- gateway-provider-security-hadoopauth/src/test/java/org/apache/knox/gateway/hadoopauth/filter/HadoopAuthFilterTest.java
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceMessages.java
Changed the default value of `knox.token.impersonation.enabled` and added some helpful DEBUG-level log messages.
Tested in a live cluster with more than one topology w/ the `KNOXTOKEN` service with different parameter list.
> KNOX-2829 - Impersonation is disabled if knox.token.impersonation.enabled is not added in the KNOXTOKEN service configuration

- gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/GatewayDispatchFilter.java
- gateway-spi/src/test/java/org/apache/knox/gateway/dispatch/GatewayDispatchFilterTest.java
In isDispatchAllowed we check the full URL against the whitelist regexp (including /path, but not including query parameters). This makes complicated and error prone to configure the regular expression.
gateway-site.xml
```xml
<property>
<name>gateway.dispatch.whitelist.services</name>
<value>HBASEUI,DATANODE,HBASEUI,HDFSUI,JOBHISTORYUI,NODEUI,YARNUI,knoxauth</value>
<description>The comma-delimited list of service roles for which the gateway.dispatch.whitelist should be applied.</description>
</property>
```
Tested manually.
> KNOX-2827 - isDispatchAllowed should cut off path segments from the URL

- gateway-provider-security-hadoopauth/src/main/java/org/apache/knox/gateway/hadoopauth/HadoopAuthMessages.java
- gateway-provider-security-hadoopauth/src/main/java/org/apache/knox/gateway/hadoopauth/filter/HadoopAuthFilter.java
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceMessages.java
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/deploy/TokenServiceDeploymentContributor.java
- gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
- gateway-spi/src/main/java/org/apache/knox/gateway/i18n/GatewaySpiMessages.java
- gateway-spi/src/main/java/org/apache/knox/gateway/util/AuthFilterUtils.java
Prior to my changes, both Knox's `HadoopAuthFilter` and `TokenResource` classes used Hadoop's `ProxyUsers` class that maintains a static `ImpersonationProvider` instance and invokes delegation methods on that. Subsequent `ProxyUsers.refreshSuperUserGroupsConfiguration` calls overwrite this impersonation provider. This causes a problem in the following cases:
- end-users have multiple Knox topologies where token impersonation enabled with different proxyuser configurations in the `KNOXTOKEN` service
- even in the same topology if the authentication method is Kerberos (thus we have the `HadoopAuth` filter enabled and configured) and the `KNOXTOKEN` service with impersonation enabled with another proxuyser configuration
The solution is to eliminate the need for this static `ProxyUsers` …
> KNOX-2831 - Make Hadoop impersonation work across topologies and roles with different proxyuser configs

- gateway-service-definitions/src/main/resources/services/oozie/5.0.0/rewrite.xml
Oozie's "root" rewrite rule must be more strict making it not to match to HDFS paths like "hdfs://namespace/oozie/libraries"
I did manual test steps in my environment:
* I run an Oozie job using Hue having a workflow property: prop1=hdfs://namespace/oozie/libraries
* checked the value is broken
* then I edited /var/lib/knox/gateway/data/services/oozie/5.0.0/rewrite.xml to apply the change
* then restarted Knox
* then waited two minutes
* then started the same Oozie workflow via Hue
then I experienced on the issue is gone. I did revert the change, tun the whole again then the issue came again. Then repeated the whole with the fix and the …
> KNOX-2841 Oozie "root" rewrite rule's pattern is too open

- gateway-test-release/pom.xml
- pom.xml
SecureKnoxShellTest was broken due to a NoClassDefFound error. It seems miniDFS now requires mockito, which needed to be added to Knox test dependencies.
mvn -Ppackage,release clean verify
> KNOX-2840 - SecureKnoxShellTest broken

- gateway-server/src/test/java/org/apache/knox/gateway/websockets/GatewayWebsocketHandlerTest.java
Disabled `GatewayWebsocketHandlerTest.testValidWebShellRequest()` temporarily. 
Let the build run here.
> KNOX-2846 - Disabling org.apache.knox.gateway.websockets.GatewayWebsocketHandlerTest.testValidWebShellRequest()

- gateway-server/src/test/java/org/apache/knox/gateway/websockets/GatewayWebsocketHandlerTest.java
Let's see if it fixes this:
```
2022-11-28T05:34:23.3732998Z [ERROR] testValidWebShellRequest(org.apache.knox.gateway.websockets.GatewayWebsocketHandlerTest)  Time elapsed: 0.585 s  <<< ERROR!
2022-11-28T05:34:23.3733695Z java.lang.IllegalStateException: Unable to load cache item
2022-11-28T05:34:23.3734384Z 	at org.apache.knox.gateway.websockets.GatewayWebsocketHandlerTest.testValidWebShellRequest(GatewayWebsocketHandlerTest.java:88)
2022-11-28T05:34:23.3735487Z Caused by: java.lang.IllegalAccessError: class javax.xml.parsers.FactoryFinder (in unnamed module @0x38954d02) cannot access class jdk.xml.internal.SecuritySupport (in module java.xml) because module java.xml does not export jdk.xml.internal to unnamed module @0x38954d02
2022-11-28T05:34:23.3736670Z 	at …
```
> KNOX-2846 - Fix GatewayWebsocketHandlerTest.testValidWebShellRequest

- gateway-server/src/main/java/org/apache/knox/gateway/GatewayMessages.java
- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/topology/impl/DefaultTopologyService.java
- gateway-server/src/main/java/org/apache/knox/gateway/topology/monitor/RemoteConfigurationMonitorServiceFactory.java
- gateway-server/src/main/java/org/apache/knox/gateway/topology/monitor/ZkRemoteConfigurationMonitorService.java
- gateway-server/src/main/java/org/apache/knox/gateway/topology/monitor/db/DbRemoteConfigurationMonitorService.java
- gateway-server/src/main/java/org/apache/knox/gateway/topology/monitor/db/RemoteConfig.java
- gateway-server/src/main/java/org/apache/knox/gateway/topology/monitor/db/RemoteConfigDatabase.java
- gateway-server/src/main/resources/createKnoxProvidersTable.sql
- gateway-server/src/main/resources/createKnoxTokenDescriptorsTable.sql
- gateway-server/src/test/java/org/apache/knox/gateway/topology/monitor/db/DbRemoteConfigurationMonitorServiceTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/topology/monitor/db/RemoteConfigDatabaseTest.java
- gateway-spi-common/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
[KNOX-2835](https://issues.apache.org/jira/browse/KNOX-2835) introduced an unwanted side effect after enabling the SQL based topology monitor.
The intent of  synchronization which was added in KNOX-2835 is:
* If a descriptor/provider was deleted from the DB the monitor should delete the descriptor/provider from the local file system
But what really happens, implementation wise is that:
* If a descriptor/provider exists on the file system but doesn't exist in the DB the topology monitor is going to delete it.
These two are not exactly the same. If a user creates a descriptor/provider on the file system, it will be deleted by the topology monitor even though it never existed in the DB. The Zookeeper implementation uses onDeleteEvents which are only triggered when something was previously …
> KNOX-2844 - Remote config monitor should not automatically delete local files if they're missing from the DB

- gateway-server/src/main/java/org/apache/knox/gateway/util/JDBCUtils.java
- gateway-server/src/test/java/org/apache/knox/gateway/util/JDBCUtilsTest.java
From now on our end-users can define the username and password connection properties as `gateway_database_user` and `gateway_database_password` aliases so that this sensitive information should not be included in the supplied JDBC URL.
Additionally, SSL configuration happens for both connection types (JDBC URL or separate property declaration).
Updated existing JUnit test cases and conducted the following manual testing:
I configured my local PostgreSQL server to accept SSL connections, enforce passwords and created the following user/DB for testing:
```
postgres=# CREATE USER smolnar LOGIN PASSWORD 'cloudera';
CREATE ROLE
postgres=# CREATE DATABASE mydatabase WITH OWNER = smolnar;
CREATE DATABASE
```
```
$ psql "sslmode=verify-full host=localhost dbname=mydatabase …
```
> KNOX-2851 - Username and password properties can be set as aliases even when clients use JDBC URL.

- gateway-admin-ui/admin-ui/app/new-desc-wizard/new-desc-wizard.component.html
- gateway-admin-ui/admin-ui/app/new-desc-wizard/new-desc-wizard.component.ts
- gateway-admin-ui/admin-ui/app/provider-config-wizard/provider-config-wizard.component.html
- gateway-admin-ui/admin-ui/app/provider-config-wizard/provider-config-wizard.component.ts
- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-service-admin/src/main/java/org/apache/knox/gateway/service/admin/TopologiesResource.java
- gateway-spi-common/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
- gateway-spi/src/main/java/org/apache/knox/gateway/i18n/GatewaySpiMessages.java
- gateway-test/src/test/java/org/apache/knox/gateway/GatewayAdminTopologyFuncTest.java
When creating a new descriptor or provider config, knox should check if there is an existing read-only descriptor/provider with the same name.
Using this config:
```xml
<property>
<name>gateway.read.only.override.topologies</name>
<value>admin,manager,xxx</value>    
</property>
<property>
<name>gateway.read.only.override.providers</name>
<value>prov1,prov2</value>
</property>
```
Checking descriptor creation (negative case):
Plus positive case.
> KNOX-2848: Prevent overwriting generated descriptors/providers

- gateway-admin-ui/package-lock.json
- knox-homepage-ui/package-lock.json
- knox-token-generation-ui/package-lock.json
- knox-token-management-ui/package-lock.json
- knox-webshell-ui/package-lock.json
- knox-webshell-ui/package.json
The `@angular-eslint/schematics` dependency was upgraded from `1.2.0` to `15.1.0` in Webshell-UI.
The `decode-uri-component` in all angular projects was upgraded from `0.2.0` to `0.2.2`.
I have done the following manual tests on the UI:
Homepage:
* Tried the links
* Mouse on service name -> description shows up
* When UI services are clicked they navigate to UI URL
* When API services are clicked description shows up
* Dropdown menus open and close
* New topologies appear under the topologies menu
Token-generation:
* set server-managed to true and false
* set impersonation to true and false
* set lifespan.input.enabled to true and false
* tried to generate token over the max lifespan limit -> generate anyway/adjust lifetime
* generated tokens until reached token limit
* authenticated with …
> KNOX-2852 - Bumped decode-uri-component in angular projects and schematics in webshell-ui

- gateway-service-definitions/src/main/resources/services/hbaseui/2.1.0/rewrite.xml
- gateway-service-definitions/src/main/resources/services/hbaseui/2.1.0/service.xml
In HBASE-20904 we added support for /prometheus endpoints under Hbase WebUI. 
So in this PR added configurations to make sure that /prometheus endpoints works fine through the proxy.
Copied the patched files "rewrite.xml" and "service.xml" into knox directory and restarted the knox. When opened the Hbase WebUI, the /prometheus endpoint started working as expected. Earlier it used to give 404 error without proxying configurations.
(If this patch involves UI changes, please …
> KNOX-2855:Added Hbase UI proxying for prometheus end points

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/monitor/PollingConfigurationAnalyzer.java
- pom.xml
Upgrade CM API version
Tested on a local cluster 
```
2023-01-06 11:46:58,551  INFO  discovery.cm (ClouderaManagerServiceDiscovery.java:discoverCluster(259)) - Performing cluster discovery for "Cluster 1"
2023-01-06 11:46:58,551  INFO  discovery.cm (ClouderaManagerServiceDiscovery.java:discoverCluster(280)) - Skipping service discovery: OZONE-1 (OZONE)
2023-01-06 11:46:58,551  INFO  discovery.cm (ClouderaManagerServiceDiscovery.java:discoverCluster(283)) - Discovering service: SOLR-1 (SOLR) ...
2023-01-06 11:46:58,552  INFO  discovery.cm (ClouderaManagerServiceDiscovery.java:discoverCluster(293)) - Discovering service role: SOLR-1-SOLR_SERVER-c0f21f059915235fddf68e4bd6267b28 (SOLR_SERVER) ...
2023-01-06 11:46:58,552  INFO  discovery.cm …
```
> KNOX-2861 upgrade CM API version

- gateway-service-knoxsso/src/main/java/org/apache/knox/gateway/service/knoxsso/WebSSOResource.java
- gateway-service-knoxsso/src/test/java/org/apache/knox/gateway/service/knoxsso/WebSSOResourceTest.java
Fedramp mandates this to be 15 minutes.
* Removed `knoxsso.token.ttl` from `knoxsso.xml`
* Logged in at knox ui
* Extracted and checked the "exp" field from the hadoop-jwt cookie
> KNOX-2862 - Setup idle timeout for SSO cookie to 15 minutes

- gateway-service-hashicorp-vault/src/main/java/org/apache/knox/gateway/backend/hashicorp/vault/HashicorpVaultAliasService.java
- gateway-service-hashicorp-vault/src/test/java/org/apache/knox/gateway/backend/hashicorp/vault/TestHashicorpVaultAliasService.java
Fixed the HashiCorpVaultAliasService `getPasswordFromAliasForCluster` function, because it worked incorrectly when the generate flag was set to `true`.
I extended the existing unit tests.
> KNOX-2748 - Fixed HashiCorp alias service getPasswordFromAliasForCluster

- gateway-discovery-ambari/src/main/java/org/apache/knox/gateway/topology/discovery/ambari/RESTInvoker.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscovery.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/DiscoveryApiClient.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/monitor/ClouderaManagerClusterConfigurationMonitor.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/monitor/PollingConfigurationAnalyzer.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryTest.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/monitor/PollingConfigurationAnalyzerTest.java
- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/security/impl/JettySSLService.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/security/impl/JettySSLServiceTest.java
- gateway-spi-common/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
- gateway-spi/src/main/java/org/apache/knox/gateway/util/TruststoreSSLContextUtils.java
There are 2 changes in this PR:
- TLS cipher suites and protocols are now customizable in CM service discovery:
- end-users can define the TLS protocol(s) and cipher suite(s) to use while creating a secure connection to a CM instance
- if none is defined, Knox will pick up the relevant supported values from Java's own `java.security` thru the acquired SSL context.
- Added a new method to indicate the TLS protocols to be included when creating SSL context in the embedded Jetty server. Prior to this change, end-users could only tell what to exclude.
Unit testing and running service discovery in a secure cluster with updated SSL configs.
> KNOX-2864 - TLS cipher suites and protocols are configured for CM service discovery

- gateway-server/src/main/java/org/apache/knox/gateway/GatewayFilter.java
- gateway-server/src/main/java/org/apache/knox/gateway/GatewayMessages.java
- gateway-server/src/main/java/org/apache/knox/gateway/UrlEncodedFormRequest.java
- gateway-server/src/test/java/org/apache/knox/gateway/UrlEncodedFormRequestTest.java
In section SRV.3.1.1 of Servlet spec states that any access to request parameters of an "x-www-form-urlencoded" request (e.g. using HttpServletRequest#getParameter()) can trigger the early consumption of the request InputStream.
For example:
```java
request.getParameter("doAs");
IOUtils.toString(request.getInputStream()); // <= This will be empty because getParameter() already consumed the stream
```
This causes knox to dispatch an empty request body to the service (HadoopAuthFilter always check the doAs param).
How is it fixed?
Knox as a proxy doesn't care about the request params coming from the request body. This patch introduces a wrapper class that only gets the parameters of the  "x-www-form-urlencoded" requests from the query string, ignoring the body altogether.
Tested it manually …
> KNOX-2865 -  Accessing parameters of a x-www-form-urlencoded request consumes the request body

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryMessages.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/monitor/DiscoveryConfigurationFileStore.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/monitor/PollingConfigurationAnalyzer.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/monitor/DiscoveryConfigurationFileStoreTest.java
As described in the corresponding JIRA, Knox should handle the situation when a previously stored CM discovery config file exists, but it's empty. This may prevent the Knox Gateway from starting up.
Added new JUnit test cases to cover this event and ran manual testing:
- Stopped the Knox GW in a cluster where I had descriptors with CM service discovery enabled
- truncted the `$KNOX_GW_DATA_DIR/cm_clusters/xyz.conf` file
- restarted the Knox Gateway
Prior to my changes, the Knox GW did not start; After my fix, everything is working as expected.
> KNOX-2869 - Handling the case when previously persisted CM discovery config is empty

- gateway-test/src/test/java/org/apache/knox/gateway/SimpleDescriptorHandlerFuncTest.java
- gateway-topology-simple/src/main/java/org/apache/knox/gateway/topology/simple/SimpleDescriptorHandler.java
- gateway-topology-simple/src/main/java/org/apache/knox/gateway/topology/simple/SimpleDescriptorMessages.java
The `discovery-type` is defined set to default `"ClouderaManager"` if it's missing, so a discovery is always triggered even if the `discovery-address` is missing.
This patch adds an additional check to see if the url is set or not.
descriptor: test.json
```json
{
"provider-config-ref":"ldap",
"discovery-type": "ClouderaManager",
"discovery-address": "http://localhost/test",
"cluster": "test",
"services":[
{"name":"NAMENODE"},
{"name":"WEBHDFS"}
]
}
```
provider: ldap.json
```json
{
"providers": [
{
"role": "authentication",
"name": "ShiroProvider",
"enabled": "true",
"params": {
"sessionTimeout": "20",
"main.ldapRealm": "org.apache.knox.gateway.shirorealm.KnoxLdapRealm",
"main.ldapContextFactory": "org.apache.knox.gateway.shirorealm.KnoxLdapContextFactory", …
```
> KNOX-2871 - Refine should perform discovery check

- pom.xml
pty4j depends on log4j1. Unfortunately 0.12.x pty4j is compiled with jdk11 so upgrade to a new version is not yet possible. This patch excludes the transitive dependency.
```bash
$ mvn dependency:tree
```
```bash
$ ls dep/*log4j*
dep/log4j-api-2.17.1.jar	dep/log4j-core-2.17.1.jar	dep/log4j-slf4j-impl-2.17.1.jar
```
Opened webshell on admin UI and tested the basic functionality
> KNOX-2879 - pty4j depends on log4j1

- gateway-server/src/main/java/org/apache/knox/gateway/util/KnoxCLI.java
- gateway-server/src/test/java/org/apache/knox/gateway/util/KnoxCLITest.java
- gateway-server/src/test/resources/conf-demo/conf/topologies/sandbox.xml
Added alias service lookup when dealing with LDAP system passwords in a form of `${ALIAS=value}`. 
Added new unit test case to cover this improvement, and ran manual testing:
Added the following parameters in the KnoxSSO topology:
```
<param>
<name>main.ldapRealm.contextFactory.systemUsername</name>
<value>uid=admin,ou=people,dc=hadoop,dc=apache,dc=org</value>
</param>        
<param>
<name>main.ldapRealm.contextFactory.systemPassword</name>
<value>${ALIAS=ldapsystempassword}</value>
</param>
```
Saved `ldapsystempassword`:
```
$ bin/knoxcli.sh create-alias ldapsystempassword --value admin-password --cluster knoxsso
ldapsystempassword has been successfully created.
```
Prior to my changes; I got this:
```
$ bin/knoxcli.sh system-user-auth-test --cluster knoxsso …
```
> KNOX-2881 - KnoxCLI handles aliases when testing LDAP (system) authentication

- gateway-provider-security-hadoopauth/src/main/java/org/apache/knox/gateway/hadoopauth/filter/HadoopAuthFilter.java
`auditService.attachContext(context);` should be called so that the logging information is stored in the thread context.
Tested manually.
> KNOX-2883 Missing attach logging context from HadoopAuthFilter

- gateway-provider-identity-assertion-common/src/main/java/org/apache/knox/gateway/IdentityAsserterMessages.java
- gateway-provider-security-hadoopauth/src/main/java/org/apache/knox/gateway/hadoopauth/HadoopAuthMessages.java
I changed Hadoop Authentication message level from `DEBUG` to `ERROR`.
Re-deployed Knox, made sure to break token impersonation, and confirmed that logs showed the authentication failures on the `ERROR` level:
```
2023-03-20 10:22:48,956 36349731-605c-4b5f-ae05-006cff5feaf0 ERROR knox.gateway (CommonIdentityAssertionFilter.java:doFilter(223)) - Proxy user Authentication failed: org.apache.knox.gateway.util.AuthorizationException: org.apache.hadoop.security.authorize.AuthorizationException: User: admin is not allowed to impersonate bob
```
> KNOX-2889 - Changed message level when logging Hadoop Authentication failure on impersonation paths

- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/dispatch/ConfigurableHADispatch.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/dispatch/i18n/HaDispatchMessages.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/HaServiceConfig.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/impl/DefaultHaServiceConfig.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/impl/HaDescriptorConstants.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/impl/HaDescriptorFactory.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/impl/HaDescriptorManager.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/impl/HaServiceConfigConstants.java
- gateway-provider-ha/src/test/java/org/apache/knox/gateway/ha/dispatch/DefaultHaDispatchTest.java
- gateway-service-webhdfs/src/main/java/org/apache/knox/gateway/hdfs/dispatch/AbstractHdfsHaDispatch.java
- gateway-service-webhdfs/src/main/java/org/apache/knox/gateway/hdfs/dispatch/HdfsHttpClientDispatch.java
- gateway-service-webhdfs/src/test/java/org/apache/knox/gateway/hdfs/dispatch/WebHdfsHaDispatchTest.java
- gateway-test/src/test/java/org/apache/knox/gateway/WebHdfsHaFuncTest.java
Make sure we don't failover for non-idempotent requests such as POST. The request will anyways fail because the input response stream has already been closed so there is no point "retrying" the request. 
Following are the proposed changes:
- Prevent failover for non-idempotent requests in `ConfigurableHADispatch`
- Prevent failover for non-idempotent requests in `AbstractHdfsHaDispatch`, unfortunately `AbstractHdfsHaDispatch` was not using `ConfigurableHADispatch`, with this change it will be extending `ConfigurableHADispatch`.
- Also added is a configuration option for HA Provider `failoverNonIdempotentRequestEnabled` which will enable/disable failover for non-idempotent requests. Default value of `failoverNonIdempotentRequestEnabled` is `false`
e.g.
```
<param>
<name>WEBHDFS</name> …
```
> KNOX-2890 - Prevent non-idempotent requests from failing over

- gateway-shell/src/main/java/org/apache/knox/gateway/shell/ClientContext.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/KnoxSession.java
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/util/ClientTrustStoreHelper.java
- gateway-shell/src/test/java/org/apache/knox/gateway/shell/KnoxSessionTest.java
Until now, the truststore type was hardcoded to `JKS` in KnoxShell when handling trust stores. With this change, 
Added a new unit test case to cover this change and tested manually in a FIPS-enabled cluster where `BCFKS` (Bouncy Castle) truststores were used.
> KNOX-2895 - KnoxShell supports dynamic truststore type when connecting to Knox

- gateway-provider-security-authz-composite/src/main/java/org/apache/knox/gateway/deploy/impl/CompositeAuthzDeploymentContributor.java
NullPointerException is thrown when the referenced provider is invalid in a composite provider.
```
<provider>
<role>authorization</role>
<name>CompositeAuthz</name>
<param>
<name>composite.provider.names</name>
<value>x</value>
</param>
</provider>
```
Manually:
```
2023-03-29 10:19:20,541  ERROR knox.gateway (DeploymentFactory.java:contributeServices(514)) - Failed to contribute service [role=WEBHDFS, name=null]: org.apache.knox.gateway.deploy.DeploymentException: Invalid composite provider name: x role: authorization provider: CompositeAuthz topology: sandbox
org.apache.knox.gateway.deploy.DeploymentException: Invalid composite provider name: x role: authorization provider: CompositeAuthz topology: sandbox
at …
```
> KNOX-2894 - NPE when invalid composite provider name is given

- gateway-server/src/main/java/org/apache/knox/gateway/GatewayMessages.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/topology/monitor/DescriptorsMonitor.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/topology/DefaultTopologyServiceTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/topology/simple/SimpleDescriptorHandlerTest.java
- gateway-test/src/test/java/org/apache/knox/gateway/SimpleDescriptorHandlerFuncTest.java
- gateway-topology-simple/src/main/java/org/apache/knox/gateway/topology/simple/SimpleDescriptorHandler.java
- gateway-topology-simple/src/main/java/org/apache/knox/gateway/topology/simple/SimpleDescriptorMessages.java
DescriptorMonitor should also skip generating topology when it's read only.
Manually.
> KNOX-2893 - Prevent generating topology from read only descriptor

- gateway-topology-hadoop-xml/src/main/java/org/apache/knox/gateway/topology/hadoop/xml/HadoopXmlResourceMessages.java
- gateway-topology-hadoop-xml/src/main/java/org/apache/knox/gateway/topology/hadoop/xml/HadoopXmlResourceMonitor.java
- gateway-topology-hadoop-xml/src/main/java/org/apache/knox/gateway/topology/hadoop/xml/HadoopXmlResourceParser.java
- gateway-topology-hadoop-xml/src/main/java/org/apache/knox/gateway/topology/hadoop/xml/HadoopXmlResourceParserResult.java
- gateway-topology-hadoop-xml/src/test/java/org/apache/knox/gateway/topology/hadoop/xml/HadoopXmlResourceParserTest.java
- gateway-topology-hadoop-xml/src/test/resources/testDelete.xml
1. Enabled hadoop xml resource monitor:
```
<property>
<name>gateway.cloudera.manager.descriptors.monitor.interval</name>
<value>5000</value>
</property>
```
2. Created the following hxr:  conf/descriptors/test.hxr
```
<property>
<name>dt1</name>
<value> remove </value>
</property>
<property>
<name>dt2</name>
<value>
remove
</value>
</property>
<property>
<name>topology3</name>
<value>
discoveryType=ClouderaManager#
discoveryAddress=http://host:123#
discoveryUser=user#
discoveryPasswordAlias=alias#
cluster=Cluster 1#
providerConfigRef=topology1-provider#
app:knoxauth:param1.name=param1.value#
app:admin-ui#
HIVE:url=http://localhost:456#
HIVE:version=1.0#
HIVE:httpclient.connectionTimeout=5m#
</value>
</property>
<property> …
```
> KNOX-2901 - Deleting a descriptor/provider via hadoop xml resource

- gateway-release/home/bin/gateway.sh
Adding restart command.
Normal restart:
```
bin/gateway.sh restart 
$ bin/gateway.sh restart 
Stopping Gateway with PID 54014 succeeded.
Starting Gateway Retry attempts = 5
succeeded with PID 54075.
amagyar-MBP16:test attilamagyar$ 
```
Extra params:
```
$ bin/gateway.sh restart --printEnv --test-gateway-retry-attempts 3 --test-gateway-retry-sleep 2
Stopping Gateway with PID 54075 succeeded.
APP_CONF_DIR = /Users/attilamagyar/development/test/conf
APP_LOG_DIR = /Users/attilamagyar/development/test/logs
APP_DATA_DIR = /Users/attilamagyar/development/test/data
APP_DBG_OPTS = -Xdebug -Xrunjdwp:transport=dt_socket,address=5005,server=y,suspend=n
APP_PID_DIR = /Users/attilamagyar/development/test/pids
APP_JAVA_LIB_PATH = -Djava.library.path=/Users/attilamagyar/development/test/ext/native …
```
> KNOX-2903 - Add restart command to gateway.sh

- gateway-server/src/main/java/org/apache/knox/gateway/GatewayServlet.java
The gateway descriptor importer is not thread safe and it is called from two different threads.
* I verified that calling the importer from multiple threads cause various parser exceptions (see the Jira ticket for more details).
* Tested with multiple knox restarts + curl requests at the same time.
> KNOX-2905 - GatewayDescriptorImporter is not thread safe

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscovery.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryMessages.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ServiceModelGeneratorsHolder.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/monitor/PollingConfigurationAnalyzer.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/monitor/PollingConfigurationAnalyzerTest.java
CM's `PollingConfigurationAnalyzer` ignores events of service types that have no `ServiceModelGenerator` instances to avoid redundant topology redeployment.
Updated JUnit tests and executed comprehensive manual testing in a live CM cluster with lots of services.
> KNOX-2907 - PollingConfigurationAnalyzer ignores services without service model generator

- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/dispatch/ConfigurableHADispatch.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/dispatch/i18n/HaDispatchMessages.java
- gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/DefaultDispatch.java
- gateway-util-common/src/main/java/org/apache/knox/gateway/util/HttpUtils.java
- gateway-util-common/src/test/java/org/apache/knox/gateway/util/HttpUtilsTest.java
By default Knox doesn't fail over in case of non-idempotent requests. In case of a connect exception (connection refused, unknown host, etc), it is safe to failover since the connection hasn't been established yes and the request body was not consumed.
Testet it manually with the following config:
```
<provider>
<role>ha</role>
<name>HaProvider</name>
<param>
<name>HIVE</name>
<value>enabled=true;maxFailoverAttempts=3;failoverSleep=1000</value>
</param>
</provider>
</gateway>
<service>
<url>http://10.255.255.1:1234</url>
<url>http://localhost:1701</url>
</service>
```
> KNOX-2912 - Don't fail over non idempotent requests unless it's a connect exception

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscovery.java
The CORE_SETTINGS service in CM is a special one that does not need to be discovered.
Unit testing and manual testing an a live CM cluster.
> KNOX-2909 - Ignoring CORE_SETTINGS CM service discovery

- gateway-server/src/main/java/org/apache/knox/gateway/GatewayMessages.java
- gateway-server/src/main/java/org/apache/knox/gateway/GatewayServer.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/topology/impl/DefaultTopologyService.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/topology/TopologyService.java
Descriptors are reloaded before topology redeployment at startup. Thus, Knox will have the up-to-date version of the XML topology files generated from the JSON descriptor before it's deployed as a web app in Knox.
Manually tested in a secure (i.e. Kerberos-enabled) cluster with high demand on getting a Knox Token using a topology with HadoopAuth authentication in place. Before my changes, the token generation failed 99% of the time. After the fix went in, all tokens were acquired properly.
> KNOX-2915 - Descriptors are reloaded before topology redeployment at startup

- gateway-server/src/main/java/org/apache/knox/gateway/services/topology/impl/DefaultTopologyService.java
This is a follow-up to #760 which removed the `reloadDescriptors()` call but tests indicated we still need that.
Manual testing.
> KNOX-2915 - We need reloadDescriptors() when starting the monitors

- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/dispatch/ConfigurableHADispatch.java
- gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/dispatch/i18n/HaDispatchMessages.java
- gateway-service-webhdfs/src/main/java/org/apache/knox/gateway/hdfs/dispatch/AbstractHdfsHaDispatch.java
- gateway-util-common/pom.xml
- gateway-util-common/src/main/java/org/apache/knox/gateway/util/HttpUtils.java
- gateway-util-common/src/test/java/org/apache/knox/gateway/util/HttpUtilsTest.java
ConnectionTimeout was missing from the original patch
```xml
<provider>
<role>ha</role>
<name>HaProvider</name>
<param>
<name>HIVE</name>
<value>enabled=true;maxFailoverAttempts=3;failoverSleep=1000</value>
</param>
</provider>
</gateway>
<service>
<url>http://google.com:81</url>
<url>http://localhost:1701</url>
</service>
```
> KNOX-2912 - Don't fail over non idempotent requests unless it's a connect exception - ConnectionTimeout

- gateway-service-knoxsso/src/main/java/org/apache/knox/gateway/service/knoxsso/WebSSOResource.java
- gateway-service-knoxsso/src/test/java/org/apache/knox/gateway/service/knoxsso/WebSSOResourceTest.java
- gateway-spi/src/main/java/org/apache/knox/gateway/SpiGatewayMessages.java
- gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/GatewayDispatchFilter.java
- gateway-util-common/src/main/java/org/apache/knox/gateway/util/RegExUtils.java
Using a malformed URL generates http 500 (MalformedURLException) instead of http 400.
```
curl -k -u admin:admin-password https://localhost:8443/gateway/knoxsso/api/v1/websso?originalUrl=https://localhost:5003gateway/homepage/home/
```
```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 400 Bad Request</title>
</head>
<body><h2>HTTP ERROR 400 Bad Request</h2>
<table>
<tr><th>URI:</th><td>/gateway/knoxsso/api/v1/websso</td></tr>
<tr><th>STATUS:</th><td>400</td></tr>
<tr><th>MESSAGE:</th><td>Bad Request</td></tr>
<tr><th>SERVLET:</th><td>knoxsso-knox-gateway-servlet</td></tr>
</table>
```
> KNOX-2928 - For malformed url should return 400 bad request instead of 500

- gateway-provider-rewrite/src/test/java/org/apache/knox/gateway/filter/rewrite/api/UrlRewriteProcessorTest.java
- gateway-provider-rewrite/src/test/resources/org/apache/knox/gateway/filter/rewrite/api/UrlRewriteProcessorTest/rewrite_escape.xml
- gateway-util-urltemplate/src/main/java/org/apache/knox/gateway/util/urltemplate/Expander.java
Ozone SCM UI uses placeholders such as `{{typestat.portval.toLowerCase()}}` in the HTML which are supposed to be replaced by JavaScript code. However this is the same syntax what knox uses for template variables. If no escaping is used knox will populate the the template variable with an empty string since it has no value.
But escaping `{` didn't work originally in rewrite templates (so `\{x\}` resulted literally `\{x\}`).
sandbox topology:
```xml
<service>
<role>OZONE-SCM</role>
<url>http://localhost:1701</url>
</service>
```
service.xml
```xml
<service role="OZONE-SCM" name="ozone-scm" version="1.2.0">
<metadata>
<type>UI</type>
<context>/ozone-scm/index.html?host={{BACKEND_HOST}}</context>
<shortDesc>OZONE SCM UI</shortDesc>
</metadata>
<routes>
<route path="/ozone-scm/index.html"> …
```
> KNOX-2931 - Some special characters in the rewrite rule cannot be escaped

- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/JWKSResource.java
Getting "knoxtoken/api/v1/jwks.json" generates an invalid json with missing double quotes.
E.g.:
```
{keys=[{kty=RSA, e=AQAB, use=sig, kid=zKJUa4BzKUq_oj69PH3OFeh1vsqrdPgXqNVAes6N-Xg, alg=RS256, n=gGOkOH_WEo3qgzDyY1QDIDb6NURmmc_3W89rI-fvuxVpKW-a-ePiRdRAlKWoTXu-wJ39QePixldzPj3SERmty25YN-PP5YXi798a6QmGtxcFlCtdqjYNFEimD9YJZF9zsBxTKMeLuJ7-k6LGh8ZcxSAykbEng29tEu5xvFdunMpXqWfWnYC1wu10PuuiBkyJ4PZyQ6P8QJHPL9ER9I0NwsxHnS3fnphJ8ZgdjJkINfeuOVwtSOKriMtX6qJ4rKyaZ2n9iEQSOum6CD8BNhbBo5FfrQzc8SENVbiGotCJe4hN6tIWn9OdooCo1PuXhbUEpAH-27QR5wZmuX9PS1GYxQ}]}
```
The problem only happens with a newer nimbus version (9.24), with an old 8.14.1 nimbus, both way work.
```bash
$ curl -vk https://localhost:8443/gateway/homepage/knoxtoken/api/v1/jwks.json
```
```json …
```
> KNOX-2938 - jwks.json doesn't have double quotes which makes json invalid

- gateway-server/src/main/java/org/apache/knox/gateway/util/KnoxCLI.java
- gateway-server/src/main/java/org/apache/knox/gateway/util/TopologyToDescriptor.java
While validating knoxcli.sh convert-topology  found that the cli fails with error saying invalid operation mentioned though provided valid options.
```bash
bash-4.4$ /home/knox/knox/bin/knoxcli.sh convert-topology --path "path/to/topology.xml" --provider-name my-provider.json --descriptor-name my-descriptor.json --topology-name topologyName --output-path "path/to/configs/"
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
KnoxCLI {cmd} [options]
[--help]
[version]
[create-master [--force] [--master mastersecret] [--generate]]
[create-cert [--force] [--hostname h]]
[export-cert [--type PEM|JKS|JCEKS|PKCS12]]
[create-alias aliasname …
```
> KNOX-2936 - knoxcli convert-topology doesn't work with output-path parameter

- gateway-topology-hadoop-xml/src/main/java/org/apache/knox/gateway/topology/hadoop/xml/HadoopXmlResourceParser.java
- gateway-topology-hadoop-xml/src/test/java/org/apache/knox/gateway/topology/hadoop/xml/HadoopXmlResourceParserTest.java
- gateway-topology-hadoop-xml/src/test/resources/testInvalidProvider.xml
If a provider configuration is invalid knox will save invalid file.
Enabled hadoop xml resource monitor:
```xml
<property>
<name>gateway.cloudera.manager.descriptors.monitor.interval</name>
<value>5000</value>
</property>
```
Create conf/descriptors/test.hxr with the following content:
```xml
<property>
<name>providerConfigs:invalid1,invalid2</name>
<value>
authentication;::::::::authentication.name=ShiroProvider#
authentication.param.main.pamRealm=org.apache.knox.gateway.shirorealm.KnoxPamRealm#
authentication.param.main.pamRealm.service=login#
authentication.sessionTimeout=30#
authentication.urls./**=authcBasic#role=identity-assertion#identity-assertion.name=Default#
role=authorization#
authorization.name=XASecurePDPKnox##
authorization..dummy=false
</value>
</property> …
```
> KNOX-2939 - Provider file configured with invalid syntax still gets created with few missing provider contents

- gateway-docker/src/main/resources/docker/Dockerfile
Currently docker image appears to be broken with TLS failures, this appears to be due to the underlying alpine base image. This update upgrades the alpine base image (which also pulls in few security fixes) and adds support for kerberos.
> KNOX-2932 - Fix TLS Ciphers issue and add kerberos support to the docker image

- gateway-service-definitions/src/main/resources/services/ozone-scm/1.2.0/rewrite.xml
- gateway-service-definitions/src/main/resources/services/ozone-scm/1.2.0/service.xml
In this change I added the datanode links correctly to the Ozone SCM UI and integrated the Datanode UI into Knox.
I tested it in a cluster and the datanode links on the SCM UI are redirecting to the correct Datanode UI and the content of the page is loaded correctly as well.
SCM UI when I am hovering over the datanode link it is showing the right URL (bottom of the page):
Datanode UI:
> KNOX-2887 - Add required changes to ozone-scm service definitions to handle DataNode WebUIs

- gateway-server/src/main/java/org/apache/knox/gateway/GatewayServer.java
- gateway-topology-hadoop-xml/src/main/java/org/apache/knox/gateway/topology/hadoop/xml/HadoopXmlResourceMessages.java
- gateway-topology-hadoop-xml/src/main/java/org/apache/knox/gateway/topology/hadoop/xml/HadoopXmlResourceMonitor.java
- gateway-topology-hadoop-xml/src/main/java/org/apache/knox/gateway/topology/hadoop/xml/HadoopXmlResourceParser.java
- gateway-topology-hadoop-xml/src/test/java/org/apache/knox/gateway/topology/hadoop/xml/HadoopXmlResourceParserTest.java
There are some small improvements we need to implement in our Hadoop XML resource parser code:
- better monitoring
- more logs
- removing topology-based descriptor parsing, using "forced" approach instead
- handling .hxr and advanced service discovery properties should happen before monitors are started
Tested in real CM-managed clusters and updated unit tests.
> KNOX-2942 - Miscellaneous HXR parser improvements

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscovery.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryMessages.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryRepository.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryRepositoryTest.java
Fixing NPEs in CM service discovery when it comes to CM's own CORE-SETTINGS service.
Tested in real CM-deployed cluster.
> KNOX-2943 - Handling CORE-SETTINGS service properly

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/impala/ImpalaServiceModelGenerator.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/model/impala/ImpalaServiceModelGeneratorTest.java
Ensure that Impala Daemon's `specialization` role config is stored so that CM service discovery can detect changes in that property.
Tested in a real CM-deployed cluster and updated JUnit tests.
> KNOX-2944 - Honoring the impalad_specialization role configuration

- knox-token-generation-ui/token-generation/app/token-generation.service.ts
As described in the JIRA, the `Target URL` field on the Token Generation UI was incorrect: it contained a double slash which led to 404 errors. This change removes the redundant slash from that URL. For instance:
```
https://localhost:8443//gateway/proxy-token/
```
> KNOX-2945 - Removing redundant slash from target URL on Token Generation UI

- gateway-server/src/main/java/org/apache/knox/gateway/util/KnoxCLI.java
- gateway-server/src/test/java/org/apache/knox/gateway/util/KnoxCLITest.java
Modified a check for the create-alias/create-aliases commands to support values with leading dash.
missing value:
```bash
bin/knoxcli.sh  create-alias a1 --value
``` 
value with dashes
```bash 
bin/knoxcli.sh  create-alias a1 --value ---content---
```
Incorrect usage
```bash 
bin/knoxcli.sh  create-alias a1 --value --generate
```
```bash 
bin/knoxcli.sh  create-alias a1 --value --cluster
```
Batch alias with dashes
```bash
bin/knoxcli.sh  create-aliases --alias --a1-- --value v1 --alias a2 --value --v2--
```
Batch alias missing value
```bash
bin/knoxcli.sh  create-aliases --alias --a1-- --value
```
Batch alias incorrect usage
```bash
bin/knoxcli.sh  create-aliases --alias --a1-- --value --generate
bin/knoxcli.sh  create-aliases --alias --a1-- --value --cluster
```
> KNOX-2940 - knoxcli create-alias/create-aliases command doesn't support values starting with dash

- gateway-topology-hadoop-xml/src/main/java/org/apache/knox/gateway/topology/hadoop/xml/HadoopXmlResourceMessages.java
- gateway-topology-hadoop-xml/src/main/java/org/apache/knox/gateway/topology/hadoop/xml/HadoopXmlResourceParserResult.java
- gateway-topology-hadoop-xml/src/test/java/org/apache/knox/gateway/topology/hadoop/xml/HadoopXmlResourceParserTest.java
- gateway-topology-hadoop-xml/src/test/resources/testDelete2.xml
Validating if shared provider is used by a descriptor before deleting it via hadoop xml resource monitor.
Enabling monitor:
```xml
<property>
<name>gateway.cloudera.manager.descriptors.monitor.interval</name>
<value>5000</value>
</property>
```
hxr file
```xml
<property>
<name>topology3</name>
<value>
discoveryType=ClouderaManager#
discoveryAddress=http://host:123#
discoveryUser=user#
discoveryPasswordAlias=alias#
cluster=Cluster 1#
providerConfigRef=used#
app:knoxauth:param1.name=param1.value#
app:admin-ui#
HIVE:url=http://localhost:456#
HIVE:version=1.0#
HIVE:httpclient.connectionTimeout=5m#
</value>
</property>
<property>
<name>providerConfigs:used,unused</name>
<value>remove</value>
</property>
</configuration>
```
Observed log …
> KNOX-2947 - Deleting provider via hadoop xml resource should check if the provider is used by a descriptor

- gateway-server/src/test/java/org/apache/knox/gateway/topology/simple/SimpleDescriptorFactoryTest.java
- gateway-server/src/test/resources/conf-full/conf/descriptors/test-topology.json
- gateway-test/src/test/java/org/apache/knox/gateway/SimpleDescriptorHandlerFuncTest.java
- gateway-topology-simple/src/main/java/org/apache/knox/gateway/topology/simple/SimpleDescriptor.java
- gateway-topology-simple/src/main/java/org/apache/knox/gateway/topology/simple/SimpleDescriptorHandler.java
- gateway-topology-simple/src/main/java/org/apache/knox/gateway/topology/simple/SimpleDescriptorImpl.java
Implemented the changes described in [KNOX-2948](https://issues.apache.org/jira/browse/KNOX-2948)
Unit testing and manual testing
> KNOX-2948 - encryptQueryString provision should happen if needed

- gateway-topology-hadoop-xml/src/main/java/org/apache/knox/gateway/topology/hadoop/xml/HadoopXmlResourceMonitor.java
The descriptor monitor is supposed to delete a topology file after the corresponding descriptor was deleted. But right after knox restart this doesn't work, because the hadoop xml monitor is started first and the descriptor monitor second.
gateway-site.xml
```xml
<property>
<name>gateway.cloudera.manager.descriptors.monitor.interval</name>
<value>5000</value>
</property>
```
Create a descriptor + topology via hadoop xml resource.
```xml
<property>
<name>topology3</name>
<value>
providerConfigRef=prov#
app:knoxauth:param1.name=param1.value#
app:admin-ui#
HIVE:url=http://localhost:456#
HIVE:version=1.0#
HIVE:httpclient.connectionTimeout=5m#
</value>
</property>
<property>
<name>providerConfigs:prov</name>
<value>any</value>
</property> …
```
> KNOX-2949 - Topology file is not deleted after deleting descriptor via hadoop xml resource

- gateway-provider-rewrite/src/main/java/org/apache/knox/gateway/filter/rewrite/api/CookieScopeServletFilter.java
- gateway-provider-rewrite/src/main/java/org/apache/knox/gateway/filter/rewrite/impl/CookieScopeResponseWrapper.java
- gateway-provider-rewrite/src/test/java/org/apache/knox/gateway/filter/rewrite/impl/CookieScopeResponseWrapperTest.java
- gateway-server/src/main/java/org/apache/knox/gateway/filter/PortMappingHelperHandler.java
- gateway-spi/src/main/java/org/apache/knox/gateway/filter/AbstractGatewayFilter.java
- gateway-spi/src/main/java/org/apache/knox/gateway/i18n/GatewaySpiMessages.java
When cookie path scoping is enabled knox will update the Path attribute of the cookies with `/gateway/topology_name`.
This doesn't work when a service is accessed via the default topology name (there is no `gateway/topology_name` in the url).
Enable cookie scoping + set default topology to sandbox:
```xml
<property>
<name>default.app.topology.name</name>
<value>sandbox</value>
</property>
<property>
<name>gateway.scope.cookies.feature.enabled</name>
</property>
```
Set service url in sandbox.xml:
```xml
<service>
<url>http://localhost:1701</url>
</service>
```
Set up a test http server:
```smalltalk
Teapot on
GET: '/' -> [:req |  
ZnResponse noContent
addCookie: ((ZnCookie name: 'test' value:'val') path: '/original/path'); 
yourself 
];
start. 
``` …
> KNOX-2946 - Cookie Path Scoping doesn't work when using default topology URL

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscovery.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryTest.java
Service discovery was not retried after a SocketTimeoutException.
Unittest.
> KNOX-2951 - During discovery if cm is not reachable and throws SocketException then retry is not happening

- gateway-topology-hadoop-xml/src/main/java/org/apache/knox/gateway/topology/hadoop/xml/HadoopXmlResourceParser.java
- gateway-topology-hadoop-xml/src/test/java/org/apache/knox/gateway/topology/hadoop/xml/HadoopXmlResourceParserTest.java
- gateway-topology-hadoop-xml/src/test/resources/testDescriptor.xml
My previous commit added support for a new boolean variable called `provisionEncryptQueryStringCredential` in a descriptor file. This commit makes it possible to set that new field using a Hadoop XML resource.
Unit testing.
> KNOX-2948 - HXR parser can handle the new 'provisionEncryptQueryStringCredential' boolean field in SimpleDescriptor

- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-service-metadata/src/main/java/org/apache/knox/gateway/service/metadata/KnoxMetadataResource.java
- gateway-service-metadata/src/main/java/org/apache/knox/gateway/service/metadata/TopologyInformation.java
- gateway-service-metadata/src/main/java/org/apache/knox/gateway/service/metadata/TopologyInformationWrapper.java
- gateway-spi-common/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
- knox-homepage-ui/angular.json
- knox-homepage-ui/home/app/app.module.ts
- knox-homepage-ui/home/app/topologies/topology.information.component.html
- knox-homepage-ui/home/app/topologies/topology.information.ts
- knox-homepage-ui/package-lock.json
- knox-homepage-ui/package.json
A new gateway-level configuration, called `knox.homepage.api.services.view.version`, is introduced that lets the end-users switch between the following API services views on the Knox Home page:
- v1: this is the old style list view (this is the default value)
- v2: the new style modal-window view
Manual testing with the following values in `gateway-site.xml`.
1. No `knox.homepage.api.services.view.version`
2. `knox.homepage.api.services.view.version = v1`
3. `knox.homepage.api.services.view.version = v2`
> KNOX-2896 - API services view on Knox Home page can be selected

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryMessages.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/monitor/PollingConfigurationAnalyzer.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/monitor/PollingConfigurationAnalyzerTest.java
After scaling up and down, the service list in the topologies should be regenerated. For example, if the user adds a new service component to a new host then the new URL should be added to the topology. Similarly if a service component is removed from a host, the URL should be deleted.
One small problem is that after adding a component, the new URL will appear in the topology right after the monitor picks up the change, even if the component is not yet started. Failover will handle this scenario. Plus this is not a new thing, since stopping a component has the same effect. But feel free to share you concerns regrading this.
1. Ensure that cluster config monitor is turned on in gateway-site.xml
2. Add a new component (I tested it with KAFKA_BROKER) to a host
3. Wait for the cluster config …
> KNOX-2959 - Auto discovery to support scaling scenarios

- gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/DefaultDispatch.java
Incoming Headers are not going through when using OPTIONS type HTTP requests.
Sandbox topology
```xml
<service>
<url>http://localhost:1701/headers</url>
<param>
<name>replayBufferSize</name>
<value>8</value>
</param>
</service>
```
Test HTTP server that logs out the received headers:
```smalltalk
Teapot on
OPTIONS: '/headers' -> [:req | 
req headersDo: [:n :v | Transcript show: ('Received: ', n, '=', v); cr ]. 'OK' ];
start. 
```
```
$ curl -X OPTIONS -u admin:admin-password -H 'My-Header: My-Value' -vk https://localhost:8443/gateway/sandbox/hive
```
Transcript content:
```
Received: X-Forwarded-Proto=https
Received: X-Forwarded-Port=8443
Received: X-Forwarded-Host=localhost:8443
Received: X-Forwarded-Server=localhost
Received: X-Forwarded-Context=/gateway/sandbox …
```
> KNOX-2960 - DefaultDispatch doesn't forward inbound request headers in case of requestType=OPTIONS

- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/TokenIDAsHTTPBasicCredsFederationFilterTest.java
- gateway-release/home/conf/gateway-site.xml
- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/DefaultTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/JDBCTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/TokenStateDatabase.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/TokenStateServiceMessages.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/JDBCTokenStateServiceTest.java
- gateway-service-knoxtoken/pom.xml
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceMessages.java
- gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
- gateway-service-session/src/main/java/org/apache/knox/gateway/service/session/SessionInformation.java
- gateway-service-session/src/main/java/org/apache/knox/gateway/service/session/SessionResource.java
- gateway-spi-common/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/TokenStateService.java
- knox-token-management-ui/token-management/app/app.module.ts
- knox-token-management-ui/token-management/app/knox.token.ts
- knox-token-management-ui/token-management/app/session.information.ts
- knox-token-management-ui/token-management/app/token.management.component.html
- knox-token-management-ui/token-management/app/token.management.component.ts
- knox-token-management-ui/token-management/app/token.management.service.ts
In phase II, the following features are implemented:
- Pre-configured users can see all tokens on the Token Management page.
- End-users can execute batch operations on selected Knox Tokens.
- Allowing end-users to show/hide previously disabled KnoxSSO Cookies on the Token Management page.
There is a new Gateway-level configuration that controls who can see all tokens on the Token Management UI:
```
<property>
<name>gateway.knox.token.management.users.can.see.all.tokens</name>
<value>admin</value>
<description>A comma-separated list of user names who can see all tokens on the Token Management page</description>
</property>
```
OOTB, the `admin` user acts as the superuser who has the power of controlling tokens created for others. The rest of the users can only see their own tokens only …
> KNOX-2961 - Knox SSO cookie Invalidation - Phase II

- gateway-release/home/conf/gateway-site.xml
- gateway-server/src/main/java/org/apache/knox/gateway/GatewayServer.java
- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-spi-common/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
- knox-homepage-ui/home/app/homepage.service.ts
- knox-token-generation-ui/token-generation/app/token-generation.service.ts
- knox-token-management-ui/token-management/app/token.management.component.ts
- knox-token-management-ui/token-management/app/token.management.service.ts
With this change, our end-users have a way to define custom application path aliases next to the ones we have OOTB to reach certain apps, UIs.
I added the following `gateway-site.xml` property(ies) to support this feature:
```
<property>
<name>gateway.application.path.alias.$original-application-path-to-match</name>
<value>$comma-separated-list-of-alias-names</value>
</property>
```
where
- $original-application-path-to-match indicates the existing application path we would like to have an alias for
- $comma-separated-list-of-alias-names marks the list of alias names to register (pointing to the same application as the original path above), separated by a comma if there are more
For instance:
```
<property>
<name>gateway.application.path.alias.token-generation</name> …
```
> KNOX-2950 - Handling application path aliases

- gateway-service-knoxsso/src/main/java/org/apache/knox/gateway/service/knoxsso/KnoxSSOMessages.java
- gateway-service-knoxsso/src/main/java/org/apache/knox/gateway/service/knoxsso/WebSSOResource.java
Better logging experience in KnoxSSO Cookie management.
Deployed Knox, logged in to the Knox Home page and checked logs:
```
2023-10-10 13:03:51,102 f268dade-b9ba-425d-b0d6-d3e97d6b9243 INFO  knox.gateway (CookieUtils.java:getCookiesForName(46)) - Unable to find cookie with name: hadoop-jwt
...
2023-10-10 13:04:01,683 d4e582d3-8b08-46cd-8540-60315b08a819 DEBUG service.knoxsso (WebSSOResource.java:addJWTHadoopCookie(402)) - Adding the following JWT token as a cookie: eyJraW...VHcD2Q
2023-10-10 13:04:01,684 d4e582d3-8b08-46cd-8540-60315b08a819 INFO  service.knoxsso (WebSSOResource.java:addJWTHadoopCookie(428)) - JWT cookie eyJraW...VHcD2Q successfully added.
```
> KNOX-2966 - Improved logging around KnoxSSO cookie management

- gateway-server/src/main/java/org/apache/knox/gateway/services/topology/impl/GatewayStatusService.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/topology/impl/GatewayStatusServiceTest.java
- gateway-service-health/src/main/java/org/apache/knox/gateway/service/health/PingResource.java
The gateway-status requests returns the list of pending topologies.
Added health topology:
```xml
<topology>
<gateway>
<provider>
<role>authentication</role>
<name>Anonymous</name>
</provider>
</gateway>
<service>
<role>HEALTH</role>
</service>
</topology>
```
and 2 invalid descriptors: test.json and test2.json
```
$ curl -vk https://localhost:8443/gateway/health/v1/gateway-status
```
Output
```
< HTTP/1.1 200 OK
< Date: Mon, 09 Oct 2023 10:36:50 GMT
< Cache-Control: must-revalidate,no-cache,no-store
< Content-Type: text/plain;charset=iso-8859-1
< Content-Length: 23
< 
PENDING: [test2, test]
```
> KNOX-2962 - Knox readiness check gateway-status endpoint should return the list of topologies for which it is waiting for

- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
Fixed a minor bug that prevented an otherwise enabled KnoxSSO Cookie's `enabled flag` set to true in a batch operation.
> KNOX-2968 - Batch token enable action should succeed even if enabled KnoxSSO cookies are selected

- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
- gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
Modified the logic used for calculating the token limit per user in a way such that it ignores the previously generated KnoxSSO cookies. That is, a user can have as many KnoxSSO cookies as they want, but regular tokens are still limited.
Updated JUnit tests and executed manual testing:
1. Kept the default token limit per user = 10
2. I had three different sessions in different browsers as the `admin` user
3. Disabled one session
4. In one of the remaining sessions generated 10 tokens successfully (please note even the 8th, 9th, and 10th tokens were generated despite the fact I already had 3 KnoxSSO tokens for the same user)
5. The 11th token generation failed as expected
> KNOX-2969 - KnoxSSO Cookies should be ignored while calculating token limit per user

- knox-token-management-ui/token-management/app/token.management.component.html
CSS fix of word wrapping in the `Comment` and `Additional Metadata` columns on the Token Management UI. 
Manually tested.
Before my change:
After my change:
> KNOX-2971 - Applying word wrapping in the comment and metadata columns on the Token Management UI

- gateway-service-knoxsso/src/main/java/org/apache/knox/gateway/service/knoxsso/WebSSOResource.java
- gateway-service-knoxsso/src/test/java/org/apache/knox/gateway/service/knoxsso/WebSSOResourceTest.java
Fix redirect URI when host and port are query params of originalUrl
This patch was tested locally and on an cluster with SAML.
> KNOX-2973 - Fix redirect URI when host and port are query params of originalUrl

- gateway-applications/src/main/resources/applications/knoxauth/app/logout.jsp
- gateway-service-session/src/main/java/org/apache/knox/gateway/service/session/SessionResource.java
Updated the `api/v1/sessioninfo` REST API endpoint in `SessionResouce` in a way such that it can generate a `logoutPageUrl` (used by the application logout link in Knox's logout flow) with `profile` and `topologies` query parameters in the `originalUrl` part.
Using `curl`:
1. Without any query params:
```
$ curl -ik --cookie "hadoop-jwt=eyJra...APA" -X GET "https://localhost:8443/gateway/homepage/session/api/v1/sessioninfo"
Date: Fri, 20 Oct 2023 10:47:30 GMT
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1;mode=block
Content-Type: application/xml
Content-Length: 574
<?xml version="1.0" encoding="UTF-8"?>
<sessioninfo>
<user>admin</user>
<logoutUrl>https://localhost:8443/gateway/homepage/knoxssout/api/v1/webssout</logoutUrl> …
```
> KNOX-2972 - Session resource can generate application logout URL with profile/topologies query parameters

- gateway-server/src/main/java/org/apache/knox/gateway/GatewayServer.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/topology/impl/GatewayStatusService.java
As described in KNOX-2977, from now on the `conf/descriptors` folder is also considered at topology mapping creating time.
Manually tested on a live cluster with WebHDFS and different port mappings.
> KNOX-2977 - The 'conf/descriptors' folder should be considered too when registering topology port mappings

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscovery.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryRepository.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryRepositoryTest.java
When a config change is detected by the Polling Config Analyzer then then the cache used by the service discovery will be cleared. If this happens when discovery is in progress then a NullPointerException will happen.
```java
private ServiceDetails getServiceDetails(ServiceDiscoveryConfig serviceDiscoveryConfig, ApiService service) {
return getClusterServices(serviceDiscoveryConfig).getIfPresent(service); // <= NPE
}
```
```java
@Override
public void onConfigurationChange(String source, String clusterName) {
log.clearServiceDiscoveryRepository();
repository.clear(); // this will cause the NPE
}
```
This was observed on a live cluster when certain cluster properties was changed during knox startup.
- unit test
> KNOX-2978 - Race condition between Service Discovery and Polling Config Analyzer

- gateway-service-definitions/src/main/resources/services/cm-api/1.0.0/service.xml
- gateway-service-definitions/src/main/resources/services/oozie/5.0.0/service.xml
- gateway-service-definitions/src/main/resources/services/webhdfs/2.4.0/service.xml
- gateway-service-definitions/src/main/resources/services/yarn-rm/2.5.0/service.xml
- gateway-service-metadata/src/main/java/org/apache/knox/gateway/service/metadata/ServiceModel.java
- gateway-service-metadata/src/test/java/org/apache/knox/gateway/service/metadata/ServiceModelTest.java
Testing uncovered some API samples in the existing service definition files that needed to be fixed.
Additionally, a general improvement is implemented that adds the missing slash at the beginning of the path element if it was missing from the service definition sample.
Added unit tests and confirmed that API samples are actually changed on the UI:
To see the new-style API service dialog it's essential that you set the following property in `gateway-site.xml`:
```
<property>
<name>knox.homepage.api.services.view.version</name>
<value>v2</value>
</property>
```
> KNOX-2958 - Fixed API samples for certain services

- gateway-applications/src/main/resources/applications/knoxauth/app/logout.jsp
- knox-homepage-ui/home/app/homepage.service.ts
The redundant `refresh` query parameter is no longer added at the tail of the application logout link on Knox's logout page.
Manually tested with and without the `logoutProfile` and `logoutTopologies` session resource attributes.
> KNOX-2979 - Removed redundant 'refresh' query parameter from the application logout link after originalUrl

- knox-token-management-ui/token-management/app/token.management.component.html
Applying word wrapping on the following columns in addition to metadata, comment:
- token id
- issued
- expires
- username
Manually tested by resizing my Chrome window:
> KNOX-2980 - Applying word wrapping in various columns that can have 'long' content.

- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResourceV2.java
- knox-token-generation-ui/token-generation/app/token-generation.service.ts
- knox-token-management-ui/token-management/app/token.management.service.ts
Two major changes:
- introduced v2 in the KNOXTOKEN service REST API enpoints
- deprecated `renew` and `revoke` in v1
Manually tested the Token Generation and Token Management UIs (create, enable/disable, revoke tokens) and confirmed that `renew` and `revoke` work with different HTTP methods using different versions:
```
$ curl -iku admin:admin-password -d $JWT -X POST https://localhost:8443/gateway/sandbox/knoxtoken/api/v1/token/renew
Date: Thu, 09 Nov 2023 10:31:46 GMT
Set-Cookie: KNOXSESSIONID=node0f1emmld2e9jl1tpkwa87qmn800.node0; Path=/gateway/sandbox; Secure; HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Set-Cookie: rememberMe=deleteMe; Path=/gateway/sandbox; Max-Age=0; Expires=Wed, 08-Nov-2023 10:31:46 GMT; SameSite=lax
Content-Type: application/json …
```
> KNOX-2985 - Introduced KNOXTOKEN API v2 and deprecated v1 methods

- gateway-admin-ui/admin-ui/app/app.module.ts
- gateway-admin-ui/admin-ui/app/sessionInformation/session.information.component.html
- gateway-admin-ui/admin-ui/app/sessionInformation/session.information.component.ts
- gateway-admin-ui/admin-ui/app/sessionInformation/session.information.service.ts
- gateway-admin-ui/admin-ui/app/sessionInformation/session.information.ts
- gateway-admin-ui/admin-ui/index.html
- knox-token-generation-ui/token-generation/app/session.information.component.html
- knox-token-generation-ui/token-generation/app/session.information.component.ts
- knox-token-generation-ui/token-generation/app/token-generation.models.ts
- knox-token-generation-ui/token-generation/app/token-generation.service.ts
- knox-token-generation-ui/token-generation/index.html
- knox-token-management-ui/token-management/app/app.module.ts
- knox-token-management-ui/token-management/app/session.information.component.html
- knox-token-management-ui/token-management/app/session.information.component.ts
Added information about the logged-in user on Knox UIs just like we had on the Knox Home page.
> KNOX-2929 - Logged in user is shown on Knox UIs

- gateway-server/src/main/java/org/apache/knox/gateway/GatewayMessages.java
This is a very small, but even more important change because it helps us a lot during the troubleshooting of service discovery or simple descriptor handler issues: related error stack traces are displayed on `INFO` level.
```
2023-12-15 16:57:35,494  ERROR knox.gateway (DescriptorsMonitor.java:onFileChange(123)) - An error occurred while processing dt.json : java.lang.IllegalArgumentException: Unresolved provider configuration reference: kerberos-providers
java.lang.IllegalArgumentException: Unresolved provider configuration reference: kerberos-providers
at org.apache.knox.gateway.topology.simple.SimpleDescriptorHandler.handleProviderConfiguration(SimpleDescriptorHandler.java:266) ~[gateway-topology-simple-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
at …
```
> KNOX-2993 - Logging error stack trace at INFO level when failed to parse a descriptor

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryMessages.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/monitor/PollingConfigurationAnalyzer.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/monitor/PollingConfigurationAnalyzerTest.java
Actual cluster configuration change monitoring should not happen until the Knox Gateway is fully up and running and all the topologies are deployed.
Updated existing unit tests and added a new test case to cover this new functionality. Apart from this, I also conducted an E2E test round on a live CM cluster (I set the `gateway.cluster.config.monitor.cm.interval` to `5` to make sure we see config monitor attempts every 5 seconds).
After I restarted Knox I confirmed the feature is working:
```
2024-01-03 12:55:15,551  INFO  knox.gateway (GatewayServer.java:startGateway(389)) - Starting gateway...
...
2024-01-03 12:55:15,607  INFO  discovery.cm (PollingConfigurationAnalyzer.java:run(203)) - Started ClouderaManager cluster configuration monitor (checking every 5 seconds)
2024-01-03 …
```
> KNOX-2994 - PollingConfigurationAnalyzer starts after the Knox GW is up and running

- gateway-spi/src/main/java/org/apache/knox/gateway/deploy/ServiceDeploymentContributorBase.java
- gateway-spi/src/main/java/org/apache/knox/gateway/topology/Topology.java
- gateway-spi/src/test/java/org/apache/knox/gateway/topology/TopologyTest.java
When there are multiple providers in one topology, knox gets the first one, without checking if it's enabled or disabled.
Therefore having 2 identity-assertion providers where the first is disabled and the 2nd is enabled, doesn't work.
We should find the first enabled provider instead.
1st provider enabled
```xml
<provider>
<role>identity-assertion</role>
<name>SwitchCase</name>
<param>
<name>principal.case</name>
<value>upper</value>
</param>
<param> 
<name>group.principal.case</name>
<value>upper</value>
</param>    
</provider>
```
2nd provider disabled:
```xml
<provider>
<role>identity-assertion</role>
<name>Regex</name>
<enabled>false</enabled>
<param>
<name>input</name>
<value>ad(.*)</value>
</param>  
<param>   
<name>output</name>
<value>{1}max</value> …
```
> KNOX-2982 - Having one disabled one enabled identity-assertion providers doesn't work

- gateway-server/src/test/java/org/apache/knox/gateway/topology/simple/SimpleDescriptorHandlerTest.java
- gateway-server/src/test/resources/conf-full/conf/shared-providers/test-providers.json
- gateway-topology-simple/src/main/java/org/apache/knox/gateway/topology/simple/SimpleDescriptorHandler.java
As described in [KNOX-3001](https://issues.apache.org/jira/browse/KNOX-3001), if the shared provider, descriptor, service, or application originally contains XML-escaped values, Knox will persist topologies in a way such that those already escaped values become doubly-escaped.
To avoid this issue the following was implemented:
- unescape the value first
- escape the unescaped result
I updated existing JUnit tests where a shared provider config contains both a single `&` and an escaped `&amp;` in its .json file. The test then proves the generated XML is parsed properly and contains the desired `&` value in the SAX document.
I also ran integration tests with the following shared-provider and descriptor files:
```
$ cat conf/shared-providers/smolnar.json 
{
"providers" : [ {
"role" : …
```
> KNOX-3001 - Avoid double XML-escaping during topology persistence from descriptors

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryMessages.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/DiscoveryApiClient.java
- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-spi-common/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
Adding configurable connect, read and write timeout parameters to CM's discovery client.
gateway-site.xml
```xml
<property>
<name>gateway.cloudera.manager.service.discovery.connect.timeout.ms</name>
<value>15000</value>
</property>
<property>
<name>gateway.cloudera.manager.service.discovery.read.timeout.ms</name>
<value>16000</value>
</property>
<property>
<name>gateway.cloudera.manager.service.discovery.write.timeout.ms</name>
<value>17000</value>
</property>
```    
```bash
cat conf/descriptors/test.json
{
"name" : "cdp-proxy",
"discovery-type" : "ClouderaManager",
"discovery-address" : "http://HOST:7180",
"discovery-user" : "test",
"discovery-pwd-alias" : "pass",
"provider-config-ref" : "default-providers",
"read-only" : true,
"cluster" : "Cluster 1",
"services" : [ {
"name" : …
```
> KNOX-3000 - Add configurable socket / read timeout parameter to discovery client

- gateway-docker/src/main/resources/docker/Dockerfile
- gateway-docker/src/main/resources/docker/gateway-entrypoint.sh
This PR adds public AWS certs to Knox truststore and adds a few parameters that can be configured on the fly 
- KNOX_MASTER_SECRET - (optional) master secret for knox in a file, default value is 'knox'
- MASTER_SECRET - (optional) master secret for knox, value not a file location , default value is 'knox'
- KNOX_CERT - (optional) the location of a public PEM-encoded certificate file for the gateway
- KNOX_KEY - (optional) the location of a private PEM-encoded key file for the gateway
- KEYSTORE_PASSWORD_FILE - (optional) the location of a file containing the passphrase to use for generated keystores, default randomly generated base 64 string
- ALIAS_PASSPHRASE - (optional) Keystore signing password
- CA_FILE - (optional) the location of a file containing the PEM-encoded CA bundle for Knox …
> KNOX-2999 - [Docker] Add public CA to Knox trust store

- gateway-service-metadata/src/main/java/org/apache/knox/gateway/service/metadata/KnoxMetadataResource.java
- gateway-service-metadata/src/main/java/org/apache/knox/gateway/service/metadata/ServiceModel.java
- gateway-service-metadata/src/test/java/org/apache/knox/gateway/service/metadata/ServiceModelTest.java
- knox-homepage-ui/home/app/topologies/service.ts
- knox-homepage-ui/home/app/topologies/topology.information.component.css
- knox-homepage-ui/home/app/topologies/topology.information.component.html
- knox-homepage-ui/home/app/topologies/topology.information.component.ts
There are two important pieces of this PR:
1. the `getTopologies` REST API endpoint in `KnoxMetadataResource` was modified in a way such that it includes only one item per service role (IMPALAUI, WEBHDFS, HUE, HBASEUI, etc...) with a list of service URLs from now on. In previous versions it was different: the response had `N` items per service role with a unique service URL.
```
$ curl -H 'Accept: application/json' -iku admin:admin-password https://localhost:8443/gateway/sandbox/api/v1/metadata/topologies?name=sandbox
Date: Wed, 31 Jan 2024 09:32:09 GMT
Set-Cookie: KNOXSESSIONID=node0pafwbogn50gjy2zjiaxuchwx0.node0; Path=/gateway/sandbox; Secure; HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Set-Cookie: rememberMe=deleteMe; Path=/gateway/sandbox; Max-Age=0; Expires=Tue, …
```
> KNOX-3003 - Services with more than one serviceUrl metadata are grouped on the Knox Home page

- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/JWTMessages.java
- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/AbstractJWTFilter.java
- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/SSOCookieFederationFilter.java
- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/AbstractJWTFilterTest.java
- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/SSOCookieProviderTest.java
- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/TestFilterConfig.java
- gateway-service-knoxsso/src/main/java/org/apache/knox/gateway/service/knoxsso/WebSSOResource.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/TokenMetadata.java
In this change the recently added KnoxSSO Cookie invalidation feature is extended like this:
- new token metadata is saved for KnoxSSO cookie called `lastUsedAt`
- the value of this token metadata is updated upon every successful KnoxSSO cookie verification. Therefore UI services that use KnoxSSO go through token verification every time they contact the Knox Gateway. When that verification succeeds, we know the KnoxSSO cookie was in use so that we can actualize the value.
- another new config was introduced on the topology level: `sso.idle.timeout.seconds`. The default value of this config is `-1`, meaning the idleness check should be ignored when verifying KnoxSSO cookies. This parameter should be added in the `SSOCookieProvider` federation filter block to enable the idle timeout …
> KNOX-3005 - Implemented KnoxSSO idle timeout

- gateway-provider-security-shiro/pom.xml
- gateway-provider-security-shiro/src/main/java/org/apache/knox/gateway/shirorealm/KnoxPamRealm.java
- pom.xml
PAM module returns garbage group names due to a thread safety problem:
```
2024-02-07 12:41:44,954 23da5c8b-2664-4c94-a356-fd569eff930c INFO  knox.gateway (KnoxPamRealm.java:doGetAuthorizationInfo(129)) - Computed roles/groups: [nifire39965:] for principal: knoxui
2024-02-07 12:41:44,956 6778ee4d-f655-4d09-b111-2e28ca3f1d4b INFO  knox.gateway (KnoxPamRealm.java:doGetAuthorizationInfo(129)) - Computed roles/groups: [mapredx] for principal: knoxui
2024-02-07 12:41:44,957 9829bbe7-ff7f-4c87-9a65-cbc589be7583 INFO  knox.gateway (KnoxPamRealm.java:doGetAuthorizationInfo(129)) - Computed roles/groups: [mail:x:12] for principal: knoxui
2024-02-07 12:42:03,082 a02943fc-2d6b-402f-b938-041fb64eee0a INFO  knox.gateway (KnoxPamRealm.java:doGetAuthorizationInfo(129)) - Computed roles/groups: [cdro] …
```
> KNOX-3006 - PAM module occasionally generates garbage group names

- gateway-release/home/conf/topologies/manager.xml
Adds KNOX-SESSION to manager.xml for out of the box functionality of the Admin UI and displaying the logged in username.
Manually tested the Admin UI and ran all unit tests.
> KNOX-3009 - KNOX-SESSION missing from Manager Topology and Admin UI

- gateway-server/src/main/java/org/apache/knox/gateway/util/DescriptorGenerator.java
- gateway-server/src/main/java/org/apache/knox/gateway/util/KnoxCLI.java
- gateway-server/src/main/java/org/apache/knox/gateway/util/ServiceUrls.java
- gateway-server/src/test/java/org/apache/knox/gateway/util/DescriptorGeneratorTest.java
Adding a command to knoxcli that can generate a topology descriptor from a list of URLs.
Usage:
```
Create Knox topology descriptor file for one service
Options are as follows: 
--service-urls-file (required) path to a text file containing service urls 
--service-name (required) the name of the service, such as WEBHDFS, IMPALAUI or HIVE 
--descriptor-name (required) name of descriptor to be created 
--provider-name (required) name of the referenced shared provider 
--output-dir (optional) output directory to save the descriptor file 
--force (optional) force rewriting of existing files, if not used, command will fail when the configs files with same name 
already exist. 
--param service-param-name1 service-param-value1
--param service-param-nameN service-param-valueN
```
```bash
cat …
```
> KNOX-3002 - KnoxCLI command for generating descriptor for a role type from a list of hosts

- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-spi-common/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
- gateway-spi/src/main/java/org/apache/knox/gateway/SpiGatewayMessages.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
- gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/DefaultHttpClientFactory.java
- gateway-spi/src/test/java/org/apache/knox/gateway/dispatch/DefaultHttpClientFactoryTest.java
With the default cookie spec policy, the apache http client rejects cookies if their expiration date doesn't follow the expected format (EEE, dd-MMM-yy HH:mm:ss z).
For example a cookie with an expiration = `Sun, 06 Nov 1994 08:49:37 GMT` is rejected by default.
If the cookiespec is set to 'standard' the cookie will be accepted.
```smalltalk
Teapot on
GET: '/' -> [:req |  ZnResponse noContent
addCookie: ((ZnCookie name: 'test' value:'val') expires: 'Sun, 06 Nov 1994 08:49:37 GMT'; yourself); 
addCookie: ((ZnCookie name: 'test2' value:'val') expiresTimeStamp: DateAndTime now; yourself);     	
addCookie: ((ZnCookie name: 'test3' value:'val') expires: 'Wed, 14-Feb-2024 09:23:27 GMT'; yourself);     	    	
yourself ];
start. 
```
1.
```xml
<property>
<name>gateway.httpclient.cookieSpec</name> …
```
> KNOX-3007 - Make http client cookie spec parameter configurable

- gateway-release/home/conf/topologies/manager.xml
Accidentally added the `KNOX-SESSION` service twice after it was added by #843 . Therefore I'm removing the new addition with this PR.
Verified on FS.
> KNOX-3008 - Removing KNOX-SESSION as it was added by KNOX-3009

- pom.xml
Before my change, any time I ran a KnoxCLI command I saw the following warning messages wrt. there are multiple SLF4J bindings on the classpath:
```
$ bin/knoxcli.sh create-master --master gateway
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/sandormolnar/test/knoxGateway/bin/../dep/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/sandormolnar/test/knoxGateway/bin/../dep/logback-classic-1.2.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Master secret has been persisted to disk.
```
I also confirmed that we have had …
> KNOX-3011 - Excluded logback-[core|classic] as transitive dependencies pulled in by Zookeeper

- gateway-provider-rewrite/src/main/java/org/apache/knox/gateway/filter/rewrite/impl/json/JsonFilterReader.java
- gateway-provider-rewrite/src/test/java/org/apache/knox/gateway/filter/rewrite/impl/json/JsonFilterReaderTest.java
Implemented the changes I listed in [KNOX-2995](https://issues.apache.org/jira/browse/KNOX-2995):
- Solve the problem of page parsing failure when Json returns NaN value.
> Added JsonReadFeature.ALLOW_NON_NUMERIC_NUMBERS.mappedFeature() to support this feature
I click on the page with return json and the content of Resopnse is empty. like this :
Checking the gateway.log log shows the following error message.
The display results after my repair are as follows：
I have added test cases. You can run the test cases to see if they are successful.
Run JsonFilterReaderTest.testNaN() function. 
Or look at the actual problems I encountered above to test.
> KNOX-2995 - Support json parsing NaN values

- gateway-service-definitions/src/main/resources/services/ozone-scm/1.2.0/rewrite.xml
- gateway-service-definitions/src/main/resources/services/ozone-scm/1.4.0/rewrite.xml
- gateway-service-definitions/src/main/resources/services/ozone-scm/1.4.0/service.xml
In Ozone in [HDDS-9732](https://issues.apache.org/jira/browse/HDDS-9732) the datanode links were changed on the SCM UI. We need to reflect these changes in Knox. As Ozone is 1.4.0 since the last changes in Knox, I added a new folder for the `ozone-scm` service with the changes and left the 1.2.0 folder as it was. 
Tested the changes in a cluster. Before my changes it was redirecting to the DN UI without Knox, so the link was not rewritten:
With the changes Knox rewrites the link to the correct url:
> KNOX-3012 - Fix the DN links on the Ozone SCM UI

- gateway-service-definitions/src/main/resources/services/hdfsui/3.0.0/rewrite.xml
Add proxy for hdfs UI network topology, Clicking the hdfs UI network topology proxy failed, the page should be displayed and should not be Error.
issues: [knox-2996](https://issues.apache.org/jira/browse/KNOX-2996)
> KNOX-2996 - Add proxy for hdfs UI network topology

- gateway-service-definitions/src/main/resources/services/yarnui/2.7.0/rewrite.xml
- YARNUI/yarn/outbound/node3 rule rewrites the https schemes to http
- To fix the issue we skip this rule in case if the schema is https
- unit tests
- manually deployed a cluster and verified the url stays https
- run MapReduce job
- after that i checked the ResourceManager UI behind Knox
- verified the scheme stayed https which links to the NodeManager (befor the change it was http cause the node3 rule)
> KNOX-3013 - Knox redirecting Yarn Node Manager URLs to http instead of https

- gateway-provider-security-authz-path-acls/pom.xml
- gateway-provider-security-authz-path-acls/src/main/java/org/apache/knox/gateway/deploy/impl/PathAclsAuthzDeploymentContributor.java
- gateway-provider-security-authz-path-acls/src/main/java/org/apache/knox/gateway/filter/AclsAuthorizationResources.java
- gateway-provider-security-authz-path-acls/src/main/java/org/apache/knox/gateway/filter/InvalidACLException.java
- gateway-provider-security-authz-path-acls/src/main/java/org/apache/knox/gateway/filter/PathAclParser.java
- gateway-provider-security-authz-path-acls/src/main/java/org/apache/knox/gateway/filter/PathAclsAuthorizationFilter.java
- gateway-provider-security-authz-path-acls/src/main/java/org/apache/knox/gateway/filter/PathAclsAuthorizationMessages.java
- gateway-provider-security-authz-path-acls/src/main/resources/META-INF/services/org.apache.knox.gateway.deploy.ProviderDeploymentContributor
- gateway-provider-security-authz-path-acls/src/test/java/org/apache/knox/gateway/filter/PathAclParserTest.java
- gateway-provider-security-authz-path-acls/src/test/java/org/apache/knox/gateway/filter/PathAclsAuthzFilterTest.java
- gateway-release/pom.xml
- pom.xml
This change proposes a new authorization provider `PathAclsAuthz` that authorized based on request path. Authorization is done based on path matching similar to rewrite rules.
Format is very similar to  AclsAuthz provider with an addition of path. The format is 
`{path};{users};{groups}:{ips}`
One important thing to note here is that the path is not plural, there has to be one and only one path defined. 
In case one wants multiple paths they can define multiple rules with rule name as a parameter e.g. 
KNOXTOKEN.{rule_name}.path.acl
_These are special cases for rule names_
This rule will be applied to ALL services defined in the topology
```
<param>
<name>path.acl</name>
<value>https://*:*/**/knoxtoken/api/**;admin;*;*</value> 
</param>
```
This rule will be applied to only the service …
> KNOX-2998 - Path based authorization provider

- knox-token-generation-ui/token-generation/app/token-generation.component.html
- knox-token-generation-ui/token-generation/app/token-generation.service.ts
Two changes on the `Token Generation UI`:
- if the `homepage` topology is configured with `Unlimited token lifetime`, the lifetime adjustment popup will not shown. The logic was there before, this was a casting issue between strings and numbers in the JS code.
- added an `exclamation` icon to better emphasize the `Unlimited lifetime` setting on the UI.
Manually tested and confirmed that the popup is no longer displayed when creating a 1-year token with `Unlimited lifetime` settings. The new exclamation mark is shown as expected (tested with and without the `-1` TTL).
> KNOX-3017 - Avoid showing lifetime adjustment popup when TTL is set to -1

- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/DefaultTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/TokenStateDatabase.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/JDBCTokenStateServiceTest.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/KnoxToken.java
- knox-token-generation-ui/token-generation/app/token-generation.service.ts
- knox-token-management-ui/token-management/app/token.management.component.ts
The `Token Management` and `Token Generation` UIs are updated in a way such that they display `Never expires` in case a token never expires (that is, if the token's expiration is set to a negative number).
Moreover, the automated token eviction logic is modified to never remove those tokens from the underlying token state backend.
Updated existing unit tests to cover the token eviction logic change and ran manual testing on the UI.
> KNOX-3018 - Tokens that never expire should not be evicted automatically and their expiration should be displayed properly

- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/AbstractJWTFilter.java
- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/JWTFederationFilter.java
- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/ClientIdAndClientSecretFederationFilterTest.java
Adding support for integrations to Knox proxied services and APIs via OAuth style cllient credentials flow. This allows an integration that is provided a CLIENT_ID and CLIENT_SECRET to authenticate to Knox and directly access proxied services with those or exchange those credentials for short lived JWT based access, id and refresh tokens.
This change introduces only the acceptance of the Knox TokenID and Passcode tokens as CLIENT_ID and CLIENT_SECRET in a standard OAuth 2.0 client credentials flow request body. This body will contain the following params:
1. grant_type and it will be "client_credentials"
2. client_id which will be the KnoxToken tokenId or KnoxID
3. client_secret which will be the passcode token for which we store the hash
Authentication using this flow will result in the …
> KNOX-3016 - add support for client credentials flow

- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/DefaultTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/JDBCTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/TokenStateDatabase.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/JDBCTokenStateServiceTest.java
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
- gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/KnoxToken.java
Implemented what's described in [KNOX-3019](https://issues.apache.org/jira/browse/KNOX-3019):
- if `knox.token.exp.max-lifetime` is set to a negative value, tokens can be renewed without a maximum lifetime check
- only non-expired tokens can be renewed
Updated current and added new JUnit tests.
Conducted manual testing. In both test rounds, the Token TTL was set to 60 seconds and the token renewal interval was 30 seconds
**1. Maximum lifetime set to 120 seconds**
```
<param>
<name>knox.token.exp.max-lifetime</name>
<value>120000</value>
</param>
<param>
<name>knox.token.exp.renew-interval</name>
<value>30000</value>
</param>
```
```
curl -iku admin:admin-password https://localhost:8443/gateway/sandbox/knoxtoken/api/v2/token
Date: Wed, 13 Mar 2024 09:48:02 GMT
... …
```
> KNOX-3019 - Allow token renewal without upper bound for non-expired tokens

- gateway-provider-security-shiro/pom.xml
- gateway-provider-security-shiro/src/main/java/org/apache/knox/gateway/ShiroMessages.java
- gateway-provider-security-shiro/src/main/java/org/apache/knox/gateway/deploy/impl/ShiroDeploymentContributor.java
- gateway-provider-security-shiro/src/main/java/org/apache/knox/gateway/filter/ShiroSubjectIdentityAdapter.java
- gateway-release/home/conf/topologies/sandbox.xml
- gateway-test/src/test/java/org/apache/knox/gateway/GatewayShiroAuthTest.java
- Support `anon` in Shiro provider i.e. support for following param in shiro provider
```
<param>
<name>urls./knoxtoken/api/v1/jwks.json</name>
<value>anon</value>
</param>
```
- Add `/knoxtoken/api/v1/jwks.json` to unauthenticated path list in Shiro provider example in sandbox.xml
Tested locally
```
curl -v -k GET https://localhost:8443/gateway/sandbox/knoxtoken/api/v1/jwks.json
*   Trying 127.0.0.1:8443...
* Connected to localhost (127.0.0.1) port 8443 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* …
```
> KNOX-3014 - Fix a bug where unauthenticated path configured in shiro provider throw exception

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryMessages.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/monitor/ClusterConfigurationFileStore.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/monitor/ClusterConfigurationFileStoreTest.java
As described in the corresponding KNOX-3022 JIRA, it might happen - due to various IO reasons - that the CM cluster configuration file is empty at Knox startup time. This could prevent the Knox Gateway from starting.
In this PR we fix this issue.
Added a new JUnit test case as well as ran manual testing on a real cluster using CM discovery. Once my patch was applied, the Knox Gateway started properly, and the empty file log entry appeared as expected:
```
grep "is empty" /var/log/knox/gateway/gateway.log 
2024-03-19 02:56:57,434 WARN  discovery.cm (ClusterConfigurationFileStore.java:get(107)) - Previously saved cluster configuration file /var/lib/knox/gateway/data/cm-clusters/https___CM-HOST_CM-PORT-Cluster_1.ver is empty.
```
> KNOX-3022 - Handling the case when previously persisted CM cluster config file is empty

- gateway-release-common/home/bin/knox-functions.sh
- gateway-release/home/bin/gateway.sh
- gateway-release/home/bin/knoxcli.sh
- gateway-release/home/bin/ldap.sh
I updated the existing login in `knox-functions.sh` to successfully check Java executables under `/usr` if no `JAVA_HOME` is set or Java is not available on the path.
In addition to fixing the issue, I added an option to display the Java with the `--verbose` option (when using KnoxCLI, `--verbose true` should be used.
Checked the updated scripts on [shellcheck.net](https://www.shellcheck.net/) and tested them manually:
- `gateway.sh`
```
$ bin/gateway.sh restart --verbose
Found Java at /usr/local/opt/openjdk@8/bin/java
Stopping Gateway with PID 12173 succeeded.
Starting Gateway succeeded with PID 12346.
$ bin/gateway.sh restart
Stopping Gateway with PID 12346 succeeded.
Starting Gateway succeeded with PID 12419.
```
- `knoxcli.sh`
```
$ bin/knoxcli.sh export-cert --type JKS --verbose true …
```
> KNOX-3024 - Fixed Java finding issues

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscovery.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryMessages.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryTest.java
- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-spi-common/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
I added two new gateway-level configurations:
- `gateway.cloudera.manager.service.discovery.excluded.service.types`
- `gateway.cloudera.manager.service.discovery.excluded.role.types`
Both configurations can store a collection of comma-separated Cloudera Manager service or role types that should be excluded from CM service discovery. They both default to an empty set, meaning full CM discovery.
During a CM service discovery attempt, those configurations are checked and based on the supplied values the discovery logic skips the given service(s) or role(s) discovery.
I added and updated existing JUnit tests.
Tested on a live CM cluster:
After restarting Knox, I exported discovery-related logs into [cm_discovery.txt](https://github.com/apache/knox/files/14789431/cm_discovery.txt)
```
grep …
```
> KNOX-3026 - End-users can exclude certain services or roles from CM service discovery

- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/OAuthResource.java
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/deploy/TokenServiceDeploymentContributor.java
- gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
This change will extend the existing TokenResource for KNOXTOKEN service to include OAuth specifics such as expected URL, error messages and flows to support Token Exchange Flow and Token Refresh.
This is being driven by a specific need to proxy access to the Iceberg REST Catalog API. In this specific usecase, we need to intercept the use of the following endpoint URLs and serve the token exchange flow for the authenticating user.
/v1/oauth/tokens
Details for these requirements can be found in the openapi description for the catalog API [1].
In addition to this usecase, we should add generic support for the token exchange flow with more generic URL that better aligns with what others use.
/oauth/v1/token
We will support the use of the "oauth" service name within the existing KNOXTOKEN …
> KNOX-3028 - add support for OAuth Token Exchange to KNOXTOKEN

- gateway-server/src/main/java/org/apache/knox/gateway/services/topology/impl/DefaultTopologyService.java
- gateway-server/src/main/java/org/apache/knox/gateway/util/TopologyUtils.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/topology/TopologyService.java
- gateway-topology-simple/src/main/java/org/apache/knox/gateway/topology/simple/SimpleDescriptorHandler.java
- gateway-topology-simple/src/main/java/org/apache/knox/gateway/topology/simple/SimpleDescriptorMessages.java
This change makes the `TopologyUtils.parse(...)` methods thread safe by synchronizing them. Another update is that occurrences of `SAXParseException` are handled separately and logged properly.
Multiple automated tests were executed parallel to challenge Knox (more than 50 at a time). These tests were capable of reproducing the issue constantly. After repeating the same tests 3 times, we found no problems.
> KNOX-3030 - Make TopologyUtils.parse thread safe

- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/JWTMessages.java
- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/AbstractJWTFilter.java
- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/JWTFederationFilterTest.java
I updated the passcode verification logic in a way such that it returns an HTTP error response with 401 error code if clients want to verify a passcode token without properly configured token state service.
I added the missing JUnit test cases and re-run the `curl` command I used for reproducing the issue:
```
$ curl -iku Passcode:TkdVd1l6VTBPR0l0TmpVMk9DMDBNRFl4TFdFelpHTXROakk1TURnd09EYzJOVEJoOjpNREV6T0dGaFpXUXRZMkV5WVMwME4yWXhMVGhsWkRndFpUQmpNemszTlRrMlpqazE= https://localhost:8443/gateway/proxy-token/v1/gateway-status
HTTP/1.1 401 Unauthorized
Cache-Control: must-revalidate,no-cache,no-store
Content-Type: text/html;charset=iso-8859-1
Content-Length: 684
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 401 Error in token provider …
```
> KNOX-3032 - Passcode use without token state service returns 401

- gateway-spi/src/main/java/org/apache/knox/gateway/SpiGatewayMessages.java
- gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/ConfigurableDispatch.java
- gateway-spi/src/test/java/org/apache/knox/gateway/dispatch/ConfigurableDispatchTest.java
This PR extends configurable dispatch to optionally add authenticated principal and groups to the outbound request as headers (header names are configurable). By default this feature is turned off and will only be enabled if users update the dispatch config in service defition with param `shouldIncludePrincipalAndGroups` (demonstrated below)
Following properties are configurable on dispatch
- `shouldIncludePrincipalAndGroups` Should the principal and groups be passed to the dispatched request as request params.
- `actorIdHeaderName` Header name for the principal, default value is X-Knox-Actor-ID
- `actorGroupsHeaderPrefix` Prefix for header containing groups, default value is X-Knox-Actor-Groups. Note: header names are assigned as X-Knox-Actor-Groups-1, X-Knox-Actor-Groups-2, depending on …
> KNOX-3023 - Include groups in a header in ConfigurableDispatch

- gateway-provider-identity-assertion-common/src/main/java/org/apache/knox/gateway/identityasserter/common/filter/VirtualGroupMapper.java
- gateway-util-common/src/test/java/org/apache/knox/gateway/plang/InterpreterTest.java
The virtual groups through predicate evaluations should include a means to dynamically add a group principal with the same name as the username.
This will require intercepting the configured mapping key name which usually ends with the literal virtual group name that will be added upon matching of the predicate logic.
For this, we will add an optional Logical Virtual Group which will need to be resolved rather than used as a literal. For this specific usecase, we can use syntax such as:
```
<param>
<name>group.mapping.$PRIMARY_GROUP</name>
<value>(not (member username))</value>
</param>
```
This will add a primary group for all …
> KNOX-3036 - Add Primary Group Virtual Group

- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/JWTMessages.java
- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/JWTFederationFilter.java
- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/ClientIdAndClientSecretFederationFilterTest.java
- gateway-util-common/pom.xml
- gateway-util-common/src/main/java/org/apache/knox/gateway/util/RequestBodyUtils.java
- gateway-util-common/src/test/java/org/apache/knox/gateway/util/RequestBodyUtilsTest.java
As described in the [corresponding JIRA](https://issues.apache.org/jira/browse/KNOX-3037), Knox no longer accepts the `grant_type` and `client_secret` as query parameters. Instead, they should be passed in the request body.
For reviewers: I'm not satisfied with the `WARN` message I added in case the client secret is passed as a query param.  I'm hoping for a better sentence from someone :)
Added JUnit tests and conducted manual testing:
1. Using the request body:
```
$ curl -ik -X GET -H "Content-Type: application/x-www-form-urlencoded" --data "grant_type=client_credentials" --data "client_id=$CLIENT_ID" --data-urlencode "client_secret=$CLIENT_SECRET" https://localhost:8443/gateway/tokenbased/oauth/v1/token
Date: Wed, 08 May 2024 11:19:06 GMT
Content-Type: application/json …
```
> KNOX-3037 - Client credentials flow accepts essential parameters in the request body only

- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/OAuthResource.java
- gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
To honor the contract of the existing expiration time in the database for Knox Tokens, I removed the override in the new `OAuthResource` class. Thus, everything that depends on this field will be the same as in the case of our "regular" tokens (token eviction is the most important piece here).
To indicate the actual OAuth token lifetime, I changed the meaning of the `expires_in` field in the JSON response: that's the configured TTL in seconds.
Updated JUnit tests and executed manual testing:
```
$ curl -ik -X POST -H "Content-Type: application/x-www-form-urlencoded" --data "grant_type=client_credentials" --data "client_id=$CLIENT_ID" --data-urlencode "client_secret=$CLIENT_SECRET" https://localhost:8443/gateway/tokenbased/oauth/v1/token
Date: Thu, 10 May 2024 23:46:18 GMT …
```
> KNOX-3038 - The expires_in field in OAuthResource response returns the configured token TTL.

- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/JWTMessages.java
- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/AbstractJWTFilter.java
- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/AbstractJWTFilterTest.java
- gateway-service-hbase/src/test/java/org/apache/knox/gateway/hbase/HBaseDispatchTest.java
This PR adds the ability to validate a JWT token using multiple ways at the same time. Previously, we could only authenticate JWT token using **either**
1. PEM cert
2. JWKS url
3. Knox signing key
With this PR, knox will validate the incoming JWT token using all the above mechanisms if they are configured. 
> KNOX-3040 - Support multiple ways to verify JWT tokens

- gateway-server/src/main/java/org/apache/knox/gateway/GatewayMessages.java
- gateway-server/src/main/java/org/apache/knox/gateway/GatewayServer.java
- gateway-server/src/main/java/org/apache/knox/gateway/util/KnoxCLI.java
Rootcause of this Issue:
Due to improper maven build, We were getting NullPointer Exception as Gatewayserver was not able to find 'build.properties' file (eventhough build.properties was part of gateway-server.jar file)
Error Messgae:
{{
SEVERE: Failed to start gateway: java.lang.NullPointerException
java.lang.NullPointerException
at java.util.Properties$LineReader.readLine(Properties.java:434)
at java.util.Properties.load0(Properties.java:353)
at java.util.Properties.load(Properties.java:341)
at org.apache.knox.gateway.GatewayServer.loadBuildProperties(GatewayServer.java:306)
at org.apache.knox.gateway.GatewayServer.main(GatewayServer.java: …
> KNOX-3043 - NullpointerException in calling loadBuildProperties

- gateway-release-common/home/bin/knox-functions.sh
Fix an issue where `java -version` is not evaluated when java is not set.
> KNOX-3049 Fix startup for JDK17

- gateway-server/src/main/java/org/apache/knox/gateway/GatewayMessages.java
- gateway-server/src/main/java/org/apache/knox/gateway/GatewayServer.java
Modified GatewayMessages, GatewayServer such that port number will be written without ',' character.
Log message before change :  Port 1,243 is already in use.
Log message after change :  Port 1243 is already in use.
Tested with Existing GatewayPortMappingConfigTest testsuite.
> KNOX-3044 - Port numbers are written with ',' format in logs

- .github/workflows/main.yml
- gateway-provider-security-hadoopauth/src/test/java/org/apache/knox/gateway/hadoopauth/filter/HadoopAuthFilterTest.java
- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/JWTMessages.java
- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/AbstractJWTFilter.java
- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/JWTFederationFilter.java
- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/AbstractJWTFilterTest.java
- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/DefaultTokenAuthorityService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/TokenAuthorityServiceMessages.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/topology/DefaultTopologyServiceTest.java
- gateway-service-knoxsso/src/test/java/org/apache/knox/gateway/service/knoxsso/WebSSOResourceTest.java
- gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
- gateway-spi-common/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/JWTokenAuthority.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/impl/JWTToken.java
- gateway-spi/src/test/java/org/apache/knox/gateway/services/security/token/impl/JWTTokenTest.java
- pom.xml
This PR is a followup to KNOX-3040 and adds support for multiple JWKS endpoints. Users can specify one JWKS endpoint or multiple comma separated JWKS endpoints as shown in following example.
```
<param>
<name>knox.token.jwks.url</name>
<value>https://example.com/oauth2/keys?accountId=1234567890, https://www.googleapis.com/oauth2/v3/certs</value>
</param>
``` 
Note that the parameter name `knox.token.jwks.url` did not change. 
This PR also fixes some deprecated classes and adds supports for JWKS caching and retries (just one retry). 
TTL for JWKS caching is set to 2 hours. 
Two parameters were added one topology level `knox.token.jwks.urls` indicating support for multiple jwks urls (this is in addition to previous param which also supports multiple jwks urls but differs in name only) and …
> KNOX-3040 - Followup patch. Support for multiple JWKS endpoints + code cleanup

- gateway-server-launcher/src/main/resources/META-INF/launcher.cfg
- gateway-util-launcher/src/main/java/org/apache/knox/gateway/launcher/Command.java
A new path /usr/share/java/*.jar is added on the classpath which is located outside of the Knox installation folder. Users can place 3rd-party JARs in /usr/share/java and those will be included on the classpath.
Changes were tested locally with test servers.
- Removed dependency from /dep/ folder so gateway fails to start.
- Placed missing dependency on the new path that is now included on the classpath.
- Verified with memory dump that the necessary class is indeed loaded. Also gateway successfully starts.
> KNOX-3047 - Classpath extension for optional dependencies

- gateway-server/src/main/java/org/apache/knox/gateway/GatewayFilter.java
- gateway-server/src/test/java/org/apache/knox/gateway/GatewayFilterTest.java
Modern browsers ignore caching headers as meta elements. Due to this Firefox loads index.html from cache and the user won't be redirected to the Knox login page when there is no Cookie present and the user can't use the homepage.
Added new tests.
Manually tested by loading the home page and checking for the new headers in the HTTP response.
> KNOX-3054 - Replace ignored meta tag cache headers to HTTP headers

- gateway-server/src/main/java/org/apache/knox/gateway/GatewayServer.java
Modified error handling when a topology is being redeployed, such that the response is not HTTP 404 'Not Found', but rather HTTP 503 'Service Unavailable'. The 503 response is much more likely to be retried by clients than is a 404 response.
Added a Jetty ErrorHandler that checks whether or not the topology being requested is in a Set marked as inactive. Topology names are add to this inactive set when the associated topology is deactivated, and removed from this set when the topology is reactivated. In the case of topology deletion, the topology is marked as inactive, but then removed from the inactive set because we know it's being deleted.
I deployed a test topology with a demo LDAP provider and the Knox Token service.
I then ran the following script with …
> KNOX-3058: Avoid 404 When Topology Is Being Redeployed

- gateway-server/pom.xml
- pom.xml
Changed the scope for the MySQL Connector dependency to provided.
Ran tests locally
> KNOX-3055: Change MySQL connector dependency scope to provided

- gateway-release/home/conf/gateway-log4j2.xml
Added monitorInterval property to the Configuration tag in the log4j2 configuration file. With this change Knox can change log level at runtime there is no need to restart the service.
Ran existing tests locally.
Tested the new behaviour locally by changing the knox.gateway log level to TRACE and checking the gateway.log file for DEBUG and TRACE level logs.
> KNOX-3063: Added monitorInterval to log4j2 configuration file

- gateway-shell/pom.xml
- gateway-shell/src/main/java/org/apache/knox/gateway/shell/ClientContext.java
- pom.xml
Removed commons-configuration 1.10 and 2.1 and upgraded them to commons-configuration2 2.10.1
Ran tests locally
> KNOX-3059: Upgrade Commons-configuration2 to 2.10.1

- gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
TokenServiceResourceTest - testLimitingTokensPerUser method acquires many tokens within a tight for loop and does not insure that the tokenIds are unique.
This results in test failures for the unlimited tokens per user on certain machines.
This may also point to a larger concurrency problem which needs investigation. Will file a separate JIRA for this. This may be an issue with the test or the UUID use for the tokenID in general. In the meantime, we can't have builds failing on certain machines.
This change interrogates the response and adds an assertion to ensure that the tokenId is unique. It seems the time spent in doing the check "fixes" the failures. The same "fix" was accomplished with a sleep of 1ms between token acquisitions.
Prior to this fix the following test failure was …
> KNOX-3069 - Fix Flakey Test - TokenServiceResourceTest

- gateway-provider-security-shiro/src/main/java/org/apache/knox/gateway/deploy/impl/ShiroConfig.java
Shiro was upgraded from 1.10.0 to 1.13.0 in a previous [PR](https://github.com/apache/knox/pull/853). Due to this the GatewayBasicFuncTest.testEncodedForwardSlash is failing. This fix is addressing that.
Unit tests
> KNOX-3072: Fix for GatewayBasicFuncTest.testEncodedForwardSlash fail

- gateway-provider-security-hadoopauth/src/test/java/org/apache/knox/gateway/hadoopauth/filter/HadoopAuthFilterTest.java
- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/AbstractJWTFilter.java
- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/AbstractJWTFilterTest.java
- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/JWTAsHTTPBasicCredsFederationFilterTest.java
- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/SSOCookieProviderTest.java
Added a topology-level JWTProvider param for enabling token signature verification fallback to Knox's key(s) when a PEM and/or JWKS URL(s) are explicitly configured for the verification. By default, if one or both of those explicit methods is configured, the verification will not fallback to Knox's key(s).
Unit tests and manual testing was performed to validate the flow and conditions.
> KNOX-3073 - Token verification fallback to Knox keys behavior should be configurable

- gateway-spi/pom.xml
- gateway-spi/src/main/java/org/apache/knox/gateway/SpiGatewayMessages.java
- gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/DefaultHttpAsyncClientFactory.java
- gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/DefaultHttpClientFactory.java
- gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/GatewayDispatchFilter.java
- gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/HttpAsyncClientFactory.java
- gateway-spi/src/main/java/org/apache/knox/gateway/sse/SSEDispatch.java
- gateway-spi/src/main/java/org/apache/knox/gateway/sse/SSEEntity.java
- gateway-spi/src/main/java/org/apache/knox/gateway/sse/SSEException.java
- gateway-spi/src/main/java/org/apache/knox/gateway/sse/SSEResponse.java
- gateway-spi/src/main/java/org/apache/knox/gateway/sse/SSEvent.java
- gateway-spi/src/test/java/org/apache/knox/gateway/dispatch/DefaultHttpAsyncClientFactoryTest.java
- gateway-spi/src/test/java/org/apache/knox/gateway/sse/SSEDispatchTest.java
- gateway-spi/src/test/java/org/apache/knox/gateway/sse/SSEEntityTest.java
- gateway-spi/src/test/java/org/apache/knox/gateway/sse/SSEventTest.java
- pom.xml
SSE support for Knox.
Currently Knox is not working with SSE. In case of SSE the response header contains Content-Type = text/event-stream, in which case the server will send messages terminated by \n\n. Knox should send these messages to the client as they arrive. Currently Knox collects them all, and once the server closes the connection sends all of them concatenated to each other to the client.
Requirement:
Full support in Knox for Server Sent Events.
Definition of done:
Clients can connect to SSE endpoints in the backend via Knox.
Server Sent Events (https://html.spec.whatwg.org/multipage/server-sent-events.html#server-sent-events) are forwarded by Knox from the server to the client as soon as they are received.
Unit tests.
Locally tested with a custom SSE service.
Any SSE service …
> KNOX-3065: SSE support for Knox

- gateway-service-definitions/src/main/resources/services/hbaseui/2.5.10/rewrite.xml
- gateway-service-definitions/src/main/resources/services/hbaseui/2.5.10/service.xml
New service.xml and rewrite.xml configuration for HBase UI v2.5.10.
For example /table.jsp or /userSnapshots.jsp rules are currently missing for the latest stable release of HBase
Tested locally on the CERN clusters against HBase UI v2.5.10 with Knox v2.
> KNOX-3074: Add hbase ui service config and rewrite rules for jsp pages missing in HBase v2.5.10

- gateway-service-definitions/src/main/resources/services/yarnui/2.7.0/rewrite.xml
Knox Gateway for Yarn ResourceManager REST API should respect query parameters.
The conclusion is: `{**}?{**}` works and `{**}` will ignore query params.
There is already one can prove that patten `{**}?{**}` works with query parameters and without parameters.
https://github.com/apache/knox/blob/d21cf8f63944afdd5d4ffa0236a16cd788d9a14a/gateway-provider-rewrite/src/test/java/org/apache/knox/gateway/filter/rewrite/api/UrlRewriteProcessorTest.java#L274-L303
and rewrite.xml :
https://github.com/apache/knox/blob/d21cf8f63944afdd5d4ffa0236a16cd788d9a14a/gateway-provider-rewrite/src/test/resources/org/apache/knox/gateway/filter/rewrite/api/UrlRewri …
> KNOX-3046 - Yarn REST API should support query parameters

- gateway-provider-security-shiro/pom.xml
- gateway-provider-security-shiro/src/main/java/org/apache/knox/gateway/ShiroMessages.java
- gateway-provider-security-shiro/src/main/java/org/apache/knox/gateway/shirorealm/KnoxCacheManager.java
- gateway-provider-security-shiro/src/test/java/org/apache/knox/gateway/shirorealm/KnoxCacheManagerTest.java
- pom.xml
Upgrade ehcache from 2.x to 3.x
Currently with 2.x the CacheManager is a Singleton therefore every cache will be stored in the same CacheManager. Due to this caches with the same name will be created only once and different topologies are using the same cache. For example if a user authenticates in the sandbox topology the same user and password can be used for other topologies as well where ehcache is enabled and the cache name is the same. This could cause issues if the ldap configuration is different. 
With Ehcache 3.x creating the CacheManager is our responsibility. Different topologies will have different configurations and caches even with the same name. Every topology that enables ehcache needs a different configuration file. The persistence attribute has to be unique.
<persistence …
> KNOX-3067: Upgrade ehcache to 3.3.1

- gateway-demo-ldap/pom.xml
- gateway-docker/pom.xml
- gateway-provider-security-pac4j/pom.xml
- pom.xml
Upgrade Bouncy Castle to 1.78 due to 
- CVE-2023-33202
- CVE-2023-33201
- CVE-2024-29857
- CVE-2024-30171
- CVE-2024-30172
- CVE-2024-34447
Ran tests locally
Checked the dependency tree with: `mvn dependency:tree -Dincludes=org.bouncycastle | grep "org.bouncycastle"`
Checked the dep folder after ant install-test-home with: `ls -la *bp*`
> KNOX-3061: Upgrade Bouncy Castle to 1.78

- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/JDBCTokenStateService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/TokenStateDatabase.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/JDBCTokenStateServiceTest.java
As described in KNOX-3075, when the token TTL was set to -1 (which allows creating never-expiring tokens), JDBC TSS threw an `UnknownTokenException`. This is wrong. It should have returned the configured `-1` value.
I updated existing JUnit tests to handle the path when fetching tokens for a user. I also added 2 new test cases to ensure this issue never occurs again.
> KNOX-3075 - Handling unlimited token expiration in JDBC TSS properly

- gateway-docker/src/main/resources/docker/Dockerfile
- gateway-docker/src/main/resources/docker/gateway-entrypoint.sh
- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/DefaultTokenAuthorityService.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/TokenAuthorityServiceMessages.java
- gateway-spi-common/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
- pom.xml
1. Ability to validate JWT tokens that are missing `typ` header for configured issuers.
1.1. This is configured by gateway-site.xml property `gateway.token.issuers.ignore.type.validation`
3. Add letsencrypt staging cert to knox docker image
> KNOX-3087 - Provide a way to validate JWT tokens that are missing typ header and Add letsencrypt staging cert to knox docker image

- gateway-release-common/home/bin/knox-functions.sh
Added explicit JVM exports to fix broken Ranger plug-in group lookups with Java 17
Unit and manual testing.
> KNOX-3088: Fix Ranger plug-in group lookup with Java 17

- gateway-provider-security-shiro/pom.xml
- pom.xml
This change reverts KNOX-3006, which replaced the libpam4j implementation in an attempt to resolve the intermittent garbage group names issue. However, this change apparently does not completely resolve that issue AND it introduces intermittent authentication failures.
Unit and manual testing.
> Revert KNOX-3006

- gateway-service-definitions/src/main/resources/services/hbaseui/2.1.0/rewrite.xml
KNOX-3095 : Added Hbase UI proxying for Startup progress
Added rewrite rule for "Startup Progress" on HBase UI.
Copied the rewrite.xml file to a cluster, restarted Knox, and verified the URL is redirecting correctly.
> KNOX-3095:Added HBase UI proxying for Startup progress

- gateway-provider-security-pac4j/src/test/java/org/apache/knox/gateway/pac4j/filter/Pac4jDispatcherFilterTest.java
This PR adds a unit test for pac4j.cookie.max.age param
> KNOX-3077 - Add unit test for pac4j.cookie.max.age param

- gateway-provider-security-authc-remote/src/main/java/org/apache/knox/gateway/filter/RemoteAuthFilter.java
- gateway-provider-security-authc-remote/src/test/java/org/apache/knox/gateway/filter/RemoteAuthFilterTest.java
The initial implementation of RemoteAuthProvider caches authenticated Subjects locally based on the header that contained the credentials. While the cache is designed to provide only a few mins of caching, it is less than ideal to use the credentials as keys. This needs to be strengthened to use a hash as to not inadvertently risk leaking the credentials.
This will require some overhead involved in the hashing so we may need to find something else but we shouldn't use the credentials themselves. We would normally have to do a hash for implementing authentication for things like RDMS or LDAP based passwords, etc.
Refactored and ran existing unit tests to ensure no regression was introduced.
> KNOX-3101 - hash key for RemoteAuthProvider cache

- gateway-server/src/main/java/org/apache/knox/gateway/GatewayMessages.java
- gateway-server/src/main/java/org/apache/knox/gateway/GatewayServer.java
- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/security/impl/JettySSLService.java
- gateway-server/src/test/java/org/apache/knox/gateway/GatewayGlobalConfigTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/security/impl/JettySSLServiceTest.java
- gateway-server/src/test/resources/conf-site/conf/gateway-site.xml
- gateway-spi-common/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/SSLService.java
Currently if the user adds `gateway.client.auth.needed` as true to the gateway-site.xml every topology will enforce this. There is no option to exclude from this policy. The user can also specify gateway.client.auth.wanted as true however the policy is not enforced in this case.
We need the ability to be able to exclude topologies in case the client auth is needed.
Example setup:
By adding the below to the gateway-site.xml we enable the client auth needed policy. To be able to exclude a topology from this we have to define a port mapping for that topology and add it to the `gateway.client.auth.exclude` as well.
<property>
<name>gateway.client.auth.needed</name>
</property>
<property>
<name>gateway.port.mapping.health</name>
<value>9443</value>
</property>
<property> …
> KNOX-3099: Ability to exclude topologies form client auth needed policy

- gateway-provider-security-authc-remote/src/main/java/org/apache/knox/gateway/filter/RemoteAuthFilter.java
- gateway-provider-security-authc-remote/src/test/java/org/apache/knox/gateway/filter/RemoteAuthFilterTest.java
Initial iteration of the RemoteAuthProvider has support for a single HTTP Header containing the group memberships. The Pre API in the Knox Auth Service breaks memberships up across multiple headers to manage the size.
We need to determine a syntax as an explicit list or a range with some builtin syntax of a numeric suffix. Otherwise, it will need a list of possible header names with it accommodating the largest set which seems odd.
Ran existing unit tests plus new tests for the new functionality.
> KNOX-3100 - RemoteAuthProvider to accept multiple group headers

- gateway-provider-security-authc-remote/pom.xml
- gateway-provider-security-authc-remote/src/main/java/org/apache/knox/gateway/filter/RemoteAuthFilter.java
- gateway-provider-security-authc-remote/src/test/java/org/apache/knox/gateway/filter/RemoteAuthFilterTest.java
The initial implementation of the RemoteAuthProvider only has the initial access level audit. We need to add not only the result of the authentication attempt but also add the correlation id for the audit entries to the call to the remote auth service so that the audit logs can be correlated.
Added new unit tests and ran all existing tests.
Manually tested with a single instance and traced the call from through the initial topology and the "remote" endpoint. Note the correlation id is the same for all of the entries. This will follow across instances as well.
```
25/02/27 23:53:15 ||9f67555c-6561-40fb-ad39-6fa8ac4fa1f9|audit|[0:0:0:0:0:0:0:1]|KNOXTOKEN||||access|uri|/gateway/tokengen/knoxtoken/api/v1/token|unavailable|Request method: GET
25/02/27 23:53:15 …
```
> KNOX-3102 - Complete Auditing in RemoteAuthProvider

- gateway-provider-security-authc-remote/src/main/java/org/apache/knox/gateway/filter/RemoteAuthFilter.java
The audit log entry for the RemoteAuthProvider currently doesn't include groups that have been returned by the remote authentication service via the groups header.
This change will add them to the audit log from the established Java Subject's GroupPrincipals.
Existing unit tests to ensure no regression
Manually tested and observed the change in the audit log with the added groups array listed
```
25/03/01 17:16:49 ||62d338e7-32fe-48a4-b174-ed9c5977c8e9|audit|[0:0:0:0:0:0:0:1]|KNOXTOKEN||||access|uri|/gateway/tokengen/knoxtoken/api/v1/token|unavailable|Request method: GET
25/03/01 17:16:49 ||62d338e7-32fe-48a4-b174-ed9c5977c8e9|audit|127.0.0.1|KNOX-AUTH-SERVICE||||access|uri|/gateway/sandbox/auth/api/v1/pre|unavailable|Request method: GET
25/03/01 17:16:49 …
```
> KNOX-3104 - Add groups to the RemoteAuthProvider audit entry

- gateway-provider-security-authc-remote/src/main/java/org/apache/knox/gateway/filter/RemoteAuthFilter.java
- gateway-provider-security-authc-remote/src/test/java/org/apache/knox/gateway/filter/RemoteAuthFilterTest.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/security/impl/DefaultKeystoreService.java
- gateway-spi/src/main/java/org/apache/knox/gateway/services/security/KeystoreService.java
I originally had this topology level config only for the truststore and password but decided that it should be configured at the gateway level. However, it is much easier to use specific truststores for dev and testing environments than adding a cert from one Knox to another's truststore which may have other certs, etc.
This change will add the params for location and password with alias service support of the password.
Added new unit tests, ran all existing tests and manually tested with another knox instance.
`curl -ivku admin:admin-password https://localhost:8444/gateway/tokengen/knoxtoken/api/v1/token`
Audit logs for each instance are below to show the correlation ID across instances:
Local instance:
```
25/03/03 23:21:10 ||878975c9-de91-4da3-94e8-f716ce5b337a|audit|[0:0:0:0:0:0:0:1]|K …
```
> KNOX-3105 - Add Topology Level Config for Truststore to RemoteAuthProvider

- gateway-provider-security-authc-remote/src/main/java/org/apache/knox/gateway/filter/RemoteAuthFilter.java
- gateway-provider-security-authc-remote/src/test/java/org/apache/knox/gateway/filter/RemoteAuthFilterTest.java
Added Alias support for the truststore password.
Also moved the creation and load of the truststore to the init method rather than the request processing path.
This required an adjustment in the way that the topology level truststore tests were written and the expectations to fail fast at init time which broke previous expectations of the request results reflecting truststore issues or success.
Existing unit tests and new test approaches for previously provided local truststore.
Manual run with separate Knox instance and export cert as the truststore.
> KNOX-3107 - Alias Support for the RemoteAuthProvider truststore password

- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/AbstractJWTFilter.java
- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/AbstractJWTFilterTest.java
- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/TokenIDAsHTTPBasicCredsFederationFilterTest.java
While we have a change to introduce the ability to use multiple JWKS Urls to verify a token signature, without this change any tokens would need to have the same Issuer. This isn't ideal and limits the flexibility that we are looking for.
This change is only an iteration beyond that approach but still not ideal. We will want to have a better isolation of the expected claims, algorithms, etc - per token. This will suffice for now but we will revisit it in the near future for better isolation.
Here we will simply change the expectedIssuers param to be a List of Strings from a comma separated list and introduce a keyword "NONE" to indicate even though there are expected audiences for some tokens, it is also possible to accept a token with no audience as well. This is an opt-in only feature …
> KNOX-3052: Allow Multiple Issuers and JWTs with no Audience in same Topology as Others

- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/AbstractJWTFilter.java
- gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/JWTFederationFilter.java
- gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/JWTFederationFilterTest.java
Currently, passcode tokens can only be used as passwords with HTTP Basic authentication headers.
This change will enable them to be accepted as Authorization: Bearer tokens.
Will need to be able to distinguish between a JWT and a Passcode token when presented as a Bearer token.
This will allow Passcode tokens to be used as API_KEYs.
Manually tested, added new unit tests and ran all existing unit tests.
`curl -ivk -H "Authorization: Bearer TWpNMFlUTTNZamN0WVdaa09DM...U5XVXdabVF4OjpORFptTnpReU9URXROREUyWlMwMFpETXhMVGt6TnpRdE9HRXlZemt3WW1Rek5XRm0=" -X POST https://localhost:8444/gateway/tokengen/knoxtoken/api/v1/token`
To a topology protected with RemoteAuthProvider which makes a remote auth call to a separate topology configured with the JWTProvider and server managed tokens.
Results
```
* …
```
> KNOX-3109 - Passcode Tokens to use as Bearer Token

- gateway-server/src/main/java/org/apache/knox/gateway/GatewayMessages.java
- gateway-server/src/main/java/org/apache/knox/gateway/GatewayServer.java
- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-server/src/main/java/org/apache/knox/gateway/filter/HSTSHandler.java
- gateway-server/src/test/java/org/apache/knox/gateway/GatewayGlobalConfigTest.java
- gateway-server/src/test/java/org/apache/knox/gateway/filter/HSTSHandlerTest.java
- gateway-server/src/test/resources/conf-site/conf/gateway-site.xml
- gateway-spi-common/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
- gateway-test/src/test/java/org/apache/knox/gateway/GatewayHSTSTest.java
This PR introduces the ability to enable `Strict-Transport-Security` header globally for all responses (even 404). Currently there is a topology wide configuration in the WebAppSec provider. The users now can enable it for only specific topologies or globally as well. If both is enabled and there is a request for that specific topology the WebAppSec configuration will take precedence. 
To enable the global configuration the below is required in the gateway-site.xml configuration file. The `option` config is optional, the default value is `max-age=31536000` (Its the same for the WebAppSec provider as well).
```
<property>
<name>gateway.strict.transport.enabled</name>
</property>
<property>
<name>gateway.strict.transport.option</name>
<value>max-age=31</value> …
```
> KNOX-3111: Gobal config for HSTS headers

- gateway-util-launcher/src/main/java/org/apache/knox/gateway/launcher/GatewayServerClasspathExtender.java
- gateway-util-launcher/src/test/java/org/apache/knox/gateway/launcher/GatewayServerClasspathExtenderTest.java
This change is an improvement on [KNOX-3108](https://issues.apache.org/jira/browse/KNOX-3108) (classpath extension). The gateway config file's location is read from a system property first during classpath extension. The solution is similar to the one we already have when we look for the config file on GatewayConfigImpl class.
Unit tests
Manually tested
> KNOX-3122:Gateway config path is read from system property first during classpath extension

- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/APIKeyResource.java
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/ClientCredentialsResource.java
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/OAuthResource.java
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/PasscodeTokenResourceBase.java
- gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
While both the CLIENTID and APIKEY APIs default the knox.token.ttl to -1 to never expire, we do not prevent actual expirations. In the case that there is a configured expiration, return the expiration in the response as appropriate for the clients.
Added new unit tests.
Built and ran all existing and new tests.
```
curl -ivku admin:admin-password -X POST "https://localhost:8443/gateway/sandbox/clientid/api/v1/oauth/credentials?comment=ljm&contact=test-contact&md_externalUserName=Larry%20McCay&md_email=email&md_companyName=companyName"
.
.
.
{"client_secret":"WTJSaU16QmpOVGt0T....oak9ETXROREkyTUdRek5HVTROVGhpOjpPVFkzTkRBNVpHUXRZekF5T0MwME1tSTNMV0l3WldRdE5qUTVabU0xTm1JM09Ea3o=","expires_in":54,"client_id":"cdb30c59-1fe5-4...d34e858b"}
```
> KNOX-3129 - Add expiry to APIKEY and CLIENTID API Responses

- gateway-provider-security-webappsec/src/main/java/org/apache/knox/gateway/webappsec/deploy/WebAppSecContributor.java
- gateway-provider-security-webappsec/src/main/java/org/apache/knox/gateway/webappsec/filter/SecurityHeaderFilter.java
- gateway-provider-security-webappsec/src/test/java/org/apache/knox/gateway/webappsec/SecurityHeaderFilterTest.java
In order to add various security headers to a response, we can add a generic filter for which init params with the param name and value indicating the header name and string representing the directives for the header respectively.
This will allow admins to configure things like Content-Security-Policy, Cache-Control, etc. without the need to add separate filters for each one.
New unit tests were added.
All new and existing tests were run.
Manual testing was done with the following web app sec provider config and curl command:
```
<provider>
<role>webappsec</role>
<name>WebAppSec</name>
<param>
<name>csrf.customHeader</name>
<value>X-XSRF-Header</value>
</param>
<param>
<name>csrf.methodsToIgnore</name>
<value>GET,OPTIONS,HEAD</value>
</param>
<param> …
```
> KNOX-3124 - Add Security Header filter to WebAppSec Provider

- gateway-util-common/src/test/java/org/apache/knox/gateway/util/JsonUtilsTest.java
This PR addresses an issue where JsonUtilsTest.testRenderAsJsonStringWithDateFormat would fail on some machines and not other. The problem is the epoch chosen before `1609459200000L` was on a boundary or day, date and month (2020-12-31-2021-01-01), a bit of a clock skew with millisecond precision might throw the tests off. 
This PR uses the epoch `1746108169L` (in millisec) which hopefully tolerates few millisec swings as it is in the middle of the day. (Thu, 01 May 2025 14:02:49 GMT)
> KNOX-3060 - Fix an issue with JsonUtilsTest.testRenderAsJsonStringWithDateFormat which can fail due to clock skew

- pom.xml
Upgraded jackson from 2.14.3 to 2.18.2
What changes were proposed in this pull request?
This PR proposes for the latest version of the jackson.
How was this patch tested?
Tested on local, seems works fine with this latest version.
> KNOX-3079: Bump jackson to 2.18.2

- gateway-provider-security-pac4j/src/main/java/org/apache/knox/gateway/pac4j/filter/Pac4jDispatcherFilter.java
- gateway-provider-security-pac4j/src/main/java/org/apache/knox/gateway/pac4j/session/KnoxSessionStore.java
- gateway-provider-security-pac4j/src/test/java/org/apache/knox/gateway/pac4j/MockHttpServletResponse.java
- gateway-provider-security-pac4j/src/test/java/org/apache/knox/gateway/pac4j/Pac4jProviderTest.java
- gateway-provider-security-pac4j/src/test/java/org/apache/knox/gateway/pac4j/filter/Pac4jDispatcherFilterTest.java
- gateway-provider-security-pac4j/src/test/java/org/apache/knox/gateway/pac4j/session/KnoxSessionStoreTest.java
- gateway-service-knoxsso/src/main/java/org/apache/knox/gateway/service/knoxsso/WebSSOResource.java
- gateway-util-common/src/main/java/org/apache/knox/gateway/util/SetCookieHeader.java
- gateway-util-common/src/test/java/org/apache/knox/gateway/util/SetCookieHeaderTest.java
This change makes the SameSite attribute for the pac4j session cookies configurable. The default value is `Strict`.
The pac4j Cookie class doesn't support the SameSite attribute so I had to change the implementation to Set-Cookie headers.
Modified MockHttpServletResponse class to accommodate the testing of multiple Set-Cookie headers.
Manually tested, unit tests
> KNOX-3148: Make SameSite configurable for pac4j session cookies

- gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/DefaultTokenAuthorityService.java
- gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/JWKSourceBuilderTest.java
- gateway-spi-common/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
- gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
Added support for caching JWKS keys. Added following configurable options to cache jwks keys 
These parameters can be configured in gateway-site.xml
1. `gateway.jwks.cache.ttl` (default value 20 mins)
2. `gateway.jwks.cache.refresh.interval` (default value 20 mins)
Locally, added a unit test
> KNOX-3150 - Add support for caching JWKS keys

- gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/DefaultTokenAuthorityService.java
Previous fix for KNOX-3150 might not have addresses the caching issue completely. This is a followup fix to that. 
To recap, https://github.com/apache/knox/pull/1044 added support for caching JWKS keys. Following configurable options were added for caching jwks keys
These parameters can be configured in `gateway-site.xml` (in line with other parameters around JWKS configuration e.g. `gateway.token.issuers.ignore.type.validation`)
1. `gateway.jwks.cache.ttl` (default value 20 mins)
2. `gateway.jwks.cache.refresh.interval` (default value 20 mins)
This patch was tested locally: 
1. Created a topology with a JWKS endpoint
2. ensured that the jwks endpoint was reachable
3. Verified that the token was validated
4. Made the jwks endpoint unreachable 
5. created a new token (we cache the …
> KNOX-3150 - Fix a bug where jwks keys might not be cached properly

- gateway-service-definitions/src/main/resources/services/pinot/1.3.0/rewrite.xml
- gateway-service-definitions/src/main/resources/services/pinot/1.3.0/service.xml
Gateway log were filled with the below error during startup due to the pinot service xmls added in [KNOX-3139](https://github.com/apache/knox/pull/1034) I fixed the service and rewrite xmls and the errors are gone.
```
ERROR knox.gateway (ServiceDefinitionsLoader.java:lambda$loadServiceDefinitions$1(92)) - Failed to unmarshall service definition file /Users/thanicz/dev/public/knox/install/knox-2.1.0-SNAPSHOT/data/services/pinot/1.3.0/service.xml file : javax.x
ml.bind.UnmarshalException
- with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 20; columnNumber: 6; The processing instruction target matching "[xX][mM][lL]" is not allowed.]
javax.xml.bind.UnmarshalException: null 
```
Unit tests, checked the gateway.log during startup
> KNOX-3152: Fixed pinot service xml format issue

- gateway-release/home/bin/knoxcli.sh
knoxcli.sh should use the found java path when querying the jdk version.
Also, the launching command should also quote the JAVA variable as in knox-functions.sh appstart.
Tested on a dev cluster with openJDK 17.
invoke-knox-cli.sh: 
```bash
#!/bin/bash
export KNOX_GATEWAY_DATA_DIR=/var/lib/knox/gateway/data;
export KNOX_GATEWAY_CONF_DIR=/var/lib/knox/gateway/conf;
bash -x knox-bin-path/knoxcli.sh "$@"
```
Test commands:
```bash
./invoke-knox-cli.sh create-cert --hostname host-fqdn --force
./invoke-knox-cli.sh list-alias
```
The create-cert command fails as java version 17 is not detected, add-exports are not appended to the command line 
(X509CertificateUtil.java:generateCertificate(276)) - Error in generating certificate: java.lang.IllegalAccessException: class …
> KNOX-3153: Fix Java command invocations in knoxcli.sh

- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/APIKeyResource.java
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/ClientCredentialsResource.java
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/PasscodeTokenResourceBase.java
- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/ServletContextWrapper.java
- gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
Issue: The extension APIs of KNOXTOKEN: APIKEY and CLIENTID APIs are unable to be colocated with the KNOXTOKEN API in the same topology due to param name conflicts. This results in unexpected results when the TTL or other params are set in one or more of the APIs.
Solution: I provided prefixes for all extension APIs that extend the PasscodeTokenResourceBase class via a getPrefix() method on each implementation. Those prefixes are used to disambiguate the params at initialization time and then are stripped from the params and reset to the expected names in KNOXTOKEN implementation.
This insures that the params do not collide and that the implementation has the expected values at runtime.
Note: there may be a more fundamental issue that has required this change that has been lurking for …
> KNOX-3155 - Isolate the CLIENTID and APIKEY param names from KNOXTOKEN

- pom.xml
Upgraded protobuf from 3.16.3 to 3.25.5
What changes were proposed in this pull request?
This PR proposes for the latest version of the protobuf.
How was this patch tested?
Tested on local, seems works fine with this latest version.
> KNOX-3078: Bumpup protobuf to 3.25.5

- gateway-applications/pom.xml
- gateway-applications/src/main/resources/applications/knoxauth/app/logout.jsp
- gateway-applications/src/main/resources/applications/knoxauth/app/redirecting.jsp
- gateway-util-common/src/main/java/org/apache/knox/gateway/util/Urls.java
- gateway-util-common/src/test/java/org/apache/knox/gateway/util/UrlsTest.java
Adding basic url check and for originalUrl for logout and redirecting jsp. Also encoding urls for javascript and html output.
Tested using a dev cluster. simple login and sso, global logout was also tested with CAS PAC4J demo app.
> KNOX-3132: Improve URL checks for originalUrl

- gateway-server/src/main/java/org/apache/knox/gateway/services/metrics/impl/instr/InstrHttpClientBuilderProvider.java
- gateway-server/src/main/java/org/apache/knox/gateway/services/metrics/impl/instr/InstrUtils.java
Fix [KNOX-2954](https://issues.apache.org/jira/browse/KNOX-2954) 
The name of service metric should not contain hbase rowkey
Apply this PR and recompile
Deploy new jar files to ${KNOX_HOME}/lib direcotry and restart gateway
Use rowkey to query from hbase
Use visualVM or other tool to check whether the name of service metric contains rowkey
> KNOX-2954 - Gateway metric name contain rowkey led to full gc

- pom.xml
Upgrading json-smart from 2.4.9 to 2.5.2
What changes were proposed in this pull request?
This PR proposes for the latest version of the json-smart.
How was this patch tested?
Tested on local by running the build via mvn -Prelease clean install.
> KNOX-3168: Updating json-smart to 2.5.2

- gateway-service-definitions/pom.xml
- pom.xml
This XML validation is aiming to avoid cases like https://github.com/apache/knox/pull/1034 where a service definition were merged with an incorrect XML format. The build should fail in these cases.
Ran mvn verify on correct and incorrect XMLs
```
[ERROR] Failed to execute goal org.codehaus.mojo:xml-maven-plugin:1.1.0:validate (default) on project gateway-service-definitions: While parsing /Users/thanicz/dev/public/knox/gateway-service-definitions/src/main/resources/services/pinot/1.3.0/rewrite.xml, at file:/Users/thanicz/dev/public/knox/gateway-service-definitions/src/main/resources/services/pinot/1.3.0/rewrite.xml, line 23,  column 7: fatal error: The element type "rewrite" must be terminated by the matching end-tag "</rewrite>".
[ERROR] While parsing …
```
> KNOX-3177: gateway-service-definitions build time XML validation

- gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/PasscodeTokenResourceBase.java
Changed the base class for PasscodeTokenResourceBase from TokenResource to TokenResourceV2.
Full build and verify, and manually validated the HTTP methods allowed for the various token lifecycle operations using the CLIENTID service (e.g., revoke requires DELETE rather than POST).
> KNOX-3181: PasscodeTokenResourceBase should extend TokenResourceV2

- pom.xml
Excluded the transient netty dependency versions pulled in via hadoop-common and zookeeper.
Full build and unit tests were executed and passed.
> KNOX-3182: Exclude netty from hadoop-common and zookeeper Dependencies

- pom.xml
commons-lang 2.6 is referenced in the parent pom however it is not used. The commons-lang library is not present in the `/dep` folder either after installing. This change removes commons-lang 2.6 from the pom.xml.
Build, unit tests, checked basic functionality (homepage, knoxsso)
> KNOX-3183: Remove unused commons-lang 2.6

- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryMessages.java
- gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/monitor/PollingConfigurationAnalyzer.java
- gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/monitor/PollingConfigurationAnalyzerTest.java
As described in KNOX-3194, the cluster-level `RollingRestart` and `RestartWaitingForStalenessSuccess` should trigger a full service discovery.
Updated and executed existing unit tests.
Manual testing on a real cluster with HMS (I'll add details later...)
> KNOX-3194 - CM-initiated rolling restart and waitForStalenessSuccess commands should trigger a discovery round

- pom.xml
- Removed `jakarta.activation-api` duplication.
- Specified the `com.sun.activation` version so it is easily distinguished from jakarta activation-api
Build, unit tests
> KNOX-3203: Remove jakarta activation-api duplication
