gateway-provider-identity-assertion-common/pom.xml
gateway-provider-identity-assertion-common/src/test/java/org/apache/knox/gateway/identityasserter/function/UsernameFunctionProcessorTest.java
gateway-provider-rewrite-func-service-registry/pom.xml
gateway-provider-rewrite-func-service-registry/src/test/java/org/apache/knox/gateway/svcregfunc/impl/ServiceRegistryFunctionsTest.java
gateway-provider-rewrite/pom.xml
gateway-provider-rewrite/src/test/java/org/apache/knox/gateway/filter/rewrite/api/UrlRewriteServletContextListenerTest.java
gateway-provider-rewrite/src/test/java/org/apache/knox/gateway/filter/rewrite/api/UrlRewriteServletFilterTest.java
gateway-provider-rewrite/src/test/java/org/apache/knox/gateway/filter/rewrite/impl/FrontendFunctionProcessorTest.java
gateway-server/src/main/java/org/apache/knox/gateway/filter/RequestUpdateHandler.java
gateway-server/src/main/java/org/apache/knox/gateway/trace/AccessHandler.java
gateway-test-utils/pom.xml
gateway-test/src/test/java/org/apache/knox/gateway/GatewayMultiFuncTest.java
gateway-test/src/test/java/org/apache/knox/gateway/SimpleDescriptorHandlerFuncTest.java
pom.xml

This is for review only. Patches will be attached to KNOX-1516

KNOX-1516 - Upgrade Jetty to 9.4.12

---

.travis.yml
gateway-adapter/pom.xml
gateway-provider-rewrite/pom.xml
gateway-server/pom.xml
gateway-service-admin/pom.xml
gateway-service-definitions/pom.xml
gateway-service-remoteconfig/pom.xml
gateway-service-test/pom.xml
gateway-spi/pom.xml
gateway-test/pom.xml
gateway-util-common/pom.xml
pom.xml

This is more for review. Patches will be put on KNOX-1458.
For reference builds on my fork branch KNOX-1458 are here: https://travis-ci.org/risdenk/knox/branches

KNOX-1458 - Support JDK 9/10/11

---

gateway-docker/README.md
gateway-docker/pom.xml
gateway-docker/src/assembly/docker-files.xml
gateway-docker/src/main/resources/docker-compose.yml
gateway-docker/src/main/resources/docker/Dockerfile
gateway-docker/src/main/resources/docker/gateway-entrypoint.sh
gateway-docker/src/main/resources/docker/ldap-entrypoint.sh
pom.xml

This is for helping with review only. Patches will be posted to KNOX-1285.

KNOX-1285 - Create Apache Knox Dockerfile and image

---

.github/PULL_REQUEST_TEMPLATE.md
pom.xml

Created the PR template for Knox
I edited this template using a Markdown editor and copy pasted the submitted template here to ensure it looks like as expected.

KNOX-1760 - Created Pull Request template

---

gateway-release/pom.xml
gateway-service-definitions/src/main/resources/services/jkg/1.1.2/service.xml
gateway-service-jkg/pom.xml
gateway-service-jkg/src/main/java/org/apache/knox/gateway/jkg/JkgDispatch.java
pom.xml

https://issues.apache.org/jira/browse/KNOX-1835
(Please fill in changes proposed in this fix)
(If this patch involves UI changes, please attach a screen-shot; otherwise, remove this)

KNOX-1835 JKG KERNEL_USERNAME should be added when not present

---

build-tools/src/main/resources/build-tools/checkstyle/checker.xml
pom.xml

Upgrade checkstyle to 8.19
`mvn -T.5C verify -Ppackage,release`

KNOX-1844 - Upgrade checkstyle to 8.19

---

gateway-service-definitions/src/main/resources/services/hbaseui/2.1.0/rewrite.xml
gateway-service-definitions/src/main/resources/services/hbaseui/2.1.0/service.xml

Current HBase UI was extremely broken, tons of dead/incorrect links. This corrects all of them but the LogLevel servlet.
Deployed Knox 1.3.0-SNAPSHOT locally with HBase 2.1.5-SNAPSHOT and validated that the UI can be traversed in full.

KNOX-1866 Fix HBase UI proxying.

---

gateway-service-definitions/src/main/resources/services/hbaseui/2.1.0/rewrite.xml
gateway-service-definitions/src/main/resources/services/hbaseui/2.1.0/service.xml

Fix HBase UI service.xml version
Checked that HBase UI works with new version

KNOX-1868 - HBase UI changes from KNOX-1866 aren't picked up due to service.xml version

---

gateway-service-definitions/src/main/resources/services/hue/1.0.0/rewrite.xml
gateway-service-definitions/src/main/resources/services/hue/1.0.0/service.xml

First version of the Hue UI service definition
Manual

KNOX-1862 - Add Service Definition for Hue UI

---

gateway-release/home/conf/topologies/sandbox.xml

Provide default configuration for Hue in topology
Manual

KNOX-1916 - Provide default configuration for Hue in topology

---

gateway-test-release/pom.xml
gateway-test-release/webhdfs-kerb-test/pom.xml
gateway-test-release/webhdfs-kerb-test/src/test/java/org/apache/hadoop/http/HttpServer2.java
gateway-test-release/webhdfs-test/pom.xml
gateway-test-release/webhdfs-test/src/test/java/org/apache/hadoop/http/HttpServer2.java
pom.xml

* Upgrades Jetty to 9.4.19.v20190610
* Patches Hadoop `HttpServer2` class for Jetty 9.4.x
* Removes need for Hadoop Jetty 9.3.x version

KNOX-1885 - Upgrade jetty to 9.4.19.v20190610

---

gateway-admin-ui/package-lock.json
gateway-admin-ui/pom.xml

Upgrade nodejs to latest LTS v10.16.0

KNOX-1923 - Upgrade nodejs to latest LTS v10.16.0

---

gateway-provider-security-shiro/pom.xml
pom.xml

Upgrade libpam4j to 1.11 and update Maven coordinate.

KNOX-1924 - Upgrade org.abstractj.libpam4j 1.9.1 to org.kohsuke.libpam4j 1.11

---

gateway-provider-security-shiro/src/main/java/org/apache/knox/gateway/shirorealm/KnoxPamRealm.java

Minor code cleanup based on reviewing KnoxPamRealm for threading issues.

KNOX-1925 - KnoxPamRealm code cleanup

---

gateway-admin-ui/package.json
gateway-admin-ui/proxy.conf.json

Improve development by adding angular proxy conf and updated npm start
Develop AdminUI locally with `./gateway-admin-ui/npm run start` and checking that url updated to `http://localhost:4200/gateway/manager/admin-ui`

KNOX-1956 - Improve AdminUI development by using angular proxy conf

---

gateway-service-definitions/src/main/resources/services/ranger/1.0.0/service.xml

Change RANGER service definition dispatch to ConfigurableDispatch. It is observed that RANGER service is used alongside RANGERUI service to serve UI.
This patch was locally tested.

KNOX-2012 Fix an issue where multiple sessions are created during Ranger login

---

gateway-provider-ha/pom.xml
gateway-server/pom.xml
gateway-server/src/test/java/org/apache/knox/gateway/services/security/impl/ZookeeperRemoteAliasMonitorTest.java
gateway-server/src/test/java/org/apache/knox/gateway/services/security/impl/ZookeeperRemoteAliasServiceTest.java
gateway-server/src/test/java/org/apache/knox/gateway/topology/monitor/ZooKeeperConfigurationMonitorTest.java
gateway-service-remoteconfig/pom.xml
gateway-service-remoteconfig/src/test/java/org/apache/knox/gateway/service/config/remote/zk/RemoteConfigurationRegistryClientServiceTest.java
gateway-test/pom.xml
gateway-test/src/test/java/org/apache/knox/gateway/topology/monitor/RemoteConfigurationMonitorTest.java
pom.xml

KNOX-2010 - Upgrade zookeeper to 3.5.5

---

gateway-shell/src/main/java/org/apache/knox/gateway/shell/table/KnoxShellTable.java
gateway-shell/src/test/java/org/apache/knox/gateway/shell/table/KnoxShellTableTest.java

Ability to sort ascending and descending a table based on a column.
Manual and unit tests.

KNOX-2027 - Need a reverse order sort on a table based on a column.

---

gateway-shell/src/main/java/org/apache/knox/gateway/shell/table/KnoxShellTableFilter.java
gateway-shell/src/main/java/org/apache/knox/gateway/shell/table/KnoxShellTableFilterException.java
gateway-shell/src/test/java/org/apache/knox/gateway/shell/table/KnoxShellTableFilterTest.java
gateway-shell/src/test/java/org/apache/knox/gateway/shell/table/KnoxShellTableTest.java

Ability to filter, sort, and select based on a case insensitive column name.
Manual and unit tests

KNOX-2024 - KnoxShellTable - Case Insensitive Operations with Col Names

---

gateway-server/src/main/java/org/apache/knox/gateway/deploy/impl/ServiceDefinitionDeploymentContributor.java
gateway-service-definitions/src/main/resources/services/hue/1.0.0/service.xml
gateway-service-definitions/src/main/resources/services/ranger/1.0.0/service.xml
gateway-service-definitions/src/main/resources/services/rangerui/1.0.0/service.xml

* Fixes `ServiceDefinitionDeploymentContibutor` to call `setServiceRole` as needed by `ConfigurableHADispatch`
* Sets `ha-classname` to `ConfigurableHADispatch` where appropriate
* `mvn -T.5C clean verify -Ppackage,release -Dshellcheck`
* Manual tests for HA dispatch

KNOX-2061 - ConfigurableHADispatch needs to be wired up

---

gateway-shell/src/main/java/org/apache/knox/gateway/shell/table/KnoxShellTable.java

Fixed missing javadocs that caused build failure
mvn -Dmaven.javadoc.failOnError=true -Dmaven.javadoc.failOnWarnings=true -DskipTests=true -Dcheckstyle.skip=true -Dspotbugs.skip=true -Dmdep.skip=true -Djacoco.skip=true javadoc:javadoc javadoc:test-javadoc

KNOX-2063 - KnoxShellTable javadoc failures

---

gateway-admin-ui/admin-ui/app/app.module.ts
gateway-admin-ui/admin-ui/app/resource/resource.component.html
gateway-admin-ui/admin-ui/app/service-definition/new-service-definition.component.css
gateway-admin-ui/admin-ui/app/service-definition/new-service-definition.component.html
gateway-admin-ui/admin-ui/app/service-definition/new-service-definition.component.ts
gateway-admin-ui/admin-ui/app/service-definition/servicedefinition-detail.component.ts
gateway-admin-ui/admin-ui/app/service-definition/servicedefinition.service.ts
gateway-admin-ui/admin-ui/assets/new-service-definition-template.xml
gateway-admin-ui/package-lock.json
gateway-admin-ui/package.json
pom.xml

From now on end-users can submit their own service definition from scratch (a simple template is provided).
See [this video](https://streamable.com/r09t4) about my integration tests.

KNOX-2068 - Let end-users add a new service definition from scratch

---

gateway-service-definitions/src/main/resources/services/druid-coordinator-ui/0.0.1/rewrite.xml

Add new rewrite rule for druid coordinator ui.
Before:
After:

KNOX-2075: Druid coordinator ui is broken

---

build-tools/src/main/resources/build-tools/dependency-check/suppressions.xml
pom.xml

Adds suppressions for false positives from OWASP dependency check plugin.
* `mvn -DskipTests=true -Dcheckstyle.skip=true -Dspotbugs.skip=true -Dmdep.skip=true -Djacoco.skip=true -Powasp package org.owasp:dependency-check-maven:5.2.2:aggregate`

KNOX-2098 - OWASP Add Nov 2019 suppressions for false positives

---

pom.xml

Upgrade mina 2.0.20 to 2.0.21
`mvn -T.5C verify -Ppackage,release -Dshellcheck`

KNOX-2113 - Upgrade mina-core to 2.0.21

---

gateway-provider-rewrite-step-secure-query/src/main/java/org/apache/knox/gateway/securequery/SecureQueryEncryptProcessor.java
gateway-service-nifi/src/main/java/org/apache/knox/gateway/dispatch/NiFiDispatch.java
gateway-service-nifi/src/main/java/org/apache/knox/gateway/dispatch/NiFiHaDispatch.java
gateway-shell/src/main/java/org/apache/knox/gateway/shell/KnoxSh.java
gateway-shell/src/main/java/org/apache/knox/gateway/shell/table/KnoxShellTableHistoryAspect.java
gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/AbstractGatewayDispatch.java
gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/DefaultDispatch.java
gateway-spi/src/main/java/org/apache/knox/gateway/security/SubjectUtils.java

* NPE checks
* Override method
* Avoid loop for first value in a set

KNOX-2122 - Misc code cleanup

---

gateway-provider-rewrite/src/main/java/org/apache/knox/gateway/filter/rewrite/impl/html/HtmlFilterReaderBase.java
gateway-server/src/main/java/org/apache/knox/gateway/services/topology/impl/DefaultTopologyService.java
gateway-shell/pom.xml
gateway-shell/src/main/java/org/apache/knox/gateway/shell/jdbc/Database.java
gateway-shell/src/main/java/org/apache/knox/gateway/shell/jdbc/derby/DerbyDatabase.java
gateway-shell/src/main/java/org/apache/knox/gateway/shell/jdbc/derby/DerbyDatabaseException.java
gateway-shell/src/main/java/org/apache/knox/gateway/shell/table/JDBCKnoxShellTableBuilder.java
gateway-shell/src/test/java/org/apache/knox/gateway/shell/table/KnoxShellTableTest.java
gateway-shell/src/test/resources/createBooksTable.sql
gateway-shell/src/test/resources/insertBooks.sql
gateway-util-common/src/main/java/org/apache/knox/gateway/audit/api/CorrelationContext.java
gateway-util-common/src/main/java/org/apache/knox/gateway/util/X500PrincipalParser.java
pom.xml

Fixing issues found by `sonarcloud`:
```
mvn clean -Dshellcheck=true -T1C verify -Prelease,package
...
[INFO] Total time: 18:28 min (Wall Clock)
[INFO] Finished at: 2019-11-18T18:20:55+01:00
[INFO] Final Memory: 414M/2435M
```

KNOX-2131 - Fixed sonarcloud bugs

---

gateway-server/src/main/java/org/apache/knox/gateway/trace/KnoxErrorHandler.java
pom.xml

Upgrade jetty to 9.4.24.v20191120

KNOX-2142 - Upgrade jetty to 9.4.24.v20191120

---

pom.xml

KNOX-2143 - Upgrade shiro to 1.4.2

---

gateway-spi/src/main/java/org/apache/knox/gateway/util/WhitelistUtils.java
gateway-spi/src/test/java/org/apache/knox/gateway/util/WhitelistUtilsTest.java

Add an `HTTPS_ONLY` whitelist default config that configures the whitelist only for HTTPS urls.
`mvn -T.5C verify -Ppackage,release -Dshellcheck`

KNOX-2145 - WhitelistUtils should have an HTTPS_ONLY template

---

gateway-server/src/main/java/org/apache/knox/gateway/topology/simple/SimpleDescriptorHandler.java
gateway-server/src/test/java/org/apache/knox/gateway/topology/simple/SimpleDescriptorHandlerTest.java

The `KNOX` service usually does not come with any `url` or `parameter` so that we should allow this service to be added in the generated topology without these attributes.
Updated and ran JUnit tests.

KNOX-2154 - Allow KNOX service during topology generation without URLs and parameters

---

gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/nifi/NifiRegistryServiceModelGenerator.java
gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/nifi/NifiServiceModelGenerator.java
gateway-discovery-cm/src/main/resources/META-INF/services/org.apache.knox.gateway.topology.discovery.cm.ServiceModelGenerator
gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryTest.java

Added service discovery Support for NiFi and NiFi Registry UI
Tested locally

KNOX-1951 - Service Discovery Support for NiFi and NiFi Registry UI

---

gateway-server/src/main/java/org/apache/knox/gateway/services/security/impl/DefaultKeystoreService.java
gateway-server/src/test/java/org/apache/knox/gateway/services/security/impl/DefaultKeystoreServiceTest.java

Add synchronization to `addCredentialForCluster` and `removeCredentialForCluster` to prevent read then write synchronization issues. Added a test that failed without this change for each method and then confirmed passed with fix.
* Checked new unit test fails without change
* Checked new unit test doesn't fail with change

KNOX-2200 - DefaultKeystoreService can lose entries under concurrent access

---

gateway-server/src/main/java/org/apache/knox/gateway/GatewayMessages.java
gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/AliasBasedTokenStateService.java
gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/DefaultTokenStateService.java
gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/TokenStateServiceMessages.java
gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/DefaultTokenStateServiceTest.java
gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceMessages.java

Added logging to the Token and TokenState services.
Manually tested by way of visual inspection of logs.

KNOX-2209 - Improve logging for Knox token handling

---

gateway-test/pom.xml
pom.xml

Fix broken OIDC KnoxSSO integration
This patch was locally tested

KNOX-2231 - Fix KnoxSSO OIDC integration

---

gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/AliasBasedTokenStateService.java
gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/DefaultTokenStateService.java
gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/TokenStateServiceMessages.java
gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/DefaultTokenStateServiceTest.java
gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
gateway-test-release-utils/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java

This PR adds a periodic task that looks for expired tokens and then evicts them. The aim of this task to run at a low priority and be able to gracefully handle failures if there are issues. 
Local testing

KNOX-2214 - Periodic job to evict expired tokens

---

pom.xml

KNOX-2243 - Upgrade groovy to 3.0.1

---

gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
gateway-server/src/test/java/org/apache/knox/gateway/config/impl/GatewayConfigImplTest.java

Change gateway.server.header.enabled default to false

KNOX-2285 - Change gateway.server.header.enabled default to false

---

pom.xml

* Upgrade apacheds.directory.server.version to 2.0.0.AM26

KNOX-2338 - Upgrade apacheds.directory.server.version to 2.0.0.AM26

---

gateway-shell/src/main/java/org/apache/knox/gateway/shell/commands/AbstractKnoxShellCommand.java
gateway-shell/src/main/java/org/apache/knox/gateway/shell/commands/AbstractSQLCommandSupport.java
gateway-shell/src/main/java/org/apache/knox/gateway/shell/commands/CSVCommand.java
gateway-shell/src/main/java/org/apache/knox/gateway/shell/commands/DataSourceCommand.java
gateway-shell/src/main/java/org/apache/knox/gateway/shell/commands/SelectCommand.java
gateway-shell/src/main/java/org/apache/knox/gateway/shell/commands/WebHDFSCommand.java

Change-Id: I6f6b9fb6293c259e5def1dc2927c4da1038301c2
Need to add some helpful description and usage details to the KnoxShell custom commands so that they are available in the interactive shell.
Patch was manually tested using the :help command in the KnoxShell interactive shell.

KNOX-2341 - KnoxShell Custom Commands need Description and Usage Details

---

.github/workflows/main.yml

Add Github Actions for CI
It ran on my fork: https://github.com/risdenk/knox/actions/runs/75532177

KNOX-2339 - Add Github Actions for CI

---

.github/workflows/main.yml

Disabled shellcheck for github actions. Short term until figure out why this broke.
* Waiting for PR results

KNOX-2347 - Disable shellcheck for github actions

---

gateway-admin-ui/admin-ui/app/provider-config-wizard/ha-provider-config.ts
gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/deploy/HaProviderDeploymentContributor.java
gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/HaServiceConfig.java
gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/impl/DefaultHaServiceConfig.java
gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/impl/HaDescriptorConstants.java
gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/impl/HaDescriptorFactory.java
gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/impl/HaDescriptorManager.java
gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/impl/HaServiceConfigConstants.java
gateway-provider-ha/src/test/java/org/apache/knox/gateway/ha/deploy/HaProviderDeploymentContributorTest.java
gateway-provider-ha/src/test/java/org/apache/knox/gateway/ha/dispatch/DefaultHaDispatchTest.java
gateway-provider-ha/src/test/java/org/apache/knox/gateway/ha/provider/impl/HaDescriptorFactoryTest.java
gateway-provider-ha/src/test/java/org/apache/knox/gateway/ha/provider/impl/HaDescriptorManagerTest.java
gateway-server/src/test/java/org/apache/knox/gateway/topology/simple/ProviderConfigurationParserTest.java
gateway-server/src/test/java/org/apache/knox/gateway/topology/simple/SimpleDescriptorHandlerTest.java
gateway-service-rm/src/test/java/org/apache/knox/gateway/rm/dispatch/RMHaDispatchTest.java
gateway-service-webhdfs/src/main/java/org/apache/knox/gateway/hdfs/i18n/WebHdfsMessages.java
gateway-service-webhdfs/src/test/java/org/apache/knox/gateway/hdfs/dispatch/WebHdfsHaDispatchTest.java
gateway-test/src/test/java/org/apache/knox/gateway/PortMappingHelper.java
gateway-test/src/test/java/org/apache/knox/gateway/WebHdfsHaFuncTest.java

* Remove unused `maxRetryAttempts` and `retrySleep`
* Manually verified these configs aren't doing anything today

KNOX-2346 - Remove unused maxRetryAttempts and retrySleep

---

gateway-cm-integration/src/main/java/org/apache/knox/gateway/ClouderaManagerIntegrationMessages.java
gateway-cm-integration/src/main/java/org/apache/knox/gateway/cm/descriptor/ClouderaManagerDescriptorMonitor.java
gateway-cm-integration/src/main/java/org/apache/knox/gateway/topology/discovery/advanced/AdvanceServiceDiscoveryConfigurationMessages.java
gateway-cm-integration/src/main/java/org/apache/knox/gateway/topology/discovery/advanced/AdvancedServiceDiscoveryConfigurationMonitor.java
gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java

KNOX-2353 - Disabled CM descriptor monitoring and advanced service discovery changes monitoring by default

---

gateway-service-definitions/src/main/resources/services/hdfsui/3.0.0/rewrite.xml

https://issues.apache.org/jira/browse/KNOX-2367
Rewrite rules for HDFS UI fonts and bootstrap.min.css.map
On a cluster

KNOX-2367. Fix rewrite rules for HDFS UI fonts and bootstrap.min.css.map

---

gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/SSOCookieFederationFilter.java

Fix the case where response is written multiple times.

KNOX-2369 - Fix IllegalStateException in case of expired or invalid token

---

gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/SSOCookieFederationFilter.java

Update the property name 
Tested locally.

KNOX-2393 - Update the propert name to 'sso.unauthenticated.path.list' to be in-line with other property names

---

gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/JWTMessages.java
gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/AbstractJWTFilter.java
gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/AccessTokenFederationFilter.java

Added the token id and the displayable token representation in the logs so that it's going to be easier to track down a token related issue in the future.
Tested manually.

KNOX-2382 - Logging token identifier for easier error debugging

---

gateway-admin-ui/package-lock.json
gateway-admin-ui/package.json
knox-homepage-ui/package-lock.json
knox-homepage-ui/package.json
pom.xml

Update the AdminUI and Homepage NodeJS dependencies.
```
./gateway-admin-ui/npm audit fix
./knox-homepage-ui/npm audit fix
```
* `mvn -T.75C clean verify -U -Ppackage,release -Dshellcheck`

KNOX-2404 - Update AdminUI and Homepage NodeJS dependencies

---

pom.xml

Upgrade Shiro to 1.5.3
`mvn -U -T.75C clean verify -Ppackage,release -Dshellcheck`

KNOX-2221 - Upgrade shiro to 1.5.3

---

gateway-provider-security-pac4j/pom.xml
gateway-provider-security-pac4j/src/main/java/org/apache/knox/gateway/pac4j/filter/Pac4jDispatcherFilter.java
gateway-provider-security-pac4j/src/main/java/org/apache/knox/gateway/pac4j/filter/Pac4jIdentityAdapter.java
gateway-provider-security-pac4j/src/main/java/org/apache/knox/gateway/pac4j/session/KnoxSessionStore.java
gateway-provider-security-pac4j/src/test/java/org/apache/knox/gateway/pac4j/Pac4jProviderTest.java
pom.xml

* Upgrade pac4j to 4.0.3
* Upgrade opensaml to 3.4.5

KNOX-2337 - Upgrade pac4j to 4.0.3 and opensaml to 3.4.5

---

gateway-spi/src/main/java/org/apache/knox/gateway/SpiGatewayMessages.java
gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/ConfigurableDispatch.java
gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/DefaultDispatch.java
gateway-spi/src/test/java/org/apache/knox/gateway/dispatch/ConfigurableDispatchTest.java

The changes are around cleaning up ConfigurableDispatch.
The patch was tested locally

KNOX-2468 - Improve ConfigurableDispatch set cookies

---

gateway-server/src/main/java/org/apache/knox/gateway/websockets/GatewayWebsocketHandler.java
gateway-server/src/test/java/org/apache/knox/gateway/websockets/WebsocketBackendUrlTest.java
gateway-server/src/test/java/org/apache/knox/gateway/websockets/WebsocketEchoTestBase.java

Fix an issue with rewriting websockets for socket.io backend
Patch was tested locally

KNOX-1361 Fix issues when proxying websockets via socket.io

---

gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerCluster.java
gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerServiceDiscoveryMessages.java
gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/ServiceModel.java
gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/hdfs/NameNodeServiceModelGenerator.java
gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/model/solr/SolrServiceModelGenerator.java
gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/ClouderaManagerClusterTest.java
gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/model/hdfs/NameNodeServiceModelGeneratorTest.java
gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/model/hdfs/WebHdfsServiceModelGeneratorTest.java
gateway-discovery-cm/src/test/java/org/apache/knox/gateway/topology/discovery/cm/model/solr/SolrServiceModelGeneratorTest.java
gateway-topology-simple/src/main/java/org/apache/knox/gateway/topology/simple/SimpleDescriptor.java
gateway-topology-simple/src/main/java/org/apache/knox/gateway/topology/simple/SimpleDescriptorHandler.java

Added logging for qualifying service param mismatches, testing for the Solr case of such params, and did a little refactoring.
Added ClouderaManagerClusterTest, executed other existing tests, and performed some manually testing.

KNOX-2533 - Qualifying service params for discovery improvements

---

gateway-admin-ui/package-lock.json
gateway-provider-security-hadoopauth/src/test/java/org/apache/knox/gateway/hadoopauth/filter/HadoopAuthFilterTest.java
gateway-provider-security-jwt/pom.xml
gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/JWTMessages.java
gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/AbstractJWTFilter.java
gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/JWTFederationFilter.java
gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/AbstractJWTFilterTest.java
gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/JWTAsHTTPBasicCredsFederationFilterTest.java
gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/JWTFederationFilterTest.java
gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/SSOCookieProviderTest.java
knox-homepage-ui/package-lock.json

Moved token verification until after expiry evaluation, and added caching of successful token verification.
Added test to AbstractJWTFilterTest, and executed existing tests.

KNOX-2542 and KNOX-2544

---

gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/JWTMessages.java
gateway-server/src/main/java/org/apache/knox/gateway/GatewayMessages.java
gateway-server/src/main/java/org/apache/knox/gateway/services/factory/AbstractServiceFactory.java
gateway-server/src/main/java/org/apache/knox/gateway/services/factory/TokenStateServiceFactory.java
gateway-server/src/main/java/org/apache/knox/gateway/services/security/impl/ZookeeperRemoteAliasService.java
gateway-server/src/main/java/org/apache/knox/gateway/services/token/RemoteTokenStateChangeListener.java
gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/AliasBasedTokenStateService.java
gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/DefaultTokenStateService.java
gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/JournalBasedTokenStateService.java
gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/TokenStatePeristerMonitorListener.java
gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/TokenStatePersisterMonitor.java
gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/TokenStateServiceMessages.java
gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/ZookeeperTokenStateService.java
gateway-server/src/test/java/org/apache/knox/gateway/services/factory/TokenStateServiceFactoryTest.java
gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/AliasBasedTokenStateServiceTest.java
gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/ZookeeperTokenStateServiceTest.java
gateway-util-common/src/main/java/org/apache/knox/gateway/util/ExecutorServiceUtils.java

See JIRA [description](https://issues.apache.org/jira/browse/KNOX-2551).
Ran/updated unit test:
```
$ mvn clean -Dshellcheck=true -DskipTests verify -Prelease,package -am -pl gateway-
...
INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:19 min
[INFO] Finished at: 2021-03-15T02:22:30+01:00
[INFO] Final Memory: 176M/1517M
```
Executed various E2E tests in real test environments with Knox HA and different token state service implementations.

KNOX-2551 - Token state management improvements

---

gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/DefaultTokenAuthorityService.java
gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/TokenAuthorityServiceMessages.java
gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/DefaultTokenAuthorityServiceTest.java
gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/DefaultTokenStateServiceTest.java
gateway-service-knoxsso/src/test/java/org/apache/knox/gateway/service/knoxsso/WebSSOResourceTest.java
gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/JWKSResource.java
gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/JWKSResourceTest.java
gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/JWTokenAttributes.java
gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/JWTokenAttributesBuilder.java
gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/TokenUtils.java
gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/impl/JWTProviderMessages.java
gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/impl/JWTToken.java
gateway-spi/src/test/java/org/apache/knox/gateway/services/security/token/impl/JWTTokenTest.java

This change adds `kid` and `jku` claims to JWT tokens issues by Knox
The patch was tested locally on a local cluster.

KNOX-2575 - Add  `kid` and `jku`  claims to JWT tokens issues by Knox

---

gateway-applications/src/main/resources/applications/tokengen/app/index.html
gateway-applications/src/main/resources/applications/tokengen/app/js/tokengen.js

Limiting the comment field length to 255 characters. I also added validation on that field in case the limit does not take place for any reason.
Manually tested and confirmed that end-users cannot enter comments greater than 255 characters.

KNOX-2613 - Limiting and validating the comment's length on Token Generation UI

---

gateway-applications/src/main/resources/applications/tokengen/app/index.html
gateway-applications/src/main/resources/applications/tokengen/app/js/tokengen.js

Improvements on Token Generation UI:
- more refined DIV elements
- copy-to-clipboard function is invoked when end-users click on `JWT token`, `Passcode token`, and `Target Base URL` labels.
Manually tested

KNOX-2617 - Minor style changes and copy-to-clipboard functionality added for JWT/Passcode tokens and base target UL fields on the Token Generation UI

---

gateway-applications/src/main/resources/applications/tokengen/app/index.html
gateway-applications/src/main/resources/applications/tokengen/app/js/tokengen.js

Implemented the `copy-to-clipboard` function in a cross-browser safe manner.
Tested manually using Google Chrome, Firefox and Safari.

KNOX-2632 - Properly copying generated content on tokengen UI

---

gateway-server/src/main/java/org/apache/knox/gateway/util/KnoxCLI.java
gateway-server/src/test/java/org/apache/knox/gateway/util/KnoxCLITest.java

A new Knox CLI command is developed to generate a JWK and print it into the STDOUT.
Accepted JWK algorithms are HS256, HS384, and HS512.
Added new JUnit test cases and executed manual testing:
```
$ bin/knoxcli.sh generate-jwk --jwkAlg HS256
v8Oq3NmmR1_SEXgD15Hz4xYzkFZkR8Y1v8XOVgl43kg
$ bin/knoxcli.sh generate-jwk --jwkAlg HS384
dMidyzj0d89YvBOZt-Ygac2NZ9ATgD3x9Zme6eY90TTrBPpJdxHi0Lczc1XjNaAn
$ bin/knoxcli.sh generate-jwk --jwkAlg HS512
nUt2NtWi7il6gDClTlBGjcp6788gGeQRAYDD3RynhpbF-F6UatAietlt_OWUIFdqxLqkhbqBFhzQpUpxRJUWLQ
$ bin/knoxcli.sh generate-jwk --jwkAlg HS256 --saveAlias my.generated.jwk
my.generated.jwk has been successfully created.
$ bin/knoxcli.sh list-alias
Listing aliases for: __gateway
my.generated.jwk
knox.token.hash.key
2 items.
$ bin/knoxcli.sh generate-jwk --jwkAlg HS256 …
```

KNOX-2637 - Added a new Knox CLI command to generate JWK secrets

---

gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/TokenStateServiceMessages.java

Typo fix.
```
mvn clean -Dshellcheck=true verify -Prelease,package
```

KNOX-2610 Typo in token alias persistence log message

---

gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java

When the hmac secret length is shorter than the required then token generation will fail with no meaningful message.
```json
{ "Unable to acquire token." }
```
The gateway log doesn't contain any information about what went wrong.
I found no simply way to add validation logic to the secret creation (bin/knoxcli.sh create-alias gateway.signing.hmac.secret --value <..>) and prevent creating the secret with invalid length, so I added a check to TokenResorce>>init() instead.
This throws an exception from the init and prevent the initializaiton of TokenResource, result http 500 when calling a method.
One thing to consider: Instead of throwing exception maybe we want to log the error and continue. Not sure which one would be better. 
1. Created a shorter than expected secret:
```
$ …
```

KNOX-2574 - Missing proper logging when hmac secret is short

---

gateway-provider-security-pac4j/pom.xml
pom.xml

Remove Hibernate dependency since it is only included transitively for dependency test.
`mvn -U -T.75C clean verify -Ppackage,release -Dshellcheck`

KNOX-2640 - Remove hibernate dependency

---

gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/dispatch/ConfigurableHADispatch.java
gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/dispatch/i18n/HaDispatchMessages.java
gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/provider/impl/DefaultHaProvider.java
gateway-provider-ha/src/test/java/org/apache/knox/gateway/ha/dispatch/ConfigurableHADispatchTest.java
gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/DefaultDispatch.java

This change fixes the way HA Loadbalancing cookie is set and addresses the concurrency issue when multiple requests are issues.
This patch was tested on a HA cluster.

KNOX-2641 Fix invalid session handle issue with Hive HA

---

gateway-applications/src/main/resources/applications/knoxauth/app/logout.jsp

This PR cleans up pac4j cookies after logout 

KNOX-2673 - Clean up cookies after logout

---

pom.xml

[KNOX-2540](https://issues.apache.org/jira/browse/KNOX-2540): fix dependency conflict issue for org.apache.curator:curator-client:jar
running automated unit/integration tests

KNOX-2540: fix dependency conflict issue

---

pom.xml

Upgrade Log4j2 to log4j-2.15.0
```
(base) ➜  knox git:(master) ✗ mvn dependency:list | grep log4j
Picked up _JAVA_OPTIONS: -Djava.awt.headless=true
[INFO] gateway-i18n-logging-log4j                                         [jar]
[INFO]    org.apache.logging.log4j:log4j-api:jar:2.15.0:provided -- module org.apache.logging.log4j
[INFO]    org.apache.logging.log4j:log4j-core:jar:2.15.0:provided -- module org.apache.logging.log4j.core [auto]
[INFO]    org.apache.logging.log4j:log4j-api:jar:2.15.0:compile -- module org.apache.logging.log4j
[INFO]    org.apache.logging.log4j:log4j-core:jar:2.15.0:compile -- module org.apache.logging.log4j.core [auto]
[INFO]    org.apache.logging.log4j:log4j-slf4j-impl:jar:2.15.0:compile -- module org.apache.logging.log4j.slf4j [auto]
[INFO] …
```

KNOX-2696 -  Upgrade Log4j2 to log4j-2.15.0

---

pom.xml

Bumped Log4J version to 2.16. Details in the JIRA!
```
mvn dependency:tree -Dincludes=org.apache.logging.log4j
[INFO] Scanning for projects...
[INFO] Reactor Build Order:
[INFO] 
[INFO] build-tools                                                        [jar]
[INFO] gateway                                                            [pom]
[INFO] gateway-test-utils                                                 [jar]
[INFO] gateway-i18n                                                       [jar]
[INFO] gateway-util-common                                                [jar]
[INFO] gateway-util-configinjector                                        [jar]
[INFO] gateway-util-launcher …
```

KNOX-2697 - Upgraded Log4j to 2.16

---

pom.xml

Upgraded Log4J to 2.17.1 due to various security vulnerabilities.
Built the project and tested the final deliverable:
```
$ mvn -DskipTests -Dcheckstyle.skip=true -Dfindbugs.skip=true -Dpmd.skip=true -Drat.skip -Ppackage package
...
[INFO] Total time:  02:41 min
[INFO] Finished at: 2022-01-13T11:56:28+01:00
$ unzip -l target/2.0.0-SNAPSHOT/knox-2.0.0-SNAPSHOT.zip | grep "dep/log4j"
24279  01-22-2020 15:10   knox-2.0.0-SNAPSHOT/dep/log4j-slf4j-impl-2.17.1.jar
301872  01-22-2020 15:10   knox-2.0.0-SNAPSHOT/dep/log4j-api-2.17.1.jar …
```

KNOX-2702 - Upgraded Log4J to 2.17.1

---

gateway-spi/src/main/java/org/apache/knox/gateway/dispatch/HeaderPreAuthFederationDispatch.java

HeaderPreAuthFederationDispatch should extend ConfigurableDispatch

KNOX-2708 - HeaderPreAuthFederationDispatch should extend ConfigurableDispatch

---

gateway-applications/src/main/resources/applications/knoxauth/app/redirecting.jsp

Added some defensive logic in redirecting.jsp to avoid NullPointerException in some cases.
Manual testing.

KNOX-2706 - Possible NPE in redirecting.jsp

---

pom.xml

https://issues.apache.org/jira/browse/KNOX-2727
update pom
CI build

KNOX-2727 upgrade spring due to cve

---

pom.xml

[KNOX-2722](https://issues.apache.org/jira/browse/KNOX-2722)
Change jar version
CI build

KNOX-2722 upgrade common-compress to 1.21

---

pom.xml

https://issues.apache.org/jira/browse/KNOX-2717
security issue in shiro
(If this patch involves UI changes, please attach a screen-shot; otherwise, remove this)

KNOX-2717: upgrade shiro

---

pom.xml

Upgrade netty version to latest

KNOX-2743 - Upgrade netty

---

gateway-shell/src/main/java/org/apache/knox/gateway/shell/ClientContext.java

A small change that was left out from KNOX-2736. 
N/A

KNOX-2736 Knox clients should support retry/failover - addendum

---

pom.xml

https://issues.apache.org/jira/browse/KNOX-2750 - security issue in gson
See also https://github.com/apache/knox/pull/580
(If this patch involves UI changes, please attach a screen-shot; otherwise, remove this)
CI build

KNOX-2750: upgrade gson due to security issue

---

pom.xml

https://issues.apache.org/jira/browse/KNOX-2718
CI build

KNOX-2718: upgrade xmlsec due to security issue

---

pom.xml

https://issues.apache.org/jira/browse/KNOX-2754
Also - https://github.com/apache/knox/pull/557
CI build
(If this patch involves UI changes, please attach a screen-shot; otherwise, remove this)

KNOX-2754: upgrade hadoop-common due to cve

---

gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java

2 major changes in the PR:
1. Using the previously introduced `knox.token.impersonation.enabled` parameter to control proxyuser actions
2. Proxyuser config refresh and authorization takes place only, and only if
2.1. Token management is enabled
2.2. Impersonation is enabled 
Manually tested as described in the JIRA (see `Test to reproduce`).

KNOX-2770 - KnoxToken doAs support depends on token state service and a service-level configuration

---

gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
gateway-server/src/main/java/org/apache/knox/gateway/services/security/impl/JettySSLService.java
gateway-server/src/test/java/org/apache/knox/gateway/config/impl/GatewayConfigImplTest.java
gateway-server/src/test/java/org/apache/knox/gateway/services/security/impl/JettySSLServiceTest.java
gateway-spi-common/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java

disable renegotiation for embedded jetty

KNOX-2772 - add configuration for jetty renegotiation

---

gateway-server/src/main/java/org/apache/knox/gateway/GatewayServer.java
gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
gateway-server/src/test/java/org/apache/knox/gateway/config/impl/GatewayConfigImplTest.java
gateway-spi-common/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
gateway-test/src/test/java/org/apache/knox/gateway/SimpleDescriptorHandlerFuncTest.java

support multiple hosts for gateway.host config

KNOX-2779 - support multiple hosts for gateway.host config

---

pom.xml

json-smart + spring version upgrade.
```bash
$ mvn dependency:tree | grep json-smart
$ mvn dependency:tree | grep spring
```

KNOX-2786 - Upgrade spring and json-smart due to CVEs

---

gateway-provider-security-pac4j/pom.xml
gateway-provider-security-pac4j/src/main/java/org/apache/knox/gateway/pac4j/filter/Pac4jDispatcherFilter.java
gateway-provider-security-pac4j/src/main/java/org/apache/knox/gateway/pac4j/filter/Pac4jIdentityAdapter.java
pom.xml

KNOX-2787 - Upgrade pac4j to 4.5.6

---

gateway-provider-security-hadoopauth/src/test/java/org/apache/knox/gateway/hadoopauth/filter/HadoopAuthFilterTest.java
gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/JWTMessages.java
gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/JWTFederationFilter.java
gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/SSOCookieFederationFilter.java
gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/AbstractJWTFilterTest.java
gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/JWTFederationFilterTest.java

As described in [KNOX-2794](https://issues.apache.org/jira/browse/KNOX-2794), the JWT federation filter is enhanced to support authentication using a JWT supplied via an HTTP cookie. 
Updated existing JUnit test classes and have new test cases to cover the new functionality.
In addition to unit testing comprehensive manual test steps were executed as follows:
1. Deployed a new topology called `tokenexchange`:
```
<?xml version="1.0" encoding="UTF-8"?>
<topology>
<name>tokenexchanged</name>
<gateway>
<provider>
<role>federation</role>
<name>JWTProvider</name>
<param>
<name>knox.token.use.cookie</name>
</param>
<param>
<name>knox.token.exp.server-managed</name>
</param>
</provider>
</gateway>
<service>
<role>KNOXTOKEN</role> …
```

KNOX-2794 - Added cookie auth support into JWT federation provider

---

gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceMessages.java

Added some very useful log message entries on `DEBUG` level.
Manually tested.

KNOX-2808 - Added log entries upon successful/failed token impersonation

---

gateway-provider-jersey/src/main/java/org/apache/knox/gateway/jersey/JerseyServiceDeploymentContributorBase.java
gateway-provider-security-dos/pom.xml
gateway-provider-security-dos/src/main/java/org/apache/knox/gateway/deploy/impl/DosFilterDeploymentContributor.java
gateway-provider-security-dos/src/main/resources/META-INF/services/org.apache.knox.gateway.deploy.ProviderDeploymentContributor
gateway-release/pom.xml
gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
gateway-server/src/main/java/org/apache/knox/gateway/deploy/DeploymentFactory.java
gateway-server/src/main/java/org/apache/knox/gateway/deploy/impl/ApplicationDeploymentContributor.java
gateway-server/src/main/java/org/apache/knox/gateway/deploy/impl/ServiceDefinitionDeploymentContributor.java
gateway-spi-common/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
gateway-spi/src/main/java/org/apache/knox/gateway/deploy/ProviderDeploymentContributorBase.java
gateway-spi/src/main/java/org/apache/knox/gateway/deploy/ServiceDeploymentContributorBase.java
pom.xml

A new module called: `gateway-provider-security-dos` was added. It adds jetty's `DoSFilter` to the topology when configured in the topology file. The configuration options are the same as jetty's DoSFilter and can be found in jetty's DoSFilter documentation (https://archive.eclipse.org/jetty/9.0.0.RC0/apidocs/org/eclipse/jetty/servlets/DoSFilter.html), except when using delayMs with 0 or higher value or using throttling the `gateway.servlet.async.supported` configuration must be set to `true` in `gateway-site.xml` configuration file (it defaults to false)! 
An example topology configuration:
Topology:
```
<provider>
<role>dos</role>
<name>JettyDoS</name>
<param>
<name>maxRequestsPerSec</name>
<value>1</value>
</param>
<param>
<name>delayMs</name>
<value>0</value> …
```

KNOX-2806 - Implement a new DoS security provider

---

pom.xml

The following dependencies were upgraded:
- hadoop: `3.2.3` -> `3.2.4`
- jetty: `9.4.45.v20220203` -> `9.4.48.v20220622`
- postgresql: `42.3.3` -> `42.4.1`
- woodstox: `6.1.1` -> `6.4.0`
- shiro: `1.8.0` -> `1.10.0`
I have configured `postgresql` for jdbc token state service.
I have created test topology on admin ui:
```
<topology>
<uri>https://localhost:8443/gateway/test</uri>
<name>test</name>
<timestamp>1669992953127</timestamp>
<generated>true</generated>
<redeployTime>0</redeployTime>
<gateway>
<provider>
<role>federation</role>
<name>JWTProvider</name>
<param>
<name>knox.token.exp.server-managed</name>
</param>
</provider>
</gateway>
<service>
<url>http://www.blankwebsite.com/</url>
</service>
</topology>
```
Generated …

KNOX-2850 - Bumped shiro, jetty, postgresql, hadoop, woodstox dependencies

---

gateway-service-definitions/src/main/resources/services/hiveserver2ui/3.1.2/rewrite.xml

Fix a url proxy of Hiveserver2 UI
UI test
Before fixed
After fixed

KNOX-2813 Fix a url proxy of Hiveserver2 UI

---

gateway-server/pom.xml
pom.xml

KNOX-2853 - Bumps hsqldb from 2.4.0 to 2.7.1.

---

gateway-release/home/conf/topologies/homepage.xml

Fixed typos
Manual verification.

KNOX-2857 - Fixed typo in some of the config names

---

knox-webshell-ui/angular.json
knox-webshell-ui/package.json

I modified the Angular settings within `knox-webshell-ui` to conform to the same configuration we have in other UI projects.
Built the entire Knox deliverable locally and asked @zeroflag to do the same with my patch before I opened this PR.
After that I tested that WebShell is actually working.

KNOX-2860 - Build the knox-webshell-ui project the same way as we build other UIs

---

knox-token-management-ui/package-lock.json
knox-token-management-ui/package.json
knox-token-management-ui/token-management/app/app.module.ts
knox-token-management-ui/token-management/app/knox.token.ts
knox-token-management-ui/token-management/app/token.management.component.html
knox-token-management-ui/token-management/app/token.management.component.ts
knox-token-management-ui/token-management/assets/token-management-ui.css
knox-token-management-ui/token-management/index.html

Replaced the old Angular2 Datatable with a more modern Material Table implementation and configured filtering, sorting, and pagination on both tables on the Token Management UI.
Manual testing with a huge amount of tokens created (2k) to ensure the new implementation still performs.

KNOX-2859 - Token Management UI improvements

---

gateway-server/src/main/java/org/apache/knox/gateway/websockets/GatewayWebsocketHandler.java
gateway-server/src/test/java/org/apache/knox/gateway/websockets/GatewayWebsocketHandlerTest.java

Make sure webshell WS connections work when used with LB
Using Unittests

KNOX-2872 - Make sure webshell WS connections work when used with LB

---

gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/ZookeeperTokenStateServiceTest.java
pom.xml

Upgrading curator and zookeeper.
```bash
$ mvn test -Dtest=ZookeeperTokenStateServiceTest
```

KNOX-2873 - Upgrade curator version to 5.4.0 and zookeeper to 3.8.1

---

build.xml

Update build.xml with correct gateway version
locally

KNOX-2888 - Update gateway-version to 2.1.0 in build.xml

---

gateway-provider-ha/src/main/java/org/apache/knox/gateway/ha/dispatch/ConfigurableHADispatch.java

Make sure we mark the endpoint as failed in case of non-idempotent request failures.
Make sure unit tests pass

KNOX-2904 -  Mark the endpoint as failed when we failover AND request is non-idempotent

---

gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/SSOCookieFederationFilter.java

Unauthenticated path list doesn't work when hadoop-jwt cookie exists but it's invalid / expired.
```xml
<topology>
<gateway>
<provider>
<role>federation</role>
<name>SSOCookieProvider</name>
<param>
<name>sso.unauthenticated.path.list</name>
<value>/favicon.ico;test;unsafepath</value>
</param>
</provider>
<provider>
<role>identity-assertion</role>
<name>Default</name>
</provider>
<provider>
<role>hostmap</role>
<name>static</name>
<param>
<name>localhost</name>
<value>sandbox,sandbox.hortonworks.com</value>
</param>
</provider>
</gateway>
<service>
<role>CM-UI</role>
<url>https://www.google.com</url>
</service>
</topology>
```
```bash
curl --cookie "hadoop-jwt=invalid" -k …
```

KNOX-2898 - Reconsider the usage of sso.unauthenticated.path.list

---

gateway-server/src/main/java/org/apache/knox/gateway/services/topology/impl/GatewayStatusService.java
gateway-server/src/test/java/org/apache/knox/gateway/services/topology/impl/GatewayStatusServiceTest.java
gateway-service-health/src/main/java/org/apache/knox/gateway/service/health/PingResource.java

Revert "KNOX-2962 - Knox readiness check gateway-status endpoint should return the list of topologies for which it is waiting for"

---

gateway-release/home/conf/topologies/homepage.xml

Config cleanup.
Confirmed that Knox's `homepage` topology comes with the updated configs.

KNOX-2992 - Cleaned up impersonation configs

---

gateway-service-metadata/src/main/java/org/apache/knox/gateway/service/metadata/ServiceModel.java
gateway-service-metadata/src/test/java/org/apache/knox/gateway/service/metadata/ServiceModelTest.java

Updated the IMPALA URL on the Knox Home page as described in [KNOX-3004](https://issues.apache.org/jira/browse/KNOX-3004).
Actualized the corresponding JUnit tests and ran manual testing.

KNOX-3004 - Building a valid JDBC URL for Impala

---

gateway-service-definitions/src/main/resources/services/ozone-scm/1.4.0/service.xml

I fixed the ozone version in the ozone-scm 1.4.0 service.xml.
I tested the changes on a cluster.

KNOX-3029 - Fix Ozone version in ozone-scm 1.4.0 service.xml

---

gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/JWTMessages.java
gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/AbstractJWTFilter.java
gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/AbstractJWTFilterTest.java

Minor changes to messages and added a unit test

KNOX-3040 - Some followup minor fixes

---

gateway-service-definitions/src/main/resources/services/ranger/2.3.0/rewrite.xml
gateway-service-definitions/src/main/resources/services/ranger/2.3.0/service.xml

Added service definitions for Ranger. 
The patch was tested locally.

KNOX-3045 - Adding the most recent service definitions for Ranger

---

gateway-util-common/pom.xml
gateway-util-common/src/main/java/org/apache/knox/gateway/util/JsonUtils.java

Fix an issue which can throw error in token deserialization.
This patch was tested locally on a local cluster.

KNOX-3060 - Knox Homepage token management does not work when Cookie Management is enabled

---

gateway-service-definitions/src/main/resources/services/iceberg-rest/0.0.1/rewrite.xml
gateway-service-definitions/src/main/resources/services/iceberg-rest/0.0.1/service.xml

Add a service definition and rewrite rules for Apache Iceberg REST Catalog API service.

KNOX-3068 Iceberg REST Catalog service definition

---

gateway-service-metadata/src/main/java/org/apache/knox/gateway/service/metadata/KnoxMetadataResource.java
gateway-shell/src/main/java/org/apache/knox/gateway/shell/KnoxSh.java
gateway-util-common/src/main/java/org/apache/knox/gateway/util/X509CertificateUtil.java

Modify the Metadata API to return the certificate chain when a load balancer is between Knox and its clients.
Unit tests and manual tests with a LB in front of Knox.

KNOX-3085: Metadata API should return the certificate chain (if any) instead of only the configured Knox instance certificate

---

pom.xml

Update snakeyaml dependency to 2.4
Tested the build locally

KNOX-3117 - Update snakeyaml dependency to 2.4

---

gateway-util-common/src/test/java/org/apache/knox/gateway/util/JsonUtilsTest.java

This patch was missing Unit Tests so adding tests.
Tested locally

KNOX-3060 - Adding missing unit tests

---

pom.xml

Upgrade the Apache commons-lang3 dependency to version 3.14.0
Ran full build and verify tests.

KNOX-3147: Upgrade commons-lang3 to 3.14.0

---

gateway-service-auth/src/main/java/org/apache/knox/gateway/service/auth/ExtAuthzResource.java

Add support for PATCH verb for extauthz endpoint

KNOX-3050 - Add PATCH support for extauthz endpoint

---

pom.xml

Upgrade libraries with CVE fixes
Tested locally

KNOX-3178 - Upgrade dependencies
